### ISSUE TITLE
k0s install controller failed while adding user

### ISSUE THREAD

**Issue by fancl20** [k0sproject/k0s#1019]
**Version**
```
$ k0s version
v1.21.2+k0s.1
```
**Platform**
Which platform did you run k0s on?
```
$cat /etc/os-release
NAME=Fedora
VERSION="34.20210711.0 (IoT Edition)"
ID=fedora
VERSION_ID=34
VERSION_CODENAME=""
PLATFORM_ID="platform:f34"
PRETTY_NAME="Fedora 34.20210711.0 (IoT Edition)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:34"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/34/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=34
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=34
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="IoT Edition"
VARIANT_ID=iot
OSTREE_VERSION='34.20210711.0
```
**What happened?**
```
$ sudo k0s install controller --enable-worker
INFO[2021-07-17 11:14:41] no config file given, using defaults
INFO[2021-07-17 11:14:41] creating user: etcd
useradd: user 'etcd' already exists
INFO[2021-07-17 11:14:41] creating user: kube-apiserver
INFO[2021-07-17 11:14:41] creating user: konnectivity-server
INFO[2021-07-17 11:14:41] creating user: kube-scheduler
Error: failed to create controller users: failed to run command "useradd" "--home" "/var/lib/k0s" "--shell" "/usr/sbin/nologin" "--system" "--no-create-home" "etcd": exit status 9
2021-07-17 11:14:41.702582 I | failed to create controller users: failed to run command "useradd" "--home" "/var/lib/k0s" "--shell" "/usr/sbin/nologin" "--system" "--no-create-home" "etcd": exit status 9
[fancl20@homeserver-controller ~]$ sudo k0s install controller --enable-worker
INFO[2021-07-17 11:15:09] no config file given, using defaults
INFO[2021-07-17 11:15:09] creating user: etcd
useradd: user 'etcd' already exists
Error: failed to create controller users: failed to run command "useradd" "--home" "/var/lib/k0s" "--shell" "/usr/sbin/nologin" "--system" "--no-create-home" "etcd": exit status 9
2021-07-17 11:15:09.914503 I | failed to create controller users: failed to run command "useradd" "--home" "/var/lib/k0s" "--shell" "/usr/sbin/nologin" "--system" "--no-create-home" "etcd": exit status 9
```

**How To Reproduce**
`k0s install controller --enable-worker` on fresh installed Fedora-Iot

**Expected behavior**
Install succeeded.

**Additional context**
```
$ getent passwd | grep etcd
etcd:x:998:997:etcd user:/var/lib/etcd:/sbin/nologin
$ cat /etc/passwd | grep etcd
```
I believe the problem was caused by golang/go#27412, which os/user will only look into /etc/passwd when CGO is disabled. It's actually documented in os/user:

> For most Unix systems, this package has two internal implementations of resolving user and group ids to names. One is written in pure Go and parses /etc/passwd and /etc/group. The other is cgo-based and relies on the standard C library (libc) routines such as getpwuid_r and getgrnam_r.

 Mayby use `getent` binary by default and only fallback to os/user when it's not available?

**Comment by jnummelin** [comment]
Closing as we expect that recent-ish changes to use `usergo` build flag should also fix this.

**Comment by bugthing** [comment]
@jnummelin sorry to post on a closed issue, possible bad netiquette :grimacing: .. but I seem to have this exact problem with k0s install (v1.22.2+k0s.1) and rather than start a new issue, it seems sensible to ask here.

Do I need to apply the build flag (usergo) myself or is an upstream thing that should just start to work?
Essentially I am stuck and wondering if there anything I can do.. any advice?

FYI.
I have attempted to install using v1.23.1+k0s.0 and the problem persists but with slightly different output.
I am using a newer version of CoreOS (VERSION="35.20211203.3.0") bare metal install
