### ISSUE TITLE
`k0s start` fails on Linux with OpenRC

### ISSUE THREAD

**Issue by jewertow** [k0sproject/k0s#1035]
**Version**
```
1.21
```
**Platform**
Which platform did you run k0s on?
```
$ Alpine
```
**What happened?**
Command `k0s start` fails with the following output:
```
./k0s start
Error: exit status 1
Usage:
  k0s start [flags]

Flags:
  -h, --help   help for start

Global Flags:
      --data-dir string                Data Directory for k0s (default: /var/lib/k0s). DO NOT CHANGE for an existing setup, things will break!
      --debug                          Debug logging (default: false)
      --log-flush-frequency duration   Maximum number of seconds between log flushes (default 5s)
      --version version[=true]         Print version information and quit

2021-07-29 20:39:55.466742 I | exit status 1
```

This output doesn't explain what's wrong, so I tried to start k0s directly with `rc-service`:
```
rc-service k0scontroller start
 * Starting k0s ...
 * supervise-daemon: --pidfile must be specified
 * failed to start k0s                                                                                                                                                                                  [ 
 * ERROR: k0scontroller failed to start
```

So as logs say, I added a `pidfile=/var/run/k0s.pid` to `/etc/init.d/k0scontroller` and it worked.

**Solution**
To fix this bug we could add `pidfile=` to service template for OpenRC in `install/service.go`. Unfortunately kardianos/service doesn't contain `pidfile` in a default template, so there has to be used a custom template.

To be consistent with systemd, it would be also required to add `PIDFile` entry to systemd template.

**How To Reproduce**
1. Download k0s and make it executable:
```
wget -O k0s https://github.com/k0sproject/k0s/releases/download/v1.21.2+k0s.1/k0s-v1.21.2+k0s.1-amd64
chmod u+x k0s
```
2. Setup Alpine VM, install and start k0s:
```
Vagrant.configure("2") do |config|

  config.vm.define "k0s" do |node|
    node.vm.box = "generic/alpine38"
    node.vm.hostname = "k0scontroller"
    node.vm.provider :virtualbox do |vb|
      vb.memory = 2048
      vb.cpus = 2
    end
    node.vm.provision :file, source: "./k0s", destination: "/home/vagrant/k0s"
  end

end

$ k0s install controller --single
$ k0s start
```

If you agree to fix this problem as I suggested I can submit a pull request.

**Comment by ncopa** [comment]
what version of openrc and alpine?

**Comment by jasmingacic** [comment]
in our integration tests that run very often we test openRC. https://github.com/k0sproject/k0s/blob/main/inttest/ctr/ctr_test.go#L37-L41

**Comment by trawler** [comment]
It's not necessary to use a pidfile for the correct operation of OpenRC. Do you by any chance have `command_background=true` set in your OpenRC system?

According to the docs, this will 
```This forces the "--make-pidfile" and "--pidfile" options, so the pidfile variable must be set.```

**Comment by jewertow** [comment]
Ok, it didn't work, because I used Alpine 3.8 with OpenRC 0.38. I tried it on Alpine 3.14 with OpenRC 0.43 and it works.
