### ISSUE TITLE
how to install controller with environment variable set for ETCD_UNSUPPORTED_ARCH?

### ISSUE THREAD

**Issue by tuananh** [k0sproject/k0s#1037]
the default command to install controller doesn't have the env var set. what's the proper way to do it?

right now, i need to install the service as normal and then update the service file.

**Comment by logan2211** [comment]
Workaround using systemd service environment override:

```
mkdir /etc/systemd/system/k0scontroller.service.d
cat << EOF > /etc/systemd/system/k0scontroller.service.d/override.conf
[Service]
Environment=ETCD_UNSUPPORTED_ARCH=arm64
EOF
systemctl daemon-reload
systemctl restart k0scontroller
```

**Comment by jnummelin** [comment]
This is also documented at https://docs.k0sproject.io/main/environment-variables/, thus closing
