### ISSUE TITLE
Add `apparmor_parser` to the requisites

### ISSUE THREAD

**Issue by e-minguez** [k0sproject/k0s#1039]
**Version**
```
$ k0s version
v1.21.3+k0s.0
```
**Platform**
Which platform did you run k0s on?
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 10 (buster)
Release:	10
Codename:	buster
```

**What happened?**
The pods on the kube-system are not being created right after deploying k0s and the event shows:

```
5m49s       Warning   Failed              pod/kube-router-cphpf                 Error: failed to create containerd container: get apparmor_parser version: exec: "apparmor_parser": executable file not found in $PATH
```

**How To Reproduce**
Just run the quick installer on armbian (pine64 in my case) then observe the events on the kube-system namespace. 

**Expected behavior**
Everything works fine.

**Screenshots & Logs**
See before

**Additional context**
Installing `apparmor` via `apt` works

**Comment by jnummelin** [comment]
I agree there should be some mention of these type of "indirect" dependencies on the docs. For example something like:
```
If you have apparmor enabled in your host make sure you got all the needed tools in place....
```

In this particular case it's containerd that [sees apparmor is enabled](https://github.com/containerd/containerd/blob/587fc092598791ab58bfa275958ce20cc5d80783/pkg/apparmor/apparmor_linux.go#L35-L44) on the system and it tries to use it to create the profiles. I'm definitely no apparmor expert but having it enabled but not having the needed tools in place for it feels like generic host configuration issue.
