### ISSUE TITLE
HAProxy example should have multiple backends with checks?

### ISSUE THREAD

**Issue by rgl** [k0sproject/k0s#1042]
The example at https://docs.k0sproject.io/v1.21.3+k0s.0/high-availability/#example-configuration-haproxy is suggesting to configure HAProxy as:

```
frontend kubeAPI
    bind :6443
    default_backend back
frontend konnectivityAgent
    bind :8132
    default_backend back
frontend konnectivityServer
    bind :8133
    default_backend back
frontend controllerJoinAPI
    bind :9443
    default_backend back

backend back
    server k0s-controller1 <ip-address1>
    server k0s-controller2 <ip-address2>
    server k0s-controller3 <ip-address3>
```

Isn't this lacking checks? At minimum, check whether a TCP connection can be established?

And for doing that, I think we need to configure multiple backends. One for each port, right?

Also, maybe combine the `frontend`/`backend` in a single `listen` block?

All combined, it should look something alike:

```
listen kubeApiServer
  bind :6443 name kubeApiServer
  option tcp-check
  balance roundrobin
  default-server inter 10s rise 3 fall 3 slowstart 60s maxconn 250 maxqueue 256 weight 100
  server kubeApiServer1 <ip-address1>:6443 check
  server kubeApiServer2 <ip-address2>:6443 check
  server kubeApiServer3 <ip-address3>:6443 check

# AND repeat each listen block for the other ports: 8132, 8133, 9443.
```

What do you think?

**Comment by soider** [comment]
While the example supposed to be just a hint, how to actually LB works, your suggestion looks great! 

Do you want to contribute that example?

**Comment by mviitane** [comment]
Hi @rgl,

The purpose with this example was to provide a simple/minimum configuration for HAProxy.

> Isn't this lacking checks? At minimum, check whether a TCP connection can be established?
`Defaults` section in haproxy.cfg can be used to change the default mode to tcp (as written in the tutorial). Then this doesn’t need to be repeated in other sections.

> And for doing that, I think we need to configure multiple backends. One for each port, right?
This can be done, but it’s not needed. One backend serves the purpose when you don’t configure the port. If the port isn’t specified, then HAProxy will use the same port that the client connected on, and thus one backend is enough.

> Also, maybe combine the frontend/backend in a single listen block?
As I understand you can use `listen` block to do the same as `frontend/backend`. I think it’s a matter of taste which one to use.

**Comment by rgl** [comment]
> The purpose with this example was to provide a simple/minimum configuration for HAProxy.

I think the minimum configuration should include the https health checks. That would show us how to configure a load balancer that has the same/equivalent guarantees as the in-cluster Services provided by Kubernetes (i.e. they do http(s) level health checks). 

I have a working example for the https health check at https://github.com/rgl/rancher-ubuntu-vagrant/blob/12c87d3fed465099ae534a7b2948a72459f13dc7/provision-haproxy.sh#L53-L69, but that is only for the kube-apiserver endpoint. For the other k0s endpoints, I didn't find the health checks documentation, can you please point me to them?

**Comment by mviitane** [comment]
ok, I got your point for https health checks. I just tried the HAProxy with this kind config:

```
frontend kubeAPI
    bind :6443
    default_backend kubeAPI_backend
frontend konnectivityServer
    bind :8132
    default_backend konnectivityServer_backend
frontend controllerJoinAPI
    bind :9443
    default_backend controllerJoinAPI_backend

backend kubeAPI_backend
    server k0s-controller1 <ip-address1>:6443 check check-ssl verify none
    server k0s-controller2 <ip-address2>:6443 check check-ssl verify none
    server k0s-controller3 <ip-address3>:6443 check check-ssl verify none
backend konnectivityServer_backend
    server k0s-controller1 <ip-address1>:8132 check check-ssl verify none
    server k0s-controller2 <ip-address2>:8132 check check-ssl verify none
    server k0s-controller3 <ip-address3>:8132 check check-ssl verify none
backend controllerJoinAPI_backend
    server k0s-controller1 <ip-address1>:9443 check check-ssl verify none
    server k0s-controller2 <ip-address2>:9443 check check-ssl verify none
    server k0s-controller3 <ip-address3>:9443 check check-ssl verify none

```
check-ssl forces encryption of all health checks over SSL. 

When verify is set to 'none', client certificate is not requested. This is to keep it simple and have HAProxy without certificates as it only forwards them in any case (doesn't terminate tls). Of course the certificate validation can be added on top.

What do you think about this example? This would improve the current example config in the docs?

**Comment by rgl** [comment]
> When verify is set to 'none', client certificate is not requested. This is to keep it simple and have HAProxy without certificates as it only forwards them in any case (doesn't terminate tls). Of course the certificate validation can be added on top.

`verify none` is not about the client certificate, its about the backend server certificate.

`verify none` configures haproxy to skip the verification of the backend server certificate (making it accept any server certificate, which invalidates/removes the tls security).

also keep in mind that tls termination is about the connection from the client to haproxy; its not about the connection between haproxy and the backend server.

> What do you think about this example? This would improve the current example config in the docs?

its a little better, but its still not showing us how to do the application level health checks. for this, we need something alike:

```
listen kubeApi
  bind 10.10.0.3:6443 name kubeApi
  option tcplog
  option tcp-check
  option httpchk GET /healthz "HTTP/1.0\r\nHost:controller.k0s.test"
  http-check expect string ok
  log global
  timeout server 1h
  balance roundrobin
  default-server inter 10s rise 3 fall 3 slowstart 60s maxconn 250 maxqueue 256 weight 100
  # verify the health check with:
  #   (printf "GET /healthz HTTP/1.0\r\nHost:controller.k0s.test\r\n\r\n"; sleep 2) | openssl s_client -connect 10.10.0.10:6443 -servername controller.k0s.test -CAfile /etc/ssl/certs/ca-certificates.crt
  # TODO kubeapi requires a client certificate. how to create one for the load balancer?
  # NB somehow, you must add the kubernetes cluster CA into your /etc/ssl/certs/ca-certificates.crt
  server kubeApi1 10.10.0.10:6443 check check-ssl check-sni controller.k0s.test ca-file /etc/ssl/certs/ca-certificates.crt
```

that still needs a client certificate for accessing the backend kubeapi server.

how can we generate a client certificate that allows haproxy to access the kubeapi server `/healthz` endpoint?

**Comment by rgl** [comment]
At https://github.com/rgl/k0s-vagrant/blob/a6c3977352a88e95a0050e57b9af5faa6ab98f75/bootstrap-k0s.sh#L163-L184 I ended up creating a service account for haproxy (which it uses to authenticate in kube-apiserver), and the haproxy configuration now looks like:

```conf
listen kubeApi
  bind 10.10.0.3:6443 name kubeApi
  option tcplog
  option tcp-check
  option httpchk GET /healthz "HTTP/1.0\r\nHost:controller.k0s.test\r\nAuthorization:Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImVtTS1oSlBkQ3FsUXkxenJabnZtQWFNb2xseC1XUFA5QkZUSjZVRm5tUWcifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJoYXByb3h5LXRva2VuLTg2ajY5Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6ImhhcHJveHkiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiI2YmVmYWU4Yy0zYmI2LTQzYzYtOTFkYi00YTZhZjUzOGQwZmMiLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6a3ViZS1zeXN0ZW06aGFwcm94eSJ9.2zP5cS2YlFjmsc_BJ3KISDBw6Ft-SqPJ5ckqm-5bz3jhyfFpRSPXZcsDPmWZ0pgi7Il6e5WPKBzzxY-XPHH8yLXZFESBtt5FYi2uRO9lrRKAqJ11laYLbAOwwMQt2kEO08cb7j3diJwjpuYka0laGUu0G9Is8Av9KuDVykHwR7R_r9mLuSDW3S3n_6LR9a2GFWBdvAPhEE6-pWBrN6GbRiW2kZI7TkOm5_xmLkr95SdDRFLJU74mPDDME8NrOhaOkMBSpF2D6L9aUhzbZtLsG-g21161KITbU3b8ZWVFKUGqJCG9i8bWgLpcE-ckarqnxETlnB3bN-Yok2vAMYwo0g"
  http-check expect string ok
  log global
  timeout server 1h
  balance roundrobin
  default-server inter 10s rise 3 fall 3 slowstart 60s maxconn 250 maxqueue 256 weight 100
  # you can verify the health check with:
  #   (printf "GET /healthz HTTP/1.0\r\nHost:controller.k0s.test\r\nAuthorization:Bearer $(cat /etc/haproxy/sa-token.txt)\r\n\r\n"; sleep 2) | openssl s_client -connect 10.10.0.10:6443 -servername controller.k0s.test -CAfile /etc/haproxy/sa-ca.pem
  server kubeApi1 10.10.0.10:6443 check check-ssl check-sni controller.k0s.test ca-file /etc/haproxy/sa-ca.pem
```

But this is way too cumbersome to bootstrap and has a major caveat, while k0sctl is bootstrapping the cluster, haproxy is not validating the server certificates not does it call the service level health checks (because the server CA and haproxy service account are not yet created).

Maybe k0sctl could somehow help?

Maybe if it would let me run some kind of hook/phase before it tries to use the external cluster address (which is handled by haproxy)? At that time I would generate a service account, and configure haproxy with the service account secret.

Also, I could only find the `/healthz` endpoint of kube-apiserver. How about the other services (konnectivity and controllerJoinApi)? Do they have healthz endpoints? If so, how can I use them?

**Comment by mviitane** [comment]
> verify none is not about the client certificate, its about the backend server certificate.

Correct, my mistake.

> also keep in mind that tls termination is about the connection from the client to haproxy; its not about the connection between haproxy and the backend server.

I consider HAProxy's role in this example just to forward packets, not to terminate TLS in any direction. That's why I've kept this basic example so far without the certs.

> how can we generate a client certificate that allows haproxy to access the kubeapi server /healthz endpoint?

Unfortunately, I don't know this part. For me this topic (with certificates) sounds like an additional chapter after the basic part to cover more details with a more complex example.

**Comment by rgl** [comment]
#1060 is a nice improvement. Thank you!

I could only find the /healthz endpoint of kube-apiserver. How about the other services (konnectivity and controllerJoinApi)? Do they have healthz endpoints? If so, how can I use them?

**Comment by jnummelin** [comment]
konnectivity has healthz endpoint at port 8092:
```
/ # curl -k http://localhost:8092/healthz
ok
```

`controllerJoinApi ` does not have specific health endpoint, thus a TCP check will be only option

**Comment by rgl** [comment]
Ah it was in another port. Maybe that could be added to the docs too.

It would be nice to have a controllerJoinApi healtz endpoint too. Should that be in another issue?

For reference, here's how the health checks currently look in my example:

```
listen kubeApi
  bind 10.10.0.3:6443 name kubeApi
  option tcplog
  option tcp-check
  option httpchk GET /healthz "HTTP/1.0\r\nHost:controller.k0s.test\r\nAuthorization:Bearer SA-TOKEN"
  http-check expect string ok
  log global
  timeout server 1h
  balance roundrobin
  default-server inter 10s rise 3 fall 3 slowstart 60s maxconn 250 maxqueue 256 weight 100
  # you can verify the health check with:
  #   (printf "GET /healthz HTTP/1.0\r\nHost:controller.k0s.test\r\nAuthorization:Bearer $(cat /etc/haproxy/sa-token.txt)\r\n\r\n"; sleep 2) | openssl s_client -connect 10.10.0.10:6443 -servername controller.k0s.test -CAfile /etc/haproxy/sa-ca.pem
  server kubeApi1 10.10.0.10:6443 check check-ssl check-sni controller.k0s.test ca-file /etc/haproxy/sa-ca.pem

listen konnectivity
  bind 10.10.0.3:8132 name konnectivity
  option tcplog
  option tcp-check
  option httpchk GET /healthz "HTTP/1.0\r\nHost:controller.k0s.test"
  http-check expect string ok
  log global
  timeout server 1h
  balance roundrobin
  default-server inter 10s rise 3 fall 3 slowstart 60s maxconn 250 maxqueue 256 weight 100
  # you can verify the health check with:
  #   (printf "GET /healthz HTTP/1.0\r\nHost:controller.k0s.test\r\n\r\n"; sleep 2) | nc 10.10.0.10 8092
  server konnectivity1 10.10.0.10:8132 check port 8092

listen controllerJoinApi
  bind 10.10.0.3:9443 name controllerJoinApi
  option tcplog
  option tcp-check
  log global
  timeout server 1h
  balance roundrobin
  default-server inter 10s rise 3 fall 3 slowstart 60s maxconn 250 maxqueue 256 weight 100
  server controllerJoinApi1 10.10.0.10:9443 check check-ssl check-sni controller.k0s.test ca-file /etc/haproxy/sa-ca.pem
```

the SA-TOKEN and sa-ca.pem are for the haproxy service account that is created in kubernetes. you can see how I'm currently doing it at https://github.com/rgl/k0s-vagrant/blob/a6c3977352a88e95a0050e57b9af5faa6ab98f75/bootstrap-k0s.sh#L165-L184

**Comment by jnummelin** [comment]
> It would be nice to have a controllerJoinApi healtz endpoint too. Should that be in another issue?

Yes, let's deal with that as separate issue

**Comment by rgl** [comment]
The issue about the healtz was created at https://github.com/k0sproject/k0s/issues/1098.

Since that was the only pending question in the issue, I'm closing it.
