### ISSUE TITLE
konnectivity-server port 8133 not available outside the node?

### ISSUE THREAD

**Issue by rgl** [k0sproject/k0s#1043]
At https://docs.k0sproject.io/v1.21.3+k0s.0/high-availability/#load-balancer its mentioned that we should load balance the following ports:

* 6443 (for Kubernetes API)
* 8132 (for Konnectivity agent)
* 8133 (for Konnectivity server)
* 9443 (for controller join API)

But for some reason, in my installation, `8133 (for Konnectivity server)` is only listening at localhost:

```console
root@controller1:~# ss -anp|grep konn|grep -i listen
tcp LISTEN 0 4096 127.0.0.1:8133 0.0.0.0:* users:(("konnectivity-se",pid=2686,fd=9))
tcp LISTEN 0 4096         *:8092       *:* users:(("konnectivity-se",pid=2686,fd=8))
tcp LISTEN 0 4096         *:8132       *:* users:(("konnectivity-se",pid=2686,fd=7))
```

Can you confirm that port 8133 should really be available to the outside of the machine?

If so, can you hint me in how can I troubleshoot why its only listening at localhost?

**Comment by mviitane** [comment]
Yes, I agree. This looks like a bug in the document. These ports are required for the control plane
6443 (for Kubernetes API)
8132 (for Konnectivity)
9443 (for controller join API)

In k0s default configuration port 8133 is set as konnectivity adminPort. This admin port is not needed in the control plane load balancer.
