### ISSUE TITLE
k0s failed to install kube-dns service

### ISSUE THREAD

**Issue by yuha0** [k0sproject/k0s#1058]
**Version**

`v1.21.3+k0s.0`

**Platform**

Debian 11 bullseye with kernel `5.10.0-7-arm64`

**What happened?**

After initialization, k0s failed to install service `kube-dns` in the cluster, although the actual coredns pods were running without problem. I had to manually apply [the manifest](https://github.com/k0sproject/k0s/blob/864a0420c570100fd856e9834a64a8d4a875f395/pkg/component/controller/coredns.go#L209-L235) to fix cluster DNS.

I deployed the cluster with my own ansible playbook. And the config file template can be found [here](https://github.com/yuha0/home-infra/blob/master/ansible/roles/k0s/templates/k0s.yaml.j2).

**How To Reproduce**

Fill the variable placeholders in [my config file template](https://github.com/yuha0/home-infra/blob/master/ansible/roles/k0s/templates/k0s.yaml.j2), and then use it to create a k0s cluster.

**Expected behavior**

k0s should be able to create the service successfully

**Screenshots & Logs**
Probably related k0s logs in syslog:

```
Aug 21 18:13:59 pi0 k0s[2495]: time="2021-08-21 18:13:59" level=info msg="E0821 18:13:59.926145    2602 repair.go
:240] the cluster IP [IPv4]:10.43.0.10 for service kube-dns/kube-system is not allocated; repairing" component=kube-apiserver

...

Aug 21 18:14:01 pi0 k0s[2495]: time="2021-08-21 18:14:01" level=info msg="2021-08-21 18:14:01.789268 W | etcdserver: read-only range request \"key:\\\"/registry/services/specs/kube-system/kube-dns\\\" \" with result \"range_response_count:1 size:1986\" took too long (867.964734ms) to execute" component=etcd

...

Aug 21 18:14:08 pi0 k0s[2495]: time="2021-08-21 18:14:08" level=info msg="W0821 18:14:08.911946    2749 endpointslice_controller.go:305] Error syncing endpoint slices for service \"kube-system/kube-dns\", retrying. Error: failed to update kube-dns-jkqf6 EndpointSlice for Service kube-system/kube-dns: endpointslices.discovery.k8s.io \"kube-dns-jkqf6\" not found" component=kube-controller-manager

...

Aug 21 18:14:08 pi0 k0s[2495]: time="2021-08-21 18:14:08" level=info msg="I0821 18:14:08.913552    2749 event.go:291] \"Event occurred\" object=\"kube-system/kube-dns\" kind=\"Service\" apiVersion=\"v1\" type=\"Warning\" reason=\"FailedToUpdateEndpointSlices\" message=\"Error updating Endpoint Slices for Service kube-system/kube-dns: failed to update kube-dns-jkqf6 EndpointSlice for Service kube-system/kube-dns: endpointslices.discovery.k8s.io \\\"kube-dns-jkqf6\\\" not found\"" component=kube-controller-manager

...

Aug 21 18:14:12 pi0 k0s[2495]: time="2021-08-21 18:14:12" level=info msg="W0821 18:14:12.061021    2749 endpointslice_controller.go:305] Error syncing endpoint slices for service \"kube-system/kube-dns\", retrying. Error: EndpointSlice informer cache is out of date" component=kube-controller-manager
```

**Additional context**

1. My control plane nodes are Raspberry Pi 4 Model B servers, so k8s components may be slow to start.
2. Looking at syslog, k0s only made one attempt to create the service, and failed. Shouldn't it retry until succeed?
3. Is it possible to skip some of [the built-in component deployments](https://docs.k0sproject.io/main/configuration/#specimages)? I'd like to tell k0s to not to worry about deploying CoreDNS as I can do it myself manually post cluster initialization. And I don't need metrics server.

**Comment by jnummelin** [comment]
> After initialization, k0s failed to install service kube-dns in the cluster

What exactly you mean by this? The `kube-dns` service was NOT created at all? If so, then I'd look for some hints in the logs why k0s failed to apply the related manifests for coreDNS.

The log messages you posted kinda hint that the service itself IS created but some of the Kubernetes components fail to populate the endpoints etc on it properly. 

> Looking at syslog, k0s only made one attempt to create the service, and failed

The messages you posted are more about k8s components "operating" on the service rather than k0s _creating_ it. The messages do tell that k8s components should retry the failed operations.

**Comment by jnummelin** [comment]
> Is it possible to skip some of the built-in component deployments? 

Not currently, WIP in PR: https://github.com/k0sproject/k0s/pull/1023
^this will be release with next release

**Comment by yuha0** [comment]
Hi @jnummelin 

> What exactly you mean by this? The kube-dns service was NOT created at all?
> ...
> The log messages you posted kinda hint that the service itself IS created

The service `kube-dns` did not exist in `kube-system` namespace when I checked. I did take a look at the API server log but I didn't see any related failure.

Anyways, to me it looks like some failures happened during cluster initialization, maybe the request didn't reach API server at all. Considering that my manual fix was just `kubectl apply` the service definition, I would expect this to be something that can be done by the k0s daemon? It took quite a while for the control plane nodes on my Raspberry Pi boards to be stabilized, I imagine that I may have a much higher success rate if it could retry applying those components at a later time.

> Not currently, WIP in PR: #1023

Awesome! Super excited about this feature. Thank you!

**Comment by jnummelin** [comment]
> Anyways, to me it looks like some failures happened during cluster initialization, maybe the request didn't reach API server at all.

This is one possibility, at last in theory. k0s main controller does wait to see the kube-api is up and running before it starts rest of the processes, but it might be possible that the api reports healthy status before all internal stuff is fully initialized. And thus the "apply" of coreDNS got broken for some reason. Hard to guess without seeing an actual error in the logs.

**Comment by yuha0** [comment]
Right, there are several `kubectl` related ansible tasks in my playbook (e.g.: adding node labels with `kubectl label node xxx` that need to be retried several times because I found the API servers (or etcd) can be flapping on start. For example, there's once when a new controller node joined my new cluster, etcd leader election kicked in, changed leader node, and caused a downtime of about ~10 seconds.

**Comment by soider** [comment]
@yuha0 can I ask you to share the content of the /var/lib/k0s/manifests?

For example, the output for the `find -type f /var/lib/k0s/manifests` would be great

**Comment by yuha0** [comment]
@soider 

```
> find /var/lib/k0s/manifests/ -type f
/var/lib/k0s/manifests/calico/calico-DaemonSet-calico-node.yaml
/var/lib/k0s/manifests/calico/calico-PodDisruptionBudget-calico-kube-controllers.yaml
/var/lib/k0s/manifests/calico/calico-ServiceAccount-calico-node.yaml
/var/lib/k0s/manifests/calico/calico-Deployment-calico-kube-controllers.yaml
/var/lib/k0s/manifests/calico/calico-ClusterRoleBinding-calico-kube-controllers.yaml
/var/lib/k0s/manifests/calico/calico-IPAMConfig-ipamconfig.yaml
/var/lib/k0s/manifests/calico/calico-ConfigMap-calico-config.yaml
/var/lib/k0s/manifests/calico/calico-ClusterRoleBinding-calico-node.yaml
/var/lib/k0s/manifests/calico/calico-ClusterRole-calico-kube-controllers.yaml
/var/lib/k0s/manifests/calico/calico-ServiceAccount-calico-kube-controllers.yaml
/var/lib/k0s/manifests/calico/calico-ClusterRole-calico-node.yaml
/var/lib/k0s/manifests/konnectivity/konnectivity-agent.yaml
/var/lib/k0s/manifests/bootstraprbac/bootstrap-rbac.yaml
/var/lib/k0s/manifests/coredns/coredns.yaml
/var/lib/k0s/manifests/kubelet/kubelet-config.yaml
/var/lib/k0s/manifests/helm/helm-crd-helm.k0sproject.io_charts.yaml
/var/lib/k0s/manifests/defaultpsp/default-psp.yaml
/var/lib/k0s/manifests/kubeproxy/kube-proxy.yaml
/var/lib/k0s/manifests/calico_init/calico-crd-kubecontrollersconfigurations.crd.projectcalico.org.yaml
/var/lib/k0s/manifests/calico_init/calico-crd-bgppeers.crd.projectcalico.org.yaml
/var/lib/k0s/manifests/calico_init/calico-crd-globalnetworksets.crd.projectcalico.org.yaml
/var/lib/k0s/manifests/calico_init/calico-crd-ippools.crd.projectcalico.org.yaml
/var/lib/k0s/manifests/calico_init/calico-crd-felixconfigurations.crd.projectcalico.org.yaml
/var/lib/k0s/manifests/calico_init/calico-crd-ipamconfigs.crd.projectcalico.org.yaml
/var/lib/k0s/manifests/calico_init/calico-crd-networksets.crd.projectcalico.org.yaml
/var/lib/k0s/manifests/calico_init/calico-crd-ipamblocks.crd.projectcalico.org.yaml
/var/lib/k0s/manifests/calico_init/calico-crd-hostendpoints.crd.projectcalico.org.yaml
/var/lib/k0s/manifests/calico_init/calico-crd-globalnetworkpolicies.crd.projectcalico.org.yaml
/var/lib/k0s/manifests/calico_init/calico-crd-blockaffinities.crd.projectcalico.org.yaml
/var/lib/k0s/manifests/calico_init/calico-crd-ipamhandles.crd.projectcalico.org.yaml
/var/lib/k0s/manifests/calico_init/calico-crd-networkpolicies.crd.projectcalico.org.yaml
/var/lib/k0s/manifests/calico_init/calico-crd-bgpconfigurations.crd.projectcalico.org.yaml
/var/lib/k0s/manifests/calico_init/calico-crd-clusterinformations.crd.projectcalico.org.yaml
/var/lib/k0s/manifests/metricserver/metric_server.yaml
```

And `/var/lib/k0s/manifests/coredns/coredns.yaml` has the expected service definition for `kube-dns`.

**Comment by yuha0** [comment]
With the new `v1.22.1+k0s.0`, I can finally manage kube-dns myself. That's always what I want, so this issue does not affect me anymore.

**Comment by jnummelin** [comment]
> With the new v1.22.1+k0s.0, I can finally manage kube-dns myself. That's always what I want, so this issue does not affect me anymore.

Why is k0s managed codeDNS not an option for you?

**Comment by jnummelin** [comment]
@yuha0 sounds reasonable. And for this purpose the nature of k0s being "bare bones" suits quite well.
