### ISSUE TITLE
Windows Worker DNS resolution and external traffic

### ISSUE THREAD

**Issue by Crespalvaro** [k0sproject/k0s#1080]
$ k0s version
v1.20.6+k0s.0
```
**Platform**
Control Plane: Ubuntu latest
Windows worker: Windows Server Core 1909 build 18363
```
Contex:

On a first successful installation I was using Windows Server Core 2019. However, my windows pods didnt had access outside of the cluster. After investigating for a while I discovered a message from Calico reporting that the minimun Windows Server build should be higher than 18317 as its using DSR Direct Server Return.

Thus, I switched to version 1909 as Its the only one I have access with a higher build version.

Regarding container runtime Im using docker. In the first installation I was using docker desktop which was giving me some problems. Therefore, as docker desktop is not intended to be used with Windows Server, [DockerMsftProvider](https://docs.microsoft.com/en-us/virtualization/windowscontainers/quick-start/set-up-environment?tabs=Windows-Server) should be used instead and I switched to it.

At the beggining everything was fine but Docker is still not stable as now Im getting an error trying to operate with the docker client:
$ docker version
Client: Mirantis Container Runtime
 Version:           20.10.6
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        b3766ff
 Built:             06/29/2021 17:14:16
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true
error during connect: In the default daemon configuration on Windows, the docker client must be run with elevated privileges to connect.: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/version: open //./pipe/docker_engine: The system cannot find the file specified.

Im suppose to get this error due to non elevated or not enough permissions. However, Im running all the command from an elevated powershell (Start-Process powershell -Verb runAs). Im on a test environment, so not a powerfull machine, and sometimes docker timeout pulling and/or extracting those huge microsoft images, thats why sometimes I have to manually pull them. I dont know if this issue will persist on a prod environment but still I have some concerns:

- Could the pod external network issue be related with docker?
- [Windows (Experimental)](https://docs.k0sproject.io/v1.21.3+k0s.0/experimental-windows/) documentation specify mirantis container runtime its required for calico setup. I didnt installed MCR and my cluster its working totally fine appart from the 2 issues already mentioned (pod internet and docker client) so as MCR installs docker enterprise, I guess we are suppose to use as cri docker engine provided in MCR which means MCR is not only needed for calico setup but a required dependency. From my point of view this is a completly wrong approach as turns an open source and free solution into a paid solution. Would MCR fix those issues? Would it provide anything else? I think this is something that needs to be clarified.

**How To Reproduce**
Installing k0s on a windows node its very tricky right now, thus I wont provide any guide of how to reproduce this issue due to its complexity at least until someone requests it.

**Expected behavior**
A clean installation of k0s windows worker node

**Screenshots & Logs**
Also add any output from kubectl if applicable:
```
If you think so I can provide kubectl and calico logs
```

**Comment by jnummelin** [comment]
AFAIK there should be no difference from k0s/kube point of view which package provides the Docker daemon on the node. Thus we should mention MCR as _one_ option to be used.

> Could the pod external network issue be related with docker?

It is possible. Have you tried running a plain container directly with docker client and see if it gets external connectivity?

There's an open PR (#654) that intended to get plain containerd to be used as the runtime on windows too though that hit some roadblocks with Calico. Those issues _should_ be resolved on Calico side now so we should probably re-open that development.

**Comment by Crespalvaro** [comment]
At the end the issue was related with something I mentioned at the beggining of this thread. We switched Windows version in order to make use of this Windows DSR feature. 

Following the documentation of k8s, section , [Networking Limitations](https://kubernetes.io/docs/setup/production-environment/windows/intro-windows-in-kubernetes/#networking-limitations) running kube-proxy in DSR mode enabled allows local traffic policy.

Taking into account that Overlay networking (VXLAN mode with calico) is in Alpha and not stable, enabling DSR was the solution as it probably applied more stability. To do so, we enabled --feature-gates="WinDSR=true" and --enable-dsr=true flags in kube-proxy service in addition to the ones you are already configuring.

**Comment by jnummelin** [comment]
> To do so, we enabled --feature-gates="WinDSR=true" and --enable-dsr=true flags in kube-proxy service in addition to the ones you are already configuring.

Does this mean we need to turn this into an "enhancement" issue so that we would allow configuring extra flags etc. for kube-proxy on Windows?

**Comment by Crespalvaro** [comment]
Most likely yes. Allowing the user specify kube-proxy extra flags would avoid us to fork and rebuild k0s as currently only support kubelet extra flags. However, I think I would be a nice approach as well to test and double check if this specific flags we are talking about should be set by default.

Btw thanks a lot for your help along this issue

**Comment by jnummelin** [comment]
Marking then as enhancement.
