### ISSUE TITLE
[Feature request] make master(s) visible on k0s and add taints to disable workloads

### ISSUE THREAD

**Issue by xinity** [k0sproject/k0s#1086]
**Is your feature request related to a problem? Please describe.**
It could be frustrating not seeing cluster masters when you fire a: `kubectl get nodes -o wide`

**Describe the solution you'd like**
It could be a better option to add taints to the master which would then disable workloads and make them "visible", than "hide" them

**Comment by jnummelin** [comment]
This is actually something we've been discussing every now-and-then. I'm (personally) slightly inclined to add controllers as nodes to kube api. The main reason being the fact that a k0s controller node will NOT ever get to a `Ready` state. That would result into few very odd feeling issues for the end-user:
- DaemonSet pods would be created for those, but "stuck" in `Pending` state forever
- User see the node and taints and all, but cannot ever make the node schedulable. Might give totally wrong idea what it is
- Might cause some side effects on other controllers/operators which operate on node objects

However we have been thinking if it would make sense to have a CRD for the k0s controller nodes to get those registered by the controllers and updating the status etc info on those.

**Comment by ncopa** [comment]
You can already now start the controllers with `--enable-worker` and then add the taints and they should become visible if that is important for you.

**Comment by jnummelin** [comment]
> they should become visible if that is important for you.

Well, `--enable-worker` does have the _slight_ side-effect of running the workloads too on the controller node. :)

**Comment by xinity** [comment]
@jnummelin but correctly tainted it shouldn't right? 😉

I'm asking because I aim to use k0s deployed with k0sctl for my kubernetes training attendees. And have the ability to see the masters is in this case useful even though I completely understand your point in hiding them by default

Which lends me to the point of how to add the correct opinion when I use k0sctl to deploy the cluster?

**Comment by ncopa** [comment]
> > they should become visible if that is important for you.
> 
> Well, `--enable-worker` does have the _slight_ side-effect of running the workloads too on the controller node. :)

That was the intention, as I understood it, and then control it with taints?

**Comment by jnummelin** [comment]
@xinity IF you really want to run controllers with `--enable-worker` and the "side-effects" are OK you should use something like this in k0sctl:
```
spec:
  hosts:
  - role: controller+worker
    ssh:
      address: 10.0.0.1
```
Currently k0sctl does NOT configure taints so you must do that in some other way.

But as said, I'm quite hesitant on putting plain controller (not running with `--enable-worker` or `--singe`) as a node into the kube api. IMO that'll create just too much confusion.

**Comment by xinity** [comment]
got it @jnummelin the good point is , i'll battle test it by tomorrow for you :)
I'll keep you posted for sure on how it goes :)

**Comment by sedlund** [comment]
I am making the masters worker nodes as well tainting them with:

`kubectl taint nodes master1 node-role.kubernetes.io/master=:NoSchedule`

This allows prometheus and loki deployments to use tolerations and schedule there and monitor them.

Ideally I think k0s should add a node label to the masters:
`kubectl label node master1 node-role.kubernetes.io/control-plane=true`

that way you can use a label selector to taint all the masters with one command

`kubectl taint nodes -l node-role.kubernetes.io/control-plane=true node-role.kubernetes.io/master=:NoSchedule`

**Comment by jnummelin** [comment]
> Ideally I think k0s should add a node label to the masters

You mean when the controller is run with `--enable-worker`? If yes, then I agree that k0s should do it automatically. As well as add the standard taint for it.

**Comment by jnummelin** [comment]
When we implement this, one things that needs to be confirmed is that all the system components like networking, kube-proxy etc. have proper tolerations in place.
