### ISSUE TITLE
Having a docker-configured ContainerD config.toml on a system breaks kubelet startup

### ISSUE THREAD

**Issue by trawler** [k0sproject/k0s#1095]
**Version**
```
$ v1.22.1+k0s and up
```
**What happened?**
When running k0s worker (or controller with a worker enabled set-up), kubelet fails to start with the following error:
```
Sep 02 12:56:02 controller-0 k0s[2007862]: time="2021-09-02 12:56:02" level=info msg="E0902 12:56:02.139045 2009500 server.go:294] \"Failed to run kubelet\" e
rr=\"failed to run Kubelet: failed to create kubelet: get remote runtime typed version failed: rpc error: code = Unimplemented desc = unknown service runtime.
v1alpha2.RuntimeService\"" component=kubelet
Sep 02 12:56:02 controller-0 k0s[2007862]: time="2021-09-02 12:56:02" level=warning msg="exit status 1" component=kubelet
```

**Root Cause**
This problem only happens in systems that have containerd instance that's originally installed by `docker` and contains the following line:
```
disabled_plugins = ["cri"]
```
Since docker doesn't need CRI, it was disabled in https://github.com/docker/engine/pull/29, but kubelet does.
When starting k0s, containerd picks up the default `config.toml` created by the docker installation, and kubelet startup breaks. By removing the docker-created config.toml, or by enabling the cri plugin, kubelet starts up as expected.

The reason this is happening now, is that kubernetes just now implemented the deprecation of docker-shim that was announced back in December: https://kubernetes.io/blog/2020/12/02/dockershim-faq/#when-will-dockershim-be-removed

**How To Reproduce**
Run k0s version 1.22 and up on a system that has docker installed.

**Workaround**

The temporary workaround is to create separate containerd config before starting k0s
```
mkdir /etc/k0s
touch /etc/k0s/containerd.toml 
```
This trigger k0s to use the found file as the config for containerd as described in https://docs.k0sproject.io/v1.22.1+k0s.0/runtime/#containerd-configuration

And as the file is empty it'll make containerd to use the default config as k0s would expect anyways.

**Comment by ncopa** [comment]
We used to explicitly add `--config=/etc/k0s/containerd.toml` but with containerd 1.5 it fails to start up if the file is missing, and apparently it picks up the system containerd (docker's) config by default.

related commit 20b8f6f7f227277c7a655bf6e00cb2370c1853f2

**Comment by xinfengliu** [comment]
I have a feeling that we may add an empty `/etc/k0s/containerd.toml` during k0s provisioning or k0supgrade (if the file does not exist). 
I believer many users have docker installed when they run k0s, they will hit this issue.
