### ISSUE TITLE
k0s behind company proxy

### ISSUE THREAD

**Issue by wheestermans31** [k0sproject/k0s#1099]
The standard in our company is to get outside using proxy. How can I configure the proxy, so that the retrieval of images passes the proxy. Tried using the standard HTTP_PROXY and HTTPS_PROXY variables, but without success.

**Comment by wheestermans31** [comment]
We have a solution for this?

**Comment by jnummelin** [comment]
@wheestermans31 how did you set up the proxy envs for k0s?

In docs there's some example how to setup the proxy envs via systemd drop-in file: https://docs.k0sproject.io/v1.22.1+k0s.0/environment-variables/

**Comment by wheestermans31** [comment]
Trying the single instance setup 

/usr/local/bin/k0s install controller --single --debug
/usr/local/bin/k0s start

**Comment by wheestermans31** [comment]
On Oracle Linux

**Comment by xinfengliu** [comment]
I tested the systemd drop-in as @jnummelin suggested , it works as expected. I tested both `k0s v1.22.1` which uses containerd `1.5.5` and `k0s v1.21.2` which uses containerd `1.4.4`. 
 
`NO_PROXY` is also needed to exclude pod CIDR, k8s service CIDR and nodes subnet CIDR. Here's my example:
```
[Service]
Environment="HTTP_PROXY=socks5://172.27.130.158:1080"
Environment="HTTPS_PROXY=socks5://172.27.130.158:1080"
Environment="NO_PROXY=10.0.0.0/8,192.168.146.0/24"
```
You need to apply the drop-in to `k0scontroller` systemd service or `k0sworker` systemd service on all nodes.

**Comment by wheestermans31** [comment]
Ok, I just cleaned my single node setup, trued to recreated on my Oracle Linux 7, but now other issue, let me try to fix this first? Our Oracle Linux install is causing me a lot of issues so far.

See, https://github.com/k0sproject/k0s/issues/1107

**Comment by wheestermans31** [comment]
Problem was due to misconfigured proxy configuration.

**Comment by wheestermans31** [comment]
The following proxy settings solved the issue.

/etc/systemd/system/k0scontroller.service.d/http-proxy.conf
[Service]
Environment="HTTP_PROXY=http://proxy.common.eu.corp.toyota.com:8080"
Environment="HTTPS_PROXY=http://proxy.common.eu.corp.toyota.com:8080"
Environment="NO_PROXY=localhost,127.0.0.1,10.0.0.0/8,192.168.146.0/24"
