### ISSUE TITLE
Multiple kubernetes versions?

### ISSUE THREAD

**Issue by rgl** [k0sproject/k0s#1101]
**Is your feature request related to a problem? Please describe.**

As of today, the [external-dns add-on is not compatible with kubernetes 1.22](https://github.com/kubernetes-sigs/external-dns/issues/2168). As such, I cannot upgrade to latest k0s.

Is/will/are multiple kubernetes versions supported? For example, is having the same [support cycle of kubernetes be followed (i.e. last three minor versions: 1.22.x, 1.21.x, 1.20.x)](https://kubernetes.io/releases/)?

**Describe the solution you'd like**

Somehow let me declare the kubernetes version and/or have a release for each kubernetes branch.

**Comment by jnummelin** [comment]
We are bumping up the older k0s version too, e.g. 1.21.4+k0s was just released.

What comes to 1.20 series I think we go pretty much by the community needs, if there's users who want newer 1.20.x, then we do it.

Having a same set of k0s features for ALL supported kube releases is not really technically doable, or at least not an easy thing. Thus the new k0s features will typically only land into the latest kube minor version "branch"

**Comment by rgl** [comment]
It would be nice to have that documented so we known what to expect from the k0s project. Namely, how will it address the multiple kubernetes branches (e.g. k0s will follow all the current kubernetes branches) and how new k0s features will be introduced (e.g. only in the latest kubernetes branch).
