### ISSUE TITLE
Separate `lint` target into own workflow

### ISSUE THREAD

**Issue by jnummelin** [k0sproject/k0s#1106]
Currently the lint job is slightly flaky:
```
  Running [/home/runner/golangci-lint-1.29.0-linux-amd64/golangci-lint run --out-format=github-actions] in [] ...
  level=error msg="Timeout exceeded: try increasing it by passing --timeout option"
  
  Error: golangci-lint exit with code 4
  Ran golangci-lint in 365299ms
```

The part that makes this super frustrating is the fact that GH actions only allow to re-run ALL the jobs in a workflow. So to get the lint to pass we need to always re-run ALL smokes etc..

So we should really separate the lint job to a separate workflow so we do not have to re-run everything when only lint fails with some flake.

**Comment by soider** [comment]
obsoleted via #1132
