### ISSUE TITLE
Error spinning up single node k0s on Oracle Linux

### ISSUE THREAD

**Issue by wheestermans31** [k0sproject/k0s#1107]
To be able to check some other ticket for accessing images behind company proxy, I cleaned my previous k0s single node installation, stop/reset + restart server. But now the k0s doesn't even come up correctly.

Running Oracle Linux:
Linux lxdocapa16 3.10.0-1160.11.1.el7.x86_64 #1 SMP Tue Dec 15 11:58:45 PST 2020 x86_64 x86_64 x86_64 GNU/Linux

Logs:
[k0s.log](https://github.com/k0sproject/k0s/files/7116431/k0s.log)

Seems my Oracle Linux 4 node causes me a lot of issues so far.

**Comment by wheestermans31** [comment]
The following processes are running:

sh-4.2# ps -ef | grep k0s
root       4853      1  1 15:50 ?        00:00:11 /usr/local/bin/k0s controller --debug=true --single=true
kube-ap+   4875   4853  2 15:50 ?        00:00:17 /var/lib/k0s/bin/kine --endpoint=sqlite:///var/lib/k0s/db/state.db?more=rwc&_journal=WAL&cache=shared --listen-address=unix:///run/k0s/kine/kine.sock:2379
kube-ap+   4885   4853  5 15:50 ?        00:00:43 /var/lib/k0s/bin/kube-apiserver --v=1 --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname --advertise-address=10.100.114.93 --requestheader-client-ca-file=/var/lib/k0s/pki/front-proxy-ca.crt --service-cluster-ip-range=10.96.0.0/12 --tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 --enable-bootstrap-token-auth=true --proxy-client-cert-file=/var/lib/k0s/pki/front-proxy-client.crt --requestheader-extra-headers-prefix=X-Remote-Extra- --requestheader-username-headers=X-Remote-User --service-account-jwks-uri=https://kubernetes.default.svc/openid/v1/jwks --proxy-client-key-file=/var/lib/k0s/pki/front-proxy-client.key --requestheader-group-headers=X-Remote-Group --anonymous-auth=false --requestheader-allowed-names=front-proxy-client --allow-privileged=true --tls-cert-file=/var/lib/k0s/pki/server.crt --insecure-port=0 --profiling=false --enable-admission-plugins=NodeRestriction,PodSecurityPolicy --secure-port=6443 --authorization-mode=Node,RBAC --client-ca-file=/var/lib/k0s/pki/ca.crt --tls-private-key-file=/var/lib/k0s/pki/server.key --service-account-signing-key-file=/var/lib/k0s/pki/sa.key --kubelet-client-certificate=/var/lib/k0s/pki/apiserver-kubelet-client.crt --kubelet-certificate-authority=/var/lib/k0s/pki/ca.crt --api-audiences=https://kubernetes.default.svc --service-account-issuer=https://kubernetes.default.svc --kubelet-client-key=/var/lib/k0s/pki/apiserver-kubelet-client.key --service-account-key-file=/var/lib/k0s/pki/sa.pub --etcd-servers=unix:///run/k0s/kine/kine.sock:2379
kube-sc+   5006   4853  0 15:50 ?        00:00:02 /var/lib/k0s/bin/kube-scheduler --kubeconfig=/var/lib/k0s/pki/scheduler.conf --v=1 --bind-address=127.0.0.1 --leader-elect=true --profiling=false --authentication-kubeconfig=/var/lib/k0s/pki/scheduler.conf --authorization-kubeconfig=/var/lib/k0s/pki/scheduler.conf --leader-elect=false
kube-ap+   5021   4853  1 15:50 ?        00:00:13 /var/lib/k0s/bin/kube-controller-manager --authentication-kubeconfig=/var/lib/k0s/pki/ccm.conf --cluster-signing-cert-file=/var/lib/k0s/pki/ca.crt --v=1 --node-cidr-mask-size=24 --cluster-signing-key-file=/var/lib/k0s/pki/ca.key --requestheader-client-ca-file=/var/lib/k0s/pki/front-proxy-ca.crt --service-account-private-key-file=/var/lib/k0s/pki/sa.key --cluster-cidr=10.244.0.0/16 --service-cluster-ip-range=10.96.0.0/12 --allocate-node-cidrs=true --bind-address=127.0.0.1 --cluster-name=k0s --terminated-pod-gc-threshold=12500 --kubeconfig=/var/lib/k0s/pki/ccm.conf --client-ca-file=/var/lib/k0s/pki/ca.crt --enable-hostpath-provisioner=true --use-service-account-credentials=true --controllers=*,bootstrapsigner,tokencleaner --profiling=false --authorization-kubeconfig=/var/lib/k0s/pki/ccm.conf --root-ca-file=/var/lib/k0s/pki/ca.crt --leader-elect=true --leader-elect=false

**Comment by wheestermans31** [comment]
Previously I had kubelet related issues, see https://github.com/k0sproject/k0s/issues/1095. But now not seeing any of the failures, so looks to me something else

**Comment by wheestermans31** [comment]
I don't see the single node coming up after 

sh-4.2# /usr/local/bin/k0s install controller --single --debug
sh-4.2# /usr/local/bin/k0s install start
sh-4.2# /usr/local/bin/k0s kubectl get node
No resources found
sh-4.2# /usr/local/bin/k0s kubectl get pod --all-namespaces
NAMESPACE     NAME                              READY   STATUS    RESTARTS   AGE
kube-system   coredns-5ccbdcc4c4-9v4qh          0/1     Pending   0          21m
kube-system   metrics-server-6bd95db5f4-w9hf6   0/1     Pending   0          21m

**Comment by wheestermans31** [comment]
Issue due to misconfigured proxy configuration! Closed.

**Comment by mrfy** [comment]
Hi @wheestermans31, I've got same problem: after starting k0s with `--enable-worker` flag, k0s service starts but does not create worker node. What does "misconfigured proxy configuration" mean in your solution? Thanks :)
