### ISSUE TITLE
Konnectivity pod access to metrics server going out of the cluster

### ISSUE THREAD

**Issue by wheestermans31** [k0sproject/k0s#1117]
We have two konnectivity pods running (two worker nodes)

```
NAME                              READY   STATUS    RESTARTS      AGE     IP               NODE         NOMINATED NODE   READINESS GATES
konnectivity-agent-67w2s          1/1     Running   0             2m29s   10.244.1.68      lxdocapa23   <none>           <none>
konnectivity-agent-cvn4m          1/1     Running   0             2m28s   10.244.0.99      lxdocapa22   <none>           <none>

metrics-server-6bd95db5f4-dv5sn   1/1     Running   0             4m19s   10.244.1.57      lxdocapa23   <none>           <none>

```
What we see is that for some reason the access to to metrics pod, over the service IP is always passing our company firewall instead of staying internally inside the cluster.

We are running oracle Linux 7 and we have set proxy configuration on the controller and worker level. But to my opinion , this is not even in scope for internal cluster communication.

Controller

```
/etc/systemd/system/k0scontroller.service.d/http-proxy.conf
[Service]
Environment="HTTP_PROXY=http://proxy.common.eu.corp.toyota.com:8080"
Environment="HTTPS_PROXY=http://proxy.common.eu.corp.toyota.com:8080"
Environment="NO_PROXY=localhost,127.0.0.1,10.0.0.0/8,192.168.146.0/24,10.100.114.0/24"

```

Worker

```
/etc/systemd/system/k0sworker.service.d/http-proxy.conf
[Service]
Environment="HTTP_PROXY=http://proxy.common.eu.corp.toyota.com:8080"
Environment="HTTPS_PROXY=http://proxy.common.eu.corp.toyota.com:8080"
Environment="NO_PROXY=localhost,127.0.0.1,10.0.0.0/8,192.168.146.0/24,10.100.114.0/24"
```

I even tried setting proxy on the konnectivity daemonset .

But the konnectivity  pod seems to connect all the time to the metrics server via our company firewall, meaning leaving the cluster network. Not normal to my opinion. I don't see what this may happen.

**Comment by wheestermans31** [comment]
In normal scenario, proxy is even out-of-scope, this is internal cluster communication I would say.

**Comment by jnummelin** [comment]
> konnectivity pod seems to connect all the time to the metrics server via our company firewall

That does sound odd indeed. What kind of traffic is seen? In which case does this happen? Does it happen when you connect to metrics directly from the host?

As you said, the connection should go like konnectivity pod --> metrics svc --> metrics pod. Of course the metrics svc being a "normal" set of iptables managed by kube-proxy.

Just some random-ish ideas:
Do you have multiple interfaces on the nodes? by default kube-proxy uses ALL interfaces to bind the GoBGP daemon and I'm just thinking could this cause the traffic to be routed via wrong interface? See: https://github.com/cloudnativelabs/kube-router/blob/master/docs/bgp.md#bgp-listen-address-list

**Comment by wheestermans31** [comment]
Checking...

**Comment by wheestermans31** [comment]
The issue is seen when the metrics pod is restarted, during that time the request over the metrics service IP seems to leave the cluster and passing the company firewall. Once the metrics is up, no new deny entries on the firewall level. I have tested restarting all other pods, like proxy, router,... the ones in default installation, in kube-system, no issue, until the metrics one is restarted.

**Comment by wheestermans31** [comment]
Scaling the metrics deployment to 0 is not causing the same issue, seems to be when pod is killed the hard way using kubectl -n kube-system delete.

**Comment by jnummelin** [comment]
> request over the metrics service IP seems to leave the cluster and passing the company firewall

Can you see from where the request originates from?

From the API there's a constant "ping" to the metrics API as it's registered as API extension. (To have kubectl top commands working). The API is configured to connect to cluster services via konnectivity tunnel. Hence would be interesting to see where the traffic originates, from the controller (API ) or from worker (konnectivity agent).

**Comment by jnummelin** [comment]
Closing as non active, @wheestermans31  reopen if still an issue
