### ISSUE TITLE
Donate k0s to CNCF?

### ISSUE THREAD

**Issue by ThomasLohmann** [k0sproject/k0s#1118]
Hi everyone,

any plans to donate k0s to CNCF like k3s did? It could boost k0s to the next level and make it probably the default distro for a lot of projects in the future. Otherwise, it could be quite hard for k0s to achieve the same reach like k3s, kops and Kubespray have at the moment. In addition, I believe that mainly the donated CNCF projects will survive in the long-run. Since most clients don't prefer any kind of lock in/Walled Garden + most developers will support the CNCF projects.

See the following link (k3s is currently the only CNCF distro): https://landscape.cncf.io/card-mode?category=certified-kubernetes-distribution&grouping=category&selected=k3s

Regards,
Thomas

**Comment by ncopa** [comment]
Interesting idea! We don't have any current plans for this but may look into this in the future.

Thanks!
