### ISSUE TITLE
Traefik Helm Chart Seems to be ignored Completely

### ISSUE THREAD

**Issue by dmlond** [k0sproject/k0s#1122]
**Version**
```
$ k0s version
```
v1.22.1+k0s.1

**Platform**
Which platform did you run k0s on?
```
$ lsb_release -a
```
Tried on a Fedora 34 machine and an Ubuntu 18.04

**What happened?**

I was following along with the installation guide to install k0s on these machines. I was able to get k0s running very easily. But when I tried to install the Traefik ingress packages using the helm extensions, I experienced the same issue both times, it deploys the metallb deployment, and service, etc. but it does not deploy ANYTHING for traefik. It is as if it is not even running the helm chart at all. My goal is to deploy a single node k0s with ingress using Traefik.

**How To Reproduce**
How can we reproduce this issue? (as minimally and as precisely as possible)

curl -sSLf https://get.k0s.sh | sudo sh
k0s default-config > k0s.yaml
cat <EOF >> k0s.yaml
  extensions:
    helm:
      repositories:
      - name: traefik
        url: https://helm.traefik.io/traefik
      - name: bitnami
        url: https://charts.bitnami.com/bitnami
      charts:
      - name: traefik
        chartname: traefik/traefik
        version: "9.11.0"
        namespace: default
      - name: metallb
        chartname: bitnami/metallb
        version: "1.0.1"
        namespace: default
        values: |2
          configInline:
            address-pools:
            - name: generic-cluster-pool
              protocol: layer2
              addresses:
              - 192.168.0.5-192.168.0.10
EOF
# ensure proper indentation of yaml
sudo k0s install controller -c k0s.yaml --enable-worker
sudo k0s start
sudo k0s kubectl get events --wait
# wait for it to settle down a few minutes
sudo k0s kubectl get all

**Expected behavior**

I expect it to install all the things that are shown in the 'Traefik Ingress Controller' documentation for my version of k0s
NAME                                                 READY   STATUS    RESTARTS   AGE
pod/metallb-1607085578-controller-864c9757f6-bpx6r   1/1     Running   0          81s
pod/metallb-1607085578-speaker-245c2                 1/1     Running   0          60s
pod/traefik-1607085579-77bbc57699-b2f2t              1/1     Running   0          81s

NAME                         TYPE           CLUSTER-IP       EXTERNAL-IP      PORT(S)                      AGE
service/kubernetes           ClusterIP      10.96.0.1        <none>           443/TCP                      96s
service/traefik-1607085579   LoadBalancer   10.105.119.102   192.168.0.5      80:32153/TCP,443:30791/TCP   84s

NAME                                        DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR            AGE
daemonset.apps/metallb-1607085578-speaker   1         1         1       1            1           kubernetes.io/os=linux   87s

NAME                                            READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/metallb-1607085578-controller   1/1     1            1           87s
deployment.apps/traefik-1607085579              1/1     1            1           84s

NAME                                                       DESIRED   CURRENT   READY   AGE
replicaset.apps/metallb-1607085578-controller-864c9757f6   1         1         1       81s
replicaset.apps/traefik-1607085579-77bbc57699              1         1         1       81s

**Screenshots & Logs**
Also add any output from kubectl if applicable:
```
$ export KUBECONFIG=/var/lib/k0s/pki/admin.conf
$ kubectl logs ...
```

sudo k0s kubectl get events --watch
LAST SEEN   TYPE     REASON              OBJECT                                     MESSAGE
0s          Normal   ScalingReplicaSet   deployment/metallb-1631628138-controller   Scaled up replica set metallb-1631628138-controller-689bfb9d7b to 1
0s          Normal   SuccessfulCreate    replicaset/metallb-1631628138-controller-689bfb9d7b   Created pod: metallb-1631628138-controller-689bfb9d7b-5ppjx
0s          Warning   FailedScheduling    pod/metallb-1631628138-controller-689bfb9d7b-5ppjx    no nodes available to schedule pods
0s          Warning   FailedToCreateEndpoint   endpoints/kube-dns                                    Failed to create endpoint for service kube-system/kube-dns: endpoints "kube-dns" already exists
0s          Warning   FailedScheduling         pod/metallb-1631628138-controller-689bfb9d7b-5ppjx    0/1 nodes are available: 1 node(s) had taint {node.kubernetes.io/not-ready: }, that the pod didn't tolerate.
0s          Normal    RegisteredNode           node/vlf-admin03-t04                                  Node vlf-admin03-t04 event: Registered Node vlf-admin03-t04 in Controller
0s          Normal    Scheduled                pod/metallb-1631628138-controller-689bfb9d7b-5ppjx    Successfully assigned default/metallb-1631628138-controller-689bfb9d7b-5ppjx to vlf-admin03-t04
0s          Normal    SuccessfulCreate         daemonset/metallb-1631628138-speaker                  Created pod: metallb-1631628138-speaker-5f4qk
0s          Normal    Scheduled                pod/metallb-1631628138-speaker-5f4qk                  Successfully assigned default/metallb-1631628138-speaker-5f4qk to vlf-admin03-t04
0s          Normal    Pulling                  pod/metallb-1631628138-speaker-5f4qk                  Pulling image "docker.io/bitnami/metallb-speaker:0.9.5-debian-10-r4"
0s          Normal    Pulling                  pod/metallb-1631628138-controller-689bfb9d7b-5ppjx    Pulling image "docker.io/bitnami/metallb-controller:0.9.5-debian-10-r5"
0s          Normal    Pulled                   pod/metallb-1631628138-speaker-5f4qk                  Successfully pulled image "docker.io/bitnami/metallb-speaker:0.9.5-debian-10-r4" in 4.042247279s
0s          Normal    Created                  pod/metallb-1631628138-speaker-5f4qk                  Created container metallb-speaker
0s          Normal    Started                  pod/metallb-1631628138-speaker-5f4qk                  Started container metallb-speaker
0s          Normal    Pulled                   pod/metallb-1631628138-controller-689bfb9d7b-5ppjx    Successfully pulled image "docker.io/bitnami/metallb-controller:0.9.5-debian-10-r5" in 5.828185437s
0s          Normal    Created                  pod/metallb-1631628138-controller-689bfb9d7b-5ppjx    Created container metallb-controller
0s          Normal    Started                  pod/metallb-1631628138-controller-689bfb9d7b-5ppjx    Started container metallb-controller

sudo k0s kubectl get all
NAME                                                 READY   STATUS    RESTARTS   AGE
pod/metallb-1631628138-controller-689bfb9d7b-5ppjx   1/1     Running   0          6m20s
pod/metallb-1631628138-speaker-5f4qk                 1/1     Running   0          5m43s

NAME                 TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
service/kubernetes   ClusterIP   10.96.0.1    <none>        443/TCP   6m36s

NAME                                        DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR            AGE
daemonset.apps/metallb-1631628138-speaker   1         1         1       1            1           kubernetes.io/os=linux   6m20s

NAME                                            READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/metallb-1631628138-controller   1/1     1            1           6m20s

NAME                                                       DESIRED   CURRENT   READY   AGE
replicaset.apps/metallb-1631628138-controller-689bfb9d7b   1         1         1       6m20s

# above was on Ubuntu 18.04, it is similar on fedora 34

**Additional context**

**Comment by soider** [comment]
It looks like the k0s.yaml you are using is broken.

Everything should go under the spec key, for example 

```
apiVersion: k0s.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s
spec:
  extensions:
    helm:
      repositories:
        - name: traefik
          url: https://helm.traefik.io/traefik
        - name: bitnami
          url: https://charts.bitnami.com/bitnami
      charts:
              - name: traefik
                chartname: traefik/traefik
                version: "9.11.0"
                namespace: default
              - name: metallb
                chartname: bitnami/metallb
                version: "1.0.1"
                namespace: default
                values: |2
                  configInline:
                    address-pools:
                    - name: generic-cluster-pool
                      protocol: layer2
                      addresses:
                      - 192.168.0.5-192.168.0.10
```

**Comment by dmlond** [comment]
its hard to copy paste stuff with proper indentation. My yaml had everything under spec.extensions the same way the documentation had it. it installed metallb, but did not install traefik.

**Comment by dmlond** [comment]
I will try your conf, though, to see if it works on my machine.

**Comment by xinfengliu** [comment]
The `traefik` chart version `9.11.0` no longer works on kube `1.22` or above. See: https://github.com/traefik/traefik-helm-chart#kubernetes-version-support , so please use the latest chart version.

In the meantime, we are fixing the k0s documentation now.
