### ISSUE TITLE
Automatically set proper node name in case of AWS EC instance

### ISSUE THREAD

**Issue by soider** [k0sproject/k0s#1123]
Often to use k8s on aws we need to have node hostname match the private DNS name record for the EC instance.
The proper name record can be achieved by calling AWS API (`http://169.254.169.254/latest/meta-data/local-hostname`)
We already have the same logic for the windows workers, and we could port it for the linux workers as well.
The location of the mentioned code is `pkg/component/worker/kubelet.go:241`

**Comment by xinfengliu** [comment]
k0s builds Kubernetes components in `providerless` mode. Not sure about what situation we should set `--hostname-override` with the private DNS name record for the EC instance. In addition,  if  `--cloud-provider` (although it will be removed in k8s 1.23) is used, `--hostname-override` is ignored.

**Comment by soider** [comment]
@xinfengliu yeah, actually I went through another round of thinking about that issue and it would bring more cons than pros. While it is a strictly requirement for windows mode, it's not a requirement for calico on linux, for example, so let's keep it simple and have that logic only on windows as it is
