### ISSUE TITLE
Containerd http_proxy for pulling images

### ISSUE THREAD

**Issue by ckoliber** [k0sproject/k0s#1125]
Hello friends
Is there anyway to set HTTP_PROXY variable for pulling images only through a proxy ?

**Comment by jewertow** [comment]
https://docs.k0sproject.io/v1.22.1+k0s.1/environment-variables/

**Comment by jewertow** [comment]
You can also look at [this demo](https://github.com/jewertow/k0s-sandbox/tree/master/cluster-behind-a-proxy) with pulling images through a proxy.

**Comment by ckoliber** [comment]
Thanks @jewertow 
But the problem with setting HTTP_PROXY in k0scontroller service is like the [old problem at k3s](https://github.com/k3s-io/k3s/issues/2026)

This proxy configuration applies to the entire system, the whole cluster traffic will pass through the proxy

Is there anyway to set HTTP_PROXY variable only for containerd internal service ?

**Comment by jewertow** [comment]
Ok, thanks. Now I understand the context.

I checked out how containerd is [started](https://github.com/k0sproject/k0s/blob/main/pkg/component/worker/containerd.go#L71), and the only [env variable passed](https://github.com/k0sproject/k0s/blob/main/pkg/supervisor/supervisor.go#L115) to  containerd process is `PATH`.

So the answer is no, it's not possible. At least for now. It should be [trivial](https://github.com/k3s-io/k3s/pull/3553/files) to implement that, but it's a question to maintainers if they want to support `CONTAINERD_*` envs.
