### ISSUE TITLE
`Supervisor.Stop()` hangs if the process is already gone

### ISSUE THREAD

**Issue by jnummelin** [k0sproject/k0s#1138]
**Version**
```
$ k0s version
```
**Platform**
Which platform did you run k0s on?
```
$ lsb_release -a
```
**What happened?**
While running smoke tests I've seen cases when stopping k0s process basically hangs. This seems to boil down to the `Supervisor.Stop()` function just hanging if for some reason the underlying supervised process is actually already gone.

**How To Reproduce**
During shutdown you need to be able to kill some processes "manualy". The timing is super critical, thus not easy to repro. I've seen this when there was some other bugs that got a "left-over" supervisor having it's stop function called.

**Expected behavior**
`Supervisor.Stop()` should return early and cleanly if there's no actual process running for it.

**Screenshots & Logs**

**Comment by xinfengliu** [comment]
It looks like `s.cmd.Wait()` could not return upon manual killing. Maybe it is because `stdout/stderr` copying was hanged. I guess we should explicitly close the pipes for `stdout/stderr`.

**Comment by xinfengliu** [comment]
I tried many times could not reproduce the issue in my testing environment. 

Stopping k0s will trigger service stop action, in `systemd` service, the `DefaultTimeoutStopSec` is 90s, after that the service will be forcibly killed. So in `systemd` environment, it could not hang for ever.

Starting k0s with `--debug` should be able to help diagnose this issue: more detailed logs and collect stack dump if needed.
