### ISSUE TITLE
Config CRD: Validate CR before trying to reconcile it

### ISSUE THREAD

**Issue by jnummelin** [k0sproject/k0s#1148]
**Is your feature request related to a problem? Please describe.**
If I make a typo or something to the config CR the reconcilers might get bit broken.

**Describe the solution you'd like**
We should run good validation BEFORE we try to reconcile the config and output the "status"

**Describe alternatives you've considered**
I see two alternatives:
- validate the config once we read it (easy-ish)
- validating admission controller of some sort (hard-ish)

**Additional context**

**Comment by ncopa** [comment]
I think it might be worth to also validate the config change before it is pushed (validating admission controller), but lets do that in a separate issue if we decide to go that route.
