### ISSUE TITLE
Status socket unlinking doesn't work with a custom status socket path

### ISSUE THREAD

**Issue by soider** [k0sproject/k0s#1159]
**Version**
```
$ k0s version
v1.22.1+k0s.1
```
**Platform**
Which platform did you run k0s on?
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal
```
**What happened?**
I am using command `sudo k0s worker --enable-cloud-provider --status-socket=/run/k0s/worker.sock <token>`

After sending stop signal (ctrl-c in the terminal) there is warning message 
```
ERRO[2021-10-01 12:07:59] failed to start status server at /run/k0s/worker.sock: http: Server closed  component=status
```

the mentioned path is not unlinked.

**How To Reproduce**
How can we reproduce this issue? (as minimally and as precisely as possible)

**Expected behavior**
the status socket path is unlinked during the stop process

**Comment by xinfengliu** [comment]
The error message is benign but misleading. Even we don't use custom socket path, we still get that error message on shutdown.
From https://pkg.go.dev/net/http#Server.Shutdown 
```
When Shutdown is called, Serve, ListenAndServe, and ListenAndServeTLS immediately return ErrServerClosed. Make sure the program doesn't exit and waits instead for Shutdown to return.
```
Maybe we should at least check `ErrServerClosed` on return of `s.httpserver.Serve`.
