### ISSUE TITLE
kube-apiserver is not reachable

### ISSUE THREAD

**Issue by chainhead** [k0sproject/k0s#1164]
**Version**
```
$ k0s version
v1.22.1+k0s.1
```
**Platform**
Which platform did you run k0s on?

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.6 LTS
Release:	18.04
Codename:	bionic
```
**What happened?**
The API server is not reachable.

**How To Reproduce**

1. Launch `k0s` with the following commands.

```bash
curl -sSLf https://get.k0s.sh | sudo sh
sudo k0s install controller --single
sudo k0s start
# Set-up kubectl
sudo cp /var/lib/k0s/pki/admin.conf $HOME/.kube/admin.conf
sudo chown $USER:$USER admin.conf
export KUBECONFIG=$HOME/.kube/admin.conf
```

2. Get IP address of `kubernetes` service
```bash
kubectl get svc
NAME         TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
kubernetes   ClusterIP   10.96.0.1    <none>        443/TCP   9s
```

3. Launch a `curl` pod and try connecting to the `Service` from Step 2.

```bash
kubectl run curl-eg --image=radial/busyboxplus:curl -i --tty --rm
curl https://10.96.0.1:443/api/
If you don't see a command prompt, try pressing enter.
[ root@curl-eg:/ ]$ curl https://10.96.0.1:443/api/

curl: (7) Failed to connect to 10.96.0.1 port 443: Connection timed out
```

**Expected behavior**
The API server should get connected from `curl` pod or elsewhere. Otherwise, installation of projects such as Metallb fails. See [here](https://github.com/metallb/metallb/issues/977).

**Screenshots & Logs**
Please let me know what logs would be helpful.

**Additional context**
Please let me know what other information may be required.

**Comment by chainhead** [comment]
This is from `openssl` client run from `alpine/openssl` pod.

```bash
OpenSSL> s_client -connect 10.96.0.1:443
140154109136200:error:0200206E:system library:connect:Operation timed out:crypto/bio/b_sock2.c:110:
140154109136200:error:2008A067:BIO routines:BIO_connect:connect error:crypto/bio/b_sock2.c:111:
connect:errno=110
error in s_client
```

**Comment by chainhead** [comment]
Interestingly, when running KinD, the `kubernetes` service is reachable (but fails with `403`) from a `curl` pod with `curl -k https://10.96.0.1:443/api/`. And. Metallb installation also goes through well.

**Comment by jnummelin** [comment]
feels like kube-proxy does not get up properly to create the service IPs (in this case `10.96.0.1` for api service).

What's the general state of all the pods, `kubectl get pod -A -o wide`

Anything on kube-proxy pod logs? Either via `kubectl -n kube-system logs kube-proxy.....` (I'm suspecting this might not actually work as the networking seems to be bit bust) or via files on `/var/log/containers/...`
