### ISSUE TITLE
continuous backup

### ISSUE THREAD

**Issue by gedw99** [k0sproject/k0s#1171]
**Is your feature request related to a problem? Please describe.**
A  continuous backup so that I can restore from it without having to do check point backups 

**Describe alternatives you've considered**

**Additional context**

litesrream is golang and uses SQLite .

It makes it easy to have all changes to SQLite continuously being backup to s3 and to restore from nothing via s3

https://github.com/benbjohnson/litestream

https://litestream.io/

**Comment by jnummelin** [comment]
Is there something currently preventing you from using litestream with k0s configured to use SQLite?

Or is this a feature request to bundle litestream with k0s so one could configure it out-of-box?

**Comment by gedw99** [comment]
Hey @jnummelin It was just a suggestion, because it gives the k0 a form of HA in the sense that you have continuous backups and restore.
