### ISSUE TITLE
k0s and k3s interoperability

### ISSUE THREAD

**Issue by sacesare** [k0sproject/k0s#1199]
It would be useful to provide interoperability with existing k3s cluster, as starting point- is there any means to generate K3S_TOKEN from k0s join token, to add k3s/k0s or other way around as worker node?

Thanks.

**Comment by mviitane** [comment]
k0s uses Konnectivity agent and server for establishing the connection between the Controller and Worker nodes.
https://kubernetes.io/docs/tasks/extend-kubernetes/setup-konnectivity/

I’m afraid k3s uses different mechanism for this and that’s why you can’t mix and match k0s and k3s nodes.
