### ISSUE TITLE
Bump calico version

### ISSUE THREAD

**Issue by soider** [k0sproject/k0s#1200]
Default version in the k0s is v3.18.1, the last one is v3.20.2

**Comment by soider** [comment]
@ncopa why is it closed if the #1253 left calico update out of the scope? is it by automation?

**Comment by ncopa** [comment]
yeah. that was unintentional. I used ~strikethrough~ and automation didn't understand the intention I guess.

**Comment by jnummelin** [comment]
The nice thing with new calico version is also support for armv7, finally:
```
$ docker manifest inspect docker.io/calico/node:v3.21.0
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
   "manifests": [
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 1791,
         "digest": "sha256:963b087cc5a3dfde1d680a3486c81c055d9ad3ebd0053663bdc712edc8f3ac97",
         "platform": {
            "architecture": "arm",
            "os": "linux",
            "variant": "v7"
         }
      },
```

**Comment by olivierHa** [comment]
Hello, 

In the new version of calico, an "api server" is available, which "could" resource management with kubectl easier (without the need of calicoctl). 

Another idea should be to include calicoctl inside k0s distribution binaries, to avoid this  download (and potential mismatch version)

Regards
