### ISSUE TITLE
`kubectl create job --from=cronjob/a a1`: error: from must be an existing cronjob: no kind "CronJob" is registered for version "batch/v1" in scheme "pkg/runtime/scheme.go:100"

### ISSUE THREAD

**Issue by shoce** [k0sproject/k0s#1227]
**Version**
```
v1.21.5+k0s.0
```
**Platform**
```
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.3 LTS
```
**What happened?**
I have a CronJob "a" that i am trying to run with `kubectl create job --from=cronjob/a a1` command. I get an error message and the job is not run:
error: from must be an existing cronjob: no kind "CronJob" is registered for version "batch/v1" in scheme "pkg/runtime/scheme.go:100"

**How To Reproduce**
Create any CronJob named "a" with spec like
```
apiVersion: batch/v1
kind: CronJob
```

Having a cronjob run command `kubectl create job --from=cronjob/a a1`.

**Expected behavior**
The job is expected to be run.

**Screenshots & Logs**
```
error: from must be an existing cronjob: no kind "CronJob" is registered for version "batch/v1" in scheme "pkg/runtime/scheme.go:100"
```

**Additional context**

**Comment by mviitane** [comment]
I quickly tried this using this simple example (on k0s v1.22.2+k0s), but wasn't able to reproduce the problem:
https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/

```
$ kubectl apply -f example_cronjob.yaml
cronjob.batch/hello created

$ kubectl get cronjob -A                                    
NAMESPACE   NAME    SCHEDULE      SUSPEND   ACTIVE   LAST SCHEDULE   AGE
default     hello   */1 * * * *   False     0        <none>          6s

$ kubectl create job --from=cronjob/hello a1
job.batch/a1 created

$ kubectl get pod a1--1-98l9v
NAME          READY   STATUS      RESTARTS   AGE
a1--1-98l9v   0/1     Completed   0          6m23s

$ kubectl logs a1--1-98l9v
Wed Nov  3 08:36:23 UTC 2021
Hello from the Kubernetes cluster

```

**Comment by shoce** [comment]
Thanks, upgraded to k0s 1.22.3 and it works now.
