### ISSUE TITLE
k0s reset does not remove k0s binary

### ISSUE THREAD

**Issue by matti** [k0sproject/k0s#1250]
related #278 #519 

running `k0s reset` does not remove `/usr/local/bin/k0s` - how do I know what else is left behind, especially in situations like #1249

**Comment by soider** [comment]
In my opinion deleting the binary is not the best behavior for reset. 

In the dev or lab like environment flow like `k0s reset && k0s install ...` feels like something natural to me.

**Comment by matti** [comment]
agreed. I was originally following up on "please implement k3s complete uninstall" (#653) which was "closed by" this reset thing.

**Comment by trawler** [comment]
Just to add a bit of context to the behaviour of `k0s reset`: its design was more inspired by `kubeadm reset` than any other tool.

**Comment by matti** [comment]
I think this discussion got sidetracked. Originally this was about k3s-uninstall.sh style behavior.
