### ISSUE TITLE
worker node shutdown waits long for containerd-shim

### ISSUE THREAD

**Issue by matti** [k0sproject/k0s#1251]
waits for containerd-shims:

<img width="751" alt="image" src="https://user-images.githubusercontent.com/3893/140654142-4f5d1c69-c5ce-4ffe-8eea-e69ffc0c78f1.png">

(Ubuntu 20.04, running in proxmox vm, hence the screenshot)

**Comment by jnummelin** [comment]
> worker node shutdown waits long

How long is long? :) I'd guess it's around 90sec which I remember is the systemd default

**Comment by matti** [comment]
but from users point of view: I have nothing running, so in my opinion a node should reboot/shut down fast

**Comment by jnummelin** [comment]
The root cause is containerd shims not handling SIGTERM properly: https://github.com/containerd/containerd/issues/5502

A fix upstream is targeted for containerd 1.6, there's not much we can do on k0s level before that ships out.

**Comment by jnummelin** [comment]
Remove stale, we're still waiting for upstream to have fix for this

**Comment by jnummelin** [comment]
There's now 1.6.0 containerd release which has this fix. We should bump main to use that.

No release yet for 1.5.x that includes this fix.

**Comment by matti** [comment]
asdf

**Comment by twz123** [comment]
k0s v1.23.5+k0s.0 is out, shipping containerd 1.5.11, which has the fix.

**Comment by twz123** [comment]
Closing as I believe this is fixed as of v1.23.5+k0s.0. Please ping me if it's not working as intended.
