### ISSUE TITLE
built-in kubectl cannot recognize kubectl plugin

### ISSUE THREAD

**Issue by cl-lab-k** [k0sproject/k0s#1264]
**Version**
```
$ k0s version
v1.22.3+k0s.0
```
**Platform**
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.6 LTS
Release:	18.04
Codename:	bionic
```
**What happened?**
k0s built-in kubectl cannot recognize kubectl plugin, but native kubectl can do so.

**How To Reproduce**
1. install k0s.
2. install [Example Plugin](https://kubernetes.io/docs/tasks/extend-kubectl/kubectl-plugins/#example-plugin) (kubectl-foo).
3. execute `k0s kubectl foo`, but cannot recognize `kubectl-foo` plugin (just print kubectl usage).
4. instal native [kubectl](https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/#install-kubectl-binary-with-curl-on-linux).
5. execute `kubectl foo` and can get `I am a plugin named kubectl-foo` message.

**Expected behavior**
`k0s kubectl foo` prints `I am a plugin named kubectl-foo` message.

**Screenshots & Logs**
```
$ sudo cp /var/lib/k0s/pki/admin.conf kubeconfig.cfg
$ export KUBECONFIG=~/kubeconfig.cfg
$ cat > ./kubectl-foo
#!/bin/bash

# optional argument handling
if [[ "$1" == "version" ]]
then
    echo "1.0.0"
    exit 0
fi

# optional argument handling
if [[ "$1" == "config" ]]
then
    echo "$KUBECONFIG"
    exit 0
fi

echo "I am a plugin named kubectl-foo"
$ chmod +x kubectl-foo
$ sudo mv kubectl-foo /usr/local/bin/
$ /usr/local/bin/kubectl-foo 
I am a plugin named kubectl-foo
$ k0s kubectl foo
kubectl controls the Kubernetes cluster manager.
(snip)
$ curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
$ chmod +x ./kubectl
$ ./kubectl foo
I am a plugin named kubectl-foo
```

**Additional context**
none.

**Comment by kke** [comment]
Whoops, misclicked.

**Comment by kke** [comment]
Very often kubectl plugins will "call back" by running `kubectl` to perform various tasks. This would not work even if the plugins would run. This needs some trickery, as mentioned in #1265 comments.
