### ISSUE TITLE
Investigate if it is possible to allow separate restart for failed e2e test suites

### ISSUE THREAD

**Issue by soider** [k0sproject/k0s#1277]
At the moment we have single workflow [go.yaml](https://github.com/k0sproject/k0s/blob/main/.github/workflows/go.yml) which has separate jobs per each e2e test suite.

Having jobs per suite allows to have concurrent test runs.

The tests we have are flaky and long because almost each e2e implements the same loop:
- set up cluster with given configuration
- do some cluster probing and assertions
- shutdown cluster

Based on the recent PRs, each suite takes 2-3 minutes to run.
The workflow has aprox 20 suites and it takes about 10-30 minutes to run the whole workflow (heavily depends on the build cache state).
If one of those ~20 tests fail, we are able to restart only the whole workflow which sometimes led to have hours of waiting time.

With #1275 merged we can move each e2e suite to a separate flow with following working loop:

- wait until k0s binary artifact is available (in the worth case scenario it can be a loop in the Makefile or shell script)
- download k0s binary
- set up cluster
- probing and assertions
- shutdown cluster

The main benefit is having way to restart only failed suite.
The downside is having more boilerplate in the .github/workflows (might be we can use some codegen tooling to leverage). Another downside is that time per each suite might be longer than now if the artifacts are slower than cache.

**Comment by kke** [comment]
I think the artifacts appear only once the whole thing has finished (at least that is the case if you look at them in the UI, it says `artifacts: -` until the whole run is finished / canceled and only then it turns to `artifacts: 1`, maybe to stop people from doing that, I don't know why.

**Comment by kke** [comment]
I don't know if something could be done using the [workflow_call](https://docs.github.com/en/actions/learn-github-actions/reusing-workflows) actions 🤔

**Comment by soider** [comment]
could be an option. I think I tried it once somewhere in the private fork, but if I recall correctly, it still forced me to restart with parent job

**Comment by kke** [comment]
Maybe jobs could be automatically retried, perhaps only if they don't reach some checkpoint.

**Comment by soider** [comment]
Close in favor of 

https://github.com/actions/runner/issues/432 

https://github.com/github/roadmap/issues/271
