### ISSUE TITLE
Pre-flight check for system level config

### ISSUE THREAD

**Issue by jnummelin** [k0sproject/k0s#1289]
**Is your feature request related to a problem? Please describe.**
Every now and then we face issues where k0s and kube bits do not boot up properly. Often the case is about missing system requirements, mainly kernel modules, cgroup or other stuff like that.

**Describe the solution you'd like**
The main k0s process could do an early "pre-flight" check and exit early with clear error what is missing. We already have a `k0s sysinfo` command which can dig the info out. Of course some flag like `--skip-system-check` would be in order to make it skip the check.

**Comment by jnummelin** [comment]
Some examples where this could help detect issues early:
https://github.com/k0sproject/k0s/issues/1289
https://github.com/k0sproject/k0s/issues/1270

**Comment by twz123** [comment]
Another issue where this could have helped: #1546.

There's definitively more things that could be checked, besides the stuff that's already part of `k0s sysinfo`:

* The [machine-id](https://github.com/denisbrodbeck/machineid/blob/v1.0.1/README.md#what-you-get).
* The general [system requirements](https://docs.k0sproject.io/v1.23.3+k0s.0/system-requirements/).
* The [host dependencies](https://docs.k0sproject.io/v1.23.3+k0s.0/internal/host-dependencies/) (although this page needs to be revised).

**Comment by wenerme** [comment]
Dose `cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory` is also required by k0s, k3s documented this, but not found in k0s doc, on in [raspberry-pi4](https://docs.k0sproject.io/v1.23.3+k0s.0/raspberry-pi4/#cgroup-configuration) section.

running in alpine 3.15, without these, will get `invalid capacity 0 on image filesystem` error

**Comment by twz123** [comment]
@wenerme k0s requires the cpuset and memory cgroup controllers, as (somewhat implicitly) documented in [OS Dependencies/Kernel configuration](https://docs.k0sproject.io/v1.23.3+k0s.1/os-deps/#kernel-configuration), which mentions `CONFIG_CPUSETS` and `CONFIG_MEMCG`. This will be stated [a bit more explicitly](https://github.com/k0sproject/k0s/blob/4e67951c8dfb67a9c9646f35920c58d1b88a0d4d/docs/external-runtime-deps.md#cgroups) in the next release. If those kernel parameters are enabled or not depends on the distribution, and may be checked with `k0s sysinfo | grep CGROUPS`. In the Raspberry Pi example that you mentioned, the parameters are not present by default, hence they need to be added manually.

**Comment by twz123** [comment]
xref #1581
