### ISSUE TITLE
Kube components left running after stoping k0s

### ISSUE THREAD

**Issue by hugochinchilla** [k0sproject/k0s#1293]
**Version**
v1.22.2+k0s.2

**Platform**
Arch linux

**What happened?**
After stopping k0s, kubernetes API is down but some kube components are still up and running

**How To Reproduce**
Stop the k0scontroller.service or run `k0s stop` and look for kube processes with `ps aux | grep kube` or `sudo systemctl status  | grep kube`

**Expected behavior**
All kubernetes components should stop.

**Screenshots & Logs**

```
hchinchilla@archer $ kubectl get nodes
NAME     STATUS   ROLES    AGE   VERSION
archer   Ready    <none>   94d   v1.22.2+k0s
```

```
hchinchilla@archer $ k0s version
v1.22.2+k0s.2
```

```
hchinchilla@archer $ sudo k0s stop
hchinchilla@archer $ sudo systemctl status

● archer
    State: running
     Jobs: 0 queued
   Failed: 0 units
    Since: Mon 2021-11-29 08:15:44 CET; 2h 38min ago
   CGroup: /
           ├─kubepods
           │ ├─burstable
           │ │ ├─podcff6d7e1-5caa-42b8-8191-8665696a8d3e
           │ │ │ ├─b2294d746f3c9adcbd85b33f03c1aa88fd75d25b5f7f996ac8c097542c3f7e65
           │ │ │ │ └─2233 /pause
           │ │ │ └─c8791af44e5abcb999d72c852a5f44b8afec9049503885af390299618873ee0f
           │ │ │   └─2268 /metrics-server --cert-dir=/tmp --secure-port=4443 --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname --kubelet-insecure-tls
           │ │ ├─pod1a8a7cfe-525f-4e92-a9ff-74d3e1a0df6e
           │ │ │ └─826fa4645af2b328282d00881a6a01df27ed9da9e94123e98d0ae7dfac873626
           │ │ │   └─1769 /pause
           │ │ └─pod534b92f7-8d8c-4b57-abef-b0b06321acb9
           │ │   ├─eab6b8d71a5b49d1c4385b44ce5e9f02029616c218af55f81998fc13a398d42b
           │ │   │ └─1882 /pause
           │ │   └─c848da0e477c335e2721446590f6d84f3bf53bdc42cc455a658d21489e7c52ef
           │ │     └─2045 /usr/local/bin/kube-router --run-router=true --run-firewall=true --run-service-proxy=false --bgp-graceful-restart=true --metrics-port=8080
           │ └─besteffort
           │   └─pod52e7e4ad-04f8-45c2-91e2-9c4cba8d6d29
           │     ├─c0dd5a19339596ea2e5ed5323a5f4ff16e2ace2607164bcec32fea4093124d7e
           │     │ └─2741 /pause
           │     └─f2eef7ea4156fb6dd6b8f1e9490dedac8798b789b040146f1bea27ff676804a2
           │       └─2776 /usr/local/bin/kube-proxy --config=/var/lib/kube-proxy/config.conf --hostname-override=archer
```

**Comment by kke** [comment]
AFAIK this is intentional.

**Comment by jnummelin** [comment]
Yes, this is very much intentional as it allows to update k0s and its embedded kube components without killing the workloads.

**Comment by hugochinchilla** [comment]
Is there a correct way to kill the kube components or kube workloads? Currently I kill the processes one by one.

Maybe it would be a good feature to add a flag to stop everything, something like `k0s stop --all`

**Comment by hugochinchilla** [comment]
any anwser?

**Comment by kke** [comment]
`k0s reset` will stop them but may do a bit more than wanted. `k0s stop --all` sounds like a good idea.

**Comment by jnummelin** [comment]
What's the use case, in what case you want to stop all containers? Usually in Kubernetes the way is to drain and cordon a node, but it's not exactly the same as stopping everything k8s related on the node.

**Comment by hugochinchilla** [comment]
My use case for k0s is to run a cluster sporadically to run integration
tests for a project. When not in use I find sometimes errors while bringing
up other projects because of port colissions (8080 especially) when that
happens I want to be able to stop all k0s.

**Comment by jnummelin** [comment]
Everything works as designed from k0s and Kubernetes point of view. If you want/need to remove all workloads then you can do so from the API (remove all deployments etc.). If you want/need to start from scratch on every CI run there's also `k0s reset` command that'll wipe all traces of k0s between runs.

**Comment by hugochinchilla** [comment]
@jnummelin I already remove all deployed workloads, what I expect from `k0s stop` (via flags or not) is to stop the kubernetes core itself. I would prefer to not reset the installation every time I want to stop it, I just want kubernetes to be like another service which can be started and stopped on demand. I know this may not make sense from a production perspective, but for a development/testing perspective makes sense.

**Comment by jnummelin** [comment]
> stop the kubernetes core itself

I assume by this you mean things like kube-proxy, coredns etc. containers? And k0s in this case is running on some "long lasting" machine which is not restarted/re-created during CI runs?

The main issue is really the fact that kubelet does not really provide an interface to tell "I want to stop, only stop not remove completely, the containers". Kubelet has a new-ish feature called ["Graceful node shutdown"](https://kubernetes.io/blog/2021/04/21/graceful-node-shutdown-beta/) but that can be only hooked to full node restarts. (AFAIK based on quick look at how it's implemented)

So essentially what you'd need (IF I got the use case right) in this case is k0s shutdown procedure, in specific order:
- stop kubelet
- stop all pods on containerd
- stop containerd itself

Or am I missing something?

I do get the usecase, but all the bits (kubelet, containerd) as kinda designed for the opposite. We do have some maybe re-usable bits for the pod stop phase as we do stop and remove pods on `k0s reset`. 

With this info I'll turn this into feature request as currently everything is working as designed.

**Comment by hugochinchilla** [comment]
Thanks @jnummelin, you got the use case right

**Comment by jnummelin** [comment]
Given that this is quite "niche" use case and how everything (kube, containerd) is designed in quite opposite way, I don't think this will be high in the core teams backlog unfortunately. But we'd definitely accept a PR for this.
