### ISSUE TITLE
Unit tests step in the build workflow takes more time than actual build (> 4 minutes on average)

### ISSUE THREAD

**Issue by soider** [k0sproject/k0s#1297]
There is a separate step in the build workflow, to run unit tests.

It seens it doesn't use already existed modules and downloads them again, making the step execution time more than 4 minutes.

**Comment by kke** [comment]
I guess this must be somehow caused by #1281

**Comment by kke** [comment]
No, this actually happens because `check-unit` is run locally via `go test` and the build happens inside a container.

**Comment by kke** [comment]
There are some things that can be tweaked in the caching to improve the CI build speed.

I guess the `make check-unit` could run in the build container, that would eliminate double downloads.

**Comment by soider** [comment]
That makes sense, may be even before build (to fail fast)
