### ISSUE TITLE
Document allowing unsafe sysctls with k0s

### ISSUE THREAD

**Issue by shoce** [k0sproject/k0s#1307]
**Is your feature request related to a problem? Please describe.**
I want to allow an unsafe sysctl to be changed.

**Describe the solution you'd like**
Would be great to have a clear documentation how to configure allowed sysctls.

**Describe alternatives you've considered**

I found this option with google:
to use `--kubelet-extra-args="--allowed-unsafe-sysctls=blabla"` - this one is deprecated
and k0s errored with a message stating that the flag is deprecated and configuration should be made with a config.
so I created a config `/root/k0s.kubelet.yaml` with exactly this content

```
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
allowedUnsafeSysctls:
- fs.inotify.max_user_instances
```

and updated `/etc/systemd/system/k0scontroller.service` with this line
```
ExecStart=/usr/local/bin/k0s controller --config=/root/k0s.yaml --single=true --kubelet-extra-args="--config=/root/k0s.kubelet.yaml"
```

and this did not work as well.

So I'm not sure how to proceed. No clear instructions could be found.

**Comment by trawler** [comment]
Added documentation for unsafe sysctls in #1627
