### ISSUE TITLE
Feature-Gate enablement

### ISSUE THREAD

**Issue by sircharta** [k0sproject/k0s#1317]
**Version**
```
$ k0s version
v1.22.2+k0s.1
```
**Platform**
Which platform did you run k0s on?
```
$ lsb_release -a
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.3 LTS
Release:        20.04
Codename:       focal
```
**What happened?**
I try to enable the device-plugins feature-gate. My attemps have not been successful yet and there is no clear documentation on how to enable feature-gates in k0s.

**How To Reproduce**
Snipped of my k0s.yaml:
```
apiVersion: k0s.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s
spec:
  api:
    address: 192.168.2.130
    port: 6443
    k0sApiPort: 9443
    sans:
    - 192.168.2.130
    - 10.1.104.0
    - 10.244.0.1
    extraArgs:
      feature-gates: "DevicePlugins=true"
  controllerManager:
    extraArgs:
      feature-gates: "DevicePlugins=true"
  workerProfiles:
    - name: custom-role
      values:
         key: featureGates
         mapping:
             innerKey: "DevicePlugins=true"
```

**Expected behavior**
I like to run a smarter-device-manager container which requieres the device-plugins feature-gate to be enabled.
I expect to enable the feature-gate.
https://gitlab.com/arm-research/smarter/smarter-device-manager

**Screenshots & Logs**

```
I1207 14:23:27.056401       1 server.go:105] Server stopped with socket /var/lib/kubelet/device-plugins/smarter-ttyS24.sock
I1207 14:23:27.056419       1 server.go:188] Removing file /var/lib/kubelet/device-plugins/smarter-ttyS24.sock
I1207 14:23:27.056463       1 main.go:229] Could not contact Kubelet, retrying. Did you enable the device plugin feature gate?
I1207 14:23:27.056492       1 server.go:188] Removing file /var/lib/kubelet/device-plugins/smarter-ttyS23.sock
I1207 14:23:27.057397       1 server.go:227] Starting to serve on/var/lib/kubelet/device-plugins/smarter-ttyS23.sock
```

* /var/lib/kubelet/device-plugins in container is mounted to /var/lib/k0s/kubelet/device-plugins on host

All I could found on how to enable a feature gate was this issue on github. In this case it does not seem to work.
https://github.com/k0sproject/k0s/issues/394

**Comment by soider** [comment]
related to the #1161
