### ISSUE TITLE
Windows (worker) binaries contain unnecessary, unused packages

### ISSUE THREAD

**Issue by trawler** [k0sproject/k0s#1324]
**Is your feature request related to a problem? Please describe.**
Our windows binary builds contain packages which are not required for worker nodes (for example, all controller related/config packages, etc.). Excluding these packages from window builds will result in a smaller, simpler binary.

**Describe the solution you'd like**
We should find a way to exclude unnecessary packages from being built on windows.

**Comment by soider** [comment]
I see two ways, both I found unwanted
- split controller and worker binaries at all 
- for the windows builds introduce platform specific controller packages with empty implementations. That leads to have a huge mess in the source code (almost every structure should be duplicated)
