### ISSUE TITLE
Automatic Kubernetes YAML validation

### ISSUE THREAD

**Issue by makhov** [k0sproject/k0s#1350]
**Is your feature request related to a problem? Please describe.**
We had several configuration mistakes in our codebase. 
@soider discovered it in the #1230 manually running `datree` check tool.
Some of them are fixed by #1344, but this can happen again.

**Describe the solution you'd like**
It would be nice to have some automation that we can run for every PR. 
There are several tools for this: kubeval, datree, etc…

**Describe alternatives you've considered**
Do it manually from time to time.

**Additional context**
There are some "false positives" in the datree's output in #1230. So we need a way to customize or disable linter rules.

**Comment by soider** [comment]
One of the possible ways is to have tool like dateree or kubeval running over /var/lib/k0s/manifests after suite run, before cleanup. May be even as a part of the common test suite, exec external binary after main test method.
