### ISSUE TITLE
When validating config against a non-existent path, the output is silent

### ISSUE THREAD

**Issue by trawler** [k0sproject/k0s#1354]
**Version**
```
v1.22.1+k0s.0-256-g28f7dbf6 (current main)
```
**Platform**
Which platform did you run k0s on?
```
Ubuntu 20.04.2 LTS
```
**What happened?**
When running `k0s validate` against a non-existent config file, no error or any output is given.

**How To Reproduce**

```
k0s validate config --config ~/foo/bar
```

**Expected behavior**
An error message somewhere in the lines of: `~/foo/bar does not exist`

**Comment by kke** [comment]
Also I think it should take take config as a positional, maybe required argument. `k0s validate config xyz.yaml` instead of `k0s validate config --config xyz.yaml`.

**Comment by kke** [comment]
#1335 is a bit related.
