### ISSUE TITLE
Allow to set Wireguard keep-alive

### ISSUE THREAD

**Issue by jnummelin** [k0sproject/k0s#1368]
**Is your feature request related to a problem? Please describe.**
When there's no traffic between nodes on Calico+wireguard setup, WG drops the connections as there's no payload running through

**Describe the solution you'd like**
I'd  like to see the tunnels being kept open with a "keep-alive" always

**Additional context**
There's an issue already open on Calico to enable this: https://github.com/projectcalico/calico/issues/5167

**Comment by matti** [comment]
workaround: https://github.com/mattirantakomi/wg-pinger by maestro @mattirantakomi

**Comment by makhov** [comment]
I submitted the PR: https://github.com/projectcalico/calico/pull/5338
