### ISSUE TITLE
docs/cli/ out of date

### ISSUE THREAD

**Issue by kke** [k0sproject/k0s#1369]
There's a bunch of subcommands missing from the documentation in `docs/cli` directory.

- k0s airgap (+subcommands)
- k0s backup
- k0s restore
- k0s sysinfo
- k0s reset
- k0s token (+subcommands)
- maybe others

Also many of the existing ones have been manually edited both for extra content and to pass linter (#953) 

Probably best to regenerate all and ignore on linter.

**Comment by trawler** [comment]
Included in #1247 (since it updated the `--config` flag in many commands)

**Comment by kke** [comment]
I wonder if we could just generate it during doc publish

**Comment by soider** [comment]
>I wonder if we could just generate it during doc publish


that would be really nice because it is a common thing (we already have PRs to update gen docs couple of times)
