### ISSUE TITLE
Maintenance tool to fix permissions

### ISSUE THREAD

**Issue by soider** [k0sproject/k0s#1381]
**Is your feature request related to a problem? Please describe.**
I'd love to have some command like `k0s internal fix-permissions` to fix permissions for all dir under the data-dir according to expectations.

**Describe the solution you'd like**
If you restore data-dir from external source (s3 bucket, backup partition, etc) there are some chances that permissionswould not be preserved. With improper permissions k0s fails to start.

The desired tool would be able to fix that behavior.

**Describe alternatives you've considered**
Another option is to try fix permissions during the start up.

**Comment by ncopa** [comment]
This is fixed by https://github.com/k0sproject/k0s/pull/1380 which will make k0s to explicitly set the permissions instead of exit with fail.
