### ISSUE TITLE
Compatibility with metrics-server >= v0.5.2

### ISSUE THREAD

**Issue by joeycumines** [k0sproject/k0s#1396]
### Before creating an issue, make sure you've checked the following:

- [X] You are running the latest released version of k0s
- [X] Make sure you've searched for existing issues, both open and closed
- [X] Make sure you've searched for PRs too, a fix might've been merged already
- [X] You're looking at docs for the released version, "main" branch docs are usually ahead of released versions.

### Version

v1.23.1+k0s.0

### Platform

```shell
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.3 LTS
Release:        20.04
Codename:       focal
```

### What happened?

I tried to upgrade the image for https://github.com/kubernetes-sigs/metrics-server to 0.5.2, but the container fails to start, with `Error: failed to create listener: failed to listen on 0.0.0.0:443: listen tcp 0.0.0.0:443: bind: permission denied`.

### Steps to reproduce

1. Use an image that's >= v0.5.2, e.g.

```
    metricsserver:
      image: gcr.io/k8s-staging-metrics-server/metrics-server
      version: v0.5.2
```
2. Deploy the k0s config change
3. Observe the behavior of the pods
```
kubectl -n kube-system describe pods -l k8s-app=metrics-server
kubectl -n kube-system logs -l k8s-app=metrics-server
```

### Expected behavior

all v0.5.x releases to work, while any of the v0.5.x releases are supported by k0s

### Actual behavior

v0.5.2 (onwards - presumably) does not work

### Additional context

Maybe I should use whatever image this project has been tested with (whatever is output by `k0s config create`?), but I figured I'd raise an issue anyway.

I believe the immediate cause is https://github.com/kubernetes-sigs/metrics-server/commit/d3265cf376031455926bc86fcfae4a7a28226e9e / https://github.com/kubernetes-sigs/metrics-server/releases/tag/v0.5.2

> Remove elevated permissions cap_net_bind_service from metrics-server

the readme https://github.com/kubernetes-sigs/metrics-server#security-context has some relevant details.

**Comment by soider** [comment]
I think we need to update bundled image, since it is a security concern.

**Comment by shuaich** [comment]
Could you check what port is used by metrics-server? The error log shows the privileged port 443 is still being used.

In k8s, 443 was replaced by 10250.
See https://github.com/kubernetes/kubernetes/blob/v1.23.1/cluster/addons/metrics-server/metrics-server-deployment.yaml#L61

**Comment by joeycumines** [comment]
@shuaich not sure if that was directed at me, but the deployment is configured with `--secure-port=443`

**Comment by shuaich** [comment]
> shuaichen not sure if that was directed at me

Yes.
