### ISSUE TITLE
Installation fails with nss-altfiles

### ISSUE THREAD

**Issue by Meroje** [k0sproject/k0s#1402]
### Before creating an issue, make sure you've checked the following:

- [X] You are running the latest released version of k0s
- [X] Make sure you've searched for existing issues, both open and closed
- [X] Make sure you've searched for PRs too, a fix might've been merged already
- [X] You're looking at docs for the released version, "main" branch docs are usually ahead of released versions.

### Version

v1.23.1+k0s.0

### Platform

```shell
Fedora CoreOS 32.20201104.3.0
```

### What happened?

As was foreshadowed in #1079
> forcing file based lookup will probably just break people's setups in a different way >:

the fix made there is breaking on rpm-ostree base distros (as far as I can tell that would be CoreOS/Flatcar/Silverblue) but the real issue is with [altfiles](https://github.com/aperezdc/nss-altfiles).

### Steps to reproduce

1. Install and configure nss-altfiles (or as in my case use Fedora Coreos)
2. Have one more of the installConfig.users defined in [/lib/passwd](https://github.com/coreos/fedora-coreos-config/blob/d1743185ffd47dce8fa5e885894d3a6a068b5dee/manifests/passwd#L16)
3. `k0s install controller`

### Expected behavior

exit 0, nor error

### Actual behavior

Errors with failure to create the user from step 2 (on a default fedora coreos this happens to etcd).
The user indeed exists so the error _to create_ is expected but this comes from the osusergo implementation not being able to find the user via nsss in the first place.

### Additional context

The obvious workaround (once all the above troubleshooting was figured out) is to change the etcduser and create a new one
```
  installConfig:
    users:
      etcdUser: k0s-etcd
```
but it would be nice for it to work out of the box (other projects have resorted to having separate musl/glibc builds).

**Comment by ncopa** [comment]
The problem here is that nss *requires* dynamic linking and we by design want static linking. We might be able to work around it by calling external `id` or `getent passwd ...` as a fallback.

What happens if you run `id -u etcd`?

**Comment by Meroje** [comment]
`id` returns the expected uid as it correctly relies on getpwnam
