### ISSUE TITLE
enable-k0s-cloud-provider doesn't assign externalIP for nodes

### ISSUE THREAD

**Issue by soider** [k0sproject/k0s#1403]
### Before creating an issue, make sure you've checked the following:

- [X] You are running the latest released version of k0s
- [X] Make sure you've searched for existing issues, both open and closed
- [X] Make sure you've searched for PRs too, a fix might've been merged already
- [X] You're looking at docs for the released version, "main" branch docs are usually ahead of released versions.

### Platform

```shell
```

### What happened?

Following https://docs.k0sproject.io/v1.23.1+k0s.0/cloud-providers/ I expect node <NODENAME> having externalIP <ADDR> after adding annotation by command 

`sudo k0s kc annotate node <NODENAME>  k0sproject.io/node-ip-external=<ADDR>` 

but it doesn't happen.

### Steps to reproduce

1. set up k0s with k0s cloud provider enabled by adding `--enable-cloud-provider` argument to k0s workers
2. annotate node with kubectl/k0s kc with address
3. check node external address

### Expected behavior

node has external address

**Comment by jnummelin** [comment]
> Steps to reproduce
> 1. set up k0s with k0s cloud provider enabled
> 2. annotate node with kubectl/k0s kc
> 3. check node external address

I _think_ you're missing a step between 1 and 2, we need to also set the `--enable-cloud-provider` flag for worker as that'll enable the nodes addresses to be managed by a "cloud-provider".

**Comment by soider** [comment]
@jnummelin  yeah, true, I did all of that on single node with --enable-worker and --enable-cloud-provider. I will edit the comment to add some clarity

**Comment by soider** [comment]
Misconfiguration
