### ISSUE TITLE
k0s kubectl does not respect -v flag

### ISSUE THREAD

**Issue by adamlamar** [k0sproject/k0s#1405]
### Before creating an issue, make sure you've checked the following:

- [X] You are running the latest released version of k0s
- [X] Make sure you've searched for existing issues, both open and closed
- [X] Make sure you've searched for PRs too, a fix might've been merged already
- [X] You're looking at docs for the released version, "main" branch docs are usually ahead of released versions.

### Version

v1.23.1+k0s.0

### Platform

```shell
# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 21.10
Release:	21.10
Codename:	impish
```

### What happened?

In `1.22.5+k0s.0`, running `k0s kubectl -v=8 get nodes` produces the expected node list and debug output from kubectl.

In `1.23.1+k0s.0`, the global `-v` flag to kubectl is unrecognized:

```
# k0s kubectl -v=8 get nodes
Error: unknown shorthand flag: 'v' in -v=8
See 'k0s kubectl get --help' for usage.
```

### Steps to reproduce

1. Run `k0s kubectl -v=8 get nodes`

### Expected behavior

The command should be run with verbose output.

### Actual behavior

The command fails to run.

**Comment by soider** [comment]
Looks like it was introduced in the 2ecb0c52f16bfb4f29e5081605b1712f814b5b49
