### ISSUE TITLE
Encrypt backups

### ISSUE THREAD

**Issue by wkonitzer** [k0sproject/k0s#1410]
### Is your feature request related to a problem? Please describe.

I would like to encrypt my backups to meet security requirements from my company.

### Describe the solution you would like

Backup encryption happens automatically with keys I supply to the software.

### Describe alternatives you've considered

Backups could be encrypted separately, but that leaves a window where a bad agent still has access to the unencrypted backup, thus it would be better if it happened as the backup is being made.

**Comment by jnummelin** [comment]
@wkonitzer do you have some requirements on the types of keys etc, that we could consider as input here? Any high level idea how you'd like to see `k0s backup` commands to utilize the provided keys?

**Comment by kke** [comment]
If `k0s backup` could output a .tar / .tar.gz to stdout, you could do `k0s backup --save-path - | gpg -c > backup.tar.gz.gpg` or similar. `k0s restore` should then also accept the archive via stdin.
