### ISSUE TITLE
allow customs node-cidr-mask-size

### ISSUE THREAD

**Issue by ghz-max** [k0sproject/k0s#1418]
### Is your feature request related to a problem? Please describe.

I would like to customize the following args in kube-controller-manager: 
- node-cidr-mask-size
- node-cidr-mask-size-ipv4
- node-cidr-mask-size-ipv6 

to run more than 256 pods per node. (default mask-size /24)

The configuration is attempted with the "extraArgs" parameters:
      spec:
        controllerManager:
          extraArgs:
            node-cidr-mask-size: "22"

### Describe the solution you would like

Change the following lines to allow customs mask-size without overwritten them

https://github.com/k0sproject/k0s/blob/8c20744761adc20222007d076452b81a5787ccf6/pkg/component/controller/controllermanager.go#L101-L112

### Describe alternatives you've considered

- k0s fork with a custom patch
- vanilla k8s deployment with kubeadm where these values can be changed

### Additional context

I'm aware of the 110 pods / node recommendation

**Comment by jnummelin** [comment]
hmm, I think we'd need to change the order of those `for` and `if-else` block to allow the override. Seems you're looked deep into this already, maybe push a PR?

**Comment by ghz-max** [comment]
I can give it a try! It would be my first ever PR on Github... will dig into the contributing doc for guidelines.
