### ISSUE TITLE
The connection to the server localhost:6443 was refused - did you specify the right host or port?

### ISSUE THREAD

**Issue by Ed87** [k0sproject/k0s#1445]
I am setting  up a cluster following this  [guide](https://techviewleo.com/deploy-kubernetes-cluster-on-debian-using-k0s/). After setting up the master and successfully adding a worker node ( another Debian10 server on my environment) I tried  adding  an additional node  (another Debian10 instance) , this time as a controller node.

However whilst adding the controller (k0s controller "<token>") node I encountered an error:

`Error while dialing dial unix /run/k0s/konnectivity-server/konnectivity-server.sock: socket: too many open files". Reconnecting...  component=kube-apiserver
INFO[2022-01-15 13:48:26] E0115 13:48:26.756594   40982 egress_selector.go:197] failed to create connection to uds name /run/k0s/konnectivity-server/konnectivity-server.sock, error: dial unix /run/k0s/konnectivity-server/konnectivity-server.sock: socket: too many open files  component=kube-apiserver
INFO[2022-01-15 13:48:26] W0115 13:48:26.756659   40982 clientconn.go:1331] [core] grpc: addrConn.createTransport failed to connect to {/run/k0s/konnectivity-server/konnectivity-server.sock /run/k0s/konnectivity-server/konnectivity-server.sock <nil> 0 <nil>}. Err: connection error: desc = "transport: Error while dialing dial unix /run/k0s/konnectivity-server/konnectivity-server.sock: socket: too many open files". Reconnecting...  component=kube-apiserver
INFO[2022-01-15 13:48:26] E0115 13:48:26.824056   40982 egress_selector.go:197] failed to create connection to uds name /run/k0s/konnectivity-server/konnectivity-server.sock, error: dial unix /run/k0s/konnectivity-server/konnectivity-server.sock: socket: too many open files  component=kube-apiserver
INFO[2022-01-15 13:48:26] W0115 13:48:26.824151   40982 clientconn.go:1331] [core] grpc: addrConn.createTransport failed to connect to {/run/k0s/konnectivity-server/konnectivity-server.sock /run/k0s/konnectivity-server/konnectivity-server.sock <nil> 0 <nil>}. Err: connection error: desc = "transport: Error while dialing dial unix /run/k0s/konnectivity-server/konnectivity-server.sock: socket: too many open files". Reconnecting...  component=kube-apiserver
INFO[2022-01-15 13:48:26] E0115 13:48:26.854444   40982 egress_selector.go:197] failed to create connection to uds name /run/k0s/konnectivity-server/konnectivity-server.sock, error: dial unix /run/k0s/konnectivity-server/konnectivity-server.sock: socket: too many open files  component=kube-apiserver
INFO[2022-01-15 13:48:26] W0115 13:48:26.854512   40982 clientconn.go:1331] [core] grpc: addrConn.createTransport failed to connect to {/run/k0s/konnectivity-server/konnectivity-server.sock /run/k0s/konnectivity-server/konnectivity-server.sock <nil> 0 <nil>}. Err: connection error: desc = "transport: Error while dialing dial unix /run/k0s/konnectivity-server/konnectivity-server.sock: socket: too many open files". Reconnecting...  component=kube-apiserver`

I have seen a fix for this issue at  [issuefix](https://github.com/k0sproject/k0s/pull/672) but I'm not quite sure _**how or what commands or file configuration changes  (if any)**_  I need to do. 

Regardless I figured I suspend this operation for now and continue to start using the cluster but it appears the attempt to add the controller node h**as broken the cluster** ! 

When I try  _**k0S kubectl get nodes**_ I am now getting an error :

`The connection to the server localhost:6443 was refused - did you specify the right host or port?`

Trying  logs :
`k0s kubectl logs 10 --tail=10
The connection to the server localhost:6443 was refused - did you specify the right host or port?``

k0S version: v1.23.1+k0s.0

Steps to reproduce  :

1. Downlaod and install binaries
`curl -sSLf https://get.k0s.sh | sudo sh`

2. Export the binary file 
`echo "export PATH=\$PATH:/usr/local/bin" | sudo tee -a /etc/profile`

3.Generate a token from the existing k0s control node
`k0s token create --role=controller`

4.Use the token to add new controller node , run command in controller node
`k0s controller "<token>"`
I have two issues:

1.  What do I need to do to fix this connection refused error , at least just restore the cluster to its state?
2. What do I need to do to  fix the error on adding controller node - all I have seen on the GitHub fix is some commits but no explicit instructions of how to apply the fix.

**Comment by soider** [comment]
Hello! 

Can I ask you to share the configuration you used for the cluster?
The same about the logs for controllers.

Worth mentioning, the proper HA set up requires you to have load balancer and the same k0s.yaml for all controllers (the default config would not work, because it always uses node local address.
The example with HAproxy is available in the k0s documentation https://docs.k0sproject.io/v1.22.5+k0s.1/high-availability/

**Comment by Ed87** [comment]
How do I check the configuration ? I assume it must be a file on the master node.  About the k0s.yaml -- to which location do I need to replicate  on the new controller node

**Comment by Ed87** [comment]
When I try to get logs also getting an error:
`k0s kubectl logs 10 --tail=10
The connection to the server localhost:6443 was refused - did you specify the right host or port?`

**Comment by Ed87** [comment]
I have NGINX already running on the instance for the master node. Which file would I need to add these lines:
`frontend kubeAPI
    bind :6443
    mode tcp
    default_backend kubeAPI_backend
frontend konnectivity
    bind :8132
    mode tcp
    default_backend konnectivity_backend
frontend controllerJoinAPI
    bind :9443
    mode tcp
    default_backend controllerJoinAPI_backend

backend kubeAPI_backend
    mode tcp
    server k0s-controller1 <ip-address1>:6443 check check-ssl verify none
    server k0s-controller2 <ip-address2>:6443 check check-ssl verify none
    server k0s-controller3 <ip-address3>:6443 check check-ssl verify none
backend konnectivity_backend
    mode tcp
    server k0s-controller1 <ip-address1>:8132 check check-ssl verify none
    server k0s-controller2 <ip-address2>:8132 check check-ssl verify none
    server k0s-controller3 <ip-address3>:8132 check check-ssl verify none
backend controllerJoinAPI_backend
    mode tcp
    server k0s-controller1 <ip-address1>:9443 check check-ssl verify none
    server k0s-controller2 <ip-address2>:9443 check check-ssl verify none
    server k0s-controller3 <ip-address3>:9443 check check-ssl verify none

listen stats
   bind *:9000
   mode http
   stats enable
   stats uri /
`

**Comment by soider** [comment]
@Ed87 the HAproxy is different part of the set up, not related to the nginx
You can either configure nginx as lb or use haproxy with the example config or use any other LB (for example, the one from amazon).

**Comment by Ed87** [comment]
thanks @soider  any links or pointers  on how to configure nginx as lb for k0s

**Comment by soider** [comment]
I don't think we have one for k0s specifically but you generally could use nginx https://docs.nginx.com/nginx/admin-guide/load-balancer/http-load-balancer/

You need to have konnectivity port (8132), kube api port (6443) and k0s join api (9443)

**Comment by Ed87** [comment]
About the k0s.yaml,, confirm I will have to replicate it to /etc/k0s on the new controller node

**Comment by soider** [comment]
Yes, you need to use the same k0s.yaml on each controller.

**Comment by Ed87** [comment]
```
spec:
  api:
    externalAddress: <load balancer public ip address>
    sans:
    - <load balancer public ip address>
```

This is what I have from the documentation. Confirm this is sufficient for the k0s.yaml (YES, i will replace the load-balancer public IP) .On another note  I assume this wont affect anything on the master node , or require any further config other than creating the k0S.yaml file.

**Comment by soider** [comment]
@Ed87 no need to fil sans section, it would be prepopulated by the value of external address. Otherwise looks good
