### ISSUE TITLE
How do I configure storage class on existing k0s cluster

### ISSUE THREAD

**Issue by Ed87** [k0sproject/k0s#1478]
When I run  `kos kubectl get storageclass`  I notice it is not provisioned and I have to add it manually. I am little unsure though on the exact procedure. The [Documentation](https://docs.k0sproject.io/main/storage/) here says k0s comes with OpenEBS installed .

What  I am unsure of is how to enable this installation in the config file.

My existing config file has this only (I assume this should be the default config file. Is this correct ?) :
`spec:
  api:
    externalAddress`

As per the guide I have stopped k0s `k0s stop` then amended the config file as follows:

`spec:
  api:
    externalAddress
  extensions:
    storage:
      type: openebs_local_storage`

Do I need to generate a new k0s.yaml and discard the existing one as per [Documentation](https://docs.k0sproject.io/main/configuration/).

 Do I need to also reinstall/install k0s, am a bit unsure because the existing k0s.yaml seems to have very little config parameters as compared to the sample given in the link .

What am I missing ?

EDIT: 

I have proceeded to generate a new k0s.yaml  that uses the existing default settings. Turns out it creates 2 k0s.yaml files with same content but different filenames (**k0s.yaml** and **k0s.yaml.save**). 
I have also effected changes as in the documentation to produce this :
`apiVersion: k0s.k0sproject.io/v1beta1
kind: ClusterConfig
metadata:
  creationTimestamp: null
  name: k0s
spec:
  api:
    address: 10.XXX.XXX.XXX
    k0sApiPort: 9443
    port: 6443
    sans:
    - 10.XX.XX.XXX
    - 172.XX.XX.XXX
    - 10.XX.XX.XXX
    - 10.XX.XX.XXX
    - fe80::XXX:XXX:XXX:XXX
    - fe80::XXX:XXX:XXX:XXX
    - fe80::XXX:XXX:XXX:XXX
    - fe80::XXX:XXX:XXX:XXX
    - fe80::XXX:XXX:XXX:XXX
    - fe80::XXX:XXX:XXX:XXX
    tunneledNetworkingMode: false
  controllerManager: {}
  extensions:
    helm:
      charts: null
      repositories: null
    **storage:
      create_default_storage_class: true
      type: openebs_local_storage**
  images:
    calico:
      cni:
        image: docker.io/calico/cni
        version: v3.21.2
      kubecontrollers:
        image: docker.io/calico/kube-controllers`

After this change I proceed to do a reinstall of the cluster :
`k0s install controller -c /etc/k0s/k0s.yaml`

but I am getting an error  _**Error: failed to install k0s service: failed to install service: Init already exists: /etc/systemd/system/k0scontroller.service**_

**Comment by Ed87** [comment]
@soider  may you assist

**Comment by jnummelin** [comment]
```
Error: failed to install k0s service: failed to install service: Init already exists: /etc/systemd/system/k0scontroller.service
```

Indicates that the systemd file already exists and currently k0s is not able to overwrite it. If you already have installed with a path to config file, you can just edit the config and restart k0s service with e.g. `sudo systemctl restart k0scontroller`. This will make k0s to take in the new config and will now also install the OpenEBS local storage provider.

**Comment by Ed87** [comment]
acknowledged thanks let me try that .

**Comment by Ed87** [comment]
@jnummelin  I have edited the config file as above , take note of the section :
`extensions:
    helm:
      charts: null
      repositories: null
    storage:
      create_default_storage_class: true
      type: openebs_local_storage`

Then proceeded to do  `sudo systemctl restart k0scontroller`.
When I execute `k0s kubectl get storageclass` I am still getting an error **No resources found**

**Comment by Ed87** [comment]
@soider @jnummelin  may you assist I seem to be stuck . Even after doing  **sudo systemctl restart k0scontroller** the storage class is not provisioned yet. 

Is k0s.yaml file in correct order ?

**Comment by jnummelin** [comment]
@Ed87 
> Is k0s.yaml file in correct order ?

Impossible to say, your copy-paste lost all the yaml formatting 😄 

On the controllers, do you see `/var/lib/k0s/manifests/helm/addon_crd_manifest_openebs.yaml` file created? That's how k0s internally deploys OpenEBS local-storage. If not, that indicates an issue in the config so k0s will not even try to deploy it.

**Comment by Ed87** [comment]
@jnummelin  the file  addon_crd_manifest_openebs.yaml is not being created , I have checked.  I have tried to validate the yaml though with  : `kubeval  k0s.yaml` but I get an error :

_**Failed initializing schema https://kubernetesjsonschema.dev/master-standalone/clusterconfig-k0s-v1beta1.json: Could not read schema from HTTP, response status is 404 Not Found**_

**Comment by Ed87** [comment]
@jnummelin  can i provide my yaml so you check if it has any issues

**Comment by soider** [comment]
@Ed87 please do so and once somebody from the team would have time, we help you

**Comment by Ed87** [comment]
@soider @jnummelin   you can access the yaml on the following  link 

[https://drive.google.com/file/d/1yKBNL_nu8YQxCjjNNC8pZWax-FTfxnmN/view?usp=sharing](url)

**Comment by jnummelin** [comment]
> the file addon_crd_manifest_openebs.yaml is not being created

That indicates that k0s is NOT trying to even deploy the OpenEBS local storage operator.

Which k0s version you are using, check with `k0s version`

Also have a look at the controller logs, if you're on a systemd enabled Linux distro, check with `journalctl -u k0scontroller.service` and search for `openebs` if you see any errors related to this.

Maybe also double/tripple check that the systemd unit for k0s is using the same config file you are editing currently. The path to the unit file is `/etc/system/systemd/k0scontroller.service` IIRC

**Comment by Ed87** [comment]
@soider @jnummelin  I have managed to setup storageclass as per `https://serverfault.com/questions/1091569/how-do-i-configure-storage-class-on-an-existing-k0s-cluster/1093670#1093670`. However provisioning a persistent volume claim after this is an issue as it remains in **Pending** mode.

As a check to satisfy the **WaitForFirstConsumer** constraint I created a deployment but after some time the persistent volume claim still remains in Pending mode.

I am pretty sure storageclass is configured well now (unless otherwise !) because when I run `k0s kubectl get storageclass` I get :

`openebs-device     openebs.io/local   Delete          WaitForFirstConsumer   false                  11h
openebs-hostpath   openebs.io/local   Delete          WaitForFirstConsumer   false                  11h
`

For contecxt my local-pvc.yaml is as below:

`apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-claim
spec:
  storageClassName: openebs.io/local
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Mi`

I want to close this one out for now but not sure if this pvc creation error could be related to how I managed to configure storageclass

**Comment by Ed87** [comment]
UPDATE : I have changed the storageClassName: value to  **`openebs-device`** . I am still getting same error .

I have done `ks describe pod mssql-depl-86c86b5f77-ldj49` and the output shows that the node is failing to schedule :

`Name:           mssql-depl-86c86b5f44-ldj49
Namespace:      default
Priority:       0
Node:           <none>
Labels:         app=mssql
                pod-template-hash=86c86b5f44
Annotations:    kubernetes.io/psp: 00-k0s-privileged
Status:         Pending
IP:
IPs:            <none>
Controlled By:  ReplicaSet/mssql-depl-86c86b5f44
Containers:
  mssql:
    Image:      mcr.microsoft.com/mssql/server:2019-CU15-ubuntu-20.04
    Port:       1433/TCP
    Host Port:  0/TCP
    Environment:
      MSSQL_PID:    Express
      ACCEPT_EULA:  Y
      SA_PASSWORD:  <set to the key 'SA_PASSWORD' in secret 'mssql'>  Optional: false
    Mounts:
      /var/opt/mssql/data from mssqldb (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-v6hff (ro)
Conditions:
  Type           Status
  PodScheduled   False
Volumes:
  mssqldb:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  mssql-claim
    ReadOnly:   false
  kube-api-access-v6lzw:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason            Age                From               Message
  ----     ------            ----               ----               -------
  Warning  FailedScheduling  17m                default-scheduler  0/1 nodes are available: 1 node(s) had taint {node-role.kubernetes.io/master: }, that the pod didn't tolerate.
  Warning  FailedScheduling  10m (x6 over 16m)  default-scheduler  0/1 nodes are available: 1 node(s) had taint {node-role.kubernetes.io/master: }, that the pod didn't tolerate.
`

I have been able to fix this previously with the command  `
k0s kubectl taint nodes svr02 node-role.kubernetes.io/master-` but this time its not working.

**Comment by Ed87** [comment]
@soider @jnummelin  anyone to assist

**Comment by Ed87** [comment]
@jnummelin  I am not on a systemd unit (maybe) because `cat /etc/system/systemd/k0scontroller.service` gives error `No such file or directory`.
**k0S version :  v1.23.1+K0s.0**

**Comment by Ed87** [comment]
@jnummelin @soider what are your usernames on slack .. definitely need more interactive assistance

**Comment by soider** [comment]
Same name as everywhere, Mikhail Sakhnov. Though need to say I am away until the end of the next week.
