### ISSUE TITLE
Installation fails on FedoraCoreOS

### ISSUE THREAD

**Issue by OrvilleQ** [k0sproject/k0s#1480]
### Before creating an issue, make sure you've checked the following:

- [X] You are running the latest released version of k0s
- [X] Make sure you've searched for existing issues, both open and closed
- [X] Make sure you've searched for PRs too, a fix might've been merged already
- [X] You're looking at docs for the released version, "main" branch docs are usually ahead of released versions.

### Version

v1.23.1+k0s.0

### Platform

```shell
Fedora CoreOS 35.20220103.3.0
```

### What happened?

The `k0s install` crashed on the Fedora CoreOS.

### Steps to reproduce

1. `k0s install controller` on Fedora CoreOS
2. `Error: failed to create controller users: exit status 9`

### Expected behavior

exit 0 with no error and cluster is ready to go.

### Actual behavior

The program crashed with `Error: failed to create controller users: exit status 9` which comes from `useradd`, `exit status 9` means the user already exist.

### Screenshots and logs

```
[root@localhost bin]# k0s install controller --single
WARN[2022-01-29 12:23:28] no config file given, using defaults
Error: failed to create controller users: exit status 9
```

### Additional context

This is a sequel to #1402.

Though 555bd82207811833b2e4cc28e7e068a74cbc359d give us the ability to detect user exists or not through `nss-altfiles`, but we are still facing the installation fail on Fedora CoreOS (or other nss-altfiles based distro). 

The program will still try to create the `etcd` user even though (I believe) it knows the user already exists.

I asked the CoreOS guys why there is a pre-defined `etcd` user and is it possible to remove them in https://github.com/coreos/fedora-coreos-tracker/issues/1083, the answer is:

>Some of those accounts are arguably there for historical reasons.  We can't remove them, though, because that would affect existing machines on upgrade, and some of those machines may be using the accounts.
>
>It sounds like k0s wants the `etcd` user to exist, though.  Can the k0s installer be fixed to use an existing user account if present?
>
>_Originally posted by @bgilbert in https://github.com/coreos/fedora-coreos-tracker/issues/1083#issuecomment-1025075427_

So, is it possible to just use the exist user instead of creating a new one?

And `userdel` during uninstallation won't work either, obviously.

**Comment by OrvilleQ** [comment]
PS. user `etcd` is located in `/usr/lib` which is read-only in Fedora CoreOS.

**Comment by jnummelin** [comment]
The related `nss-altfiles` fix got shipped with `v1.23.1+k0s.1`: https://github.com/k0sproject/k0s/releases/tag/v1.23.1%2Bk0s.1

Just tried on AWS FedoraCoreOS 35 AMI and seems to work:
```
[core@ip-172-31-44-138 ~]$ curl -sSfL  https://github.com/k0sproject/k0s/releases/download/v1.23.1+k0s.1/k0s-v1.23.1+k0s.1-amd64 -o k0s_1.23.1_1
[core@ip-172-31-44-138 ~]$ chmod a+x k0s_1.23.1_1
[core@ip-172-31-44-138 ~]$ sudo ./k0s_1.23.1_1 install controller --debug
DEBU[2022-01-31 12:08:24] found local addresses: [172.31.44.138 fe80::a6a8:e52a:a4f5:b49] 
DEBU[2022-01-31 12:08:24] found local addresses: [172.31.44.138 fe80::a6a8:e52a:a4f5:b49] 
WARN[2022-01-31 12:08:24] no config file given, using defaults         
DEBU[2022-01-31 12:08:24] found local addresses: [172.31.44.138 fe80::a6a8:e52a:a4f5:b49] 
DEBU[2022-01-31 12:08:24] found local addresses: [172.31.44.138 fe80::a6a8:e52a:a4f5:b49] 
2022/01/31 12:08:24 starting debug server under :6060
INFO[2022-01-31 12:08:24] creating user: kube-apiserver                
INFO[2022-01-31 12:08:24] creating user: konnectivity-server           
INFO[2022-01-31 12:08:24] creating user: kube-scheduler                
INFO[2022-01-31 12:08:25] Installing k0scontroller service           
```

**Comment by OrvilleQ** [comment]
Yes. you are right. the `1.23.3+k0s.0` works just fine.

I thought https://get.k0s.sh will always download the latest version, turns out the K0S_VERSION is hard coded into the script.

Thanks for your answer.

**Comment by jnummelin** [comment]
> I thought https://get.k0s.sh will always download the latest version

We had it downloading the "latest" in the past but that breaks too easily as Github's "latest" release is a time based thing rather than semver point of view. 😄

**Comment by OrvilleQ** [comment]
> We had it downloading the "latest" in the past but that breaks too easily as Github's "latest" release is a time based thing 
rather than semver point of view. 😄

Maybe we can use sh to process the Release's RSS files?

https://github.com/k0sproject/k0s/releases.atom

Like if we run `curl https://github.com/k0sproject/k0s/releases.atom | grep "<title>" | grep -v rc | grep -v notes | sed 's/<title>//g' | sed 's/<\/title>//g'` with sh, we will have a list of release version

```
sh-5.1$ curl https://github.com/k0sproject/k0s/releases.atom | grep "<title>" | grep -v rc | grep -v notes | sed 's/<title>//g' | sed 's/<\/title>//g'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 11257  100 11257    0     0  10171      0  0:00:01  0:00:01 --:--:-- 10178
    v1.23.3+k0s.0
    v1.22.6+k0s.0
    v1.21.9+k0s.0
    v1.23.1+k0s.1
```

Then we can pass it to another sh function and do some compare.
