### ISSUE TITLE
File not found error when copying kubeconfig file to jenkins context

### ISSUE THREAD

**Issue by Ed87** [k0sproject/k0s#1481]
I am trying to access a k0s cluster with Jenkins in order to deploy from Jenkins pipeline. In order to copy/paste cluster credentials in the kubeconfig file I tried to access with "~/.kube/config" command but there is an error saying "No such file or directory" i.e when I run :

`sudo cp ~/.kube/config  ~/.jenkins/.kube/`

I get  **_No such file or directory_**. 

It appears as if the config file is not there or may be located elsewhere where I am not aware. 

I have created a kubeconfig file for the root user  (on the assumption that it doesnt exist by default) as  per the documentation [here](https://docs.k0sproject.io/main/cli/k0s_kubeconfig_create/) :
`k0s kubeconfig create root`

but when I reattempt to copy I am still getting same error 'No such file or directory'. The config has been created as per output from this command `k0s kubeconfig create root` :
`
WARN[2022-01-30 17:44:16] no config file given, using defaults

apiVersion: v1
clusters:
- cluster:
    server: https://10.XXX.XXX.XXX:6443
    certificate-authority-data: xxxxxxxx
  name: k0s
contexts:
- context:
    cluster: k0s
    user: root
  name: k0s
current-context: k0s
kind: Config
preferences: {}
users:
- name: root
  user:
    client-certificate-data: xxxxxxxxxxxx`

Furthermore I can verify that the file indeed exists with command :
`k0s kubectl config view
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://localhost:6443
  name: local
contexts:
- context:
    cluster: local
    namespace: default
    user: user
  name: Default
current-context: Default
kind: Config
preferences: {}
users:
- name: user
  user:
    client-certificate-data: REDACTED
    client-key-data: REDACTED`

Where is my kubeconfig file ? One of the posts suggests using the command  `k0s kubectl get pods -v=6`  but when I run it -v seems unsupported for k0s :
```
Error: unknown shorthand flag: 'v' in -v=6
See 'k0s kubectl get --help' for usage
```.

**Comment by jnummelin** [comment]
`~/.kube/config` does NOT get created by k0s by default at all. What k0s does create by default is the "break-the-glass" admin kubeconfig which is located at `/var/lib/k0s/pki/admin.conf`. See https://docs.k0sproject.io/v1.23.3+k0s.0/FAQ/#how-do-i-connect-to-the-cluster

`k0s kubeconfig create ...` does NOT put the config into any file, it just outputs it and lets the user put/redirect it to file.

The issue with `-v` is a known problem, see https://github.com/k0sproject/k0s/issues/1405

**Comment by Ed87** [comment]
@jnummelin  I have just confirmed, when I ran  `k0s kubeconfig create ...` a file named config was actually created at ~/.kube with following  contents :
`apiVersion: v1
clusters:
- cluster:
    server: https://10.XXX.XXX.XXX:6443
    certificate-authority-data: XXXX
  name: local
contexts:
- context:
    cluster: local
    namespace: default
    user: user
  name: Default
current-context: Default
kind: Config
preferences: {}
users:
- name: user
  user:
    client-certificate-data: XXX
    client-key-data: XXX`

I assume this is wrong and will NOT work . 
I am proceeding to copy admin.conf to  ~/.kube (_**should I create subdirectory config also**_ ?). Thereafter I will copy the file to ~/.jenkins.
Confirm this is the correct procedure

**Comment by jnummelin** [comment]
`k0s kubeconfig create ...` will NOT create anything under `~/.kube`, see https://github.com/k0sproject/k0s/blob/main/cmd/kubeconfig/create.go#L71-L127

> I am proceeding to copy admin.conf to ~/.kube 

While you _CAN_ do that, I would strongly advise not to. The `admin.conf` is the ["break-the-glass" admin access config](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/#more-information), what it essentially does it e.g. bypasses the RBAC completely. In this case if access to Jenkins leaks for some reason also the "super admin" access gets leaked. I'd rather create dedicated access for Jenkins with proper RBAC allowing only the needed access.

As alternatives you have some choices:
- Create some [SA token](https://kubernetes.io/docs/reference/access-authn-authz/authentication/#service-account-tokens) for Jenkins and proper RBAC to only allow needed actions
- Use some external IdP: https://docs.k0sproject.io/v1.23.3+k0s.0/examples/oidc/oidc-cluster-configuration/?h=openid

The benefit of using a dedecated "user" and RBAC for Jenkins is the fact that you can then also revoke that access. If you use the admin.conf, there's practically no way to revoke the access.

**Comment by Ed87** [comment]
+1 thanks . will check the options and revert

**Comment by Ed87** [comment]
Closed
