### ISSUE TITLE
unable to run k0s on ZFS without manual intervention

### ISSUE THREAD

**Issue by fkaiserbio** [k0sproject/k0s#1490]
### Before creating an issue, make sure you've checked the following:

- [X] You are running the latest released version of k0s
- [X] Make sure you've searched for existing issues, both open and closed
- [X] Make sure you've searched for PRs too, a fix might've been merged already
- [X] You're looking at docs for the released version, "main" branch docs are usually ahead of released versions.

### Version

v1.23.3+k0s.0

### Platform

```shell
Ubuntu 20.04.3 LTS x86_64
containerd version: 1.4.12
ZFS userspace version: zfs-2.1.2
ZFS kernel modules version: zfs-kmod-2.0.2
```

### What happened?

k0s is not starting on a ZFS based system

### Steps to reproduce

1. install OS on ZFS root
2. try to launch k0s cluster according to the guide (https://docs.k0sproject.io/v1.21.2+k0s.1/install/)
3. k0s controller node remains in NotReady state

### Expected behavior

k0s cluster should start as expected

### Actual behavior

k0s fails to start controller node

### Additional context

This is a revisit of issue #728 which was unfortunately closed, although it provides the exact solution to the problem. But this solution was never confirmed by the issue author because he switched to LVM file system with overlayfs. I'm opening this issue to help anyone who wants to launch k0s on a ZFS-based system.

Thanks to the [comment](https://github.com/k0sproject/k0s/issues/728#issuecomment-783236376) of @[jnummelin](https://github.com/jnummelin) I could do the following steps to make k0s run easily on a ZFS-based system:

- check with `$ ctr -a /run/k0s/containerd.sock plugins ls` that the containerd ZFS snapshotter plugin is in `ok` state (should be the case if ZFS kernel modules and userspace utils are correctly configured
- create a containerd config according to the documentation: `$ containerd config default > /etc/k0s/containerd.toml`
- modify the line in `/etc/k0s/containerd.toml`:
``` 
...
    [plugins."io.containerd.grpc.v1.cri".containerd]
      snapshotter = "overlayfs"
...
```
to
``` 
...
    [plugins."io.containerd.grpc.v1.cri".containerd]
      snapshotter = "zfs"
...
```
- create a ZFS dataset to be used as snapshot storage at your desired location, e.g. `$ zfs create -o mountpoint=/var/lib/k0s/containerd/io.containerd.snapshotter.v1.zfs rpool/containerd`
- install k0s as usual, e.g `$ k0s install controller --single -c /etc/k0s/k0s.yaml`
- containerd should be launched with ZFS support and k0s should initialize the cluster correctly

I hope this is of help to anyone who wants to launch k0s on ZFS and might find its way into the docs.

**Comment by kke** [comment]
> I hope this is of help to anyone who wants to launch k0s on ZFS and might find its way into the docs

You can almost copy & paste this into a docs pr :)
