### ISSUE TITLE
Failed to run Kubelet: could not detect clock speed from output

### ISSUE THREAD

**Issue by suhabe** [k0sproject/k0s#1493]
### Before creating an issue, make sure you've checked the following:

- [X] You are running the latest released version of k0s
- [X] Make sure you've searched for existing issues, both open and closed
- [X] Make sure you've searched for PRs too, a fix might've been merged already
- [X] You're looking at docs for the released version, "main" branch docs are usually ahead of released versions.

### Version

v1.23.3+k0s.0

### Platform

```shell
k0s in Docker on M1 Mac with macOS Monterey v12.1
```

### What happened?

When running this command to create a new worker:
`k0s worker $token` 

The following error is printed out and then the command exits with status code 1, and then it'll "respawn" and continue to retry (and then exiting with the same error message) over and over again, thus never actually adding any new workers to the cluster:

`INFO[2022-02-05 21:43:26] E0205 21:43:26.583372     172 server.go:302] "Failed to run kubelet" err="failed to run Kubelet: could not detect clock speed from output: \"processor\\t: 0\\nBogoMIPS\\t: 48.00\\n..."  component=kubelet`
`WARN[2022-02-05 21:43:26] exit status 1                                 component=kubelet`
`INFO[2022-02-05 21:43:26] respawning in 5s                              component=kubelet`
`INFO[2022-02-05 21:43:31] Restarted                                     component=kubelet`

### Steps to reproduce

Follow the instructions for k0s docker at this link on an M1 Mac: https://docs.k0sproject.io/main/k0s-in-docker/ 

On an M1 Mac:
1. `docker run -d --name k0s --hostname k0s --privileged -v /var/lib/k0s -p 6443:6443 docker.io/k0sproject/k0s:latest`
2. `token=$(docker exec -t -i k0s k0s token create --role=worker)`
3. `docker run -d --name k0s-worker1 --hostname k0s-worker1 --privileged -v /var/lib/k0s docker.io/k0sproject/k0s:latest k0s worker $token`

The output of step 3 will include the error described above and then it will exit with status code 1 and then "respawn".

### Expected behavior

The expected behavior is that running the `k0s worker $token` command will add a node to the cluster.

### Actual behavior

The actual behavior is that running the `k0s worker $token` command will exit with status code 1 and respawn repeatedly and never adding a node to the cluster.

**Comment by Moroder95** [comment]
@suhabe did you ever find a solution?

**Comment by whisper-bye** [comment]
+1

**Comment by jpuskar** [comment]
This worked for me to get around the clock speed error.
I'm using Colima.

```shell
docker run \
  --name k0s \
  --hostname k0s \
  --privileged \
  -v /var/lib/k0s \
  -e DOCKER_DEFAULT_PLATFORM=linux/amd64 \
  -p 6443:6443 \
    k0sproject/k0s:v1.32.2-k0s.0
```
