### ISSUE TITLE
Document enabling swap memory for K8s v1.22+

### ISSUE THREAD

**Issue by keshavkaul** [k0sproject/k0s#1524]
### Additional context

I'm running K0s on my raspberry pi 3b that has 1GB memory. I have allocated 8GB of swap space on my microsd card of total 64GB space. The k0s cluster does not detect the swap space and hence i'm limited to only a few hundred MB of memory space to run my pods on.

**Comment by keshavkaul** [comment]
I tried
`sudo k0s install controller --single --kubelet-extra-args "--feature-gates NodeSwap=true --fail-swap-on false"`
But somehow the worker does not join the control node in single node mode. It gives an unauthenticated error with invalid bearer token.

**Comment by jnummelin** [comment]
@keshavkaul how does the systemd unit file look like that gets created via the install command?

**Comment by jnummelin** [comment]
> But somehow the worker does not join the control node in single node mode. It gives an unauthenticated error with invalid bearer token.

I believe that is because the initial try created a short lived token which is now expired. The easiest way is to run a full reset with `k0s reset`. That'll wipe out EVERYTHING k0s related so you can start from a clean slate.

I tested with a systemd unit looking like this:
```
ExecStart=/usr/local/bin/k0s controller --kubelet-extra-args='--feature-gates=NodeSwap=true --fail-swap-on=false' --single=true
```

(I didn't test the swap behaviour, but all the flags are properly set to kubelet)

**Comment by keshavkaul** [comment]
The service installed as this:
```
[Unit]
Description=k0s - Zero Friction Kubernetes
Documentation=https://docs.k0sproject.io
ConditionFileIsExecutable=/usr/local/bin/k0s

After=network-online.target
Wants=network-online.target

[Service]
StartLimitInterval=5
StartLimitBurst=10
ExecStart=/usr/local/bin/k0s controller --kubelet-extra-args=--feature-gates\x20NodeSwap=true\x20--fail-swap-on\x20false --single=true

RestartSec=120
Delegate=yes
KillMode=process
LimitCORE=infinity
TasksMax=infinity
TimeoutStartSec=0
LimitNOFILE=999999
Restart=always

[Install]
WantedBy=multi-user.target
```
`sudo k0s kubectl get node` returns `No resources found`

**Comment by keshavkaul** [comment]
@jnummelin I've updated my findings

**Comment by jnummelin** [comment]
I believe this is a case where the original try of the joining the local worker has somehow failed and now the token used is already expired. For this `--enable-worker` case k0s itself creates a super short lived (255s) token. You could try by deleting `/var/lib/k0s/kubelet-bootstrap.conf` and then restarting the main k0s service. That'll make the controller to re-create a join token and re-do the kubelet registration etc.

**Comment by jnummelin** [comment]
closing as inactive
