### ISSUE TITLE
I want extraArgs for etcd as well.

### ISSUE THREAD

**Issue by chattytak** [k0sproject/k0s#1543]
### Is your feature request related to a problem? Please describe.

I don't think I need to explain the reason in depth, but sometimes I want to tune the timeout and limit of etcd.

### Describe the solution you would like

Make sure that etcd can add arguments freely with extraArgs.

**Comment by juanluisvaladas** [comment]
I have this implemented and tested but the documentation changes aren't done yet, I have to go but the PR will be done tomorrow or later today.
