### ISSUE TITLE
[Question] how to pass extra args to kubelet

### ISSUE THREAD

**Issue by wenerme** [k0sproject/k0s#1545]
### Before creating an issue, make sure you've checked the following:

- [X] You are running the latest released version of k0s
- [X] Make sure you've searched for existing issues, both open and closed
- [X] Make sure you've searched for PRs too, a fix might've been merged already
- [X] You're looking at docs for the released version, "main" branch docs are usually ahead of released versions.

### What happened?

k0s try pull k8s.gcr.io/pause

due to GFW, this will not work, how can I change the default registry or all used images ?

this image is not listed in k0s.yaml

kubelet has `--pod-infra-container-image  k8s.gcr.io/pause:3.6`, how to config this in k0s.yaml ?

**Comment by jnummelin** [comment]
https://docs.k0sproject.io/v1.23.3+k0s.1/worker-node-config/?h=kubelet#kubelet-args

**Comment by wenerme** [comment]
thanks, I thought I can pass through k0s.yaml

**Comment by shoce** [comment]
I guess the initial problem was installing k0s on a server located in China. I have the same issue now and i guess passing a different `--pod-infra-container-image` does not help as this option only prevents the named image from being pruned, as stated in docs. At least after I changed the value to a different domain I saw the same error in logs:

```
Apr 28 18:13:45 zz-china k0s[33438]: time="2022-04-28 18:13:45" level=info msg="E0428 18:13:45.115429   33471 pod_workers.go:949] \"Error syncing pod, skipping\" err=\"failed to \\\"CreatePodSandbox\\\" for \\\"kube-proxy-xxw8c_kube-system(237ee105-1001-4131-8805-20ba60f7db2a)\\\" with CreatePodSandboxError: \\\"Failed to create sandbox for pod \\\\\\\"kube-proxy-xxw8c_kube-system(237ee105-1001-4131-8805-20ba60f7db2a)\\\\\\\": rpc error: code = Unknown desc = failed to get sandbox image \\\\\\\"k8s.gcr.io/pause:3.5\\\\\\\": failed to pull image \\\\\\\"k8s.gcr.io/pause:3.5\\\\\\\": failed to pull and unpack image \\\\\\\"k8s.gcr.io/pause:3.5\\\\\\\": failed to resolve reference \\\\\\\"k8s.gcr.io/pause:3.5\\\\\\\": failed to do request: Head \\\\\\\"https://k8s.gcr.io/v2/pause/manifests/3.5\\\\\\\": dial tcp 108.177.97.82:443: i/o timeout\\\"\" pod=\"kube-system/kube-proxy-xxw8c\" podUID=237ee105-1001-4131-8805-20ba60f7db2a" component=kubelet
```
