### ISSUE TITLE
Document about system tools requirement

### ISSUE THREAD

**Issue by wenerme** [k0sproject/k0s#1546]
### Before creating an issue, make sure you've checked the following:

- [X] You are running the latest released version of k0s
- [X] Make sure you've searched for existing issues, both open and closed
- [X] Make sure you've searched for PRs too, a fix might've been merged already
- [X] You're looking at docs for the released version, "main" branch docs are usually ahead of released versions.

### Platform

```shell
alpine
```

### What happened?

I though k0s is bundled everything, os independent, but still, a clean alpine can not run k0s.

Please document what package and modules is required to run k0s in https://docs.k0sproject.io/v1.23.3+k0s.0/system-requirements/

This is a list of packages I installed after I can not boot k0s

```bash
apk add conntrack-tools coreutils dbus findutils ipset iptables socat iproute2 nfs-utils
```

The initial boot failed is because kube-proxy need iptables, I thought k0s bundled `xtables-legacy-multi` is enough, seems not.

**Comment by wenerme** [comment]
found one by search iptable https://docs.k0sproject.io/v1.23.3+k0s.1/internal/host-dependencies/?h=iptable

this doc is not listed, maybe should add to https://docs.k0sproject.io/v1.23.3+k0s.0/system-requirements/ ?

**Comment by jnummelin** [comment]
> The initial boot failed is because kube-proxy need iptables, I thought k0s bundled xtables-legacy-multi is enough, seems not.

Yes, it needs iptables but the kube-proxy container comes with it's own iptables binary in it:
```
bash-5.1# k0s kc -n kube-system exec -t -i kube-proxy-q487m -- which iptables
/usr/sbin/iptables
```

All our smoke tests runs on Alpine env where we do not setup those packages.


What kind of errors you saw before adding these packages?

**Comment by ncopa** [comment]
> I though k0s is bundled everything, os independent

So did I also think. If its not then we have a bug.
Can you please share the exact version of k0s you are using, what version of Alpine Linux you use and what architecture (x86_64? aarch64?)

Can you share the error logs? Or a way to reproduce it.

I know that you at least need to enable the services `cgroup` and `machine-id` for Kubernetes to work. coreutils iptables etc should not be needed in recent Kubernetes.

**Comment by wenerme** [comment]
- Alpine 3.15.0
- k0s v1.23.3+k0s.0
- x86_64

The initial boot failed with kube-router crash loop

the last line of  kube-router is 
```
Failed to watch *v1.Node: failed to list *v1.Node: Get "https://10.96.0.1:443/api/v1/nodes?limit=500&resourceVersion=0": dial tcp 10.96.0.1:443: i/o timeout
```

only kube-proxy container is running.

after I installed iptables, `iptables -L` is empty.

Maybe caused by missing machine-id, I remember install dbus will create machine-id.

**Comment by ncopa** [comment]
I [added](https://gitlab.alpinelinux.org/alpine/aports/-/commit/42b9be02531e02930ae69bc90aa78328d10501d7) a simple `/etc/init.d/machine-id` service that can be enabled so you don't need to install dbus. I believe it should be enough to start that service.

**Comment by wenerme** [comment]
@ncopa thanks, maybe k0s sysinfo should check all the requirement
