### ISSUE TITLE
Error: Kubernetes cluster unreachable when I attempt helm upgrade install

### ISSUE THREAD

**Issue by Ed87** [k0sproject/k0s#1548]
I have setup helm on my Debian 10 instance where I am running k0s - when I try to do  `helm upgrade --install flextoeco .`  I am getting an error :

`Error: Kubernetes cluster unreachable: Get "https://localhost:6443/version": x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "kubernetes-ca")`

What am I missing ? 

Is there a way to skip this TLS verification or its something that could be incorrect with my cacerts.

@soider  @jnummelin

**Comment by soider** [comment]
Looks like you are using wrong auth certificates. Check your kubeconfig.

**Comment by Ed87** [comment]
mv $HOME/.kube $HOME/.kube.bak
mkdir $HOME/.kube
sudocp-I /var/lib/k0s/admin.conf $HOME/.kube/config
sudo chown$(id-u):$(id-g)$HOME/.kube/config
