### ISSUE TITLE
Unable to find cluster settings for Liveness probe ?

### ISSUE THREAD

**Issue by Ed87** [k0sproject/k0s#1549]
I am facing a **_"CrashLoopBackoff"_** error when I deploy a .Net Core API with helm upgrade --install flextoeco . :

`NAME                            READY   STATUS             RESTARTS        AGE
flextoecoapi-6bb7cdd846-r6c67   0/1     CrashLoopBackOff   4 (38s ago)     3m8s
flextoecoapi-fb7f7b556-tgbrv    0/1     CrashLoopBackOff   219 (53s ago)   10h
mssql-depl-86c86b5f44-ldj48     0/1     Pending  `

I have run `ks describe pod flextoecoapi-6bb7cdd846-r6c67` and part of the output is as below :

`Events:
Type     Reason     Age                     From               Message
  ----     ------     ----                    ----               -------
  Normal   Scheduled  5m4s                    default-scheduler  Successfully assigned default/flextoecoapi-6bb7cdd846-r6c67 to fbcdcesdn02
  Normal   Pulling    5m3s                    kubelet            Pulling image "golide/flextoeco:1.1.1"
  Normal   Pulled     4m57s                   kubelet            Successfully pulled image "golide/flextoeco:1.1.1" in 6.2802081s
  Normal   Killing    4m34s                   kubelet            Container flextoeco failed liveness probe, will be restarted
  Normal   Created    4m33s (x2 over 4m57s)   kubelet            Created container flextoeco
  Normal   Started    4m33s (x2 over 4m56s)   kubelet            Started container flextoeco
  Normal   Pulled     4m33s                   kubelet            Container image "golide/flextoeco:1.1.1" already present on machine
  Warning  Unhealthy  4m14s (x12 over 4m56s)  kubelet            Readiness probe failed: Get "http://10.244.6.59:80/": dial tcp 10.244.0.59:80: connect: connection refused
  Warning  Unhealthy  4m14s (x5 over 4m54s)   kubelet            Liveness probe failed: Get "http://10.244.6.59:80/": dial tcp 10.244.0.59:80: connect: connection refused
  Warning  BackOff    3s (x10 over 2m33s)     kubelet            Back-off restarting failed container`

Among the solutions suggested here [https://stackoverflow.com/questions/41604499/my-kubernetes-pods-keep-crashing-with-crashloopbackoff-but-i-cant-find-any-lo](url) is to _**increase the LivenessProbe setting  initialDelaySeconds**_ but I am not sure where I can find the relevant yaml.

@soider  @jnummelin  may you kindly assist

**Comment by jnummelin** [comment]
The field "path" is `pod.spec.containers.livenessProbe.initialDelaySeconds`, read more at https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle#container-probes

**Comment by Ed87** [comment]
+1 @jnummelin  I have added this to my values.yaml (I'm using helm for deployments) but not sure if its correct, the default values.yaml template is not exactly to the one at  [link](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/)

**Comment by Ed87** [comment]
Resolved by editing /templates/deployment.yaml under the charts directory for helm
