### ISSUE TITLE
 504 Gateway Timeout error when calling Ingress with MetalLB

### ISSUE THREAD

**Issue by Ed87** [k0sproject/k0s#1559]
I am getting 504 Gateway Timeout error when I attempt a request to my .Net Core API running behind Ingress Load Balancer using the call http://flextoeco.local/account?field4=3909090909090&field7=GENERIC01&field10=ABC076. 

The equivalent API call (http://16.xxx.xxx.xxx:5050/account?field4=3909090909090&field7=GENERIC01&field10=ABC076) however responds as expected when I use either **docker run** for the image or when I deploy as a **NodePort**.

This is how the API is deployed currently (helm) :

**values.yaml**

`replicaCount: 3

image:
  repository: golide/flextoeco
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "1.1.2"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000        
podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: ""
  annotations: {}
  hosts:
    - host: flextoeco.local
    - paths:
        - path: /account
          pathType: ImplementationSpecific
  tls: []

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80    
nodeSelector: {}`

**/templates/deploment.yaml**

`apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "flextoeco.fullname" . }}
  labels:
    {{- include "flextoeco.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "flextoeco.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "flextoeco.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "flextoeco.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
            containerPort: 5000
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 5000
            initialDelaySeconds: 300
            periodSeconds: 30
            timeoutSeconds: 20
          readinessProbe:
            tcpSocket:
              port: 5000
            initialDelaySeconds: 300
            periodSeconds: 30
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
 {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}`

I have already created an entry in the hosts file : [hostsfile](https://i.stack.imgur.com/LLpGt.png)
When I curl the API  ( on the host where k0s is running) I also get an error :

`curl http://flextoeco.local/account?field4=3909090909090&field7=GENERIC01&field10=ABC076
[1] 1007485
[2] 1007486
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL was not found on this server.</p>
<hr>
<address>Apache/2.4.51 (Debian) Server at flextoeco.local Port 80</address>
</body></html>
root@fbcdcesdn02:/home/golide/Projects/FlexToEcocash_main/FlexToEcocash/charts/flextoeco# <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL was not found on this server.</p>
<hr>
<address>Apache/2.4.51 (Debian) Server at flextoeco.local Port 80</address>
</body></html> `

I can see a section for backend in ingress.yaml but not sure If i should be explicitly specifying this in values.yaml (and if so what will be the value for serviceName?) :
`  backend:
          {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
          service:
            name: {{ $fullName }}
            port:
              number: {{ $svcPort }}
          {{- else }}
          serviceName: {{ $fullName }}
          servicePort: {{ $svcPort }}
          {{- end }}`

What am I missing ?

Checklist
1)Ingress is setup as per this [link](https://docs.k0sproject.io/v1.22.2+k0s.1/examples/nginx-ingress/) and I opted for the NGINX using LoadBalancer (MetalLB) way. 

2) I had a msql service/deployment with a loadbalancer and previously it didnt have any ExternalIP but after configuring it now has an allocation which means my configuration was successful :

`flextoeco             ClusterIP      10.100.113.109   <none>         80/TCP           2d12h
kubernetes            ClusterIP      10.96.0.1        <none>         443/TCP          8d
mssql-clusterip-srv   ClusterIP      10.109.74.155    <none>         1433/TCP         8d
**mssql-loadbalancer    LoadBalancer   10.98.17.80      17.168.1.180   1433:32724/TCP   8d**
`
3) I have already edited the NGINX Ingress Controller to use LoadBalancer instead of NodePort :
`ks get services -n ingress-nginx
NAME                                 TYPE           CLUSTER-IP       EXTERNAL-IP    PORT(S)                      AGE
ingress-nginx-controller             LoadBalancer   10.111.102.209   17.168.1.181   80:32137/TCP,443:30505/TCP   28h
ingress-nginx-controller-admission   ClusterIP      10.111.197.68    <none>         443/TCP                      28h
`

4) Try connecting to the Ingress controller
This is where I think I have an issue because Im not getting expected output . As per documentation _If you don't yet have any backend service configured, you should see "404 Not Found" from nginx. This is ok for now. If you see a response from nginx, the Ingress Controller is running and you can reach it using LoadBalancer._  On my part however this is what I'm getting :

**Comment by Ed87** [comment]
![image](https://user-images.githubusercontent.com/23119187/155476847-dd37d485-1fb8-4600-b459-39e143fe1b2d.png)

**Comment by Ed87** [comment]
![image](https://user-images.githubusercontent.com/23119187/155476956-ed0ce54c-36b7-4b24-9371-0167c773e2bd.png)

**Comment by Ed87** [comment]
@soider @jnummelin  I'm not sure if my config is set up well .

**Comment by Ed87** [comment]
ks get pods -n ingress-nginx  : 

`ingress-nginx-admission-create-mnpfr    0/1     Completed          0                30h
ingress-nginx-controller-7f48b8-rgksh   0/1     CrashLoopBackOff   500 (2m1s ago)   30h`

**Comment by mviitane** [comment]
Just to check did you get your MetalLB deployment working before installing Ingress (so that Kubernetes can deploy LoadBalancer service)?

**Comment by Ed87** [comment]
@mviitane  how do I check for that

**Comment by Ed87** [comment]
I have checked the using instructions from [here](https://metallb.universe.tf/configuration/troubleshooting/) . So I used my other loadbalancer service for SQL-Server (_**which I previously mentioned that it got assigned an externalIP as soon as  I finished setting up MetalLB)**_. 
` ks -n default get endpoints mssql-loadbalancer
NAME                 ENDPOINTS          AGE
mssql-loadbalancer   10.244.0.75:1433   12d
`

**Comment by Ed87** [comment]
@mviitane Away from MetalLB context I have realised that _Liveness & readiness probes are failing_ but however as I have already stated _**this happens only after I deploy the application with a LoadBalancer**_. 

  The equivalent API call (http://16.xxx.xxx.xxx:5050/account?field4=3909090909090&field7=GENERIC01&field10=ABC076) however responds as expected when I use either docker run for the image or when I deploy as a NodePort.

So I dug a little deeper with the checks on this [post](https://www.reddit.com/r/kubernetes/comments/t07fzf/504_gateway_timeout_error_on_kubernetes_ingress/)

**Comment by mviitane** [comment]
OK. It's hard to pinpoint the fault, but it could be related to the load balancer. To narrow down the problem, you could test the MetalLB load balancer setup separately (without ingress and your application) and see if you can get the example web server up and running with the load balancer:
https://docs.k0sproject.io/latest/examples/metallb-loadbalancer/

**Comment by Ed87** [comment]
+1 @mviitane  let me check that and revert
