### ISSUE TITLE
Setting up controller in the cloud and worker node in another network (on-prem or another vpc)

### ISSUE THREAD

**Issue by martencassel** [k0sproject/k0s#1582]
### Is your feature request related to a problem? Please describe.

I'm currently struggling trying to setup a master node in the cloud, and a worker node "on-prem", or in another vpc.

### Describe the solution you would like

It would be awesome if this scenario could be documented in a guide.

### Describe alternatives you've considered

Modifying the join token, changing the ip address.
Setting up certs... not sure what certs to copy.

### Additional context

I have two VPC's in azure on per node (controller and worker) to test this.

**Comment by jnummelin** [comment]
@martencassel Apparently you got all figured out. Was there something that could be highlighted in the docs for this?
