### ISSUE TITLE
Upgrade containerd to 1.6

### ISSUE THREAD

**Issue by wenerme** [k0sproject/k0s#1595]
### Is your feature request related to a problem? Please describe.

1.6 resolved this problem https://github.com/containerd/containerd/issues/4604 with https://github.com/containerd/containerd/pull/6478

```bash
sudo grep 'failed to reserve sandbox name' /var/log/k0s.log --count
```

```
1365
```

kube will resolve the problem but took sometime.

```bash
sudo grep 'failed to reserve sandbox name' /var/log/k0s.log | sed -n '1p;$p'
```

```
time="2022-03-18 01:24:53" 
time="2022-03-18 01:50:26" 
```

took 36m to fix the problem.

### Describe the solution you would like

Upgrade containerd to 1.6

### Additional context

- k0s v1.23.3+k0s.1
- containerd v1.5.9

**Comment by twz123** [comment]
The fix you mentioned was backported into [containerd 1.5.10](https://github.com/containerd/containerd/commits/v1.5.10) via containerd/containerd#6503. That release contained a security fix as well, and has already been updated in main, 1.23 and 1.22. Currently, they're available as release candidates, only:

| Branch | PR | Release candidate |
|--------|----|-------------------|
| main   | #1573  | -/- |
| 1.23   | #1576  | [1.23.4-rc.1+k0s.0] |
| 1.22   | #1575  | [1.22.7-rc.1+k0s.0] |

[1.23.4-rc.1+k0s.0]: https://github.com/k0sproject/k0s/commits/v1.23.4-rc.1%2Bk0s.0
[1.22.7-rc.1+k0s.0]: https://github.com/k0sproject/k0s/commits/v1.22.7-rc.1%2Bk0s.0

That said, the containerd 1.6 upgrade is on the radar, of course.
