### ISSUE TITLE
CRDT based Control Plane State

### ISSUE THREAD

**Issue by malarinv** [k0sproject/k0s#1625]
### Is your feature request related to a problem? Please describe.

Etcd being a strongly consistent kv store, it compromises on availability for edge use-cases, A lightweight eventually consistent control-plane state storage based on CRDTs could make k0s much more scalable and efficient.

### Describe the solution you would like

Well described in this paper https://dl.acm.org/doi/pdf/10.1145/3434770.3459730

### Describe alternatives you've considered

All other solutions aren't as performant as the CRDT based solution

### Additional context

This could be an unique/special feature of k0s :wink: 
I am not the author of the paper just found it to be an interesting read which might improve k0s/k3s. So here I am.

**Comment by jnummelin** [comment]
Not planned, community PRs welcome 😄
