### ISSUE TITLE
Implements a Cluster API Bootstrap Controller

### ISSUE THREAD

**Issue by hrenard** [k0sproject/k0s#1635]
### Is your feature request related to a problem? Please describe.

I'm just curious.

### Describe the solution you would like

It would be awesome if I could manage my clusters in a declarative and standard way on any infrastructure. 
This seems to be the goal of the [Cluster API Project](https://cluster-api.sigs.k8s.io). Did you consider implementing a Cluster API Bootstrap Controller ?

**Comment by jnummelin** [comment]
Take a look at k0sproject/k0smotron 😄
