### ISSUE TITLE
Usage of deprecated Kubelet flags: containerd, register-with-taints

### ISSUE THREAD

**Issue by twz123** [k0sproject/k0s#1636]
### Before creating an issue, make sure you've checked the following:

- [X] You are running the latest released version of k0s
- [X] Make sure you've searched for existing issues, both open and closed
- [X] Make sure you've searched for PRs too, a fix might've been merged already
- [X] You're looking at docs for the released version, "main" branch docs are usually ahead of released versions.

### Version

current main

### Platform

Linux

### What happened?

k0s uses deprecated kubelet flags:

https://github.com/k0sproject/k0s/blob/e8d317e96aaba77877bda668601d43fb42959133/pkg/component/worker/kubelet.go#L185
https://github.com/k0sproject/k0s/blob/e8d317e96aaba77877bda668601d43fb42959133/pkg/component/worker/kubelet.go#L141

### Steps to reproduce

Launch a k0s worker without specifying a CRI socket.

### Expected behavior

k0s is future-proof and doesn't use deprecated kubelet flags

### Actual behavior

k0s uses deprecated kubelet flags

### Screenshots and logs

> time="2022-04-06 10:25:13" level=info msg="Flag --containerd has been deprecated, This is a cadvisor flag that was mistakenly registered with the Kubelet. Due to legacy concerns, it will follow the standard CLI deprecation timeline before being removed." component=kubelet
time="2022-04-06 10:25:13" level=info msg="Flag --register-with-taints has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information." component=kubelet

### Additional context

#966 already mentioned the containerd flag, but the fix for it didn't address it.

**Comment by jnummelin** [comment]
This requires quite a big refactoring for the kubelet config. In nutshell the challenge is that worker gets the config from server, from the `kubelet-config...` `ConfigMap`. (via the k0s join process)

In essence this would mean:
- k0s join process gets the config, as we do already today
- k0s worker join parses the config and puts in all the "local" flags
- k0s worker join dumps the config to disk for kubelet, as we do today

**Comment by jnummelin** [comment]
(wrong button) 😂

**Comment by makhov** [comment]
What is the `--containerd` used for? I haven't found it in the docs either for v1.22 or v.1.23. Do we need it?

**Comment by jnummelin** [comment]
> What is the --containerd used for? I haven't found it in the docs either for v1.22 or v.1.23. Do we need it?

I think that was some older kube thing where it propagated some containerd info to cAdvisor based on that flag. AFAIK we can get rid of that
