### ISSUE TITLE
Bump k8s v1.24.0 / containerd 1.6.4

### ISSUE THREAD

**Issue by twz123** [k0sproject/k0s#1663]
This is a follow-up to #1634 with the next version bumps:

* [x] [Kubernetes v1.24.0](https://github.com/kubernetes/kubernetes/releases/tag/v1.24.0)
* [x] [containerd 1.6.4](https://github.com/containerd/containerd/releases/tag/v1.6.4)

**Comment by twz123** [comment]
Turns out that k8s v1.24.0-rc.1 now requires go 1.18.1 ...

**Comment by twz123** [comment]
We will skip containerd 1.6.3 and wait for containerd 1.6.4: https://github.com/containerd/containerd/issues/6876

**Comment by iusetabs** [comment]
@twz123 Just running some tests using the latest version of k0s and containerd v1.6.3. My test fails and the pod is stuck in ContainerCreating with "failed to setup network for sandbox". There is no issue with containerd v1.6.4. Is 1.6.3 going to be skipped or? 😄

**Comment by twz123** [comment]
@iusetabs Yep, k0s's integration tests were failing with 1.6.3... Skipped 1.6.3 (https://github.com/k0sproject/k0s/issues/1663#issuecomment-1113524232), already on 1.6.4 (#1690) on main.

**Comment by iusetabs** [comment]
@twz123 awesome thx very much :-D
