### ISSUE TITLE
Unable to connect to the server: x509: certificate has expired or is not yet valid:

### ISSUE THREAD

**Issue by furqanbaqai** [k0sproject/k0s#1766]
### Before creating an issue, make sure you've checked the following:

- [X] You are running the latest released version of k0s
- [X] Make sure you've searched for existing issues, both open and closed
- [X] Make sure you've searched for PRs too, a fix might've been merged already
- [X] You're looking at docs for the released version, "main" branch docs are usually ahead of released versions.

### Version

v1.21.3+k0s.0

### Platform

```shell
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.6 LTS
Release:	18.04
Codename:	bionic
```

### What happened?

Can not connect to the server, getting following error:
```
$ sudo k0s kubectl get node
Unable to connect to the server: x509: certificate has expired or is not yet valid: current time 2022-05-27T17:18:31Z is before 2022-05-27T20:50:00Z
```
Did a bit of digging and i belive this is because of the expire certs. Not sure how i can renew the certs using `k0s`. All docs are pointing to `kubeadm`. Appreciate som help

### Steps to reproduce

1. Execute `$ sudo k0s kubectl get node`

**Comment by jnummelin** [comment]
> Did a bit of digging and i belive this is because of the expire certs

Quite the contrary, it's coming from the api-server presenting a certificate that is not YET valid. So for some reason the valid-from timestamp is in the future. k0s creates the certs in a way that they are valid from the time they are created, thus this _should_ not happen. Unless there's been some server time changes (NTP syncs etc.)...

You can verify the cert details with commands like:

```
openssl x509 -in /var/lib/k0s/pki/server.crt -noout -text
```

**Comment by jnummelin** [comment]
> I was wondering, what is the internal behavior of these certs ?

k0s regenerates the client & serving certs (all non-CA certs) on every startup. The main idea was that users should update the k0s (and therefore kube version) at least once per year.

**Comment by m2acgi** [comment]
How to renew certs like `kubeadm certs renew all` ?
