### ISSUE TITLE
missing pid file to openrc init

### ISSUE THREAD

**Issue by arankaren** [k0sproject/k0s#1775]
https://github.com/k0sproject/k0s/blob/3fc8d7940d044849e6c9a0f656259167fa0d6b77/pkg/install/linux_openrc.go#L23

it's necessary add pid inside openrc init,

Please add `pidfile=/var/run/k0s.pid`:

```
...
description="{{.Description}}"
pidfile=/var/run/k0s.pid
...
```

**Comment by kke** [comment]
I think it should be [/run/k0s.pid](https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch03s15.html)

**Comment by arankaren** [comment]
> > it's necessary add pid inside openrc init
> 
> What issues you see when it's not there? (not saying we shouldn't add it smile )

without the pid the daemon does not work

**Comment by kke** [comment]
[OpenRC service script docs](https://github.com/OpenRC/openrc/blob/master/service-script-guide.md):

![image](https://user-images.githubusercontent.com/224971/174601642-c9a9f502-2ccc-4915-ac1a-4574d466bc54.png)

![image](https://user-images.githubusercontent.com/224971/174601711-6947cf84-1cbc-4192-aff1-ce858d72c49c.png)

--

Looks to me like OpenRC really wants a pidfile

It can create one on its own though:

--

![image](https://user-images.githubusercontent.com/224971/174601875-878d5700-2755-4a79-8d04-ece8d31af06f.png)

**Comment by twz123** [comment]
> without the **pid** the daemon does not work on OS with OpenRC

It works at least on [Alpine](https://wiki.alpinelinux.org/wiki/OpenRC). Can you provide more details, as requested in https://github.com/k0sproject/k0s/issues/1775#issuecomment-1160372664? Which OS does it not work on? What is the error message or what happens when it does not work?
