### ISSUE TITLE
Failed to setup network for sandbox: incompatible CNI versions; config is "1.0.0", plugin supports ["0.1.0" "0.2.0" "0.3.0" "0.3.1" "0.4.0"]

### ISSUE THREAD

**Issue by pasuder** [k0sproject/k0s#1776]
### Before creating an issue, make sure you've checked the following:

- [X] You are running the latest released version of k0s
- [X] Make sure you've searched for existing issues, both open and closed
- [X] Make sure you've searched for PRs too, a fix might've been merged already
- [X] You're looking at docs for the released version, "main" branch docs are usually ahead of released versions.

### Version

v1.23.6+k0s.2

### Platform

```shell
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.4 LTS
Release:	20.04
Codename:	focal
```

### What happened?

Pods `coredens` and `metrics-servers` are in `ContainerCreating` status since installation of fresh k0s single controller.

### Steps to reproduce

1. Follow installation as per https://docs.k0sproject.io/v1.23.6+k0s.2/install/
2. `sudo k0s kubectl get pods -A`
3. `sudo k0s kubectl -n kube-system describe pod coredns-XXXX-XXXX`

```
Warning  FailedCreatePodSandBox  82s (x17 over 4m56s) kubelet
 (combined from similar events): Failed to create pod sandbox:
    rpc error: code = Unknown desc = failed to setup network for sandbox "5ed545ae2a2539ff8124a18c7454c83cba7ea3ff6a185cbe3cbeae70f204cd05":
      incompatible CNI versions; config is "1.0.0", plugin supports ["0.1.0" "0.2.0" "0.3.0" "0.3.1" "0.4.0"]
```

### Expected behavior

All containers of `kube-system` namespace should be in `Running` state

### Actual behavior

Some containers of `kube-system` namespace are in `ContainerCreating` state.

### Screenshots and logs

```
$ kubectl -n kube-system logs coredns-8565977d9b-9fvrq
Error from server (BadRequest): container "coredns" in pod "coredns-8565977d9b-9fvrq" is waiting to start: ContainerCreating
```

### Additional context

```
$ containerd --version
containerd github.com/containerd/containerd v1.6.1 10f428dac7cec44c864e1b830a4623af27a9fc70
```

### Links

- https://github.com/containerd/containerd/issues/6876
- https://kubernetes.io/docs/tasks/administer-cluster/migrating-from-dockershim/troubleshooting-cni-plugin-related-errors/

**Comment by jnummelin** [comment]
```
$ containerd --version
containerd github.com/containerd/containerd v1.6.1 10f428dac7cec44c864e1b830a4623af27a9fc70
```

This looks fishy as that k0s version ships with containerd 1.5.11, see https://github.com/k0sproject/k0s/blob/v1.23.6+k0s.2/embedded-bins/Makefile.variables#L11

If you look at process tree (with e.g. `ps faux`), how is containerd started? I wonder if there's some other containerd bin in the PATH which k0s picks up for some reason.

Just created fresh VM to test this and I see everything getting up properly:
```
root@k0s-ubuntu20:~# k0s version
v1.23.6+k0s.2
root@k0s-ubuntu20:~# k0s kc get node,pod -A
NAME                STATUS   ROLES           AGE    VERSION
node/k0s-ubuntu20   Ready    control-plane   6m3s   v1.23.6+k0s

NAMESPACE     NAME                                  READY   STATUS    RESTARTS   AGE
kube-system   pod/kube-proxy-8mcjm                  1/1     Running   0          6m3s
kube-system   pod/kube-router-w75br                 1/1     Running   0          6m3s
kube-system   pod/coredns-8565977d9b-xqjbk          1/1     Running   0          6m7s
kube-system   pod/metrics-server-74c967d8d4-h9nx6   1/1     Running   0          6m4s
root@k0s-ubuntu20:~# /var/lib/k0s/bin/containerd --version
containerd github.com/containerd/containerd v1.5.11 3df54a852345ae127d1fa3092b95168e4a88e2f8
```
