### ISSUE TITLE
Kubelet Args vs. kubelet config file: which should be supported?

### ISSUE THREAD

**Issue by trawler** [k0sproject/k0s#1780]
Currently we have two ways to configure kubelet on the node: 
1. Kubelet extra args, which are configured by running`k0s worker --kubelet-extra-args` (example: -`-kubelet-extra-args='--event-qps=7 --enable-load-reader=true'`)
2. using a kubelet config file using a worker profile.

Currently we have[ precedence of the kubelet config from the cli flags, over the kubelet config file](https://github.com/kubernetes/kubernetes/blob/v1.24.1/cmd/kubelet/app/server.go#L202-L205).
Given the below quote from the [Kubernetes' kubelet config doc](https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/):
> Providing parameters via a config file is the recommended approach because it simplifies node deployment and configuration management.

I think we should graduate this behaviour (for consistency) and deprecate the kubelet-extra-args flag, provided that we can equate all kubelet flags to the kubelet config file values.

**Comment by soider** [comment]
I think, having args makes life much easier with a fast experiments. While we still have way to customize kubelet.conf by using k0s.yaml worker profiles, sometimes for an experiment it is easier to just run k0s without config (read as with default config). But I think it would be better if we do not pass any args to kubelet by default by changing code here https://github.com/k0sproject/k0s/blob/main/pkg/component/worker/kubelet.go#L134 to use kubelet.conf instead.
