### ISSUE TITLE
kube-apiserver keeps emitting warning when using Kine

### ISSUE THREAD

**Issue by aufarg** [k0sproject/k0s#1817]
### Before creating an issue, make sure you've checked the following:

- [X] You are running the latest released version of k0s
- [X] Make sure you've searched for existing issues, both open and closed
- [X] Make sure you've searched for PRs too, a fix might've been merged already
- [X] You're looking at docs for the released version, "main" branch docs are usually ahead of released versions.

### Version

v1.23.6+k0s.2

### Platform

```shell
LSB Version:    n/a
Distributor ID: Arch
Description:    Arch Linux
Release:        rolling
Codename:       n/a
```

### What happened?

Running `k0s controller --single` runs okay but the `kube-apiserver` keeps emitting warning messages like this:

`"{\"level\":\"warn\",\"ts\":\"2022-06-09T02:43:00.231+0800\",\"logger\":\"etcd-client\",\"caller\":\"v3/retry_interceptor.go:62\",\"msg\":\"retrying of unary invoker failed\",\"target\":\"etcd-endpoints://0xc00036b500/#initially=[unix:///run/k0s/kine/kine.sock:2379]\",\"attempt\":0,\"error\":\"rpc error: code = Unknown desc = no such table: dbstat\"}"`

It doesn't crash the cluster or anything but it makes the logs unclean.

### Steps to reproduce

1. Configure `.spec.storage.type` to `kine`
2. Run k0s controller --single

### Expected behavior

`kube-apiserver` doesn't emit warning

### Actual behavior

`kube-apiserver` keeps emitting warning messages like this:

`"{\"level\":\"warn\",\"ts\":\"2022-06-09T02:43:00.231+0800\",\"logger\":\"etcd-client\",\"caller\":\"v3/retry_interceptor.go:62\",\"msg\":\"retrying of unary invoker failed\",\"target\":\"etcd-endpoints://0xc00036b500/#initially=[unix:///run/k0s/kine/kine.sock:2379]\",\"attempt\":0,\"error\":\"rpc error: code = Unknown desc = no such table: dbstat\"}"

**Comment by twz123** [comment]
Release 1.23 backport: #1822

**Comment by twz123** [comment]
Release 1.22 backport: #1824, release 1.21 backport: #1825.
