### ISSUE TITLE
Use Rig as SSH connection layer

### ISSUE THREAD

**Issue by jnummelin** [k0sproject/k0s#1830]
Currently we've got some duplicated code in both `FootlooseSuite` and `VMSuite` for SSH connection handling. Maybe we could/should use https://github.com/k0sproject/rig/ as the SSH backbone.

**Comment by twz123** [comment]
Rig could also fit very well directly into bootloose. There's e.g. `Cluster.SSH(...)` that shells out to `ssh`. Could be replaced by a rig connection.
