### ISSUE TITLE
panic on windows (version string "v" doesn't match expected regular expression: "^v(\d+\.\d+\.\d+)"

### ISSUE THREAD

**Issue by machado2** [k0sproject/k0s#1922]
### Before creating an issue, make sure you've checked the following:

- [X] You are running the latest released version of k0s
- [X] Make sure you've searched for existing issues, both open and closed
- [X] Make sure you've searched for PRs too, a fix might've been merged already
- [X] You're looking at docs for the released version, "main" branch docs are usually ahead of released versions.

### Version

1.24.2

### Platform

```shell
windows server 2019
```

### What happened?

When I call k0s.exe, no matter the arguments I get this error:

k0s worker --cri-socket=docker:tcp://127.0.0.1:2375 --cidr-range=10.0.0.10/24 --cluster-dns=1.2.3.4 --api-server=http://batata asgsdfgsde
panic: version string "v" doesn't match expected regular expression: "^v(\d+\.\d+\.\d+)"

goroutine 1 [running]:
k8s.io/component-base/metrics.parseVersion({{0x3c03890, 0x0}, {0x3c03891, 0x0}, {0x3c038ae, 0x1}, {0x3c03fd0, 0xd}, {0x0, 0x0}, ...})
        /run/k0s-build/go/mod/k8s.io/component-base@v0.24.2/metrics/version_parser.go:47 +0x274
k8s.io/component-base/metrics.newKubeRegistry({{0x3c03890, 0x0}, {0x3c03891, 0x0}, {0x3c038ae, 0x1}, {0x3c03fd0, 0xd}, {0x0, 0x0}, ...})
        /run/k0s-build/go/mod/k8s.io/component-base@v0.24.2/metrics/registry.go:320 +0x118
k8s.io/component-base/metrics.NewKubeRegistry()
        /run/k0s-build/go/mod/k8s.io/component-base@v0.24.2/metrics/registry.go:335 +0x78
k8s.io/component-base/metrics/legacyregistry.init()
        /run/k0s-build/go/mod/k8s.io/component-base@v0.24.2/metrics/legacyregistry/registry.go:29 +0x1d

### Steps to reproduce

1. download the amd64.exe and run it on windows
2.
3.

### Expected behavior

It should work

### Actual behavior

It panics and abort

**Comment by soider** [comment]
@machado2 hello! this is going to be fixed with next minor release, the build pipeline is corrected and provides nonpanicking windows binaries

**Comment by 4x0v7** [comment]
This is still happening in `v1.24.3`. `v1.23.9` seems ok:

```powershell
C:\Users\user\Downloads> .\k0s-v1.23.9+k0s.0-amd64.exe version
v1.23.9+k0s.0
C:\Users\user\Downloads> .\k0s-v1.24.3+k0s.0-amd64.exe version
panic: version string "v" doesn't match expected regular expression: "^v(\d+\.\d+\.\d+)"

goroutine 1 [running]:
k8s.io/component-base/metrics.parseVersion ....
```
