### ISSUE TITLE
K0S installation fails with the multi-Arch docker images 

### ISSUE THREAD

**Issue by odidev** [k0sproject/k0s#1936]
### Before creating an issue, make sure you've checked the following:

- [X] You are running the latest released version of k0s
- [X] Make sure you've searched for existing issues, both open and closed
- [X] Make sure you've searched for PRs too, a fix might've been merged already
- [X] You're looking at docs for the released version, "main" branch docs are usually ahead of released versions.

### Version

v1.24.2-k0s.0

### Platform

```shell
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.4 LTS
Release:        20.04
Codename:       focal
```

### What happened?

I am working on installing K0s using docker images on the Linux/ARM64 platform, as linked here:  <https://docs.k0sproject.io/v1.24.2+k0s.0/k0s-in-docker/>. 

Docker run fails on both AMD64 and ARM64 with logs as below: 
~~~ 
$ sudo docker run -it --name k0s_destroy --hostname k0s --privileged -v /var/lib/k0s -p 6443:6443 docker.io/k0sproject/k0s:v1.24.2-k0s.0 
/entrypoint.sh: line 14: iptables-save: not found 
/entrypoint.sh: line 22: iptables-restore: not found 
/entrypoint.sh: exec: line 34: k0s: Permission denied 
~~~ 

However, k0s successfully gets installed on the AMD64 platform while using single platform (Linux/AMD64) docker images. 

I can see in the PR merged here <https://github.com/k0sproject/k0s/pull/1442/files>, that the iptables has been removed from the dependencies. This might be the possible reason for failure. 

May I know, is it done intentionally? If so, can you please guide me with the updated steps to install k0s via docker images? 

### Steps to reproduce

$ sudo docker run -it --name k0s --hostname k0s --privileged -v /var/lib/k0s -p 6443:6443 docker.io/k0sproject/k0s:v1.24.2-k0s.0 

### Expected behavior

k0s docker container should run.

### Actual behavior

k0s docker container fails to run.

**Comment by twz123** [comment]
I think this is kind of a chicken-and-egg problem. K0s itself contains those binaries, but they are not installed globally, but into k0s's data directory:

```
# ls -1  /var/lib/k0s/bin/
containerd
containerd-shim
containerd-shim-runc-v1
containerd-shim-runc-v2
ip6tables
ip6tables-restore
ip6tables-save
iptables-restore
iptables-save
kine
kube-apiserver
kube-controller-manager
kube-scheduler
kubelet
runc
xtables-legacy-multi
```

This probably needs to be addressed in the Dockerfile.

xref #1555

**Comment by odidev** [comment]
@makhov , Thank you for this PR. May I know the ETA for the official image release to DockerHub?

**Comment by makhov** [comment]
@odidev Yeah, I'm trying to figure out the best way to fix the images. We might have done that at the beginning of this week.

**Comment by makhov** [comment]
@odidev I re-pushed images both to the Docker Hub and Github Container Registry. Sorry for the delay.

**Comment by odidev** [comment]
Thank you for the release, but I am again getting the same issues while creating the k0s docker container:



~~~

$ sudo docker run -d --name k0s --hostname k0s --cgroupns=host -v /sys/fs/cgroup:/sys/fs/cgroup:rw --privileged -v /var/lib/k0s -p 6443:6443 docker.io/k0sproject/k0s:v1.24.2-k0s.0
c08e5844d988746936a1927a30327f0e89447cdb4e0435832dc9254745acf06f


$ sudo docker logs k0s
/entrypoint.sh: line 14: iptables-save: not found
/entrypoint.sh: line 22: iptables-restore: not found
/entrypoint.sh: exec: line 34: k0s: Permission denied

**Comment by makhov** [comment]
Have you pulled the new version of the image?

**Comment by odidev** [comment]
Yes, I picked the version "[v1.24.3-k0s.0](https://hub.docker.com/layers/k0s/k0sproject/k0s/v1.24.3-k0s.0/images/sha256-856556778dbb2938986de2893458f84d8508beaddf7835961f1dc0ad962be1c2?context=explore)". It is pushed 16 hours ago.

**Comment by makhov** [comment]
Well, now I see what happened. The release branch was created before the fix was merged and also the fix wasn't backported. 
I have re-pushed these images manually, pls run `docker pull k0sproject/k0s:v1.24.3-k0s.0`. 

Sorry for the inconvenience.

**Comment by odidev** [comment]
Thank you @makhov
