### ISSUE TITLE
no kind "EphemeralContainers" is registered for version "v1" in scheme

### ISSUE THREAD

**Issue by ramkicse** [k0sproject/k0s#1938]
### Before creating an issue, make sure you've checked the following:

- [X] You are running the latest released version of k0s
- [X] Make sure you've searched for existing issues, both open and closed
- [X] Make sure you've searched for PRs too, a fix might've been merged already
- [X] You're looking at docs for the released version, "main" branch docs are usually ahead of released versions.

### Version

v1.24.2+k0s

### Platform

```shell
Ubuntu 20.04.3 LTS
```

### What happened?

when i run 
 kubectl debug -it ephemeral-demo --image=busybox:1.28 --target=ephemeral-demo
i got following error
error: error updating ephemeral containers: EphemeralContainers in version "v1" cannot be handled as a Pod: no kind "EphemeralContainers" is registered for version "v1" in scheme "pkg/api/legacyscheme/scheme.go:30"

how to enable EphemeralContainers?

### Steps to reproduce

1.  kubectl run ephemeral-demo --image=k8s.gcr.io/pause:3.1 --restart=Never
2.  kubectl debug -it ephemeral-demo --image=busybox:1.28 --target=ephemeral-demo
3.

### Expected behavior

start EphemeralContainers  for debug purpose

### Actual behavior

looks like EphemeralContainers  feature gate is not enabled, even though k8s documents says its enabled 1.23 and above versions

### Screenshots and logs

<img width="855" alt="image" src="https://user-images.githubusercontent.com/1916923/180043405-d86e6810-fc38-4cbf-b590-06378d2bea5c.png">

**Comment by soider** [comment]
@ramkicse What is the kubectl version? I tried with the embedded kubectl subcomand and it seems to work.

```
➜ [REMOTE] ~ sudo ./k0s kc run ephemeral-demo --image=k8s.gcr.io/pause:3.1 --restart=Never
pod/ephemeral-demo created
➜ [REMOTE] ~ sudo ./k0s kc get pods
NAME             READY   STATUS              RESTARTS   AGE
ephemeral-demo   0/1     ContainerCreating   0          2s
➜ [REMOTE] ~ sudo ./k0s kc get pods
NAME             READY   STATUS    RESTARTS   AGE
ephemeral-demo   1/1     Running   0          4s
➜ [REMOTE] ~ sudo ./k0s kc debug -it ephemeral-demo --image=busybox:1.28 --target=ephemeral-demo
Targeting container "ephemeral-demo". If you don't see processes from this container it may be because the container runtime doesn't support this feature.
Defaulting debug container name to debugger-cbwkz.
If you don't see a command prompt, try pressing enter.
/ #
```

**Comment by ramkicse** [comment]
@soider thanks for quick update.
sorry its my mistake i was use kubectl v1.21, after upgrade cluster i forgot to upgrade my kubectl.
Now its working fine with kubectl v1.24
Thanks
