### ISSUE TITLE
K0s does not recover if embedded binaries are written only partially to a disk

### ISSUE THREAD

**Issue by jakolehm** [k0sproject/k0s#1989]
### Before creating an issue, make sure you've checked the following:

- [X] You are running the latest released version of k0s
- [X] Make sure you've searched for existing issues, both open and closed
- [X] Make sure you've searched for PRs too, a fix might've been merged already
- [X] You're looking at docs for the released version, "main" branch docs are usually ahead of released versions.

### Version

v1.23.8+k0s.0

### Platform

```shell
Distributor ID:	Debian
Description:	Debian GNU/Linux 11 (bullseye)
Release:	11
Codename:	bullseye
```

### What happened?

k0s wrote empty (or partial) binary files to disk which blocks k0s from starting properly (if for example kubelet binary is broken). Restart does not help because these broken binaries do have correct timestamp. Only way to recover is manual removal of broken binaries and then k0s restart.

### Steps to reproduce

1.
2.
3.

**Comment by jakolehm** [comment]
Forgot to mention that partial (broken) write can happen if k0s gets killed while writing those files.

**Comment by ncopa** [comment]
May also happen if disk is full.

**Comment by jnummelin** [comment]
Maybe we can store also the expected file size (on disk) into the generated offsets file. That way we can check if the embedded bins are on expected size and overwrite if needed.
