### ISSUE TITLE
panic on windows (version string "v" doesn't match expected regular expression: "^v(\d+\.\d+\.\d+)

### ISSUE THREAD

**Issue by 4x0v7** [k0sproject/k0s#2000]
### Before creating an issue, make sure you've checked the following:

- [X] You are running the latest released version of k0s
- [X] Make sure you've searched for existing issues, both open and closed
- [X] Make sure you've searched for PRs too, a fix might've been merged already
- [X] You're looking at docs for the released version, "main" branch docs are usually ahead of released versions.

### Version

panic: version string "v" doesn't match expected regular expression: "^v(\d+\.\d+\.\d+)"

### Platform

```shell
Windows 10
```

### Steps to reproduce

Run the below:

```sh
k0s-v1.24.3+k0s.0-amd64.exe version
```

### Expected behavior

Version number is printed

### Actual behavior

```sh
panic: version string "v" doesn't match expected regular expression: "^v(\d+\.\d+\.\d+)"

goroutine 1 [running]:
k8s.io/component-base/metrics.parseVersion({{0x30967d0, 0x0}, {0x30967d1, 0x0}, {0x30967ee, 0x1}, {0x3096f10, 0xd}, {0x0, 0x0}, ...})
        /run/k0s-build/go/mod/k8s.io/component-base@v0.24.3/metrics/version_parser.go:47 +0x274
k8s.io/component-base/metrics.newKubeRegistry({{0x30967d0, 0x0}, {0x30967d1, 0x0}, {0x30967ee, 0x1}, {0x3096f10, 0xd}, {0x0, 0x0}, ...})
        /run/k0s-build/go/mod/k8s.io/component-base@v0.24.3/metrics/registry.go:320 +0x118
k8s.io/component-base/metrics.NewKubeRegistry()
        /run/k0s-build/go/mod/k8s.io/component-base@v0.24.3/metrics/registry.go:335 +0x78
k8s.io/component-base/metrics/legacyregistry.init()
        /run/k0s-build/go/mod/k8s.io/component-base@v0.24.3/metrics/legacyregistry/registry.go:29 +0x1d
```

### Additional context

Seems to be a dupe of #1922

**Comment by jnummelin** [comment]
This should be fixed on 1.24.4+k0s.0 released last week.
