### ISSUE TITLE
Cluster Deployment using Hostnames with Capitial Letters Breaks during Konnectivity Service Installation Stage

### ISSUE THREAD

**Issue by Renegade-Master** [k0sproject/k0s#2011]
### Before creating an issue, make sure you've checked the following:

- [X] You are running the latest released version of k0s
- [X] Make sure you've searched for existing issues, both open and closed
- [X] Make sure you've searched for PRs too, a fix might've been merged already
- [X] You're looking at docs for the released version, "main" branch docs are usually ahead of released versions.

### Version

1.24.3+k0s.0

### Platform

```shell
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.1 LTS
Release:        22.04
Codename:       jammy
Architecture:   x86_64
Hostname:       renegade-VB <-- IMPORTANT

---

Distributor ID: Ubuntu
Description:    Ubuntu 22.04.1 LTS
Release:        22.04
Codename:       jammy
Architecture:   aarch64
Hostname:       renegade-desktop
```

### What happened?

When attempting to install a K0s Cluster using Hosts with capital letters in their Hostnames, installation will succeed, and pods will be schedulable. However, it is not possible to retrieve logs from pods, nor to exec into them, nor is it possible to port-forward any services.

### Steps to reproduce

1. Create a Multi-Node Cluster with at least one Host using capital letters in their Hostname.
2. Wait for the installation to fully apply.
3. Attempt to exec into a pod, or get the logs from a pod, or to port-forward a Service.

### Expected behavior

A Multi-Node Cluster should be capable of integrating Hosts without the requirement that their Hostname is lowercase.

### Actual behavior

When attempting any of the aforementioned three activities (retrieve logs from pods, exec into them, port-forward any services), they are all met with the same error:
```shell
/var/run/k0s/konnectivity-server/konnectivity-server.sock: connect: no such file or directory
``` 

And true enough, the `/var/run/k0s/konnectivity-server/` does exist:
```shell
$ ls -lAuhF /var/run/k0s/
total 36K
drwx--x--x 5 root                root  100 Aug  8 18:33 containerd/
-rw-r--r-- 1 root                root    5 Aug  8 18:33 containerd.pid
srw-rw---- 1 root                root    0 Aug  8 18:33 containerd.sock=
srw-rw---- 1 root                root    0 Aug  8 18:33 containerd.sock.ttrpc=
-rw-r--r-- 1 root                root    5 Aug  8 18:33 etcd.pid
-rw-r--r-- 1 root                root    5 Aug  8 18:33 k0s-control-api.pid
-rwxr-xr-x 1 root                root 2.4K Aug  8 18:33 k0s.yaml*
-rw-r--r-- 1 root                root    5 Aug  8 18:33 konnectivity.pid
drwxr-xr-x 2 konnectivity-server root   60 Aug  8 18:33 konnectivity-server/
-rw-r--r-- 1 root                root    5 Aug  8 18:33 kube-apiserver.pid
-rw-r--r-- 1 root                root    5 Aug  8 18:33 kube-controller-manager.pid
-rw-r--r-- 1 root                root    5 Aug  8 18:33 kubelet.pid
-rw-r--r-- 1 root                root    5 Aug  8 18:33 kube-scheduler.pid
srwxr-xr-x 1 root                root    0 Aug  8 18:33 status.sock=
```

But there is nothing in the `/var/run/k0s/konnectivity-server/` folder itself:
```shell
$ ls -lAuhF /var/run/k0s/konnectivity-server/
total 0
```

### Additional context

I did use K0sctl v0.13.0 to deploy the Multi-Node Cluster.

Seems to be related to the following issues:
- #1352 
- #1123 

This StackOverflow post actually convinced me to attempt changing my Hostname, and it worked after reinstalling the Cluster:
- [StackOverflow Post](https://stackoverflow.com/a/72095755/10884550)

**Comment by jnummelin** [comment]
ok, this was bit of a surprise.

This seems to boil down to the way we setup HA for konnectivity. Essentially all controllers create their own leases which we periodically count to be able to configure the konnectivity-agents properly. The lease names are set as `k0s-ctrl-<hostname>` which obviously fails when creating the `Lease` object:
```
error initially creating leader election record: Lease.coordination.k8s.io "k0s-ctrl-k0s-CTRL" is invalid: metadata.name: Invalid value: "k0s-ctrl-k0s-CTRL": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters...
```

🤦 

We need to figure out a way around this while keeping backwards compatibility. I.e. we cannot just change the naming "scheme" as that would lead to left-over leases which would screw up the konnectivity HA setup.

**Comment by jnummelin** [comment]
If I boot worker with capital letters in the hostname, it’ll show up as lowercase in the node object itself:
´´´
root@k0s-WRKR:~# hostname
k0s-WRKR
´´´
on the API:
root@k0s-CTRL:~# k0s kc get node --show-labels
NAME       STATUS   ROLES    AGE     VERSION       LABELS
k0s-wrkr   Ready    <none>   3m44s   v1.24.3+k0s   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,kubernetes.io/arch=amd64,kubernetes.io/hostname=k0s-wrkr,kubernetes.io/os=linux
so even the label gets written as lowercase
So for “symmetry” I think we could do the same for controller leases

**Comment by Renegade-Master** [comment]
> If I boot worker with capital letters in the hostname, it’ll show up as lowercase in the node object itself:
> 
> ```
> root@k0s-WRKR:~# hostname
> k0s-WRKR
> ```
> 
> on the API:
> 
> ```
> root@k0s-CTRL:~# k0s kc get node --show-labels
> NAME       STATUS   ROLES    AGE     VERSION       LABELS
> k0s-wrkr   Ready    <none>   3m44s   v1.24.3+k0s   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,kubernetes.io/arch=amd64,kubernetes.io/hostname=k0s-wrkr,kubernetes.io/os=linux
> ```
> 
> so even the label gets written as lowercase. So for “symmetry” I think we could do the same for controller leases

Yes, I noticed this as well, which is why I didn't think this was actually my issue. If you query the nodes, the labels are all lowercase and everything appears fine. It was quite _interesting_ to discover that this was actually the cause.

Thank you for investigating!

**Comment by jnummelin** [comment]
#2042 makes these bits use the same Kubernetes utils which kubelet uses for the object name derived from hostname so we get full "symmetry" for this once it lands.
