### ISSUE TITLE
Helm permissions management for SQL storage backend, are k0s affected?

### ISSUE THREAD

**Issue by m2acgi** [k0sproject/k0s#2022]
### Is your feature request related to a problem? Please describe.

According to helm documentation, when using the SQL storage backend, Kubernetes' roles can't be used to determine whether or not an user can access a given resource. Are k0s single node affected?

> https://helm.sh/docs/topics/permissions_sql_storage_backend/

**Comment by jnummelin** [comment]
No, k0s single node is NOT affected by this. Unless you specifically instruct your Helm client to talk to the backend database (which in k0s single node case by default is node-local SQLite)

**Comment by m2acgi** [comment]
Thanks a lot.
