### ISSUE TITLE
Upgrade k0s cluster

### ISSUE THREAD

**Issue by jnummelin** [k0sproject/k0s#203]
We need a controlled way to upgrade the cluster version.

**Comment by tinyzimmer** [comment]
I have a question on this topic in regards to the potential for usage in air-gapped environments. Is it in the scope of the project to provide a means for creating and applying patches (e.g. a new `k0s` binary and/or updated docker images) to existing environments?

Obviously in a situation like this you'd need to be able to disable a flow like above also.

**Comment by caruccio** [comment]
In environments where nodes have dedicated roles (like ingress-only nodes), the upgrade process must be aware not to stop all nodes at the same time. Maybe a configurable predicate should be available.

**Comment by jnummelin** [comment]
@caruccio yeah, some selector and rate (e.g. 10%) needs to be in place for controlled upgrades.

**Comment by mviitane** [comment]
Cluster upgrade delivered in k0s 0.11.
