### ISSUE TITLE
Should the NF_CONNTRACK kernel config be part of the pre-flight checks for k0s?

### ISSUE THREAD

**Issue by twz123** [k0sproject/k0s#2069]
There's [some evidence](https://github.com/k0sproject/k0s/issues/1946#issuecomment-1193331251) that without it, workers won't work. K0s already [includes it][sysinfo] in `k0s sysinfo` and also [tries to load nf_conntrack][modprobe] proactively.

Looking at [this][proxy] kube-proxy code, it seems that kube-proxy will error out anyways if nf_conntrack is unavailable. (Note that `s.Conntracker` is never `nil` for Linux.)

[modprobe]: https://github.com/k0sproject/k0s/blob/v1.24.3+k0s.0/pkg/component/worker/kernelsetup_linux.go#L69-L71
[sysinfo]: https://github.com/k0sproject/k0s/blob/v1.24.3%2Bk0s.0/internal/pkg/sysinfo/host_linux.go#L124
[proxy]: https://github.com/kubernetes/kubernetes/blob/v1.24.4/cmd/kube-proxy/app/server.go#L692-L731

**Comment by juanluisvaladas** [comment]
Kube-proxy, cilium and openvSwitch require nf_conntrack.

I don't know any implementation of kube-proxy other than kube-proxy itself or cilium that isn't based on openvSwitch so I think this is a sane thing to do.
