### ISSUE TITLE
High CPU usage kube-apiserver with virtual IP cluster

### ISSUE THREAD

**Issue by pagalba-com** [k0sproject/k0s#2108]
### Before creating an issue, make sure you've checked the following:

- [X] You are running the latest released version of k0s
- [X] Make sure you've searched for existing issues, both open and closed
- [X] Make sure you've searched for PRs too, a fix might've been merged already
- [X] You're looking at docs for the released version, "main" branch docs are usually ahead of released versions.

### Version

v1.24.3+k0s.0

### Sysinfo

<details><summary>`k0s sysinfo`</summary>

```
Machine ID: "3b66d767fae20da9e25b0a1cda09b1aa76d79033f5a5af552ac7f3e8d3dc6bf7" (from machine) (pass)
Total memory: 125.7 GiB (pass)
Disk space available for /var/lib/k0s: 16.1 GiB (pass)
Operating system: Linux (pass)
  Linux kernel release: 5.4.0-124-generic (pass)
  Max. file descriptors per process: current: 1024 / max: 1048576 (warning: < 65536)
  Executable in path: modprobe: /usr/sbin/modprobe (pass)
  /proc file system: mounted (0x9fa0) (pass)
  Control Groups: version 1 (pass)
    cgroup controller "cpu": available (pass)
    cgroup controller "cpuacct": available (pass)
    cgroup controller "cpuset": available (pass)
    cgroup controller "memory": available (pass)
    cgroup controller "devices": available (pass)
    cgroup controller "freezer": available (pass)
    cgroup controller "pids": available (pass)
    cgroup controller "hugetlb": available (pass)
    cgroup controller "blkio": available (pass)
  CONFIG_CGROUPS: Control Group support: built-in (pass)
    CONFIG_CGROUP_FREEZER: Freezer cgroup subsystem: built-in (pass)
    CONFIG_CGROUP_PIDS: PIDs cgroup subsystem: built-in (pass)
    CONFIG_CGROUP_DEVICE: Device controller for cgroups: built-in (pass)
    CONFIG_CPUSETS: Cpuset support: built-in (pass)
    CONFIG_CGROUP_CPUACCT: Simple CPU accounting cgroup subsystem: built-in (pass)
    CONFIG_MEMCG: Memory Resource Controller for Control Groups: built-in (pass)
    CONFIG_CGROUP_HUGETLB: HugeTLB Resource Controller for Control Groups: built-in (pass)
    CONFIG_CGROUP_SCHED: Group CPU scheduler: built-in (pass)
      CONFIG_FAIR_GROUP_SCHED: Group scheduling for SCHED_OTHER: built-in (pass)
        CONFIG_CFS_BANDWIDTH: CPU bandwidth provisioning for FAIR_GROUP_SCHED: built-in (pass)
    CONFIG_BLK_CGROUP: Block IO controller: built-in (pass)
  CONFIG_NAMESPACES: Namespaces support: built-in (pass)
    CONFIG_UTS_NS: UTS namespace: built-in (pass)
    CONFIG_IPC_NS: IPC namespace: built-in (pass)
    CONFIG_PID_NS: PID namespace: built-in (pass)
    CONFIG_NET_NS: Network namespace: built-in (pass)
  CONFIG_NET: Networking support: built-in (pass)
    CONFIG_INET: TCP/IP networking: built-in (pass)
      CONFIG_IPV6: The IPv6 protocol: built-in (pass)
    CONFIG_NETFILTER: Network packet filtering framework (Netfilter): built-in (pass)
      CONFIG_NETFILTER_ADVANCED: Advanced netfilter configuration: built-in (pass)
      CONFIG_NETFILTER_XTABLES: Netfilter Xtables support: module (pass)
        CONFIG_NETFILTER_XT_TARGET_REDIRECT: REDIRECT target support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_COMMENT: "comment" match support: module (pass)
        CONFIG_NETFILTER_XT_MARK: nfmark target and match support: module (pass)
        CONFIG_NETFILTER_XT_SET: set target and match support: module (pass)
        CONFIG_NETFILTER_XT_TARGET_MASQUERADE: MASQUERADE target support: module (pass)
        CONFIG_NETFILTER_XT_NAT: "SNAT and DNAT" targets support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_ADDRTYPE: "addrtype" address type match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_CONNTRACK: "conntrack" connection tracking match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_MULTIPORT: "multiport" Multiple port match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_RECENT: "recent" match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_STATISTIC: "statistic" match support: module (pass)
      CONFIG_NETFILTER_NETLINK: module (pass)
      CONFIG_NF_CONNTRACK: Netfilter connection tracking support: module (pass)
      CONFIG_NF_NAT: module (pass)
      CONFIG_IP_SET: IP set support: module (pass)
        CONFIG_IP_SET_HASH_IP: hash:ip set support: module (pass)
        CONFIG_IP_SET_HASH_NET: hash:net set support: module (pass)
      CONFIG_IP_VS: IP virtual server support: module (pass)
        CONFIG_IP_VS_NFCT: Netfilter connection tracking: built-in (pass)
      CONFIG_NF_CONNTRACK_IPV4: IPv4 connetion tracking support (required for NAT): unknown (warning)
      CONFIG_NF_REJECT_IPV4: IPv4 packet rejection: module (pass)
      CONFIG_NF_NAT_IPV4: IPv4 NAT: unknown (warning)
      CONFIG_IP_NF_IPTABLES: IP tables support: module (pass)
        CONFIG_IP_NF_FILTER: Packet filtering: module (pass)
          CONFIG_IP_NF_TARGET_REJECT: REJECT target support: module (pass)
        CONFIG_IP_NF_NAT: iptables NAT support: module (pass)
        CONFIG_IP_NF_MANGLE: Packet mangling: module (pass)
      CONFIG_NF_DEFRAG_IPV4: module (pass)
      CONFIG_NF_CONNTRACK_IPV6: IPv6 connetion tracking support (required for NAT): unknown (warning)
      CONFIG_NF_NAT_IPV6: IPv6 NAT: unknown (warning)
      CONFIG_IP6_NF_IPTABLES: IP6 tables support: module (pass)
        CONFIG_IP6_NF_FILTER: Packet filtering: module (pass)
        CONFIG_IP6_NF_MANGLE: Packet mangling: module (pass)
        CONFIG_IP6_NF_NAT: ip6tables NAT support: module (pass)
      CONFIG_NF_DEFRAG_IPV6: module (pass)
    CONFIG_BRIDGE: 802.1d Ethernet Bridging: module (pass)
      CONFIG_LLC: module (pass)
      CONFIG_STP: module (pass)
  CONFIG_EXT4_FS: The Extended 4 (ext4) filesystem: built-in (pass)
  CONFIG_PROC_FS: /proc file system support: built-in (pass)
```
</details>

### What happened?

virtual IP is assigned and configured for a controlplane nodes, which lead to excessive CPU usage on kube-apiserver, etcd and konnectivity-server.

### Steps to reproduce

1. create VIP configuration on cluster, so on of nodes has asigned virtual ip in addition to static ip.
2. create/run k0s multinode cluster
3. after some time CPU usage goes high and never down.

### Expected behavior

only IPs specified in deployment should be used fo communication, skipping additional ips assigned on same or rest interfaces.

### Actual behavior

I was able to trace down that high CPU issue is virtual IP related. There a logs from konnectivity-agent
below.

### Screenshots and logs

2022-08-26T01:59:20.860942304+03:00 stderr F I0825 22:59:20.860898       1 client.go:749] "Exiting proxyToRemote" connectionID=18544
2022-08-26T01:59:20.860945189+03:00 stderr F I0825 22:59:20.860910       1 client.go:707] "Exiting remoteToProxy" connectionID=18544
2022-08-26T01:59:20.861381052+03:00 stderr F I0825 22:59:20.861338       1 client.go:637] "received CLOSE_REQ" connectionID=18544
2022-08-26T01:59:20.861388036+03:00 stderr F I0825 22:59:20.861353       1 client.go:644] "Failed to find connection context for close" connectionID=18544
2022-08-26T01:59:21.586130245+03:00 stderr F I0825 22:59:21.586024       1 client.go:300] "Connect to" server="3b66d767fae20da9e25b0a1cda09b1aa76d79033f5a5af552ac7f3e8d3dc6bf7"
2022-08-26T01:59:21.586156855+03:00 stderr F I0825 22:59:21.586046       1 clientset.go:229] "closing connection to duplicate server" serverID="3b66d767fae20da9e25b0a1cda09b1aa76d79033f5a5af552ac7f3e8d3dc6bf7"
2022-08-26T01:59:21.586160212+03:00 stderr F I0825 22:59:21.586083       1 clientset.go:192] "duplicate server" serverID="3b66d767fae20da9e25b0a1cda09b1aa76d79033f5a5af552ac7f3e8d3dc6bf7" serverCount=3 clientsCount=1

and same repeats.

**Comment by pagalba-com** [comment]
for testing purposes, should be enough to assign two IPs from same IP pool on network interface. Example 10.0.0.2 and 10.0.0.20 on one node, and rest could be 10.0.0.3 and 10.0.0.4.

**Comment by jnummelin** [comment]
How did you configure the VIP to k0s, could you share the config?

**Comment by pagalba-com** [comment]
cluster was created with k0sctl tool. Config is following:

apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s-cluster
spec:
  hosts:
  - ssh:
      address: 192.168.1.203
    role: controller+worker
    noTaints: true
    installFlags:
    - --debug
    uploadBinary: true
    privateInterface: br0
  - ssh:
      address: 192.168.1.204
    role: controller+worker
    noTaints: true
    installFlags:
    - --debug
    uploadBinary: true
    privateInterface: br0
  - ssh:
      address: 192.168.1.202
    role: controller+worker
    noTaints: true
    installFlags:
    - --debug
    uploadBinary: true
    privateInterface: br0
  k0s:
    version: v1.24.3+k0s.0
    dynamicConfig: false
    config:
      kind: Cluster
      metadata:
        name: k0s-cluster
      spec:
        api:
          externalAddress: 192.168.1.20
          sans:
          - 192.168.1.20


-- the last part was added to test if cluster is reachable via vip as 'externalAddress' but this does not deploy at all.

**Comment by jnummelin** [comment]
I believe  the cause for this is the same as in https://github.com/k0sproject/k0s/issues/2068
Check [this comment](https://github.com/k0sproject/k0s/issues/2068#issuecomment-1220548308) for explanation how the HA konnectivity works.

The way HA communication tunnels work in konnectivity requires the `externalAddress` to behave like a LB, the agents need to get unique connections through it to all controllers. (konnectivity-servers). In this case the agent seems to get into some sort of busy(ish) loop when it sees duplicate servers via the VIP. (the VIP is "assigned" to only one controller at a time, hence duplicate connections)

**Comment by jnummelin** [comment]
As in #2068 in this specific case when you have only controller+worker nodes within a "flat" network, you can actually use `--disable-components konnectivity-server` as an `installFlags` which will disable konnectivity completely.
