### ISSUE TITLE
Network Configuration on Intial Installation

### ISSUE THREAD

**Issue by Daxcor69** [k0sproject/k0s#2114]
### Is your feature request related to a problem? Please describe.

My baremetal machines have two network interfaces. One eth0, is public and the other is eth1 which is private.  My initial install went flawlessly.   I used k0sctl with a config file for all the hosts.  The installation choose to put the cluster on the public interface.  From a security perspective this is not ideal.  I read through all the docs and was not able to find an option to select the desired network.

### Describe the solution you would like

In the config file for k0sctl I could provide a CIDR for the host network.  In my case, the private network is on 10.0.1.0/24 on eth1.  I want the public interface on each host to be the default gateway for all out going traffic.  This way we are not funneling all the outbound traffic through a single host.

### Describe alternatives you've considered

I thought of disabling the public network during the install then re-enabling it after the fact.

### Additional context

Thank you for an awesome project.

**Comment by jnummelin** [comment]
not really sure what you mean by:
> was not able to find an option to select the desired network.

k0sctl has an option to tell which interface is the private one: https://github.com/k0sproject/k0sctl/#spechostsprivateinterface-string-optional-default-

That makes k0sctl to detect the private interfaces address and configures that for all purely cluster internal things such as for etcd clustering.

In k0s config yaml, there's also field [`spec.api.address`](https://docs.k0sproject.io/head/configuration/#specapi) which configures the API server which address it should "advertise" to the cluster. (essentially which address to push for the `kubernetes` svc endpoints)

**Comment by Daxcor69** [comment]
You are correct, I didn't see that configuration value. I had to do both the interface and the ip and then it worked as expected.  I am sorry for opening the issue.  RTFM strikes once again.

Brad
