### ISSUE TITLE
Pod network does not properly work on hosts with nftables backed firewalld

### ISSUE THREAD

**Issue by jnummelin** [k0sproject/k0s#2117]
### Before creating an issue, make sure you've checked the following:

- [X] You are running the latest released version of k0s
- [X] Make sure you've searched for existing issues, both open and closed
- [X] Make sure you've searched for PRs too, a fix might've been merged already
- [X] You're looking at docs for the released version, "main" branch docs are usually ahead of released versions.

### Platform

```shell
RHEL 8.4 with firewalld defaulting to nftables backend.
```

### Version

v1.24.2+k0s.0

### What happened?

Cluster setup works and everything gets up. But pod network (== non host network pods) does not get connections to external world.  Pod trying to connect to external world gets `no route to host`.

From k0s system pods this is seen e.g. on konnectivity-agent pods. This shows up as non working `kubectl logs, kubectl exec` etc. commands as konnectivity agent cannot get connections to controllers.

### Steps to reproduce

1. 
2.
3.

### Expected behavior

Everything work when needed ports are opened in firewalld config.

### Actual behavior

![image](https://user-images.githubusercontent.com/3205505/187158187-7162d1e2-b454-45d1-b101-531979cc1989.png)

Disabling firewalld completely does "fix" the issue but obviously that's not a good solution.

Forcing firewalld to use plain iptables as the backend fixes this:
`vi /etc/firewalld/firewalld.conf`change  `FirewallBackend=nftables` to `FirewallBackend=iptables` and `systemctl restart firewalld`

### Additional context

We need to figure out if we can make all needed components (kube-router, kube-proxy, ...) to play nice with nftables.

**Comment by makhov** [comment]
We [build](https://github.com/k0sproject/k0s/blob/main/embedded-bins/iptables/Dockerfile#L19) iptables with `--disable-nftables` flag. Can we use`iptables-nft`?  This may [solve](https://developers.redhat.com/blog/2020/08/18/iptables-the-two-variants-and-their-relationship-with-nftables#using_iptables_nft) the issue.

**Comment by jlnhnng** [comment]
Yes, as far as described in the linked docs, iptables-nft would do the job. nftables is the default backend of firewalld, so in case someone does not want to change it, it would be good to have some kind of switch.

**Comment by jnummelin** [comment]
> We [build](https://github.com/k0sproject/k0s/blob/main/embedded-bins/iptables/Dockerfile#L19) iptables with --disable-nftables flag. Can we useiptables-nft? This may [solve](https://developers.redhat.com/blog/2020/08/18/iptables-the-two-variants-and-their-relationship-with-nftables#using_iptables_nft) the issue.

IF we can do some fancy selection based on what the kernel supports, we need to also ensure that all other components (kube-proxy, kube-router, ...) do the same.

**Comment by jnummelin** [comment]
One idea from team internal discussion: What if we mount k0s embedded iptables (build with support for nftables) to both kube-proxy and kube-router?

**Comment by makhov** [comment]
I managed to [build](https://github.com/k0sproject/k0s/pull/2124/files#diff-629097ea7a33928290b5e593353b180111d3cc998dfaaff91fc51bcd24d2aa12) iptables-nft and run a couple of tests against it. It works perfectly, kube-router and kube-proxy detect the iptables version to use correctly:
```
bash-5.1# k0s kc exec -it -n kube-system kube-proxy-5kmfn -- iptables -V
iptables v1.8.7 (nf_tables)
bash-5.1# k0s kc exec -it -n kube-system kube-router-v5jwv -- iptables -V
Defaulted container "kube-router" out of: kube-router, install-cni-bins (init), install-cniconf (init)
iptables v1.8.7 (nf_tables)
```

**Comment by ncopa** [comment]
> I managed to [build](https://github.com/k0sproject/k0s/pull/2124/files#diff-629097ea7a33928290b5e593353b180111d3cc998dfaaff91fc51bcd24d2aa12) iptables-nft and run a couple of tests against it. It works perfectly, kube-router and kube-proxy detect the iptables version to use correctly:

will this work if firewalld is configured with legacy iptables backend?

**Comment by makhov** [comment]
> will this work if firewalld is configured with legacy iptables backend?

As much as kube-proxy and kube-router, I suppose, if we implement the same logic as in [iptables-wrapper](https://github.com/kubernetes-sigs/iptables-wrappers/blob/master/iptables-wrapper-installer.sh).
I'm working on it now.
