### ISSUE TITLE
Proper Kine health check missing

### ISSUE THREAD

**Issue by jnummelin** [k0sproject/k0s#2135]
We've seen some cases of kine/sqlite failing to startup properly. This shows up as kube-apiserver hitting into issues like:
```
Sep 08 06:39:34 lima-lens-vm k0s[1073]: time="2022-09-08 06:39:34" level=info msg="time=\"2022-09-08T06:39:34Z\" level=error msg=\"error while range on /registry/flowschemas/ /registry/flowschemas/: disk I/O error: no such file or directory\"" component=kine
```

While we do not yet know what is the root cause for this, we've identified that restarting kine does fix the issue.

Thus if we'd have a proper health check for kine, k0s could detect this early and restart kine. Currently kine _seems_ to run fine but kube-api will hit lot of issues as it cannot read/write anything to the DB. This results into k0s restarting kube-api for a while untill it gives up. Finally systemd will restart whole k0s but that currently takes like ~5 mins.

Maybe we could do some similar query as we see kube-api failing with as a health check?

xrefs:
https://github.com/k3s-io/kine/issues/135

**Comment by soider** [comment]
https://github.com/k3s-io/kine/blob/master/pkg/server/server.go#L24

there is some kine API related to the health, should check if it is usable for us.
