### ISSUE TITLE
[Docs] Properly document control node removal procedure

### ISSUE THREAD

**Issue by jnummelin** [k0sproject/k0s#2181]
At some point in history I recall we had some docs around this area. They seem to have been lost in some refactoring. 🤦 

We need to properly document the procedure how to safely remove/replace a controller node in case of a multinode controller setup.

In case one has say three nodes A,B and C, the procedure is something like:
- On C: `k0s stop`
- On A/B: `k0s etcd leave --peer-address <10.0.0.C>`
- On C: k0s reset
- In case of replacing a node: On D: `k0s install controller --join-token/token-file <token>`

**Comment by jpigree** [comment]
> At some point in history I recall we had some docs around this area. They seem to have been lost in some refactoring. facepalm
> 
> We need to properly document the procedure how to safely remove/replace a controller node in case of a multinode controller setup.
> 
> In case one has say three nodes A,B and C, the procedure is something like:
> 
>     * On C: `k0s stop`
> 
>     * On A/B: `k0s etcd leave --peer-address <10.0.0.C>`
> 
>     * On C: k0s reset
> 
>     * In case of replacing a node: On D: `k0s install controller --join-token/token-file <token>`

I was actually searching for this information and couldn't find it anywhere in the docs. Thank you. I successfully replaced a controller with this. Can I propose a PR? I noted the steps I followed:

```
# Legend:
#controller1, controller we keep
#controller2, controller we keep
#controller3, controller we want to replace

# Delete the node in Kubernetes
kubectl drain --ignore-daemonsets --delete-emptydir-data <controller3>
kubectl delete node <controller3>

# Delete the node in ETCD
ssh <user>@<controller1>
PEER_ADRESS=$(k0s etcd member-list | python -m json.tool | grep <controller3> | cut -d"\"" -f4)
k0s etcd leave --peer-address $PEER_ADRESS
k0s token create --role controller --expiry 1h > /tmp/token
exit

# Reset the node controller3
ssh <user>@<controller3>
k0s reset
reboot

# Reinstall controller
scp <user>@<controller1>:/tmp/token <user>@<controller3>:/tmp/token
ssh <user>@<controller3>
k0s install controller <options> --token-file "/tmp/token"
```

**Comment by jnummelin** [comment]
> Can I propose a PR?

By all means, PR would be very nice

**Comment by jpigree** [comment]
Sorry. I missed your comment. Just saw the "stale" notification though. I submitted a PR. Waiting for the CI validation.
