### ISSUE TITLE
Pod Metrics not working after upgrade to v1.24.4+k0s.0 due to missing labels (container, image)

### ISSUE THREAD

**Issue by 0SkillAllLuck** [k0sproject/k0s#2187]
### Before creating an issue, make sure you've checked the following:

- [X] You are running the latest released version of k0s
- [X] Make sure you've searched for existing issues, both open and closed
- [X] Make sure you've searched for PRs too, a fix might've been merged already
- [X] You're looking at docs for the released version, "main" branch docs are usually ahead of released versions.

### Platform

```shell
Linux 5.14.0-70.22.1.el9_0.x86_64 #1 SMP PREEMPT Tue Aug 9 19:45:51 UTC 2022 x86_64 GNU/Linux
NAME="Rocky Linux"
VERSION="9.0 (Blue Onyx)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="9.0"
PLATFORM_ID="platform:el9"
PRETTY_NAME="Rocky Linux 9.0 (Blue Onyx)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:9::baseos"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-9"
ROCKY_SUPPORT_PRODUCT_VERSION="9.0"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.0"
```

### Version

v1.25.1-rc.1+k0s.0

### Sysinfo

Machine ID: "4c939139a0de3facc5913773ecc37c71633c1b4b64d20a7b9b704f33b644b2cb" (from machine) (pass)
Total memory: 15.2 GiB (pass)
Disk space available for /var/lib/k0s: 214.0 GiB (pass)
Operating system: Linux (pass)
  Linux kernel release: 5.14.0-70.22.1.el9_0.x86_64 (pass)
  Max. file descriptors per process: current: 524288 / max: 524288 (pass)
  Executable in path: modprobe: /usr/sbin/modprobe (pass)
  /proc file system: mounted (0x9fa0) (pass)
  Control Groups: version 2 (pass)
    cgroup controller "cpu": available (pass)
    cgroup controller "cpuacct": available (via cpu in version 2) (pass)
    cgroup controller "cpuset": available (pass)
    cgroup controller "memory": available (pass)
    cgroup controller "devices": available (assumed) (pass)
    cgroup controller "freezer": available (assumed) (pass)
    cgroup controller "pids": available (pass)
    cgroup controller "hugetlb": available (pass)
    cgroup controller "blkio": available (via io in version 2) (pass)
  CONFIG_CGROUPS: Control Group support: built-in (pass)
    CONFIG_CGROUP_FREEZER: Freezer cgroup subsystem: built-in (pass)
    CONFIG_CGROUP_PIDS: PIDs cgroup subsystem: built-in (pass)
    CONFIG_CGROUP_DEVICE: Device controller for cgroups: built-in (pass)
    CONFIG_CPUSETS: Cpuset support: built-in (pass)
    CONFIG_CGROUP_CPUACCT: Simple CPU accounting cgroup subsystem: built-in (pass)
    CONFIG_MEMCG: Memory Resource Controller for Control Groups: built-in (pass)
    CONFIG_CGROUP_HUGETLB: HugeTLB Resource Controller for Control Groups: built-in (pass)
    CONFIG_CGROUP_SCHED: Group CPU scheduler: built-in (pass)
      CONFIG_FAIR_GROUP_SCHED: Group scheduling for SCHED_OTHER: built-in (pass)
        CONFIG_CFS_BANDWIDTH: CPU bandwidth provisioning for FAIR_GROUP_SCHED: built-in (pass)
    CONFIG_BLK_CGROUP: Block IO controller: built-in (pass)
  CONFIG_NAMESPACES: Namespaces support: built-in (pass)
    CONFIG_UTS_NS: UTS namespace: built-in (pass)
    CONFIG_IPC_NS: IPC namespace: built-in (pass)
    CONFIG_PID_NS: PID namespace: built-in (pass)
    CONFIG_NET_NS: Network namespace: built-in (pass)
  CONFIG_NET: Networking support: built-in (pass)
    CONFIG_INET: TCP/IP networking: built-in (pass)
      CONFIG_IPV6: The IPv6 protocol: built-in (pass)
    CONFIG_NETFILTER: Network packet filtering framework (Netfilter): built-in (pass)
      CONFIG_NETFILTER_ADVANCED: Advanced netfilter configuration: built-in (pass)
      CONFIG_NETFILTER_XTABLES: Netfilter Xtables support: built-in (pass)
        CONFIG_NETFILTER_XT_TARGET_REDIRECT: REDIRECT target support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_COMMENT: "comment" match support: module (pass)
        CONFIG_NETFILTER_XT_MARK: nfmark target and match support: module (pass)
        CONFIG_NETFILTER_XT_SET: set target and match support: module (pass)
        CONFIG_NETFILTER_XT_TARGET_MASQUERADE: MASQUERADE target support: module (pass)
        CONFIG_NETFILTER_XT_NAT: "SNAT and DNAT" targets support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_ADDRTYPE: "addrtype" address type match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_CONNTRACK: "conntrack" connection tracking match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_MULTIPORT: "multiport" Multiple port match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_RECENT: "recent" match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_STATISTIC: "statistic" match support: module (pass)
      CONFIG_NETFILTER_NETLINK: module (pass)
      CONFIG_NF_CONNTRACK: Netfilter connection tracking support: module (pass)
      CONFIG_NF_NAT: module (pass)
      CONFIG_IP_SET: IP set support: module (pass)
        CONFIG_IP_SET_HASH_IP: hash:ip set support: module (pass)
        CONFIG_IP_SET_HASH_NET: hash:net set support: module (pass)
      CONFIG_IP_VS: IP virtual server support: module (pass)
        CONFIG_IP_VS_NFCT: Netfilter connection tracking: built-in (pass)
      CONFIG_NF_CONNTRACK_IPV4: IPv4 connetion tracking support (required for NAT): unknown (warning)
      CONFIG_NF_REJECT_IPV4: IPv4 packet rejection: module (pass)
      CONFIG_NF_NAT_IPV4: IPv4 NAT: unknown (warning)
      CONFIG_IP_NF_IPTABLES: IP tables support: module (pass)
        CONFIG_IP_NF_FILTER: Packet filtering: module (pass)
          CONFIG_IP_NF_TARGET_REJECT: REJECT target support: module (pass)
        CONFIG_IP_NF_NAT: iptables NAT support: module (pass)
        CONFIG_IP_NF_MANGLE: Packet mangling: module (pass)
      CONFIG_NF_DEFRAG_IPV4: module (pass)
      CONFIG_NF_CONNTRACK_IPV6: IPv6 connetion tracking support (required for NAT): unknown (warning)
      CONFIG_NF_NAT_IPV6: IPv6 NAT: unknown (warning)
      CONFIG_IP6_NF_IPTABLES: IP6 tables support: module (pass)
        CONFIG_IP6_NF_FILTER: Packet filtering: module (pass)
        CONFIG_IP6_NF_MANGLE: Packet mangling: module (pass)
        CONFIG_IP6_NF_NAT: ip6tables NAT support: module (pass)
      CONFIG_NF_DEFRAG_IPV6: module (pass)
    CONFIG_BRIDGE: 802.1d Ethernet Bridging: module (pass)
      CONFIG_LLC: module (pass)
      CONFIG_STP: module (pass)
  CONFIG_EXT4_FS: The Extended 4 (ext4) filesystem: module (pass)
  CONFIG_PROC_FS: /proc file system support: built-in (pass)

### What happened?

After upgrading to v1.24.4+k0s.0 metrics in Grafana and Lens stopped working properly, the prometheus metrics are still being collected and are containing all data that is required but the container and image labels are missing from it.

### Steps to reproduce

1. Install k0s v1.24.4+k0s.0
2. Install metrics via Lens or kube-prometheus-stack.
3. Metrics will be missing in Lens or Grafana

### Expected behavior

Metrics in Lens and Grafana should show up.
Metrics coming from cadvisor should have the container and image labels.

### Actual behavior

Metrics in Lens and Grafana don't show up.
Metrics in prometheus are missing the container and pod labels which causes Dashboards and Lens to not show the metrics.

### Additional context

Upgrading to [v1.25.1-rc.1+k0s.0](https://github.com/k0sproject/k0s/releases/tag/v1.25.1-rc.1%2Bk0s.0) does not help

Downgrading to [v1.23.10+k0s.0](https://github.com/k0sproject/k0s/releases/tag/v1.23.10%2Bk0s.0) fixes the issue.

**Comment by jnummelin** [comment]
Are you using the bundled containerD as runtime or some custom CRI?

I believe this is some sort of regression in kubelet/cadvisor related to deprecating/removing the built in docker-shim, see https://github.com/kubernetes/kubernetes/issues/111077

**Comment by 0SkillAllLuck** [comment]
Using the bundled containerD. I tried using a custom CRI and also k3s to see if the same issue happens, it seems to only happen with the bundled containerD for me.

**Comment by jnummelin** [comment]
thanks for the info.

kubelet & the embedded cadvisor in it has been notorious to have many regressions and caveats in the past. We'll dig into this.

**Comment by 0SkillAllLuck** [comment]
If it helps I tried the following ways all of which seem to work:
- Using k3s with bundled containerD [v1.5.13-k3s2](https://github.com/k3s-io/containerd/releases/tag/v1.5.13-k3s2)
- Using rke2 with bundled containerD [v1.6.8-k3s1](https://github.com/k3s-io/containerd/releases/tag/v1.6.8-k3s1)

I'll retry with v1.25.2+k0s.0 quickly to see if it works with that.

**Comment by jnummelin** [comment]
I _think_ the workaround is to add `--kubelet-extra-args="--containerd=/run/k0s/containerd.sock"` to k0s worker flags

**Comment by jnummelin** [comment]
At least that worked in my quick test. I'm in the process of doing a real fix PR for this

**Comment by jnummelin** [comment]
With the above extra flag for kubelet I see this:
```
bash-5.1# k0s kc get --raw /api/v1/nodes/worker0/proxy/metrics/cadvisor| grep 'image="[^"]' | wc -l
504
bash-5.1# k0s kc get --raw /api/v1/nodes/worker0/proxy/metrics/cadvisor| grep 'container="[^"]' | wc -l
230
```

**Comment by 0SkillAllLuck** [comment]
Yeah latest v1.25.2+k0s.0 doesn't work. Adding those kubelet args fixes the issue
