### ISSUE TITLE
Can't get DualStack working.

### ISSUE THREAD

**Issue by OrvilleQ** [k0sproject/k0s#2220]
### Before creating an issue, make sure you've checked the following:

- [X] You are running the latest released version of k0s
- [X] Make sure you've searched for existing issues, both open and closed
- [X] Make sure you've searched for PRs too, a fix might've been merged already
- [X] You're looking at docs for the released version, "main" branch docs are usually ahead of released versions.

### Platform

```shell
NAME="Fedora Linux"
VERSION="36.20220906.3.2 (CoreOS)"
ID=fedora
VERSION_ID=36
VERSION_CODENAME=""
PLATFORM_ID="platform:f36"
PRETTY_NAME="Fedora CoreOS 36.20220906.3.2"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:36"
HOME_URL="https://getfedora.org/coreos/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora-coreos/"
SUPPORT_URL="https://github.com/coreos/fedora-coreos-tracker/"
BUG_REPORT_URL="https://github.com/coreos/fedora-coreos-tracker/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=36
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=36
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="CoreOS"
VARIANT_ID=coreos
OSTREE_VERSION='36.20220906.3.2'
DEFAULT_HOSTNAME=localhost
```

### Version

v1.25.2+k0s.0

### Sysinfo

<details><summary>`k0s sysinfo`</summary>

```text
Machine ID: "3e2a83667f33454ad3307f534d62429fa8e3cd7a194ee624647e25406546b13e" (from machine) (pass)
Total memory: 7.8 GiB (pass)
Disk space available for /var/lib/k0s: 45.2 GiB (pass)
Operating system: Linux (pass)
  Linux kernel release: 5.19.6-200.fc36.x86_64 (pass)
  Max. file descriptors per process: current: 524288 / max: 524288 (pass)
  Executable in path: modprobe: /usr/sbin/modprobe (pass)
  /proc file system: mounted (0x9fa0) (pass)
  Control Groups: version 2 (pass)
    cgroup controller "cpu": available (pass)
    cgroup controller "cpuacct": available (via cpu in version 2) (pass)
    cgroup controller "cpuset": available (pass)
    cgroup controller "memory": available (pass)
    cgroup controller "devices": available (assumed) (pass)
    cgroup controller "freezer": available (assumed) (pass)
    cgroup controller "pids": available (pass)
    cgroup controller "hugetlb": available (pass)
    cgroup controller "blkio": available (via io in version 2) (pass)
  CONFIG_CGROUPS: Control Group support: built-in (pass)
    CONFIG_CGROUP_FREEZER: Freezer cgroup subsystem: built-in (pass)
    CONFIG_CGROUP_PIDS: PIDs cgroup subsystem: built-in (pass)
    CONFIG_CGROUP_DEVICE: Device controller for cgroups: built-in (pass)
    CONFIG_CPUSETS: Cpuset support: built-in (pass)
    CONFIG_CGROUP_CPUACCT: Simple CPU accounting cgroup subsystem: built-in (pass)
    CONFIG_MEMCG: Memory Resource Controller for Control Groups: built-in (pass)
    CONFIG_CGROUP_HUGETLB: HugeTLB Resource Controller for Control Groups: built-in (pass)
    CONFIG_CGROUP_SCHED: Group CPU scheduler: built-in (pass)
      CONFIG_FAIR_GROUP_SCHED: Group scheduling for SCHED_OTHER: built-in (pass)
        CONFIG_CFS_BANDWIDTH: CPU bandwidth provisioning for FAIR_GROUP_SCHED: built-in (pass)
    CONFIG_BLK_CGROUP: Block IO controller: built-in (pass)
  CONFIG_NAMESPACES: Namespaces support: built-in (pass)
    CONFIG_UTS_NS: UTS namespace: built-in (pass)
    CONFIG_IPC_NS: IPC namespace: built-in (pass)
    CONFIG_PID_NS: PID namespace: built-in (pass)
    CONFIG_NET_NS: Network namespace: built-in (pass)
  CONFIG_NET: Networking support: built-in (pass)
    CONFIG_INET: TCP/IP networking: built-in (pass)
      CONFIG_IPV6: The IPv6 protocol: built-in (pass)
    CONFIG_NETFILTER: Network packet filtering framework (Netfilter): built-in (pass)
      CONFIG_NETFILTER_ADVANCED: Advanced netfilter configuration: built-in (pass)
      CONFIG_NETFILTER_XTABLES: Netfilter Xtables support: built-in (pass)
        CONFIG_NETFILTER_XT_TARGET_REDIRECT: REDIRECT target support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_COMMENT: "comment" match support: module (pass)
        CONFIG_NETFILTER_XT_MARK: nfmark target and match support: module (pass)
        CONFIG_NETFILTER_XT_SET: set target and match support: module (pass)
        CONFIG_NETFILTER_XT_TARGET_MASQUERADE: MASQUERADE target support: module (pass)
        CONFIG_NETFILTER_XT_NAT: "SNAT and DNAT" targets support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_ADDRTYPE: "addrtype" address type match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_CONNTRACK: "conntrack" connection tracking match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_MULTIPORT: "multiport" Multiple port match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_RECENT: "recent" match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_STATISTIC: "statistic" match support: module (pass)
      CONFIG_NETFILTER_NETLINK: module (pass)
      CONFIG_NF_CONNTRACK: Netfilter connection tracking support: module (pass)
      CONFIG_NF_NAT: module (pass)
      CONFIG_IP_SET: IP set support: module (pass)
        CONFIG_IP_SET_HASH_IP: hash:ip set support: module (pass)
        CONFIG_IP_SET_HASH_NET: hash:net set support: module (pass)
      CONFIG_IP_VS: IP virtual server support: module (pass)
        CONFIG_IP_VS_NFCT: Netfilter connection tracking: built-in (pass)
      CONFIG_NF_CONNTRACK_IPV4: IPv4 connetion tracking support (required for NAT): unknown (warning)
      CONFIG_NF_REJECT_IPV4: IPv4 packet rejection: module (pass)
      CONFIG_NF_NAT_IPV4: IPv4 NAT: unknown (warning)
      CONFIG_IP_NF_IPTABLES: IP tables support: module (pass)
        CONFIG_IP_NF_FILTER: Packet filtering: module (pass)
          CONFIG_IP_NF_TARGET_REJECT: REJECT target support: module (pass)
        CONFIG_IP_NF_NAT: iptables NAT support: module (pass)
        CONFIG_IP_NF_MANGLE: Packet mangling: module (pass)
      CONFIG_NF_DEFRAG_IPV4: module (pass)
      CONFIG_NF_CONNTRACK_IPV6: IPv6 connetion tracking support (required for NAT): unknown (warning)
      CONFIG_NF_NAT_IPV6: IPv6 NAT: unknown (warning)
      CONFIG_IP6_NF_IPTABLES: IP6 tables support: module (pass)
        CONFIG_IP6_NF_FILTER: Packet filtering: module (pass)
        CONFIG_IP6_NF_MANGLE: Packet mangling: module (pass)
        CONFIG_IP6_NF_NAT: ip6tables NAT support: module (pass)
      CONFIG_NF_DEFRAG_IPV6: module (pass)
    CONFIG_BRIDGE: 802.1d Ethernet Bridging: module (pass)
      CONFIG_LLC: module (pass)
      CONFIG_STP: module (pass)
  CONFIG_EXT4_FS: The Extended 4 (ext4) filesystem: built-in (pass)
  CONFIG_PROC_FS: /proc file system support: built-in (pass)

```
</details>

### What happened?

Dualstack not working.

### Steps to reproduce

1. Deploy a Cluster with k0sctl
```yaml
apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: cell
spec:
  hosts:
  - ssh:
      address: [MASK]
      user: core
      port: 30750
    role: controller+worker
    noTaints: true
    installFlags:
    - --enable-k0s-cloud-provider=true
    - --enable-cloud-provider=true
  - ssh:
      address: [MASK]
      user: core
      port: 30750
    role: controller+worker
    noTaints: true
    installFlags:
    - --enable-k0s-cloud-provider=true
    - --enable-cloud-provider=true
  k0s:
    version: v1.25.2+k0s.0
    dynamicConfig: true
    config:
      apiVersion: k0s.k0sproject.io/v1beta1
      kind: Cluster
      metadata:
        name: cell
      spec:
        network:
          podCIDR: 10.244.0.0/16
          serviceCIDR: 10.96.0.0/12
          provider: calico
          calico:
            mode: bird
            wireguard: false
            ipAutodetectionMethod: kubernetes-internal-ip
          dualStack: 
            enabled: true
            IPv6podCIDR: "fd00::/108"
            IPv6serviceCIDR: "fd01::/108"
```

### Expected behavior

DualStack working,

### Actual behavior

It didn't

### Screenshots and logs

Refers to https://github.com/k0sproject/k0s/issues/1319

Seems like this time controller-manager isn't configured with dual-stack service-cluster-ip-range.

What I got from `systemctl status k0scontroller.service` shows:

kube-api-service `--service-cluster-ip-range=10.96.0.0/12,fd01::/108`
kube-controller-manager `--service-cluster-ip-range=10.96.0.0/12`

But I'm not sure is this the reason.

I can't use IPV6 in pod and can't assign IPV6 internal address to the node(`kubectl get node` will return nothing).

**Comment by OrvilleQ** [comment]
After disabled k0s cloud provider, everything works just fine.

**Comment by OrvilleQ** [comment]
> so are you trying to enable the built-in k0s cloud-provider AND some "real" cloud-provider? Or just the k0s internal one?

 Just the internal one. As the [document](https://docs.k0sproject.io/v1.25.2+k0s.0/cloud-providers/) said:

> To enable this functionality, add the parameter `--enable-k0s-cloud-provider=true` to all controllers, and `--enable-cloud-provider=true` to all workers.

**Comment by jnummelin** [comment]
🤦  Right, I remembered that setting the k0s provider only also enables the other flag... :D

> Dualstack not working.

Could you elaborate a bit more how this manifests itself? What exactly is not working?

**Comment by jnummelin** [comment]
After enabling the k0s cloud provider, do you actually set the wanted node addresses as annotations on the node object? See https://docs.k0sproject.io/head/cloud-providers/#k0s-cloud-provider

**Comment by OrvilleQ** [comment]
> Could you elaborate a bit more how this manifests itself? What exactly is not working?

So first thing first, It gonna take a really long time for `k0sctl` to get some thing from `k0scontroller.service` that makes it keep going. sometimes the installnation process might just failed.

After we get everything initialized and CNI interface installed, If I describe node following [this validation guide](https://kubernetes.io/docs/tasks/network/validate-dual-stack/) which should return both IPv4 and IPv6 CIDRs but I could only see IPv4 PodCIDRs.

```
kubectl get nodes [NODE] -o go-template --template='{{range .spec.podCIDRs}}{{printf "%s\n" .}}{{end}}'
```

And I can't see the internal IPv6 IP address I assigned to the node with:

```
kubectl get nodes [NODE] -o go-template --template='{{range .status.addresses}}{{printf "%s: %s\n" .type .address}}{{end}}'
```

And I can't access IPv6 inside pods, can't assign IPv6 address to pods, etc. Just everything on that validation guide are all red.

---

> The way k8s cloud providers work (all of them AFAIK, not just the k0s specific one) is that the nodes stay `NotReady` untill the cloud provider has initialized the node objects with address etc. infos.

I didn't assigned any external IP address though annotations ( But I remembered the node was Ready after install CNI, will trying to reproduce later) cause it look more like a internal issue to me rather than external issue (cause the `kube-controller-managers`'  `--service-cluster-ip-range` section only have IPv4 part instead of `kube-api-service` have both of v4 and v6).

The resaon I decided trying to remove cloudprovider is because I saw [this section](https://kubernetes.io/docs/concepts/services-networking/dual-stack/#configure-ipv4-ipv6-dual-stack) in Kubernetes' Dualstack document:

> ## Configure IPv4/IPv6 dual-stack
> To configure IPv4/IPv6 dual-stack, set dual-stack cluster network assignments:
> - kube-apiserver:
>   - `--service-cluster-ip-range=<IPv4 CIDR>,<IPv6 CIDR>`
> - kube-controller-manager:
>   - `--cluster-cidr=<IPv4 CIDR>,<IPv6 CIDR>`
>   - `--service-cluster-ip-range=<IPv4 CIDR>,<IPv6 CIDR>`
>   - `--node-cidr-mask-size-ipv4|--node-cidr-mask-size-ipv6` defaults to /24 for IPv4 and /64 for IPv6
> - kube-proxy:
>   - `--cluster-cidr=<IPv4 CIDR>,<IPv6 CIDR>`
> - kubelet:
>   - when there is no `--cloud-provider` the administrator can pass a comma-separated pair of IP addresses via `--node-ip` to manually configure dual-stack `.status.addresses` for that Node. If a Pod runs on that node in HostNetwork mode, the Pod reports these IP addresses in its `.status.podIPs` field. All `podIPs` in a node match the IP family preference defined by the `.status.addresses` field for that Node.

Therefore I'm not sure why disable cloud-provider fix this issue, It's more like a blind cat catch a dead mouse to me. But I'm happy to do some reproduce and validate work for you guys to help solve this problem if you guys need since I'm not that rush to set up my new cluster.

**Comment by jnummelin** [comment]
I tried this with following config:

```yaml
spec:
  network:
    kubeProxy:
      mode: ipvs
    provider: calico
    calico:
      mode: "bird"
    dualStack:
      enabled: true
      IPv6podCIDR: "fd00::/108"
      IPv6serviceCIDR: "fd01::/108"
    podCIDR: 10.244.0.0/16
    serviceCIDR: 10.96.0.0/12
```

I do see ipv6 assigned to a node:
```sh
kubectl get nodes worker0 -o go-template --template='{{range .spec.podCIDRs}}{{printf "%s\n" .}}{{end}}'
```

I see controller-manager populated with proper ipv6 flags:
```
--cluster-cidr=fd00::/108,10.244.0.0/16 --service-cluster-ip-range=10.96.0.0/12,fd01::/108
```

However as my test box is not really ipv6 enabled I do see some other failures, but everything gets configured properly.

I cannot immediately get why/how the k0s cloud provider would interfere here. We even have an integration testcase where we test it's ability to work with ipv6 addresses. I'll keep looking...

**Comment by jnummelin** [comment]
Oh, I _think_ I got it reproed now. I believe it's a bug in dynamic config, when that is enabled the in-cluster k0s config gets stored without the dualstack info. 🤦 
```
bash-5.1# k0s kc -n kube-system get clusterconfig k0s -o yaml | grep dualStack
    dualStack: {}
```
I've got a fix and test case verification cooking up for this.

**Comment by OrvilleQ** [comment]
@jnummelin Thanks for your awesome fix! But the backport of your fix to 1.25 somehow failed.

https://github.com/k0sproject/k0s/pull/2251#issuecomment-1305531250

Would you like to check that out later?

**Comment by jnummelin** [comment]
oh crap 🤦 

Somehow I missed the notification of the backport failing and just assumed it got properly backported. It's done now in #2439

**Comment by pinghe** [comment]
1.24 branches also need to be merged into

**Comment by pinghe** [comment]
hanks for your awesome fix!
