### ISSUE TITLE
Detailed status output for better observability

### ISSUE THREAD

**Issue by soider** [k0sproject/k0s#2273]
### Is your feature request related to a problem? Please describe.

As potential user (as operator) I want to have a way quickly understand what is the state of the cluster. From the k0s perspective, our cluster is organized via set of components. Each component handles piece of logic related to the cluster. For example, KubeletComponent is responsible for running and monitoring kubelet process.
Another example is LeaderElectorComponent, the component manages state of the leader election, without running any posix processes.

At the moment, the only way to understand, what's wrong with the state of cluster is to read logs.

It is error-prone, hard (due to noise nature of logs) and non-effective. 

### Describe the solution you would like

I suggest to improve our `component.Healthz` interface.
The current implementation looks like 
```go
// Healthz represents a component that can be checked for its health.
type Healthz interface {
	// Healthy performs a health check and indicates that the component is
	// running and functional. Whenever this is not the case, a non-nil error is
	// returned.
	Healthy() error
}

```

The Healthy method is logically called only once, during the process bootstrap.

I suggest to make it more close to the kubernetes model of the probes (https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/)

The possible realisation might be:

```go
// Healthz represents a component that can be checked for its health.
type Healthz interface {
	// Healthy is called once in a while by ComponentManager
	Healthy() HealthCheckStatus

	// Ready is called only once during bootstrap, the same way as Healthy in current implementation
	Ready() error
}


// HealthCheckStatus holds information about last health check
type HealthCheckStatus struct {
	Error error
	Message string
	At time.Time
}

```

The output of the `k0s status` might take those statuses and print them as a part of status message which might give good hints about the cluster status and where to start debug from.

### Describe alternatives you've considered

There are some solutions to monitor cluster health, from kubernetes perspective, for example https://kubernetes.io/docs/tasks/debug/debug-cluster/monitor-node-health/ we might also consider integration with such tooling to improve debugability.

### Additional context

It is only one step of improving observability in k0s. Next we might want to introduce per-component events the same way as per-component probes.

**Comment by twz123** [comment]
I think we can go without the `Ready` (the former `Healthy`) method at all, by just inlining the current calls to it into the `Start` methods of the components that implement it. See https://github.com/k0sproject/k0s/issues/1844#issue-1270592481:

> Concerning the `Healthy` method: Given that only the `Manager` uses it when starting components, I would argue that we can remove it completely. Instead, for those components that have a reasonable `Healthy` implementation, it should be embedded into the `Start` method. `Start` can then block until the component becomes healthy. The timeout loop implemented in the `Manager`'s `waitForHealthy` method could be transformed into a context that gets cancelled if `Start` doesn't return in time.

That way, the `Healthz` interface could be completely separate from the component manager. We could have some `HealthMonitor` component into which the components that expose the `Healthz` interface get added. That monitor component can report the component states via `k0s status`, k8s events or in some CRD status, whatever we want to have.

I'd also opt for adding a context to the method signatures.

**Comment by twz123** [comment]
Concerning `HealthCheckStatus`:

* How are `Error` and `Message` supposed to be related. Is it mutually exclusive, i.e. either have an error or a message? Could be that we're going without the message at all, since any extra messaging can be put into the error via a wrapping it (à la `fmt.Errorf("foo is unhealthy because it failed to do bar: %w", err)` or similar). The message in the success case wold probably be just "Healthy"?
* Would it be meaningful to have multiple health checks? I.e. return a slice of `HealthCheckStatus`, or a slice of errors in the status struct?

**Comment by soider** [comment]
I'd rather have separate Ready and Healthy methods, because the logic might be different in those, but I don't have strict opinion.

>How are Error and Message supposed to be related. Is it mutually exclusive, i.e. either have an error or a message? Could be that we're going without the message at all, since any extra messaging can be put into the error via a wrapping it (à la fmt.Errorf("foo is unhealthy because it failed to do bar: %w", err) or similar). The message in the success case wold probably be just "Healthy"?

sounds reasonable to keep only one field.

>Would it be meaningful to have multiple health checks? I.e. return a slice of HealthCheckStatus, or a slice of errors in the status struct?

what might be the reason to return a slice of status checks?

**Comment by twz123** [comment]
> I'd rather have separate Ready and Healthy methods, because the logic might be different in those, [...]

Absolutely. What I tried to say was that the component manager wouldn't need to know about the `Healthz` interface at all if the components that require some health condition at startup embed that check into their own `Start` methods. That way, the special `Ready` method would become obsolete.

> what might be the reason to return a slice of status checks?

Dunno, just a random thought. I've seen this in other health check implementations where components could report details about their sub-components. So without a clear use case, let's just stick with the simple approach.
