### ISSUE TITLE
failed to create listener listen unix /run/k0s/status.sock: bind: address already in use"

### ISSUE THREAD

**Issue by anton-schleenvoigt** [k0sproject/k0s#2283]
### Before creating an issue, make sure you've checked the following:

- [X] You are running the latest released version of k0s
- [X] Make sure you've searched for existing issues, both open and closed
- [X] Make sure you've searched for PRs too, a fix might've been merged already
- [X] You're looking at docs for the released version, "main" branch docs are usually ahead of released versions.

### Platform

```shell
Linux 5.13.0-44-generic #49~20.04.1-Ubuntu SMP Wed May 18 18:44:28 UTC 2022 x86_64 GNU/Linux
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

### Version

v1.22.4+k0s.1

### Sysinfo

KERNEL_VERSION: 5.13.0-44-generic
CONFIG_NAMESPACES: enabled
CONFIG_NET_NS: enabled
CONFIG_PID_NS: enabled
CONFIG_IPC_NS: enabled
CONFIG_UTS_NS: enabled
CONFIG_CGROUPS: enabled
CONFIG_CGROUP_CPUACCT: enabled
CONFIG_CGROUP_DEVICE: enabled
CONFIG_CGROUP_FREEZER: enabled
CONFIG_CGROUP_PIDS: enabled
CONFIG_CGROUP_SCHED: enabled
CONFIG_CPUSETS: enabled
CONFIG_MEMCG: enabled
CONFIG_INET: enabled
CONFIG_EXT4_FS: enabled
CONFIG_PROC_FS: enabled
CONFIG_NETFILTER_XT_TARGET_REDIRECT: enabled (as module)
CONFIG_NETFILTER_XT_MATCH_COMMENT: enabled (as module)
CONFIG_FAIR_GROUP_SCHED: enabled
CONFIG_OVERLAY_FS: enabled (as module)
CONFIG_BLK_DEV_DM: enabled
CONFIG_CFS_BANDWIDTH: enabled
CONFIG_CGROUP_HUGETLB: enabled
CONFIG_SECCOMP: enabled
CONFIG_SECCOMP_FILTER: enabled
CONFIG_BRIDGE: enabled (as module)
CONFIG_IP6_NF_FILTER: enabled (as module)
CONFIG_IP6_NF_IPTABLES: enabled (as module)
CONFIG_IP6_NF_MANGLE: enabled (as module)
CONFIG_IP6_NF_NAT: enabled (as module)
CONFIG_IP_NF_FILTER: enabled (as module)
CONFIG_IP_NF_IPTABLES: enabled (as module)
CONFIG_IP_NF_MANGLE: enabled (as module)
CONFIG_IP_NF_NAT: enabled (as module)
CONFIG_IP_NF_TARGET_REJECT: enabled (as module)
CONFIG_IP_SET: enabled (as module)
CONFIG_IP_SET_HASH_IP: enabled (as module)
CONFIG_IP_SET_HASH_NET: enabled (as module)
CONFIG_IP_VS_NFCT: enabled
CONFIG_LLC: enabled (as module)
CONFIG_NETFILTER_NETLINK: enabled (as module)
CONFIG_NETFILTER_XTABLES: enabled (as module)
CONFIG_NETFILTER_XT_MARK: enabled (as module)
CONFIG_NETFILTER_XT_MATCH_ADDRTYPE: enabled (as module)
CONFIG_NETFILTER_XT_MATCH_CONNTRACK: enabled (as module)
CONFIG_NETFILTER_XT_MATCH_MULTIPORT: enabled (as module)
CONFIG_NETFILTER_XT_MATCH_RECENT: enabled (as module)
CONFIG_NETFILTER_XT_MATCH_STATISTIC: enabled (as module)
CONFIG_NETFILTER_XT_NAT: enabled (as module)
CONFIG_NETFILTER_XT_SET: enabled (as module)
CONFIG_NETFILTER_XT_TARGET_MASQUERADE: enabled (as module)
CONFIG_NF_CONNTRACK: enabled (as module)
CONFIG_NF_DEFRAG_IPV4: enabled (as module)
CONFIG_NF_DEFRAG_IPV6: enabled (as module)
CONFIG_NF_NAT: enabled (as module)
CONFIG_NF_REJECT_IPV4: enabled (as module)
CONFIG_STP: enabled (as module)
OS: Linux
CGROUPS_CPU: enabled
CGROUPS_CPUACCT: enabled
CGROUPS_CPUSET: enabled
CGROUPS_DEVICES: enabled
CGROUPS_FREEZER: enabled
CGROUPS_MEMORY: enabled
CGROUPS_PIDS: enabled
CGROUPS_HUGETLB: enabled

### What happened?

First, i followed these steps --> https://docs.k0sproject.io/v0.10.0/examples/ansible-playbook/ to create a a cluster with Ansible script. The main difference in my setup is that I actually have 6 physical nodes. Have no other modification more then the inventory file.

I run the command: **ansible-playbook site.yml -i inventory/multipass/inventory.yml**

- The first time i run the command, the Ansible failed for some nodes, ssh issue. I fixed those errors
- I run the command ansible-playbook reset.yml -i inventory/multipass/inventory.yml To reset the systemctl service created on the nodes. 
- I then run the command --> ansible-playbook site.yml -i inventory/multipass/inventory.yml once more
For some reason: see log file

4. I used: netstat -tulpen | grep 6443 and it does not comeback with anything. So i cannot find any bind to that port 
6. I have tested to reboot the systems.
7. I modified the timeout in the service config file from 100 to 500 to make sure that it is not a timing issue. 
8. I tried even to remove /etc/systemd/system/k0scontroller.service manually and performed systemctl daemon-reload
 

### Steps to reproduce

1. git clone https://github.com/movd/k0s-ansible.git
2. Modify inventory file
3. Run command --> ansible-playbook site.yml -i inventory/multipass/inventory.yml
4. Run command --> ansible-playbook reset.yml -i inventory/multipass/inventory.yml
5. Run command --> ansible-playbook site.yml -i inventory/multipass/inventory.yml

### Expected behavior

I expected that systemct status k0scontroller.service was able to connect to localhost:6443 

### Actual behavior

The service k0scontroller.service times out when connect to localhost:6443

### Screenshots and logs

Complete ansible log see debug.txt
[debug.txt](https://github.com/k0sproject/k0s/files/9820322/debug.txt)
From service k0scontroller.service journal
2. **Error: listen unix /run/k0s/status.sock: bind: address already in use**
[journal.txt](https://github.com/k0sproject/k0s/files/9820348/journal.txt)

**Comment by jnummelin** [comment]
fixed in #2225 and subsequent backports
