### ISSUE TITLE
Buggy integration test: `cnichange`

### ISSUE THREAD

**Issue by twz123** [k0sproject/k0s#2289]
The `cnichange` integration test is buggy.

The test checks if the k0s controller startup fails after the CNI provider changed. It launches k0s via SSH and expects to see an error:
https://github.com/k0sproject/k0s/blob/v1.25.2+k0s.0/inttest/cnichange/cnichange_test.go#L45-L46

But: k0s actually won't fail to startup, it will simply stick to the previous provider. This is due to the fact that the checks reside in the `Reconcile` methods of the calico/kuberouter controller components nowadays, which won't trigger a termination of the controller, but rather log an error and post a Kubernetes event.

The test still succeeds because the SSH connection will be terminated as soon as the integration test's context deadline is exceeded. The SSH call will return with a context error (presumably "deadline exceeded"), which satisfies the test assertion just fine.

**Comment by twz123** [comment]
Moreover: `check-config` seems to hceck similar things. Maybe the `cnichange` test is obsolete?

**Comment by jnummelin** [comment]
> Moreover: check-config seems to test similar things. Maybe the cnichange test is obsolete?

IIRC they test it differently, one tests with dynamic config and the other via "normal" k0s.yaml changes.
