### ISSUE TITLE
(question) cannot scrape system components metrics

### ISSUE THREAD

**Issue by mtb-xt** [k0sproject/k0s#2321]
Hey everyone, this is not really a k0s issue, but I guess one that could be better documented.

I'm trying to set up prometheus monitoring by following this - https://docs.k0sproject.io/v1.25.2+k0s.0/system-monitoring/ 

I've enabled the flag `--enable-metrics-scraper` on the controllers, I can see 'k0s-pushgateway' pod, I've configured a prometheus operator servicemonitor to monitor the service, and I can see the metrics from job="kube-scheduler" and job="kube-controller-manager".
I've also set honor_labels: true on the servicemonitor.

But prometheus alerts that both kube jobs are failing, and the 'up' metric for job="kube-scheduler", for example, returns nothing.

If anyone successfully configured scraping of pushgateway, I'd appreciate the help (and I'll try to create a PR to update the article on k0s site)

**Comment by makhov** [comment]
Hi @mtb-xt! 

The `up` metric is defined by Prometheus itself for every job (e.g. every scrape config), so there is no trivial way to add the metric for the `kube-scheduler` and `kube-controller-manager` jobs. 

The easiest option to mitigate the issue is to change the expression of the alert and check for the absence of some metric, for instance:

```
absent(apiserver_audit_event_total{job="kube-scheduler"})
```

**Comment by mtb-xt** [comment]
Got it, thanks! I'll give it a go. Those alerts come from `kube-prometheus-stack` chart. 
Would a PR to add this info to docs be ok?

**Comment by jnummelin** [comment]
> Would a PR to add this info to docs be ok?

Of course!

**Comment by fenio** [comment]
Since @mtb-xt hasn't submitted PR I did it on my own cause I had exactly same problems and I found in this ticket very useful info, so thanks @mtb-xt for digging into that ;)
