### ISSUE TITLE
Trying to restore a backup: etcd mvcc: database space exceeded 

### ISSUE THREAD

**Issue by till** [k0sproject/k0s#2358]
### Before creating an issue, make sure you've checked the following:

- [X] You are running the latest released version of k0s
- [X] Make sure you've searched for existing issues, both open and closed
- [X] Make sure you've searched for PRs too, a fix might've been merged already
- [X] You're looking at docs for the released version, "main" branch docs are usually ahead of released versions.

### Platform

```shell
Linux 5.10.142-flatcar #1 SMP Tue Oct 11 18:43:33 -00 2022 x86_64 GNU/Linux
NAME="Flatcar Container Linux by Kinvolk"
ID=flatcar
ID_LIKE=coreos
VERSION=3033.3.6
VERSION_ID=3033.3.6
BUILD_ID=2022-10-11-1924
PRETTY_NAME="Flatcar Container Linux by Kinvolk 3033.3.6 (LTS 2022)"
ANSI_COLOR="38;5;75"
HOME_URL="https://flatcar.org/"
BUG_REPORT_URL="https://issues.flatcar.org"
FLATCAR_BOARD="amd64-usr"
```

### Version

v1.23.10+k0s.0

### Sysinfo

<details><summary>`k0s sysinfo`</summary>

```shell

KERNEL_VERSION: 5.10.142-flatcar
CONFIG_INET: enabled
CONFIG_NETFILTER_XT_TARGET_REDIRECT: enabled (as module)
CONFIG_NETFILTER_XT_MATCH_COMMENT: enabled (as module)
CONFIG_NAMESPACES: enabled
CONFIG_UTS_NS: enabled
CONFIG_IPC_NS: enabled
CONFIG_PID_NS: enabled
CONFIG_NET_NS: enabled
CONFIG_CGROUPS: enabled
CONFIG_CGROUP_FREEZER: enabled
CONFIG_CGROUP_PIDS: enabled
CONFIG_CGROUP_DEVICE: enabled
CONFIG_CPUSETS: enabled
CONFIG_CGROUP_CPUACCT: enabled
CONFIG_MEMCG: enabled
CONFIG_CGROUP_SCHED: enabled
CONFIG_FAIR_GROUP_SCHED: enabled
CONFIG_EXT4_FS: enabled (as module)
CONFIG_PROC_FS: enabled
CONFIG_OVERLAY_FS: enabled (as module)
CONFIG_BLK_DEV_DM: enabled (as module)
CONFIG_CFS_BANDWIDTH: enabled
CONFIG_CGROUP_HUGETLB: enabled
CONFIG_SECCOMP: enabled
CONFIG_SECCOMP_FILTER: enabled
CONFIG_BRIDGE: enabled (as module)
CONFIG_IP6_NF_FILTER: enabled (as module)
CONFIG_IP6_NF_IPTABLES: enabled (as module)
CONFIG_IP6_NF_MANGLE: enabled (as module)
CONFIG_IP6_NF_NAT: enabled (as module)
CONFIG_IP_NF_FILTER: enabled (as module)
CONFIG_IP_NF_IPTABLES: enabled
CONFIG_IP_NF_MANGLE: enabled (as module)
CONFIG_IP_NF_NAT: enabled (as module)
CONFIG_IP_NF_TARGET_REJECT: enabled (as module)
CONFIG_IP_SET: enabled (as module)
CONFIG_IP_SET_HASH_IP: enabled (as module)
CONFIG_IP_SET_HASH_NET: enabled (as module)
CONFIG_IP_VS_NFCT: enabled
CONFIG_LLC: enabled (as module)
CONFIG_NETFILTER_NETLINK: enabled (as module)
CONFIG_NETFILTER_XTABLES: enabled
CONFIG_NETFILTER_XT_MARK: enabled (as module)
CONFIG_NETFILTER_XT_MATCH_ADDRTYPE: enabled (as module)
CONFIG_NETFILTER_XT_MATCH_CONNTRACK: enabled (as module)
CONFIG_NETFILTER_XT_MATCH_MULTIPORT: enabled (as module)
CONFIG_NETFILTER_XT_MATCH_RECENT: enabled (as module)
CONFIG_NETFILTER_XT_MATCH_STATISTIC: enabled (as module)
CONFIG_NETFILTER_XT_NAT: enabled (as module)
CONFIG_NETFILTER_XT_SET: enabled (as module)
CONFIG_NETFILTER_XT_TARGET_MASQUERADE: enabled (as module)
CONFIG_NF_CONNTRACK: enabled (as module)
CONFIG_NF_DEFRAG_IPV4: enabled (as module)
CONFIG_NF_DEFRAG_IPV6: enabled (as module)
CONFIG_NF_NAT: enabled (as module)
CONFIG_NF_REJECT_IPV4: enabled (as module)
CONFIG_STP: enabled (as module)
OS: Linux
CGROUPS_CPU: enabled
CGROUPS_CPUACCT: enabled
CGROUPS_CPUSET: enabled
CGROUPS_DEVICES: enabled
CGROUPS_FREEZER: enabled
CGROUPS_MEMORY: enabled
CGROUPS_PIDS: enabled
CGROUPS_HUGETLB: enabled
```
</details>

### What happened?

Trying to update the OS and our k0s cluster to a new release (via `k0sctl`). I think we first hit a weird (ext4) kernel bug which made the node unresponsive under high i/o and I couldn't figure it out. For some reason the etcd cluster stopped working when I rebooted the node ("mvcc: database space exceeded") and I couldn't figure out why that happened in the first place. But ultimately, I think that triggered the kernel bug (unrelated) but leads down an interesting road of recovering a k0s cluster.

Generally, this is not a huge issue for us as this is a staging cluster (and we can rebuild it completely) but for the sake of trying recovery we discovered that "something" went so wrong that the etcd cluster becomes completely unmanagable. And that "state" is also in the backup.

So we deleted everything and tried to `k0sctl apply -c ... --restore-from back.tar.gz`. And that worked for one node and then it was stuck on "generating token". On closer inspection it brought back, "etcd: mvcc: database space exceeded" (when it's trying to create a join token for controllers) — (would be nice if it didn't display `--help` there as it is clearly not a "Usage error") from the backup.

```sh
core@node-001 ~ $ sudo /opt/bin/k0s token create --role controller --expiry 10m0s
Error: etcdserver: mvcc: database space exceeded
Usage:
  k0s token create [flags]

Examples:
k0s token create --role worker --expiry 100h //sets expiration time to 100 hours
k0s token create --role worker --expiry 10m  //sets expiration time to 10 minutes


Flags:
      --debugListenOn string   Http listenOn for Debug pprof handler (default ":6060")
      --expiry string          Expiration time of the token. Format 1.5h, 2h45m or 300ms. (default "0s")
  -h, --help                   help for create
      --role string            Either worker or controller (default "worker")
      --status-socket string   Full file path to the socket file. (default "/run/k0s/status.sock")
  -v, --verbose                Verbose logging (default: false)
      --wait                   wait forever (default false)

Global Flags:
      --data-dir string   Data Directory for k0s (default: /var/lib/k0s). DO NOT CHANGE for an existing setup, things will break!
      --debug             Debug logging [$DEBUG]
```

Since the `k0scontroller` on the (first) node was running, we've been trying to fix it so it could move on:

```shell
sudo etcdctl defrag --command-timeout=120s --cert=/var/lib/k0s/pki/apiserver-etcd-client.crt --key=/var/lib/k0s/pki/apiserver-etcd-client.key --insecure-skip-tls-verify=true
Finished defragmenting etcd member[127.0.0.1:2379]
sudo etcdctl alarm disarm --command-timeout=120s --cert=/var/lib/k0s/pki/apiserver-etcd-client.crt --key=/var/lib/k0s/pki/apiserver-etcd-client.key --insecure-skip-tls-verify=true
memberID:16717790760937561046 alarm:NOSPACE
sudo etcdctl endpoint status --command-timeout=120s --cert=/var/lib/k0s/pki/apiserver-etcd-client.crt --key=/var/lib/k0s/pki/apiserver-etcd-client.key --insecure-skip-tls-verify=true
127.0.0.1:2379, e0a7698ba06bd809, 3.5.4, 2.1 GB, true, false, 7, 755, 755,
```

Ultimately, this made the "stacks" (e.g. calico, ...) start on the node, instead of just getting flooded with etcd error messages.

Then we proceeded with a `k0sctl apply -c ...` (**without** `--restore-from`) and it seems to progress and install the other controller nodes. Once they started, the logs are getting flooded with:

```
:HTTP/2.0 (04-Nov-2022 12:02:36.615) (total time: 10000ms):" component=kube-apiserver
Nov 04 12:02:46 node-001.testing k0s[5743]: time="2022-11-04 12:02:46" level=info msg="Trace[464336665]: [10.0007052s] [10.0007052s] END" component=kube-apiserver
Nov 04 12:02:46 node-001.testing k0s[5743]: time="2022-11-04 12:02:46" level=info msg="{\"level\":\"warn\",\"ts\":\"2022-11-04T12:02:46.678Z\",\"caller\":\"rafthttp/stream.go:653\",\"msg\":\"request sent was ignored by remote peer due to cluster ID mismatch\",\"remote-peer-id\":\"1d648adf16689f9e\",\"remote-peer-cluster-id\":\"e158a6315a4d4ced\",\"local-member-id\":\"e0a7698ba06bd809\",\"local-member-cluster-id\":\"b24fc8ef84a590ae\",\"error\":\"cluster ID mismatch\"}" component=etcd
Nov 04 12:02:46 node-001.testing k0s[5743]: time="2022-11-04 12:02:46" level=info msg="{\"level\":\"warn\",\"ts\":\"2022-11-04T12:02:46.678Z\",\"caller\":\"rafthttp/stream.go:653\",\"msg\":\"request sent was ignored by remote peer due to cluster ID mismatch\",\"remote-peer-id\":\"1d648adf16689f9e\",\"remote-peer-cluster-id\":\"e158a6315a4d4ced\",\"local-member-id\":\"e0a7698ba06bd809\",\"local-member-cluster-id\":\"b24fc8ef84a590ae\",\"error\":\"cluster ID mismatch\"}" component=etcd
```

So the recovery didn't work as expected and the IDs of the etcd members don't line up (for whatever reason). We kept all hostnames and IPs the same, but I am guessing I somehow need to remove some servers and re-add them?

I have been trying to do a `member list`, but this leads to this error message:

```
core@node-001 ~ $ sudo etcdctl member list --command-timeout=120s --cert=/var/lib/k0s/pki/apiserver-etcd-client.crt --key=/var/lib/k0s/pki/apiserver-etcd-client.key --insecure-skip-tls-verify=true
{"level":"warn","ts":"2022-11-04T12:16:49.367Z","logger":"etcd-client","caller":"v3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0000e48c0/#initially=[127.0.0.1:2379]","attempt":0,"error":"rpc error: code = Unavailable desc = etcdserver: request timed out"}
```

I went on to the other control plane nodes (`node-002` and `node-003`) to `sudo systemctl stop k0scontroller` and restarted it on `node-001`, hoping to make member list work again. But it still timeouts.  I ultimately cannot get any `etcdctl` commands to work. They all run into timeouts. This is super frustrating since I think we are close to recovering the thing if we can somehow remove the members and add them again.

As an alternative, maybe `--restore-from` should bootstrap a new etcd cluster instead. I think it's what most documentation suggests.

### Steps to reproduce

1. See
2. Above

### Expected behavior

Restore works. More etcdctl is exposed in `k0s` and more of it is documented how it's being run (since it's embedded). Also related: #1920

### Actual behavior

Broken cluster

**Comment by till** [comment]
I used an older backup (from September) and that restore worked right away, but of course there's about a "month" of changes that are not on the cluster.

**Comment by jnummelin** [comment]
What this sounds to me, unfortunately, is that the etcd backup itself is somehow "corrupted" from the time you hit the ext4 kernel stuff.

As I can see from the `etcdctl endpoint status` output, you only have a single node in the cluster. And that's how the etcd restore process works with k0s, you restore data on the first node and then re-join the rest as they'd join a new cluster. Once the other nodes join they'll sync up the data from the first node.

What I do not get is how etcd is refusing the join for other two nodes.

**Comment by jnummelin** [comment]
> What I do not get is how etcd is refusing the join for other two nodes.

Oh, IIRC restore in etcd "re-configures" member IDs and cluster ID, so the two other nodes probably have still their etcd data dirs intact and are trying to use "old" clusterID.

What I'd try is to remove (or move somewhere else if you want to keep them for reference/restore/... purpose) the etcd data dir on the controller 2&3, and then try again

**Comment by till** [comment]
We deleted and rebooted everything between attempts. (`k0s reset` etc.)

Restore works with an older backup right away. So the logic is working, but somehow the latest backup was completely broken.

I couldn't get it to stabilize at all.

**Comment by till** [comment]
@jnummelin what's the easiest way to see how the embedded etcds are configured? As in, if auto-compaction is running etc..

**Comment by jnummelin** [comment]
```
cat /proc/$(pidof etcd)/cmdline | xargs -0 | tr " " "\n"
```

**Comment by till** [comment]
Do you have any thoughts to establish some kind of document or maybe even feature for backups? Currently pondering if I should run `k0sctl backup` every hour. But not even sure how to catch corrupt backups. 😵‍💫

**Comment by jnummelin** [comment]
We have docs around backup: https://docs.k0sproject.io/v1.25.3+k0s.0/backup/

As we have `k0s backup` as a command out-of-the-box, I'm not sure I get what you mean by having it as a feature? :) You mean something where k0s itself is able to have some cron like schedule defined and can then push the backups to external storage like S3?

**Comment by till** [comment]
I build a github action to do exactly that, that's why I was asking about getting a k0sctl image published.

Though not sure yet how to monitor etcd since they run embedded and how to make sure the backups are not corrupted. 😅
