### ISSUE TITLE
Network Switching

### ISSUE THREAD

**Issue by khusseini** [k0sproject/k0s#2420]
### Is your feature request related to a problem? Please describe.

Currently there is no built in way to easily switch network with k0s. I have tried to replace configurations and restart the k0scontroller serivce on my local machine but without success. I currently  have to completely destroy the cluster and reinstall it in order to use it in a new network. It would be amazing if there was a command to switch to a new network.

### Describe the solution you would like

`sudo k0s network-set 192.168.0.101`

### Describe alternatives you've considered

Here is a script that I have tried however I am not able to communicate with k0s as soon as I am in a new network. 

```
#!/usr/bin/env bash

install_yq() {
    wget https://github.com/mikefarah/yq/releases/download/${VERSION}/${BINARY} -O /usr/bin/yq &&\
    chmod +x /usr/bin/yq
}

if [[ ! -f /usr/bin/yq ]]
 then
    VERSION=v4.18.1
    BINARY=yq_linux_amd64
    install_yq
fi

from=${1}
to=${2}

patch_config() {
    yq -i '.spec.extensions.storage.type = "openebs_local_storage" | .spec.extensions.storage.create_default_storage_class = true' /etc/k0s/k0s.yaml
}

new_network() {
    k0s config create > /etc/k0s/k0s.yaml
    patch_config
}

existing_network() {
    cp /etc/k0s/k0s.${to}.yaml /etc/k0s/k0s.yaml
}

k0s stop

echo "Moving from ${from} to ${to}"
mv /etc/k0s/k0s.yaml /etc/k0s/k0s.${from}.yaml


if [ -f "/etc/k0s/k0s.${to}.yaml" ]; then
    existing_network
else
    new_network
fi

systemctl restart k0scontroller
k0s kubectl wait node --all --for condition=ready
k0s kubectl patch storageclass openebs-hostpath -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'
```

**Comment by jnummelin** [comment]
By network switching, what do you actually mean? The controllers changing their network and thus getting new IP address etc.?

**Comment by khusseini** [comment]
Sorry I wasn't very clear with "network switching". 
Actually it doesn't have to be a completely new network specifically I mean the IP associated with the kube api, nameley the value of `spec.api.address` of the `k0s` configuration.

**Comment by jnummelin** [comment]
hmm, so if you change the `spec.api.address` to new IP, what exactly is not working? k0s should reconcile all the configs automatically, with one caveat. The only caveat is on pure worker nodes, k0s does not know how to change the kubelets address for API server, namely in `/var/lib/k0s/kubelet.conf`

**Comment by khusseini** [comment]
Hey, my apologies for the late reply. So I tried to simply change the IP in the `/etc/k0s/k0s.yaml` and did 

```bash
> sudo systemctl restart k0scontroller
> sudo k0s kubeconfig admin > ~/.kube/config
> kubectl get nodes
The connection to the server 192.168.178.56:6443 was refused - did you specify the right host or port?
```

It seems that the configs are note reconciled automatically. 

```bash
> sudo k0s kubectl get nodes
The connection to the server localhost:6443 was refused - did you specify the right host or port?
```

**Comment by jnummelin** [comment]
Ah, now it starts to make more sense.

So you need to also update the `spec.storage.etcd.peerAddress` field to the new address.

Are you running multiple controllers or just a single one?

If you are running multiple ones, you might be able to this kind of change only to one controller at a time as changing the addresses of etcd nodes will probably break the member and thus break the quorum of the cluster. In addition, in multinode case you might need to change the cluster membership info per https://etcd.io/docs/v3.5/op-guide/runtime-configuration/#update-advertise-peer-urls

**Comment by sacesare** [comment]
Not working for me with 1.25.4,  my scenario is simple:
1) backup cluster `k0s backup` (single node config `controller --enable-worker=true` )
2) restore on different machine with different ip/hostname, setting both `spec.storage.etcd.peerAddress` and `spec.api.address` to new ip address

etcd can't be started after that `k0s etcd member-list` report member with new(correct) host name and old address(address of previous host).

**Comment by pschichtel** [comment]
my checklist for future reference (done on 1.27.2):

1. replace the IP in the uplink NIC configuration
2. replace the IP in any relevant `/etc/hosts` entries
3. replace the IP in `/etc/k0s/k0s.yaml`, explicitly set `spec.storage.etcd.peerAddress` to new IP
4. replace the IP in `/var/lib/k0s/kubelet.conf` and `/var/lib/k0s/kubelet-bootstrap.conf`
5. delete the `default/kubernetes` service (will be recreated)
6. remove any stale default/kubernete* EndpointSlices if they exist

The `k0s etcd member-list` still shows the old IP, but in a single node setup that doesn't seem to matter.

I did step 5 after noticing "connection refused" errors and seeing that NAT rules still pointed to the old IP. After that the service was load balanced between the old and new IPs, because for some reason an EndpointSlice called `kubernetes` existed for the old IP in addition to `kubernetes-tkd2l` for the new IP. So step 3 just removes all of them, the correct one will be recreated.

**Comment by khusseini** [comment]
We worked around this problem by creating a virtual network device and assign a static IP to k0s. 
[Here is the gist of it](https://gist.github.com/khusseini/2c9da1ebe252ee040a3195ffa6e13cfa), but for day to day use I wrapped it as a systemd service. I am not sure if I should close the issue or keep it, but for me the issue is solved.

**Comment by jnummelin** [comment]
@pschichtel would you mind creating a chapter on this on the docs?

**Comment by pschichtel** [comment]
I could do that. Do you have input on where specifically I would place such a chapter within the docs?
