### ISSUE TITLE
After restoring，controller exec “k0s ctr version” can not get containerd server info 

### ISSUE THREAD

**Issue by ling1042133624** [k0sproject/k0s#2459]
### Before creating an issue, make sure you've checked the following:

- [X] You are running the latest released version of k0s
- [X] Make sure you've searched for existing issues, both open and closed
- [X] Make sure you've searched for PRs too, a fix might've been merged already
- [X] You're looking at docs for the released version, "main" branch docs are usually ahead of released versions.

### Platform

```shell
Linux 5.15.0-53-generic #59~20.04.1-Ubuntu SMP Thu Oct 20 15:10:22 UTC 2022 x86_64 GNU/Linux
NAME="Ubuntu"
VERSION="20.04 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

### Version

v1.25.2+k0s.0

### Sysinfo

Machine ID: "b820f275aba5719db041d43557f391302a29df482a55f4b96fcac217338b35e4" (from machine) (pass)
Total memory: 3.8 GiB (pass)
Disk space available for /var/lib/k0s: 78.7 GiB (pass)
Operating system: Linux (pass)
  Linux kernel release: 5.15.0-53-generic (pass)
  Max. file descriptors per process: current: 1048576 / max: 1048576 (pass)
  Executable in path: modprobe: /usr/sbin/modprobe (pass)
  /proc file system: mounted (0x9fa0) (pass)
  Control Groups: version 1 (pass)
    cgroup controller "cpu": available (pass)
    cgroup controller "cpuacct": available (pass)
    cgroup controller "cpuset": available (pass)
    cgroup controller "memory": available (pass)
    cgroup controller "devices": available (pass)
    cgroup controller "freezer": available (pass)
    cgroup controller "pids": available (pass)
    cgroup controller "hugetlb": available (pass)
    cgroup controller "blkio": available (pass)
  CONFIG_CGROUPS: Control Group support: built-in (pass)
    CONFIG_CGROUP_FREEZER: Freezer cgroup subsystem: built-in (pass)
    CONFIG_CGROUP_PIDS: PIDs cgroup subsystem: built-in (pass)
    CONFIG_CGROUP_DEVICE: Device controller for cgroups: built-in (pass)
    CONFIG_CPUSETS: Cpuset support: built-in (pass)
    CONFIG_CGROUP_CPUACCT: Simple CPU accounting cgroup subsystem: built-in (pass)
    CONFIG_MEMCG: Memory Resource Controller for Control Groups: built-in (pass)
    CONFIG_CGROUP_HUGETLB: HugeTLB Resource Controller for Control Groups: built-in (pass)
    CONFIG_CGROUP_SCHED: Group CPU scheduler: built-in (pass)
      CONFIG_FAIR_GROUP_SCHED: Group scheduling for SCHED_OTHER: built-in (pass)
        CONFIG_CFS_BANDWIDTH: CPU bandwidth provisioning for FAIR_GROUP_SCHED: built-in (pass)
    CONFIG_BLK_CGROUP: Block IO controller: built-in (pass)
  CONFIG_NAMESPACES: Namespaces support: built-in (pass)
    CONFIG_UTS_NS: UTS namespace: built-in (pass)
    CONFIG_IPC_NS: IPC namespace: built-in (pass)
    CONFIG_PID_NS: PID namespace: built-in (pass)
    CONFIG_NET_NS: Network namespace: built-in (pass)
  CONFIG_NET: Networking support: built-in (pass)
    CONFIG_INET: TCP/IP networking: built-in (pass)
      CONFIG_IPV6: The IPv6 protocol: built-in (pass)
    CONFIG_NETFILTER: Network packet filtering framework (Netfilter): built-in (pass)
      CONFIG_NETFILTER_ADVANCED: Advanced netfilter configuration: built-in (pass)
      CONFIG_NETFILTER_XTABLES: Netfilter Xtables support: module (pass)
        CONFIG_NETFILTER_XT_TARGET_REDIRECT: REDIRECT target support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_COMMENT: "comment" match support: module (pass)
        CONFIG_NETFILTER_XT_MARK: nfmark target and match support: module (pass)
        CONFIG_NETFILTER_XT_SET: set target and match support: module (pass)
        CONFIG_NETFILTER_XT_TARGET_MASQUERADE: MASQUERADE target support: module (pass)
        CONFIG_NETFILTER_XT_NAT: "SNAT and DNAT" targets support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_ADDRTYPE: "addrtype" address type match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_CONNTRACK: "conntrack" connection tracking match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_MULTIPORT: "multiport" Multiple port match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_RECENT: "recent" match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_STATISTIC: "statistic" match support: module (pass)
      CONFIG_NETFILTER_NETLINK: module (pass)
      CONFIG_NF_CONNTRACK: Netfilter connection tracking support: module (pass)
      CONFIG_NF_NAT: module (pass)
      CONFIG_IP_SET: IP set support: module (pass)
        CONFIG_IP_SET_HASH_IP: hash:ip set support: module (pass)
        CONFIG_IP_SET_HASH_NET: hash:net set support: module (pass)
      CONFIG_IP_VS: IP virtual server support: module (pass)
        CONFIG_IP_VS_NFCT: Netfilter connection tracking: built-in (pass)
      CONFIG_NF_CONNTRACK_IPV4: IPv4 connetion tracking support (required for NAT): unknown (warning)
      CONFIG_NF_REJECT_IPV4: IPv4 packet rejection: module (pass)
      CONFIG_NF_NAT_IPV4: IPv4 NAT: unknown (warning)
      CONFIG_IP_NF_IPTABLES: IP tables support: module (pass)
        CONFIG_IP_NF_FILTER: Packet filtering: module (pass)
          CONFIG_IP_NF_TARGET_REJECT: REJECT target support: module (pass)
        CONFIG_IP_NF_NAT: iptables NAT support: module (pass)
        CONFIG_IP_NF_MANGLE: Packet mangling: module (pass)
      CONFIG_NF_DEFRAG_IPV4: module (pass)
      CONFIG_NF_CONNTRACK_IPV6: IPv6 connetion tracking support (required for NAT): unknown (warning)
      CONFIG_NF_NAT_IPV6: IPv6 NAT: unknown (warning)
      CONFIG_IP6_NF_IPTABLES: IP6 tables support: module (pass)
        CONFIG_IP6_NF_FILTER: Packet filtering: module (pass)
        CONFIG_IP6_NF_MANGLE: Packet mangling: module (pass)
        CONFIG_IP6_NF_NAT: ip6tables NAT support: module (pass)
      CONFIG_NF_DEFRAG_IPV6: module (pass)
    CONFIG_BRIDGE: 802.1d Ethernet Bridging: module (pass)
      CONFIG_LLC: module (pass)
      CONFIG_STP: module (pass)
  CONFIG_EXT4_FS: The Extended 4 (ext4) filesystem: built-in (pass)
  CONFIG_PROC_FS: /proc file system support: built-in (pass)

### What happened?

After restoring，controller exec “k0s ctr version” can not get containerd server info 

### Steps to reproduce

1. install 
    executes `k0sctl apply --disable-telemetry -c k0sctl_deploy_tmp/k0sctl_deploy.yml` on k0sctl_node 

`
# k0sctl_deploy.yml
---
apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s-cluster
spec:
  hosts:
  - ssh:
      address: 192.168.122.144 
      user: root
      port: 22
      keyPath: /root/.ssh/id_ed25519
    role: controller+worker
    installFlags:
      - --no-taints
    uploadBinary: true
    k0sBinaryPath: "/root/桌面/k0s/issue_32_25/cloud-service-k0s-deploy/ansible/.k0s_dependencies/k0s"
    files:
      - name: bundle-file
        src: "/root/桌面/k0s/issue_32_25/cloud-service-k0s-deploy/ansible/.k0s_dependencies/k0s-airgap-bundle"
        dstDir: /var/lib/k0s/images/
        perm: 0666

  - ssh:
      address: 192.168.122.216  
      user: root
      port: 22
      keyPath: /root/.ssh/id_ed25519
    role: worker
    uploadBinary: true
    k0sBinaryPath: "/root/桌面/k0s/issue_32_25/cloud-service-k0s-deploy/ansible/.k0s_dependencies/k0s"
    files:
      - name: bundle-file
        src: "/root/桌面/k0s/issue_32_25/cloud-service-k0s-deploy/ansible/.k0s_dependencies/k0s-airgap-bundle"
        dstDir: /var/lib/k0s/images/
        perm: 0666

  - ssh:
      address: 192.168.122.46  
      user: root
      port: 22
      keyPath: /root/.ssh/id_ed25519
    role: worker
    uploadBinary: true
    k0sBinaryPath: "/root/桌面/k0s/issue_32_25/cloud-service-k0s-deploy/ansible/.k0s_dependencies/k0s"
    files:
      - name: bundle-file
        src: "/root/桌面/k0s/issue_32_25/cloud-service-k0s-deploy/ansible/.k0s_dependencies/k0s-airgap-bundle"
        dstDir: /var/lib/k0s/images/
        perm: 0666

  k0s:
    version: v1.25.2+k0s.0
    dynamicConfig: false

`

2. backup
    `k0s backup --save-path=/root`

3. restore 
  `
root@k0s-master:/var/lib/k0s#  k0s stop
root@k0s-master:/var/lib/k0s#  mv etcd etcd-bak
root@k0s-master:/var/lib/k0s# k0s restore /root/k0s_backup_2022-11-25T10_59_15_000Z.tar.gz
root@k0s-master:/var/lib/k0s#  k0s start
`

4. test k0s containerd version
`
root@k0s-master:/var/lib/k0s# k0s ctr version
Client:
  Version:  1.6.8
  Revision: 9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
  Go version: go1.19.1

Error: failed to dial "/run/k0s/containerd.sock": context deadline exceeded: connection error: desc = "transport: error while dialing: dial unix:///run/k0s/containerd                         .sock: timeout"
Usage:
  k0s ctr [flags]

Flags:
  -h, --help   help for ctr

root@k0s-master:/var/lib/k0s# 
`

### Expected behavior

`
root@k0s-master:~# k0s ctr version
Client:
  Version:  1.6.8
  Revision: 9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
  Go version: go1.19.1

Server:
  Version:  1.6.8
  Revision: 9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
  UUID: 4e85d06f-822b-4514-acee-fe54b79c8593
root@k0s-master:~#

`

### Screenshots and logs
`journalctl -u k0scontroller `
[journalctl.log](https://github.com/k0sproject/k0s/files/10111607/journalctl.log)

**Comment by juanluisvaladas** [comment]
@ling1042133624 I believe I found the issue. I at some point a directory called `/var/lib/k0s/images/images` during `k0s retore` and this provokes some error during the startup. 

I'm not done with the investigation but I believe removing  `/var/lib/k0s/images/images` and restarting the k0scontroller service should fix it:

```
# k0s restore /root/backup/k0s_backup_2022-11-30T15_44_19_000Z.tar.gz
root@k0saio:/var/lib/k0s# rmdir /var/lib/k0s/images/images/
root@k0saio:/var/lib/k0s# k0s start
root@k0saio:/var/lib/k0s# k0s ctr version
Client:
  Version:  1.6.9
  Revision: 1c90a442489720eec95342e1789ee8a5e1b9536f
  Go version: go1.19.3

Server:
  Version:  1.6.9
  Revision: 1c90a442489720eec95342e1789ee8a5e1b9536f
  UUID: aee75713-ae5a-4d32-b136-41f5cf6eda51
```


Also it's pretty obvious that this directory is created by k0s restore checking the strace output.
```
root@k0saio:~# cat backup/restore.strace | grep var.lib.k0s.images
3129  execve("/usr/bin/cp", ["cp", "-r", "/tmp/k0s-backup4266984751/images", "/var/lib/k0s/images"], 0xc00053ec30 /* 29 vars */) = 0
3129  newfstatat(AT_FDCWD, "/var/lib/k0s/images", {st_mode=S_IFDIR|0755, st_size=4096, ...}, 0) = 0
3129  newfstatat(AT_FDCWD, "/var/lib/k0s/images/images", 0x7ffe032f2330, AT_SYMLINK_NOFOLLOW) = -1 ENOENT (No such file or directory)
3129  mkdir("/var/lib/k0s/images/images", 0755) = 0
3129  newfstatat(AT_FDCWD, "/var/lib/k0s/images/images", {st_mode=S_IFDIR|0755, st_size=4096, ...}, AT_SYMLINK_NOFOLLOW) = 0
```

I just don't know where in the code just yet.

**Comment by juanluisvaladas** [comment]
I'm adding another comment for the future in case someone hits this in the future.

While writing the tests for my patch I just realized that restore of every FileSystemStep is broken. The affected paths are:
- /var/lib/k0s/pkis gets restored to /var/lib/k0s/pkis/pkis
- /var/lib/k0s/manifests gets restored to /var/lib/k0s/manifests/manifest
- /var/lib/k0s/images gets restored to /var/lib/k0s/images/images
- /var/lib/k0s/helm  gets restored to /var/lib/k0s/helm/helm

The good news is that the data is actually there and the problem is only with the restore. To fix the restore quite simply move the contents of these directories into their parent directory and make sure to remove /var/lib/k0s/images/images. This will be patched soon.
