### ISSUE TITLE
Remove command line configs for CNI no longer in scope for kubelet in Windows

### ISSUE THREAD

**Issue by wizpresso-steve-cy-fan** [k0sproject/k0s#2460]
### Before creating an issue, make sure you've checked the following:

- [X] You are running the latest released version of k0s
- [X] Make sure you've searched for existing issues, both open and closed
- [X] Make sure you've searched for PRs too, a fix might've been merged already
- [X] You're looking at docs for the released version, "main" branch docs are usually ahead of released versions.

### Platform

```shell
Windows
```

### Sysinfo

<details><summary>`k0s sysinfo`</summary>
```text
➡️ Please replace this text with the output of `k0s sysinfo`. ⬅️
```
</details>

### What happened?

> Prior to Kubernetes 1.24, the CNI plugins could also be managed by the kubelet using the cni-bin-dir and network-plugin command-line parameters. These command-line parameters were removed in Kubernetes 1.24, with management of the CNI no longer in scope for kubelet.
> 
> See [Troubleshooting CNI plugin-related errors](https://kubernetes.io/docs/tasks/administer-cluster/migrating-from-dockershim/troubleshooting-cni-plugin-related-errors/) if you are facing issues following the removal of dockershim.

But under Windows:
https://github.com/k0sproject/k0s/blob/fba695b9e8a760f107f8bea0a32d217397cbda81/pkg/component/worker/kubelet.go#L172-L179

but because of:
```
 args["--network-plugin"] = "cni"
 args["--cni-bin-dir"] = "C:\\k\\cni" 
```
This contradicts the new changes made in Kubernetes and thus results in Windows worker not working at all in crash loop.

The obvious workaround is to downgrade the cluster before this change came in effect, but it is not possible for an existing cluster to downgrade. A new cluster to specify the last K8S version without that specific change has the be scaffolded instead.

### Steps to reproduce

1. Install Docker Desktop
2. Use Windows Container
3. Install k0s
4. Install a worker

### Expected behavior

It works

### Actual behavior

It's not okay. Downgrading to 1.23.8 doesn't work for a 1.25.4 master either

**Comment by jnummelin** [comment]
What is the issue actually, hard to decipher :)

**Comment by wizpresso-steve-cy-fan** [comment]
@jnummelin I haven't write the title right, my apologies. 
Removing these two lines should be the first step to restoring Windows worker support in k0s. I think that would be a long way to go however.
