### ISSUE TITLE
Documentation inconsistency: single binary vs. airgap image bundle

### ISSUE THREAD

**Issue by aceeric** [k0sproject/k0s#2465]
### Before creating an issue, make sure you've checked the following:

- [X] You are running the latest released version of k0s
- [X] Make sure you've searched for existing issues, both open and closed
- [X] Make sure you've searched for PRs too, a fix might've been merged already
- [X] You're looking at docs for the released version, "main" branch docs are usually ahead of released versions.

### Platform

```shell
n/a
```

### Version

v1.25.4+k0s.0

### Sysinfo

n/a

### What happened?

All - [this page](https://docs.k0sproject.io/v1.25.4+k0s.0/) says "k0s is distributed as a single binary...", but the [airgapped install](https://docs.k0sproject.io/v1.25.4+k0s.0/airgap-install/) instructions say "...Airgap installation requires an image bundle, which contains all the needed container images..."

When you say "k0s is distributed as a single binary" it makes one think that all the Kubernetes components - controller manager, api server, kubelet, etc. are embedded in that single binary.

So these two assertions seem contradictory. That fact that the image bundle is required in an air-gapped install suggests that the non air-gapped install is using an OCI registry to pull additional images and would fail if the registry were not available.

### Steps to reproduce

n/a

### Expected behavior

n/a

### Actual behavior

n/a

### Screenshots and logs

n/a

### Additional context

n/a

**Comment by jnummelin** [comment]
> That fact that the image bundle is required in an air-gapped install suggests that the non air-gapped install is using an OCI registry to pull additional images and would fail if the registry were not available.

This is correct interpretation.

We need to be bit more exact on the docs, hence labeling as docs issue.

**Comment by kke** [comment]
Could we build the `airgap-bundle` so that it includes k0s too? So you would have "k0s for internet-enabled environments" and "a bigger k0s for airgapped environments"?

**Comment by jnummelin** [comment]
@kke you mean we bigger "version" would be the usual k0s bin but with additionally bundled images too in it? Which it could somehow detect being there and can extract by itself?

**Comment by lchunleo** [comment]
Can I understand how the k0s and the image bundle work together in the air gap environment? There seem no information how to use them together in the air gap environment other than downloaded them
