### ISSUE TITLE
request for comments: improve cross-component dependencies in the component manager

### ISSUE THREAD

**Issue by mikhail-sakhnov** [k0sproject/k0s#2551]
### Is your feature request related to a problem? Please describe.

Some of k0s internal components have natural dependency between each other. The majority of those are just covered by eventually consistent nature of the bootstrap process.

But there is some minor set of components which have ad-hoc explicit wait for:
- extension controller waits for CRD registration
- oci bundle controller waits for containerd be ready
- once in a while we have issue with not applying rbac correctly
- probably something else

### Describe the solution you would like

It would be awesome, if ComponentManager had a way to enforce deps between components. While implementation of dependencies itself is not that hard, the important note to keep in mind is that 90% of components do not need to wait for any deps and the desire is to keep code for those components unchanged. 

My suggestion is to change component manager interface from current (pseudocode)
```
//In the code snippets I intentionally skip all other methods of CM which are not related to the context of the rfc
Add(ctx, component) 
```

to 

```

type handleID uint

Add(ctx, component)
Register(ctx, component) handleID
EnforceDeps(handleID, handleID)
```

where the Register is equal to the current Add implementation with the only difference that Register returns some handle id, which in a sense, semantically act as a file descriptor or any kind of a resource descriptor. With a current implementation it might be just an index for cm.Components slice which tracks all registered components.
The add will be as simple as calling Register while ignoring return result.

The EnforceDeps accepts two handleIDs and ensures dependency between component A and component B (A is waiting for B, naming could be revisited to make it more clear).

Later, we have in CM following methods:

```
Init(ctx) error
Start(ctx) error
```

To ensure the deps we can re-sort the slice of components (cm.Components) in the required order according to the calls of EnforceDeps, either on each call of EnforceDeps or only once, before calling Start first time, the exact details are not important in the context of the issue.

With that approach we can leave 90% of the components as is, not even touching it. As an addition, the necessity to have both components handle id to ensure dependency will nature limit us to keep logically coupled in the same scope.
The example of a usage might look like (modified `cmd/worker/worker.go`):

```
	componentManager := manager.New(pr)
	if runtime.GOOS == "windows" && c.CriSocket == "" {
		return fmt.Errorf("windows worker needs to have external CRI")
	}
        var containerIDHandle = undefinedHandleID // some guard value, for example -1

	if c.CriSocket == "" {
		containerIDHandle = componentManager.Register(ctx, &worker.ContainerD{
			LogLevel: c.Logging["containerd"],
			K0sVars:  c.K0sVars,
		})
	}

	ociBundleHandleID := componentManager.Add(ctx, worker.NewOCIBundleReconciler(c.K0sVars))
	if c.WorkerProfile == "default" && runtime.GOOS == "windows" {
		c.WorkerProfile = "default-windows"
	}

	kubeletHandleID := componentManager.Add(ctx, &worker.Kubelet{
		CRISocket:           c.CriSocket,
		EnableCloudProvider: c.CloudProvider,
		K0sVars:             c.K0sVars,
		KubeletConfigClient: kubeletConfigClient,
		LogLevel:            c.Logging["kubelet"],
		Profile:             c.WorkerProfile,
		Labels:              c.Labels,
		Taints:              c.Taints,
		ExtraArgs:           c.KubeletExtraArgs,
		IPTablesMode:        c.WorkerOptions.IPTablesMode,
	})

        cm.EnforceDeps(ociBundleHandleID, containerIDHandle)
        cm.EnforceDeps(kubeletHandleID, containerIDHandle)
```

### Describe alternatives you've considered

The explicit registration with a given name like:

```
Add(ctx, name, component)
```

The downside is that we need to change a lot of components registration and introduce unused entity

Another option would be to avoid changing component manager at all. The components which require any dependencies should have those dependencies as fields and explicitly wait for them in Start method. 

For example, the example above might be changed as:
```
	componentManager := manager.New(pr)
	if runtime.GOOS == "windows" && c.CriSocket == "" {
		return fmt.Errorf("windows worker needs to have external CRI")
	}
        var containerIDHandle = undefinedHandleID // some guard value, for example -1
       var containerDComponent Component
	if c.CriSocket == "" {
		containerDComponent = componentManager.Register(ctx, &worker.ContainerD{
			LogLevel: c.Logging["containerd"],
			K0sVars:  c.K0sVars,
		})
	} else {
            containerDComponent = newStubComponent() // mock component which always ready
       }

	ociBundleHandleID := componentManager.Add(ctx, worker.NewOCIBundleReconciler(c.K0sVars, containerDComponent))
	if c.WorkerProfile == "default" && runtime.GOOS == "windows" {
		c.WorkerProfile = "default-windows"
	}

        kubeletComp := &worker.Kubelet{
		CRISocket:           c.CriSocket,
		EnableCloudProvider: c.CloudProvider,
		K0sVars:             c.K0sVars,
		KubeletConfigClient: kubeletConfigClient,
		LogLevel:            c.Logging["kubelet"],
		Profile:             c.WorkerProfile,
		Labels:              c.Labels,
		Taints:              c.Taints,
		ExtraArgs:           c.KubeletExtraArgs,
		IPTablesMode:        c.WorkerOptions.IPTablesMode,
                ContainerDComponent: containerDComponent,
	}
	componentManager.Add(ctx, kubeletComp)
```

the Start methods of kubelet and or oci bundle components might look like

```


// Run runs kubelet
func (k *Kubelet) Start(ctx context.Context) error {
        if err := manager.WaitForReady(k.containerD); err != nil {
                return fmt.Errorf("containerd is required for kubelet component but not ready")
       }
        // the rest goes as is
	cmd := "kubelet"

	kubeletConfigData := kubeletConfig{
		ClientCAFile:       filepath.Join(k.K0sVars.CertRootDir, "ca.crt"),
		VolumePluginDir:    k.K0sVars.KubeletVolumePluginDir,
		KubeReservedCgroup: "system.slice",
		KubeletCgroups:     "/system.slice/containerd.service",
	}
	if runtime.GOOS == "windows" {
		cmd = "kubelet.exe"
	}
}
```

The main pro is the simplicity. Though we might have issues if a component would not be created and started in a correct order.

**Comment by jnummelin** [comment]
We can probably implement much of this using some DI framework.
