### ISSUE TITLE
`make docs-serve-dev` tries to use nonexistent container image

### ISSUE THREAD

**Issue by mhutter** [k0sproject/k0s#2642]
### Before creating an issue, make sure you've checked the following:

- [X] You are running the latest released version of k0s
- [X] Make sure you've searched for existing issues, both open and closed
- [X] Make sure you've searched for PRs too, a fix might've been merged already
- [X] You're looking at docs for the released version, "main" branch docs are usually ahead of released versions.

### Platform

```shell
n/a
```

### Version

main branch

### Sysinfo

-

### What happened?

The docs cannot be built/served because `make` tries to pull an image tag that does not exist.

### Steps to reproduce

    make clean
    make docs-serve-dev

### Expected behavior

Docs being served

### Actual behavior

Error message from `docker build` command

### Screenshots and logs

```
make[1]: Entering directory '/home/user/dev/k0s/docs'
docker build \
  --build-arg PYTHON_IMAGE_VERSION=3.10.5-alpine3.17 \
  -t 'k0sdocs.docker-image.serve-dev' -f 'Dockerfile.serve-dev' .
Sending build context to Docker daemon  6.144kB
Step 1/11 : ARG PYTHON_IMAGE_VERSION
Step 2/11 : FROM python:${PYTHON_IMAGE_VERSION} as builder
manifest for python:3.10.5-alpine3.17 not found: manifest unknown: manifest unknown
```

### Additional context

`make` constructs the `$PYTHON_IMAGE_VERSION` variable based on values from `docs/Makefile.variables`.

```
...
alpine_version = 3.17
...
python_version = 3.10.5
...
```

This results in a value of `3.10.5-alpine3.17`.... which [does not exist](https://hub.docker.com/_/python/tags?page=1&name=3.10.5-alpine)

**Comment by mhutter** [comment]
Workaround: Adjust `docs/Makefile.variables` to a version that does exist.

Possible permanent fix: Remove `$(alpine_version)` entirely from docs-related make tasks. I don't think it matters too much, as long as the Python version is correct.

**Comment by twz123** [comment]
Thanks @mhutter, good catch! The CI missed this one.
