### ISSUE TITLE
Feature gate ServiceInternalTrafficPolicy is GA

### ISSUE THREAD

**Issue by twz123** [k0sproject/k0s#2645]
### Before creating an issue, make sure you've checked the following:

- [X] You are running the latest released version of k0s
- [X] Make sure you've searched for existing issues, both open and closed
- [X] Make sure you've searched for PRs too, a fix might've been merged already
- [X] You're looking at docs for the released version, "main" branch docs are usually ahead of released versions.

### Platform

```shell
N/A
```

### Version

main

### Sysinfo

<details><summary>`k0s sysinfo`</summary>
N/A
</details>

### What happened?

API Server logs a notice about the removal of the GA feature gate ServiceInternalTrafficPolicy:

> Setting GA feature gate ServiceInternalTrafficPolicy=true. It will be removed in a future release.

### Steps to reproduce

Launch a k0s controller and watch the logs.

### Expected behavior

k0s doesn't use this feature flag any more.

### Actual behavior

k0s doesn't uses this feature flag.

### Screenshots and logs

See above.

### Additional context

It has been introduced in #1287.

**Comment by mikhail-sakhnov** [comment]
As discussed: I am going to introduce new config section to enable features-gate through config file, without manually building the extra-args. 

This will also touch the #2693 issue.

**Comment by twz123** [comment]
I believe this has been fixed as part of #2987.
