### ISSUE TITLE
IPv6 / dual stack integration testing

### ISSUE THREAD

**Issue by twz123** [k0sproject/k0s#2653]
There's currently no proper IPv6 / dual stack support in the k0s integration test suite. This is not ideal, as k0s explicitly supports dual stack. The current `dualstack` integration test only checks that k0s passes the correct flags to the components involved, but doesn't verify that the networking is actually operational in any way.

The upcoming kube-router major release adds support for dual stack, so both CNI implementations natively supported by k0s are now IPv6-enabled. Might be a good time to actually add some proper test coverage for these setups.

There's some challenges, though:

* Docker needs to be setup for IPv6.
* Footloose might need some more patches to support IPv6 as well.

Other things TBD:

* Configure k0s's footloose container accordingly
* Maybe find a way to extend `FootlooseSuite` and friends to select the mode (v4/v6/dual)

**Comment by martencassel** [comment]
What kind of integration tests would be required for covering dualstack ? 

Would enabling IPv6 support int the docker daemon like so
   "ipv6": true,"fixed-cidr-v6": "2001:db8:1::/64"
be enough for such a test ?

**Comment by twz123** [comment]
> What kind of integration tests would be required for covering dualstack ?

We [already have](https://github.com/k0sproject/k0s/blob/v1.26.0%2Bk0s.0/inttest/dualstack/dualstack_test.go) a "test" for dual stack, but this merely checks if k0s passes the right args to its components. We'd need to have some tests that actually probe IPv6 connectivity. The current tests don't do that because it's not expected to work in the current test setup anyway.

> Would enabling IPv6 support in https://docs.docker.com/config/daemon/ipv6/ be enough for such a test ?

That's basically the first bullet point. The other bullet points may require a solution as well.
