### ISSUE TITLE
OS dependencies not working as expected due to busybox

### ISSUE THREAD

**Issue by mbentley** [k0sproject/k0s#267]
While something like Alpine Linux may or may not be in scope, I noticed that `find` and `du` in busybox do not have the required flags that are being used.  There is also a dependency to have `iptables` from the host.  It is easy enough to install the necessary packages (`coreutils` `findutils` `iptables`) but I am not sure if this is a concern or not and I wanted to mention it in case we are looking to remove more dependencies from the host OS.

I found the specific errors by combing through the exit codes from the `mke server` binary logs with a `| grep "exit " | grep -v "exit code 0"'`

**Comment by jnummelin** [comment]
Closing this as we've created further more detailed issues to address the topics
