### ISSUE TITLE
Route all traffic to and between workers through SSH

### ISSUE THREAD

**Issue by emchristiansen** [k0sproject/k0s#2678]
### Is your feature request related to a problem? Please describe.

I have machines which I'd like to use as worker nodes, but I don't have the rights to open ports and I'm basically limited to SSH (port 22) access.

### Describe the solution you would like

It would be great if all communication to and between workers could be routed through SSH connections.
(I can run the controllers on machines where I can open ports.)

[This document](https://docs.k0sproject.io/v1.21.3+k0s.0/networking/) suggests this is partially done via Konnectivity and reverse SSH tunnels, but the chart at the end makes it seem like other ports might also be required (could you please clarify?).

### Additional context

See this DevOps question:
https://devops.stackexchange.com/questions/17356/how-to-run-kubernetes-workers-on-machines-with-very-few-open-ports-that-i-dont

**Comment by jnummelin** [comment]
> I have machines which I'd like to use as worker nodes, but I don't have the rights to open ports and I'm basically limited to SSH (port 22) access.

So the worker nodes cannot connect to each others on any other port than 22?

Can your worker nodes get connections to outside world?

In general the networking components (CNI) we support cannot AFAIK "tunnel" via SSH like you suggest. In general the issue is that SSH tunnels are always point-to-point and thus cannot be used as generic network layer as such. You'd need to have something on top that does the "routing".

The only "trick" that comes to my mind is to connect the worker nodes to some VPN like network (if they can connect to external services), [Tailscale](https://tailscale.com/) for example. Tailscale creates a VPN "mesh" between the workers (and controllers if you wish) and assigns IPs from `100.64.0.0/10` pool which you could use as the connections between nodes.

This does impose some potential challenges:
- latency: worker node traffic might route via "internet" (encrypted of course). also there's now three layers of networking: underlay (the real network on the machines) + Tailscale + CNI
- reliability: I'm not too familiar with this aspect of Tailscale


The konnectivity setup in k0s does solve this only in the controller-worker comms part. With konnectivity k0s workers establish tunnels (gRPC with TLS) to controllers which the controller can use as "reverse tunnels".

**Comment by emchristiansen** [comment]
Thanks for that tip, Tailscale seems like a really useful tool!

Even with Tailscale, though, I'm getting a timeout in the "validating api connection" part of the `apply` command:

![Screenshot 2023-02-03 at 10 43 54 AM](https://user-images.githubusercontent.com/225668/216659623-d7199296-d00b-4dff-8601-2f2389c808e9.png)

It looks like `k0s` is grabbing the "real" private IP address of the controller (`172.31.2.241`), when I actually want it to use its Tailscale address for everything (right?).
Is this something I can force in `k0s`?

Here is my config:

![Screenshot 2023-02-03 at 10 45 42 AM](https://user-images.githubusercontent.com/225668/216661227-a4eb8f25-a212-4146-b046-052bcc2e2a96.png)

Here's the relevant part from my log file:

![Screenshot 2023-02-03 at 10 55 24 AM](https://user-images.githubusercontent.com/225668/216661587-a69927df-5015-4919-9d1c-14b30b48c22f.png)

**Comment by jnummelin** [comment]
Try with something like this:
```
apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s-cluster
spec:
  hosts:
  - ssh:
      address: 1.2.3.4 # VM in public cloud
      user: root
    role: controller
    privateInterface: tailscale0
  - ssh:
      address: 192.168.205.4 # machine running on Multipass VM
      user: ubuntu
    role: worker
    privateInterface: tailscale0
```

There's ongoing discussion at k0sctl repo side on this too: https://github.com/k0sproject/k0sctl/issues/456

**Comment by emchristiansen** [comment]
Thank you so much, it seems to work!

BTW, I couldn't find the schema for the `kind: Cluster` config anywhere, not even in the code*.
Could y'all add it to the documentation?
(Even a link to the source code that defines it would be super helpful.)

*I just grepped this repo for "privateInterface" and found nothing.

**Comment by twz123** [comment]
Some links to the things you were looking for:

The k0s cluster config options are covered in the docs here: https://docs.k0sproject.io/v1.26.0+k0s.0/configuration/

The sources are here: https://github.com/k0sproject/k0s/tree/v1.26.0%2Bk0s.0/pkg/apis/k0s.k0sproject.io/v1beta1

The privateInterface is a k0sctl setting: https://github.com/k0sproject/k0sctl/tree/v0.15.0#spechostsprivateinterface-string-optional-default-

Hope that helps.

**Comment by pschichtel** [comment]
Btw SSH also allows creating routable tunnels using its `-w` option.

**Comment by jnummelin** [comment]
> Btw SSH also allows creating routable tunnels using its -w option.

Oh, didn't know that. I've always thought it can only do "port-to-port" tunneling. Any nice tutorials you know of how this could be used in cases like this?

**Comment by juanluisvaladas** [comment]
It's worth mentioning that tunneling TCP over TCP has terrible performance in both bandwidth and latency
is generally considered a bad idea (specially read the references 7 and 8 regarding the TCP meltdown): https://en.wikipedia.org/wiki/Tunneling_protocol#Secure_Shell_tunneling

If it works it's fine, but if the connection is unstable you'll run into problems and if you stress the connection you are extremely likely to run into problems.

**Comment by emchristiansen** [comment]
@juanluisvaladas, do you know if that applies to Tailscale (which uses WireGuard)?
Here's an informal benchmark I found of WireGuard:
https://www.reddit.com/r/linux/comments/9bnowo/wireguard_benchmark_between_two_servers_with_10/

**Comment by emchristiansen** [comment]
What is the relationship, if any, between a `kind: Cluster` and a `kind: ClusterConfig`? Can I supply a `kind: ClusterConfig` to `k0s apply`, or do I need to manually SSH into the controllers to change their `kind: ClusterConfig`s?

**Comment by juanluisvaladas** [comment]
@emchristiansen I'm not familiar with Tailscale, if Tailscale encapsulates wireguard over TCP using something like udptunnel then it will have the same problems. Wireguard by itself [doesn't allow tunneling over TCP 
](https://www.wireguard.com/known-limitations/) so benchmarks if tailscape is tunneling it over TCP it the benchmarks that you may find are invalid.

**Comment by twz123** [comment]
> What is the relationship, if any, between a `kind: Cluster` and a `kind: ClusterConfig`? Can I supply a `kind: ClusterConfig` to `k0s apply`, or do I need to manually SSH into the controllers to change their `kind: ClusterConfig`s?

There's no such thing as `k0s apply`, you probably mean `k0sctl apply`. It's important to note that there's two distinct tools: `k0s` and `k0sctl`. The latter (`k0sctl`) is used to deploy `k0s` onto a set of machines to form a Kubernetes cluster via [remote access](https://github.com/k0sproject/rig#protocols). The ClusterConfig CRD is part of k0s and controls most of k0s's node and cluster related options (a few are solely accessible via CLI flags). The Cluster CRD is part of k0sctl. It [embeds](https://github.com/k0sproject/k0sctl/tree/v0.15.0#speck0sconfig-mapping-optional-default-auto-generated) a ClusterConfig in its `spec.k0s.config` field. That config is then copied to the machines (listed in the `spec.hosts` array in k0sctl's Cluster CRD).

So you don't need to manually SSH into the machines to distribute the ClusterConfig, k0sctl will do it for you.

**Comment by emchristiansen** [comment]
@twz123 Thank you, that makes sense! I've replied in [this related issue](https://github.com/k0sproject/k0s/issues/2719).
