### ISSUE TITLE
Document how to enable Kubernetes API in alpha stage 

### ISSUE THREAD

**Issue by acollign** [k0sproject/k0s#2693]
### Is your feature request related to a problem? Please describe.

The v1.26  release note advertises new APIs in alpha stage but does not link to a document describing how to enable them.

https://www.mirantis.com/blog/k0s-1-26-released

### Describe the solution you would like

It would be awesome to document how to enable alpha stage features. As far as I understand, the following steps are required:
- enable ValidatingAdmissionPolicy feature gate
- enable admissionregistration.k8s.io/v1alpha1 API

Reference: https://github.com/douglasmakey/k8s-validating-admission-policy#testing-k8s-126-locally

### Describe alternatives you've considered

For the time being, I will just use microk8s as documented by https://github.com/douglasmakey/k8s-validating-admission-policy#testing-k8s-126-locally. I am eager to test the same on k0s!

**Comment by acollign** [comment]
I've found a way to enable the ValidatingAdmissionPolicy feature, not sure if it is idiomatic though. It is possible to add extra arguments to the api-server. The following snippet will enable the feature gate and the API.

        extraArgs:
          feature-gates: ValidatingAdmissionPolicy=true
          runtime-config: admissionregistration.k8s.io/v1alpha1=true

https://docs.k0sproject.io/v1.23.5+k0s.0/configuration/#specapi

**Comment by jnummelin** [comment]
Yes, that is the way to add any extra configs to api-server. Maybe we should have some examples like this in the docs for the `spec.api.extraArgs` definition.

**Comment by acollign** [comment]
Thanks @jnummelin!
