### ISSUE TITLE
Make it possible to run k0s with only the kernel as a dependency

### ISSUE THREAD

**Issue by phroggyy** [k0sproject/k0s#271]
As MKE should be able to run on any Linux kernel, we don't want any hard dependencies. Currently, the `kubelet` has some hard dependencies, as documented in https://github.com/Mirantis/mke/blob/main/docs/internal/host-dependencies.md.

We should aim to remove all non-kernel dependencies, either through bundling more things into mke or, preferably, contribute to upstream where possible to remove those dependencies.

Spawned from #176

**Comment by ncopa** [comment]
the kubernetes/kubernetes#96115 has been merged upstream which means that with kubernetes 1.22 we only need iptables.
