### ISSUE TITLE
Please provide more detailed instructions for using a configuration file when using `k0sctl`

### ISSUE THREAD

**Issue by emchristiansen** [k0sproject/k0s#2719]
### Is your feature request related to a problem? Please describe.

I'd like to switch to Calico for networking, but [the instructions here](https://docs.k0sproject.io/v1.26.1+k0s.0/configuration/) either don't work or aren't complete.

### Describe the solution you would like

Please provide a clearer explanation of what we're supposed to do.

E.g., assume I'm using `k0sctl apply --config k0sctl.yaml` to create the cluster [as described here](https://docs.k0sproject.io/v1.26.1+k0s.0/k0sctl-install/).
At what point should I modify the configuration file?
Do I need to SSH into each controller machine so I can edit the local `/etc/k0s/k0s.yaml` files?
Do I then run the `stop` and `start` commands on each controller?

Is there any way to provide a custom configuration _without_ manually logging into each controller machine?
If so, how?

**Comment by twz123** [comment]
> I'd like to switch to Calico for networking, but [the instructions here](https://docs.k0sproject.io/v1.26.1+k0s.0/configuration/) either don't work or aren't complete.

What configuration did you actually try out and what happened? You need to set [`spec.network.provider`](https://docs.k0sproject.io/v1.26.1+k0s.0/configuration/#specnetwork) to `calico`. The settings for calico are documented below the section for [`spec.network.calico`](https://docs.k0sproject.io/v1.26.1+k0s.0/configuration/#specnetworkcalico).

Note that switching the CNI for an already deployed cluster is [not supported](https://docs.k0sproject.io/v1.26.1+k0s.0/networking/?h=notes#notes) by k0s. This is a setting that needs to be set when deploying the initial cluster. See also https://github.com/k0sproject/k0s/issues/2712#issuecomment-1423774791.

> Please provide a clearer explanation of what we're supposed to do.

When using k0sctl, the k0s configuration is embedded in k0sctl's configuration. So all the [k0s configuration options](https://docs.k0sproject.io/v1.26.1+k0s.0/configuration/#configuration-file-reference) go into the [k0sctl.yaml file](https://github.com/k0sproject/k0sctl/tree/v0.15.0#configuration-file) below the [`spec.k0s.config`](https://github.com/k0sproject/k0sctl/tree/v0.15.0#speck0sversion-string-optional-default-auto-discovery) field.

> At what point should I modify the configuration file?

Before running [`k0sctl apply`](https://github.com/k0sproject/k0sctl/tree/v0.15.0#k0sctl-apply).

> Do I need to SSH into each controller machine so I can edit the local /etc/k0s/k0s.yaml files?

k0sctl will do this once for you when you first deploy the cluster using `k0sctl apply`.

> Do I then run the stop and start commands on each controller?

k0sctl will currently only restart k0s in case of cluster upgrades, i.e. when a newer k0s version shall be deployed. There's a k0s feature called [dynamic configuration](https://docs.k0sproject.io/v1.26.1+k0s.0/dynamic-configuration/), though. This allows for configuration changes to an already deployed cluster. The ClusterConfig CRD is then stored in the cluster and may be altered via the Kubernetes API, e.g. by using `kubectl -n kube-system edit clusterconfig k0s`. Yo can enable dynamic configuration for a cluster by setting [`spec.k0s.dynamicConfig`](https://github.com/k0sproject/k0sctl/tree/v0.15.0#speck0sdynamicconfig-boolean-optional-default-false) to `true` in your k0sctl configuration.

**Comment by emchristiansen** [comment]
Thanks, [the README for `k0sctl`](https://github.com/k0sproject/k0sctl) made it all click into place.

I think you can ignore all my previous questions, but I suggest you link to the `k0sctl` README in the [Configuration Options page](https://docs.k0sproject.io/v1.26.1+k0s.0/configuration/), with a note that says something like:

>  `k0sctl` can deploy your configuration options at cluster creation time. Your options should go in the `k0s.config` section of the config. See the `k0sctl` README for more documentation of the options.

I might also explain why the config has `kind: ClusterConfig` [here](https://docs.k0sproject.io/v1.26.1+k0s.0/configuration/#configuration-file-reference), but `kind: Cluster` in `k0s.config` in [the README here](https://github.com/k0sproject/k0sctl).

**Comment by twz123** [comment]
> I might also explain why the config has `kind: ClusterConfig` [here](https://docs.k0sproject.io/v1.26.1+k0s.0/configuration/#configuration-file-reference), but `kind: Cluster` in `k0s.config` in [the README here](https://github.com/k0sproject/k0sctl).

Ooooh, that might actually be a bug in k0sctl's README. I'm just so used to it that I simply overlooked that :eyes:. Can you maybe confirm, @kke?

**Comment by kke** [comment]
Yes. It used to be `kind: Cluster` in k0s too. I'll fix it in the k0sctl readme.
