### ISSUE TITLE
"k0s config validate" does not use the config flag

### ISSUE THREAD

**Issue by kke** [k0sproject/k0s#2791]
### Before creating an issue, make sure you've checked the following:

- [X] You are running the latest released version of k0s
- [X] Make sure you've searched for existing issues, both open and closed
- [X] Make sure you've searched for PRs too, a fix might've been merged already
- [X] You're looking at docs for the released version, "main" branch docs are usually ahead of released versions.

### Platform

```shell
Any
```

### Version

main

### Sysinfo

<details><summary>`k0s sysinfo`</summary>
```text
---
```
</details>

### What happened?

The `k0s config validate` command uses:

```go
loadingRules := config.ClientConfigLoadingRules{K0sVars: c.K0sVars}
_, err := loadingRules.ParseRuntimeConfig()
```

This does not use the `--config` flag in any way. The command always tries to validate the default config.

### Steps to reproduce

1. create an invalid config: `echo "foofoo" > invalid.yaml`
2. run `k0s config validate -v -d invalid.yaml`
3. observe it checking a different config

### Expected behavior

It should validate the file (or stdin input) given in `--config`.

### Actual behavior

The config in default location is validated instead.

### Additional context

As noted in [the forums](https://forums.k8slens.dev/t/k0s-configuration-validation/153/6)

**Comment by mwoodpatrick** [comment]
Any updates on this issue?

**Comment by kke** [comment]
No updates, I'll take a look at it tomorrow.

**Comment by mwoodpatrick** [comment]
Running with k0s versionmv1.27.1+k0s.0 and doing:

```
echo "foofoo" > invalid.yaml
k0s config validate -v -d invalid.yaml
```

I'm getting:

```
DEBU[2023-05-19 11:39:54] runtime config found: using /run/k0s/k0s.yaml
DEBU[2023-05-19 11:39:54] Starting debug server                         debug_server=":6060"
DEBU[2023-05-19 11:39:54] runtime config found: using /run/k0s/k0s.yaml

```

**Comment by kke** [comment]
Yes. #3072 will eventually fix it.
