### ISSUE TITLE
I want to change `nodePortAddresses` of kube-proxy, but the parameter does not exist in k0s.yaml.

### ISSUE THREAD

**Issue by walkure** [k0sproject/k0s#2864]
### Is your feature request related to a problem? Please describe.

Currenlty, `nodePortAddresses` for kube-proxy is unchangeable `null`  at  kubeproxy.go  and not exposed to k0s.yaml 
https://github.com/k0sproject/k0s/blob/v1.26.2%2Bk0s.0/pkg/component/controller/kubeproxy.go#L280

Therefore I cannot change `nodePortAddresses` parameter at k0s.yaml. 

### Describe the solution you would like

Please make it possible to edit `nodePortAddresses` in k0s.yaml.

**Comment by sdemura** [comment]
Hi, we are evaluating switching from rke2 to k0s, but not being able to set nodePortAddresses is a non-starter for us.
