### ISSUE TITLE
`k0s config create` generates output with status section

### ISSUE THREAD

**Issue by mikhail-sakhnov** [k0sproject/k0s#2907]
### Before creating an issue, make sure you've checked the following:

- [X] You are running the latest released version of k0s
- [X] Make sure you've searched for existing issues, both open and closed
- [X] Make sure you've searched for PRs too, a fix might've been merged already
- [X] You're looking at docs for the released version, "main" branch docs are usually ahead of released versions.

### Sysinfo

<details><summary>`k0s sysinfo`</summary>
<pre>
➡️ Please replace this text with the output of `k0s sysinfo`. ⬅️
</pre>
</details>

### What happened?

`sudo ./k0s config create` generates the yaml with status key which is not required in the actual config.

### Steps to reproduce

1.
2.
3.

### Expected behavior

No `status` key

**Comment by kke** [comment]
Still relevant I suppose
