### ISSUE TITLE
arm v7 version not working

### ISSUE THREAD

**Issue by synoniem** [k0sproject/k0s#2926]
### Before creating an issue, make sure you've checked the following:

- [X] You are running the latest released version of k0s
- [X] Make sure you've searched for existing issues, both open and closed
- [X] Make sure you've searched for PRs too, a fix might've been merged already
- [X] You're looking at docs for the released version, "main" branch docs are usually ahead of released versions.

### Platform

```shell
Linux 5.15.84-v7+ #1613 SMP Thu Jan 5 11:59:48 GMT 2023 armv7l GNU/Linux
PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

### Version

v1.26.2+k0s.1

### Sysinfo

<details><summary>`k0s sysinfo`</summary>
<pre>
Machine ID: "dbd8a962f9c80c9241a52dbf066e606908cea3280e9d07c31d19ee500b13baf8" (from machine) (pass)
Total memory: 922.1 MiB (warning: 1.0 GiB recommended)
Disk space available for /var/lib/k0s: 4.5 GiB (pass)
Operating system: Linux (pass)
  Linux kernel release: 5.15.84-v7+ (pass)
  Max. file descriptors per process: current: 1048576 / max: 1048576 (pass)
  Executable in path: modprobe: /usr/sbin/modprobe (pass)
  /proc file system: mounted (0x9fa0) (pass)
  Control Groups: version 1 (pass)
    cgroup controller "cpu": available (pass)
    cgroup controller "cpuacct": available (pass)
    cgroup controller "cpuset": available (pass)
    cgroup controller "memory": available (pass)
    cgroup controller "devices": available (pass)
    cgroup controller "freezer": available (pass)
    cgroup controller "pids": available (pass)
    cgroup controller "hugetlb": unavailable (warning)
    cgroup controller "blkio": available (pass)
  CONFIG_CGROUPS: Control Group support: no kernel config found (warning)
  CONFIG_NAMESPACES: Namespaces support: no kernel config found (warning)
  CONFIG_NET: Networking support: no kernel config found (warning)
  CONFIG_EXT4_FS: The Extended 4 (ext4) filesystem: no kernel config found (warning)
  CONFIG_PROC_FS: /proc file system support: no kernel config found (warning)
</pre>
</details>

### What happened?

k0s does not actually start:
$ sudo k0s status
Error: status: can't do http request: /run/k0s/status.sock status

Generating a join token fails with the same error.

### Steps to reproduce

 Add to /boot/cmdline.txt:  cgroup_enable=cpuset cgroup_enable=memory cgroup_enable=pids cgroup_memory=1 systemd.unified_cgroup_hierarchy=0
$ export ETCD_UNSUPPORTED_ARCH=arm
$ sudo k0s install controller -e ETCD_UNSUPPORTED_ARCH=arm
$ sudo k0s start
$ sudo k0s status
Error: status: can't do http request: /run/k0s/status.sock status

### Expected behavior

sudo k0s status
Version: v1.26.2+k0s.1
Process ID: 436
Role: controller
Workloads: true
Init System: linux-systemd

### Actual behavior

$ sudo k0s status
Error: status: can't do http request: /run/k0s/status.sock status

### Screenshots and logs

$ sudo k0s kubectl logs
error: expected 'logs [-f] [-p] (POD | TYPE/NAME) [-c CONTAINER]'.
POD or TYPE/NAME is a required argument for the logs command
See 'k0s kubectl logs -h' for help and examples

**Comment by juanluisvaladas** [comment]
Hi @synoniem,  
My guess is that k0s isn't starting at all but we can't really tell without logs. Can you please gather:
1- systemctl status k0scontroller
2- journalctl -u k0scontroller --no-pager --since '10 minutes ago'
