### ISSUE TITLE
make lint does not include inttest

### ISSUE THREAD

**Issue by juanluisvaladas** [k0sproject/k0s#2940]
### Before creating an issue, make sure you've checked the following:

- [X] You are running the latest released version of k0s
- [X] Make sure you've searched for existing issues, both open and closed
- [X] Make sure you've searched for PRs too, a fix might've been merged already
- [X] You're looking at docs for the released version, "main" branch docs are usually ahead of released versions.

### Issue

I  believe we can all agree without much discussion that it's a good idea to lint inttest and that it could help preventing some bugs in the tests themselves.

I checked the linting and I don't think anyone would argue about most stuff but, but there are 2 lint errors I think will need some discussion:

```
inttest/common/footloosesuite.go:323:53: context-as-argument: context.Context should be the first parameter of a function (revive)
func (s *FootlooseSuite) cleanupSuite(t *testing.T, ctx context.Context) {
                                                    ^
inttest/common/footloosesuite.go:401:53: context-as-argument: context.Context should be the first parameter of a function (revive)
func (s *FootlooseSuite) dumpNodeLogs(t *testing.T, ctx context.Context, node, dir string) {
```

If we want linting there are two options here:
1- We make an exception and remove the argument `context-as-argument` for inttest
2- We change the function so that context.Context is the first argument,

The convention is [**MOST** functions that use a Context **SHOULD** accept it as their first parameter](https://github.com/golang/go/wiki/CodeReviewComments#contextsl) (emphasis is mine). 
This makes sense to me to some extent but at the same time I think testing.T should go before the Context. Besides the convention says most and should so I understand it's a bit open to interpretation.

Anyway I don't feel very strongly about either option.

Of course we can keep without linting the tests but honestly I think it would be a mistake.

**Comment by jnummelin** [comment]
hmm
```
func (s *FootlooseSuite) cleanupSuite(t *testing.T, ctx context.Context)
```
as the func is part of the `FootlooseSuite` does it even need the `t` as argument, shouldn't it be able to access it via the suite itself?

> We make an exception and remove the argument context-as-argument for inttest

Can't we disable that for these funcs only and not for entire inttest?

**Comment by juanluisvaladas** [comment]
> as the func is part of the FootlooseSuite does it even need the t as argument, shouldn't it be able to access it via the suite itself?

Oh that's true, s.T() should return it. We can just remove the argument in the call.

**Comment by twz123** [comment]
This was done on purpose, as suites can change the testing.T returned by s.T(), which would then break that logic.
