### ISSUE TITLE
Node Removal

### ISSUE THREAD

**Issue by Rohmilchkaese** [k0sproject/k0s#3064]
### Is your feature request related to a problem? Please describe.

Hi,

I'm just curious: is there being worked on, that it is possible to remove nodes ?
I saw it as a known limitation on the website.. 

This might be a key thing to get working. Only being able to scale up is kinda frustrating.. 

### Describe the solution you would like

Being able to also remove nodes

**Comment by twz123** [comment]
Does this answer your question? https://docs.k0sproject.io/v1.27.1+k0s.0/remove_controller/#remove-a-controller

**Comment by Rohmilchkaese** [comment]
@twz123 Thanks a lot ! Didn't see that - it does !
