### ISSUE TITLE
k0s sysinfo could output the filesystem type

### ISSUE THREAD

**Issue by ncopa** [k0sproject/k0s#3098]
### Is your feature request related to a problem? Please describe.

Would be good to know what filesystem type /var/lib/k0s is mounted on.

### Describe the solution you would like

`k0s sysinfo` could show the file system type of /var/lib/k0s

**Comment by twz123** [comment]
Do you have any specific use case in mind?

**Comment by ncopa** [comment]
IIRC the idea came from this: https://github.com/k0sproject/k0s/issues/3096#issuecomment-1542682774

Different filesystems may report used/available disk space differently.

**Comment by ncopa** [comment]
I wonder if it actually makes sense to let k0s sysinfo check filesystem type of `/var/lib/k0s` since datadir is configurable. Maybe it would be better to add something to the log at startup?

**Comment by twz123** [comment]
> I wonder if it actually makes sense to let k0s sysinfo check filesystem type of `/var/lib/k0s` since datadir is configurable. Maybe it would be better to add something to the log at startup?

The sysprobes are actually taking this into account already.
