### ISSUE TITLE
Content digest not found when pushing images with k0s ctr image push

### ISSUE THREAD

**Issue by jsalgado78** [k0sproject/k0s#3104]
### Before creating an issue, make sure you've checked the following:

- [X] You are running the latest released version of k0s
- [X] Make sure you've searched for existing issues, both open and closed
- [X] Make sure you've searched for PRs too, a fix might've been merged already
- [X] You're looking at docs for the released version, "main" branch docs are usually ahead of released versions.

### Platform

```shell
Probed on Red Hat Enterprise Linux 9.2 x86_64 and Red Hat Enterprise Linux 8.6 x86_64
```

### Version

v1.27.1+k0s.0

### Sysinfo

<details><summary>`k0s sysinfo`</summary>
<pre>
Machine ID: "14230b582d3f48455e84f0c2f8c38ad35d1e519fb226e8edf6a4d404d615cf96" (from machine) (pass)
Total memory: 963.4 MiB (warning: 1.0 GiB recommended)
Disk space available for /var/lib/k0s: 6.8 GiB (pass)
Operating system: Linux (pass)
  Linux kernel release: 5.14.0-284.11.1.el9_2.x86_64 (pass)
  Max. file descriptors per process: current: 65536 / max: 65536 (pass)
  Executable in path: modprobe: /usr/sbin/modprobe (pass)
  /proc file system: mounted (0x9fa0) (pass)
  Control Groups: version 2 (pass)
    cgroup controller "cpu": available (pass)
    cgroup controller "cpuacct": available (via cpu in version 2) (pass)
    cgroup controller "cpuset": available (pass)
    cgroup controller "memory": available (pass)
    cgroup controller "devices": available (assumed) (pass)
    cgroup controller "freezer": available (assumed) (pass)
    cgroup controller "pids": available (pass)
    cgroup controller "hugetlb": available (pass)
    cgroup controller "blkio": available (via io in version 2) (pass)
  CONFIG_CGROUPS: Control Group support: built-in (pass)
    CONFIG_CGROUP_FREEZER: Freezer cgroup subsystem: built-in (pass)
    CONFIG_CGROUP_PIDS: PIDs cgroup subsystem: built-in (pass)
    CONFIG_CGROUP_DEVICE: Device controller for cgroups: built-in (pass)
    CONFIG_CPUSETS: Cpuset support: built-in (pass)
    CONFIG_CGROUP_CPUACCT: Simple CPU accounting cgroup subsystem: built-in (pass)
    CONFIG_MEMCG: Memory Resource Controller for Control Groups: built-in (pass)
    CONFIG_CGROUP_HUGETLB: HugeTLB Resource Controller for Control Groups: built-in (pass)
    CONFIG_CGROUP_SCHED: Group CPU scheduler: built-in (pass)
      CONFIG_FAIR_GROUP_SCHED: Group scheduling for SCHED_OTHER: built-in (pass)
        CONFIG_CFS_BANDWIDTH: CPU bandwidth provisioning for FAIR_GROUP_SCHED: built-in (pass)
    CONFIG_BLK_CGROUP: Block IO controller: built-in (pass)
  CONFIG_NAMESPACES: Namespaces support: built-in (pass)
    CONFIG_UTS_NS: UTS namespace: built-in (pass)
    CONFIG_IPC_NS: IPC namespace: built-in (pass)
    CONFIG_PID_NS: PID namespace: built-in (pass)
    CONFIG_NET_NS: Network namespace: built-in (pass)
  CONFIG_NET: Networking support: built-in (pass)
    CONFIG_INET: TCP/IP networking: built-in (pass)
      CONFIG_IPV6: The IPv6 protocol: built-in (pass)
    CONFIG_NETFILTER: Network packet filtering framework (Netfilter): built-in (pass)
      CONFIG_NETFILTER_ADVANCED: Advanced netfilter configuration: built-in (pass)
      CONFIG_NF_CONNTRACK: Netfilter connection tracking support: module (pass)
      CONFIG_NETFILTER_XTABLES: Netfilter Xtables support: built-in (pass)
        CONFIG_NETFILTER_XT_TARGET_REDIRECT: REDIRECT target support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_COMMENT: "comment" match support: module (pass)
        CONFIG_NETFILTER_XT_MARK: nfmark target and match support: module (pass)
        CONFIG_NETFILTER_XT_SET: set target and match support: module (pass)
        CONFIG_NETFILTER_XT_TARGET_MASQUERADE: MASQUERADE target support: module (pass)
        CONFIG_NETFILTER_XT_NAT: "SNAT and DNAT" targets support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_ADDRTYPE: "addrtype" address type match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_CONNTRACK: "conntrack" connection tracking match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_MULTIPORT: "multiport" Multiple port match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_RECENT: "recent" match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_STATISTIC: "statistic" match support: module (pass)
      CONFIG_NETFILTER_NETLINK: module (pass)
      CONFIG_NF_NAT: module (pass)
      CONFIG_IP_SET: IP set support: module (pass)
        CONFIG_IP_SET_HASH_IP: hash:ip set support: module (pass)
        CONFIG_IP_SET_HASH_NET: hash:net set support: module (pass)
      CONFIG_IP_VS: IP virtual server support: module (pass)
        CONFIG_IP_VS_NFCT: Netfilter connection tracking: built-in (pass)
      CONFIG_NF_CONNTRACK_IPV4: IPv4 connetion tracking support (required for NAT): unknown (warning)
      CONFIG_NF_REJECT_IPV4: IPv4 packet rejection: module (pass)
      CONFIG_NF_NAT_IPV4: IPv4 NAT: unknown (warning)
      CONFIG_IP_NF_IPTABLES: IP tables support: module (pass)
        CONFIG_IP_NF_FILTER: Packet filtering: module (pass)
          CONFIG_IP_NF_TARGET_REJECT: REJECT target support: module (pass)
        CONFIG_IP_NF_NAT: iptables NAT support: module (pass)
        CONFIG_IP_NF_MANGLE: Packet mangling: module (pass)
      CONFIG_NF_DEFRAG_IPV4: module (pass)
      CONFIG_NF_CONNTRACK_IPV6: IPv6 connetion tracking support (required for NAT): unknown (warning)
      CONFIG_NF_NAT_IPV6: IPv6 NAT: unknown (warning)
      CONFIG_IP6_NF_IPTABLES: IP6 tables support: module (pass)
        CONFIG_IP6_NF_FILTER: Packet filtering: module (pass)
        CONFIG_IP6_NF_MANGLE: Packet mangling: module (pass)
        CONFIG_IP6_NF_NAT: ip6tables NAT support: module (pass)
      CONFIG_NF_DEFRAG_IPV6: module (pass)
    CONFIG_BRIDGE: 802.1d Ethernet Bridging: module (pass)
      CONFIG_LLC: module (pass)
      CONFIG_STP: module (pass)
  CONFIG_EXT4_FS: The Extended 4 (ext4) filesystem: module (pass)
  CONFIG_PROC_FS: /proc file system support: built-in (pass)
</pre>
</details>

### What happened?

k0s ctr image push command shows a content digest not found error with some containers images

### Steps to reproduce

1. Execute: **k0s ctr image pull registry.k8s.io/ingress-nginx/controller:v1.7.1**
2. Execute: **k0s ctr image tag registry.k8s.io/ingress-nginx/controller:v1.7.1 my-harbor-registry.mydomain/ingress-nginx/controller:v1.7.1**
3. Execute:  **k0s ctr image push -k --user "user:password" my-harbor-registry.mydomain/ingress-nginx/controller:v1.7.1**
4. I get this error: **Error: content digest sha256:31953c360bca8311437640b9488fe7715384a34babc4055e0920920d2959bf09: not found**

### Expected behavior

k0s ctr image push command should work as with other container images

### Actual behavior

k0s ctr image push command fails with content digest not found error with some container images like:

registry.k8s.io/ingress-nginx/opentelemetry:v20230312-helm-chart-4.5.2-28-g66a760794
registry.k8s.io/ingress-nginx/controller:v1.7.1

k0s ctr image push works fine if I've pulled previously running k0s ctr image pull --all-platforms

### Screenshots and logs

[root@practicas ~]# journalctl -x -u k0scontroller|grep controller:v1.7.1

may 11 09:32:00 practicas.localdomain k0s[740]: time="2023-05-11 09:32:00" level=info msg="time=\"2023-05-11T09:32:00.101447529+02:00\" level=info msg=\"ImageCreate event name:\\\"registry.k8s.io/ingress-nginx/controller:v1.7.1\\\"\"" component=containerd stream=stderr
may 11 09:32:00 practicas.localdomain k0s[740]: time="2023-05-11 09:32:00" level=info msg="time=\"2023-05-11T09:32:00.131090513+02:00\" level=info msg=\"ImageUpdate event name:\\\"registry.k8s.io/ingress-nginx/controller:v1.7.1\\\"  labels:{key:\\\"io.cri-containerd.image\\\"  value:\\\"managed\\\"}\"" component=containerd stream=stderr
may 11 09:32:17 practicas.localdomain k0s[740]: time="2023-05-11 09:32:17" level=info msg="time=\"2023-05-11T09:32:17.536020919+02:00\" level=info msg=\"ImageCreate event name:\\\"registry.k8s.io/ingress-nginx/controller:v1.7.1@sha256:7244b95ea47bddcb8267c1e625fb163fc183ef55448855e3ac52a7b260a60407\\\"\"" component=containerd stream=stderr
may 11 09:32:17 practicas.localdomain k0s[740]: time="2023-05-11 09:32:17" level=info msg="time=\"2023-05-11T09:32:17.567217746+02:00\" level=info msg=\"ImageUpdate event name:\\\"registry.k8s.io/ingress-nginx/controller:v1.7.1@sha256:7244b95ea47bddcb8267c1e625fb163fc183ef55448855e3ac52a7b260a60407\\\"  labels:{key:\\\"io.cri-containerd.image\\\"  value:\\\"managed\\\"}\"" component=containerd stream=stderr

### Additional context

This command works fine with images like echoserver:

[root@practicas ~]#  k0s ctr image pull registry.k8s.io/echoserver:1.10 

registry.k8s.io/echoserver:1.10:                                                  resolved       |++++++++++++++++++++++++++++++++++++++|         
manifest-sha256:cb5c1bddd1b5665e1867a7fa1b5fa843a47ee433bbb75d4293888b71def53229: done           |++++++++++++++++++++++++++++++++++++++|         
layer-sha256:e0962580d8254d0b1ef35006d7e2319eb4870e63dc1f9573d2406c7c47d442d2:    downloading    |--------------------------------------|    0.0 B
/754.0 B                                                                                                                                          
layer-sha256:bc391bffe5907b0eaa04e96fd638784f77d39f1feb7fbe438a1dae0af2675205:    downloading    |--------------------------------------|    0.0 B
registry.k8s.io/echoserver:1.10:                                                  resolved       |++++++++++++++++++++++++++++++++++++++|         
manifest-sha256:cb5c1bddd1b5665e1867a7fa1b5fa843a47ee433bbb75d4293888b71def53229: done           |++++++++++++++++++++++++++++++++++++++|         
layer-sha256:e0962580d8254d0b1ef35006d7e2319eb4870e63dc1f9573d2406c7c47d442d2:    downloading    |--------------------------------------|    0.0 B
/754.0 B                                                                                                                                          
layer-sha256:bc391bffe5907b0eaa04e96fd638784f77d39f1feb7fbe438a1dae0af2675205:    downloading    |--------------------------------------|    0.0 B
/172.0 B                                                                                                                                          
layer-sha256:2d3e25b9e93ad26878862abee5ed02683206f6f6d57e311cdd1dedf3662b61c8:    downloading    |--------------------------------------|    0.0 B
registry.k8s.io/echoserver:1.10:                                                  resolved       |++++++++++++++++++++++++++++++++++++++|         
manifest-sha256:cb5c1bddd1b5665e1867a7fa1b5fa843a47ee433bbb75d4293888b71def53229: done           |++++++++++++++++++++++++++++++++++++++|         
layer-sha256:e0962580d8254d0b1ef35006d7e2319eb4870e63dc1f9573d2406c7c47d442d2:    downloading    |++++++++++++++++++++++++++++++++++++++|  754.0 B
registry.k8s.io/echoserver:1.10:                                                  resolved       |++++++++++++++++++++++++++++++++++++++|         
manifest-sha256:cb5c1bddd1b5665e1867a7fa1b5fa843a47ee433bbb75d4293888b71def53229: done           |++++++++++++++++++++++++++++++++++++++|         
layer-sha256:e0962580d8254d0b1ef35006d7e2319eb4870e63dc1f9573d2406c7c47d442d2:    done           |++++++++++++++++++++++++++++++++++++++|         
layer-sha256:bc391bffe5907b0eaa04e96fd638784f77d39f1feb7fbe438a1dae0af2675205:    done           |++++++++++++++++++++++++++++++++++++++|         
layer-sha256:2d3e25b9e93ad26878862abee5ed02683206f6f6d57e311cdd1dedf3662b61c8:    done           |++++++++++++++++++++++++++++++++++++++|         
config-sha256:365ec60129c5426b4cf160257c06f6ad062c709e0576c8b3d9a5dcc488f5252d:   done           |++++++++++++++++++++++++++++++++++++++|         
layer-sha256:06679f57dba70a6875e4ae5843ba2483ecab6ec48182ca8720ddc5b1863bad52:    done           |++++++++++++++++++++++++++++++++++++++| 
layer-sha256:28c6282d04f63710146ace6c7be14a40c7ee6a71a2f91316928469e4aafe0d92:    done           |++++++++++++++++++++++++++++++++++++++| 
layer-sha256:d5157969118932d522396fe278eb722551751c7aa7473e6d3f03e821a74ee8ec:    done           |++++++++++++++++++++++++++++++++++++++| 
layer-sha256:76d46396145f805d716dcd1607832e6a1257aa17c0c2646a2a4916e47059dd54:    done           |++++++++++++++++++++++++++++++++++++++| 
layer-sha256:7fd34bf149707ca78b3bb90e4ba68fe9a013465e5d03179fb8d3a3b1cac8be27:    done           |++++++++++++++++++++++++++++++++++++++| 
layer-sha256:4b12f3ef8e65aaf1fd77201670deb98728a8925236d8f1f0473afa5abe9de119:    done           |++++++++++++++++++++++++++++++++++++++| 
layer-sha256:b0e3c31807a2330c86f07d45a6d80923d947a8a66745a2fd68eb3994be879db6:    done           |++++++++++++++++++++++++++++++++++++++| 
elapsed: 5.1 s                                                                    total:  44.1 M (8.6 MiB/s)                                      
  
unpacking linux/amd64 sha256:cb5c1bddd1b5665e1867a7fa1b5fa843a47ee433bbb75d4293888b71def53229...
done: 1.932794771s

[root@practicas ~]# k0s ctr image tag registry.k8s.io/echoserver:1.10  my-harbor-registry.mydomain/ingress-nginx/echoserver:1.10

[root@practicas ~]# k0s ctr image push -k --user "user:password" my-harbor-registry.mydomain/ingress-nginx/echoserver:1.10
manifest-sha256:cb5c1bddd1b5665e1867a7fa1b5fa843a47ee433bbb75d4293888b71def53229: done           |++++++++++++++++++++++++++++++++++++++| 
config-sha256:365ec60129c5426b4cf160257c06f6ad062c709e0576c8b3d9a5dcc488f5252d:   done           |++++++++++++++++++++++++++++++++++++++| 
elapsed: 7.2 s                                                                    total:  6.3 Ki (889.0 B/s)                                      

**Ingress-nginx images are pushed fine if I pulled them with k0s ctr image pull --all-platforms**

**Comment by twz123** [comment]
I don't think this is an issue with k0s itself. I was able to reproduce the behavior using vanilla containerd/ctr version 1.6.18.

```console
$ ctr version
Client:
  Version:  v1.6.18
  Revision: 2456e983eb9e37e47538f59ea18f2043c9a73640
  Go version: go1.19.9

Server:
  Version:  v1.6.18
  Revision: 2456e983eb9e37e47538f59ea18f2043c9a73640
  UUID: 84f8a18d-102f-41ad-8eff-52d1866bda02
$ ctr image pull registry.k8s.io/ingress-nginx/controller:v1.7.1
registry.k8s.io/ingress-nginx/controller:v1.7.1:                                  resolved       |++++++++++++++++++++++++++++++++++++++|
index-sha256:7244b95ea47bddcb8267c1e625fb163fc183ef55448855e3ac52a7b260a60407:    done           |++++++++++++++++++++++++++++++++++++++|
manifest-sha256:7f5af537d80289e0f500bfd9e4da4ef5f22bbcaca1d8da7016f0539608797442: done           |++++++++++++++++++++++++++++++++++++++|
layer-sha256:6ce556c836df801f8122b520249a10731799d98671ded8b8bba06b82d1ca5b96:    done           |++++++++++++++++++++++++++++++++++++++|
config-sha256:2db0b57c87122bf9dab14f527656bb8a1665f4b6a4e56f2e7feac71502a8f7c3:   done           |++++++++++++++++++++++++++++++++++++++|
layer-sha256:63b65145d645c1250c391b2d16ebe53b3747c295ca8ba2fcb6b0cf064a4dc21c:    done           |++++++++++++++++++++++++++++++++++++++|
layer-sha256:c61852a1d454c869c329f4871030ac288c13f981e75a05956c6a5602559208b7:    done           |++++++++++++++++++++++++++++++++++++++|
layer-sha256:de1befb33c3510358367c65acdfaebc09e5260b2e65b5a0f231404c7173c0011:    done           |++++++++++++++++++++++++++++++++++++++|
layer-sha256:36aeb843eff85df19800670a4a25bd52bb362e9afd74ae3a7eeab03cad1031b9:    done           |++++++++++++++++++++++++++++++++++++++|
layer-sha256:3af847ca67b5cff8a4d741509e1ff6f95986958ca43b4d84e30637d62f588d5d:    done           |++++++++++++++++++++++++++++++++++++++|
layer-sha256:4f4fb700ef54461cfa02571ae0db9a0dc1e0cdb5577484a6d75e68dc38e8acc1:    done           |++++++++++++++++++++++++++++++++++++++|
layer-sha256:f6792653db2c6bcd68b40231529bef0142a6ac0635116efc8148e78e3d5e24de:    done           |++++++++++++++++++++++++++++++++++++++|
layer-sha256:ca7797e1dfc51d7b7d8896672b68579cdb6bc2d78fb96287930af899f8baf7a4:    done           |++++++++++++++++++++++++++++++++++++++|
layer-sha256:dd05e355bb765b78a9556099a8a8809f71bb61486dd73373da6aa25bab132f3f:    done           |++++++++++++++++++++++++++++++++++++++|
layer-sha256:6df75ccbca0b51983ec8e10bf35e99ceb6826367cf34278bc0b585d601032c56:    done           |++++++++++++++++++++++++++++++++++++++|
layer-sha256:6eeb15bc73f773c499494c636466d143bba80da4906608495166b83e6ed516c1:    done           |++++++++++++++++++++++++++++++++++++++|
layer-sha256:b2dec14bbfcbdf6770c59e7f9463bcdc0d95086147ce41f50799b2c4b4387195:    done           |++++++++++++++++++++++++++++++++++++++|
layer-sha256:794377b137abc61ceda512ff18a13118fb4a981dbd1b2bba458e115bd9acc858:    done           |++++++++++++++++++++++++++++++++++++++|
elapsed: 10.0s                                                                    total:  111.2  (11.1 MiB/s)
unpacking linux/amd64 sha256:7244b95ea47bddcb8267c1e625fb163fc183ef55448855e3ac52a7b260a60407...
done: 4.632311719s
$ IMAGE_NAME=$(uuidgen)
$ ctr image tag registry.k8s.io/ingress-nginx/controller:v1.7.1 ttl.sh/$IMAGE_NAME:1h
ttl.sh/bb0d7a42-f68a-4d08-84d0-367d4932c07f:1h
$ ctr image push ttl.sh/$IMAGE_NAME:1h
index-sha256:7244b95ea47bddcb8267c1e625fb163fc183ef55448855e3ac52a7b260a60407: waiting        |--------------------------------------|
elapsed: 0.1 s                                                                 total:   0.0 B (0.0 B/s)
ctr: content digest sha256:31953c360bca8311437640b9488fe7715384a34babc4055e0920920d2959bf09: not found
```

**Comment by twz123** [comment]
Using `content fetch` and  `--platform` worked for me:

```console
$ ctr content fetch --platform linux/amd64 registry.k8s.io/ingress-nginx/controller:v1.7.1
registry.k8s.io/ingress-nginx/controller:v1.7.1:                                  resolved       |++++++++++++++++++++++++++++++++++++++|
index-sha256:7244b95ea47bddcb8267c1e625fb163fc183ef55448855e3ac52a7b260a60407:    done           |++++++++++++++++++++++++++++++++++++++|
manifest-sha256:7f5af537d80289e0f500bfd9e4da4ef5f22bbcaca1d8da7016f0539608797442: done           |++++++++++++++++++++++++++++++++++++++|
layer-sha256:6ce556c836df801f8122b520249a10731799d98671ded8b8bba06b82d1ca5b96:    done           |++++++++++++++++++++++++++++++++++++++|
config-sha256:2db0b57c87122bf9dab14f527656bb8a1665f4b6a4e56f2e7feac71502a8f7c3:   done           |++++++++++++++++++++++++++++++++++++++|
layer-sha256:63b65145d645c1250c391b2d16ebe53b3747c295ca8ba2fcb6b0cf064a4dc21c:    done           |++++++++++++++++++++++++++++++++++++++|
layer-sha256:c61852a1d454c869c329f4871030ac288c13f981e75a05956c6a5602559208b7:    done           |++++++++++++++++++++++++++++++++++++++|
layer-sha256:de1befb33c3510358367c65acdfaebc09e5260b2e65b5a0f231404c7173c0011:    done           |++++++++++++++++++++++++++++++++++++++|
layer-sha256:36aeb843eff85df19800670a4a25bd52bb362e9afd74ae3a7eeab03cad1031b9:    done           |++++++++++++++++++++++++++++++++++++++|
layer-sha256:3af847ca67b5cff8a4d741509e1ff6f95986958ca43b4d84e30637d62f588d5d:    done           |++++++++++++++++++++++++++++++++++++++|
layer-sha256:4f4fb700ef54461cfa02571ae0db9a0dc1e0cdb5577484a6d75e68dc38e8acc1:    done           |++++++++++++++++++++++++++++++++++++++|
layer-sha256:f6792653db2c6bcd68b40231529bef0142a6ac0635116efc8148e78e3d5e24de:    done           |++++++++++++++++++++++++++++++++++++++|
layer-sha256:ca7797e1dfc51d7b7d8896672b68579cdb6bc2d78fb96287930af899f8baf7a4:    done           |++++++++++++++++++++++++++++++++++++++|
layer-sha256:dd05e355bb765b78a9556099a8a8809f71bb61486dd73373da6aa25bab132f3f:    done           |++++++++++++++++++++++++++++++++++++++|
layer-sha256:6df75ccbca0b51983ec8e10bf35e99ceb6826367cf34278bc0b585d601032c56:    done           |++++++++++++++++++++++++++++++++++++++|
layer-sha256:6eeb15bc73f773c499494c636466d143bba80da4906608495166b83e6ed516c1:    done           |++++++++++++++++++++++++++++++++++++++|
layer-sha256:b2dec14bbfcbdf6770c59e7f9463bcdc0d95086147ce41f50799b2c4b4387195:    done           |++++++++++++++++++++++++++++++++++++++|
layer-sha256:794377b137abc61ceda512ff18a13118fb4a981dbd1b2bba458e115bd9acc858:    done           |++++++++++++++++++++++++++++++++++++++|
elapsed: 10.0s                                                                    total:  97.9 M (9.8 MiB/s)
$ IMAGE_NAME=$(uuidgen)
$ ctr image tag registry.k8s.io/ingress-nginx/controller:v1.7.1 ttl.sh/$IMAGE_NAME:1h
ttl.sh/bd576a88-9e5c-4a82-9f09-4ea2aaa0a661:1h
$ ctr image push --platform linux/amd64 ttl.sh/$IMAGE_NAME:1h
manifest-sha256:7f5af537d80289e0f500bfd9e4da4ef5f22bbcaca1d8da7016f0539608797442: done           |++++++++++++++++++++++++++++++++++++++|
config-sha256:2db0b57c87122bf9dab14f527656bb8a1665f4b6a4e56f2e7feac71502a8f7c3:   done           |++++++++++++++++++++++++++++++++++++++|
elapsed: 24.9s                                                                    total:  13.1 K (538.0 B/s)
```

On another machine:

```console
$ docker run --rm -it --entrypoint bash ttl.sh/bd576a88-9e5c-4a82-9f09-4ea2aaa0a661:1h
Unable to find image 'ttl.sh/bd576a88-9e5c-4a82-9f09-4ea2aaa0a661:1h' locally
1h: Pulling from bd576a88-9e5c-4a82-9f09-4ea2aaa0a661
63b65145d645: Already exists
c61852a1d454: Pull complete
de1befb33c35: Pull complete
36aeb843eff8: Pull complete
3af847ca67b5: Pull complete
4f4fb700ef54: Pull complete
f6792653db2c: Pull complete
ca7797e1dfc5: Pull complete
dd05e355bb76: Pull complete
6df75ccbca0b: Pull complete
6eeb15bc73f7: Pull complete
b2dec14bbfcb: Pull complete
794377b137ab: Pull complete
6ce556c836df: Pull complete
Digest: sha256:7f5af537d80289e0f500bfd9e4da4ef5f22bbcaca1d8da7016f0539608797442
Status: Downloaded newer image for ttl.sh/bd576a88-9e5c-4a82-9f09-4ea2aaa0a661:1h
1a128d67dea8:/etc/nginx$ ^C
1a128d67dea8:/etc/nginx$
exit
```

**Comment by jsalgado78** [comment]
Excuse me. I see It's not a k0s issue.
Thank you very much

**Comment by jnummelin** [comment]
I _believe_ this is a bug/feature on containerd when it does platform matching. So when you do e.g. `ctr content fetch` without providing the platform (I believe same happens with pull), it downloads the manifest for the image which might have multiarch stuff in it. So basically in the manifest there's some references to say `arm64` layers but naturally those are not pulled on `amd64` machine. But then when exporting, again in the manifest there's these arm64 refs which it tries to export too if you do not specify the platform.
