### ISSUE TITLE
k0s coredns, metrics-server and konnectivity pods stuck at crashloopbackoff. 

### ISSUE THREAD

**Issue by Annuore** [k0sproject/k0s#3118]
### Before creating an issue, make sure you've checked the following:

- [X] You are running the latest released version of k0s
- [X] Make sure you've searched for existing issues, both open and closed
- [X] Make sure you've searched for PRs too, a fix might've been merged already
- [X] You're looking at docs for the released version, "main" branch docs are usually ahead of released versions.

### Platform

```shell
Linux 5.19.0-41-generic #42-Ubuntu SMP PREEMPT_DYNAMIC Mon Apr 17 19:17:03 UTC 2023 x86_64 GNU/Linux
PRETTY_NAME="Ubuntu 22.10"
NAME="Ubuntu"
VERSION_ID="22.10"
VERSION="22.10 (Kinetic Kudu)"
VERSION_CODENAME=kinetic
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=kinetic
LOGO=ubuntu-logo
```

### Version

v1.27.1+k0s.0

### Sysinfo

<details><summary>`k0s sysinfo`</summary>
<pre>
Machine ID: "48cedc11205cb4bd111c5dbd4362d14b8508b088bb8231609a4da2129a4df5d1" (from machine) (pass)
Total memory: 15.5 GiB (pass)
Disk space available for /var/lib/k0s: 193.5 GiB (pass)
Operating system: Linux (pass)
  Linux kernel release: 5.19.0-41-generic (pass)
  Max. file descriptors per process: current: 1048576 / max: 1048576 (pass)
  Executable in path: modprobe: /usr/sbin/modprobe (pass)
  /proc file system: mounted (0x9fa0) (pass)
  Control Groups: version 2 (pass)
    cgroup controller "cpu": available (pass)
    cgroup controller "cpuacct": available (via cpu in version 2) (pass)
    cgroup controller "cpuset": available (pass)
    cgroup controller "memory": available (pass)
    cgroup controller "devices": available (assumed) (pass)
    cgroup controller "freezer": available (assumed) (pass)
    cgroup controller "pids": available (pass)
    cgroup controller "hugetlb": available (pass)
    cgroup controller "blkio": available (via io in version 2) (pass)
  CONFIG_CGROUPS: Control Group support: built-in (pass)
    CONFIG_CGROUP_FREEZER: Freezer cgroup subsystem: built-in (pass)
    CONFIG_CGROUP_PIDS: PIDs cgroup subsystem: built-in (pass)
    CONFIG_CGROUP_DEVICE: Device controller for cgroups: built-in (pass)
    CONFIG_CPUSETS: Cpuset support: built-in (pass)
    CONFIG_CGROUP_CPUACCT: Simple CPU accounting cgroup subsystem: built-in (pass)
    CONFIG_MEMCG: Memory Resource Controller for Control Groups: built-in (pass)
    CONFIG_CGROUP_HUGETLB: HugeTLB Resource Controller for Control Groups: built-in (pass)
    CONFIG_CGROUP_SCHED: Group CPU scheduler: built-in (pass)
      CONFIG_FAIR_GROUP_SCHED: Group scheduling for SCHED_OTHER: built-in (pass)
        CONFIG_CFS_BANDWIDTH: CPU bandwidth provisioning for FAIR_GROUP_SCHED: built-in (pass)
    CONFIG_BLK_CGROUP: Block IO controller: built-in (pass)
  CONFIG_NAMESPACES: Namespaces support: built-in (pass)
    CONFIG_UTS_NS: UTS namespace: built-in (pass)
    CONFIG_IPC_NS: IPC namespace: built-in (pass)
    CONFIG_PID_NS: PID namespace: built-in (pass)
    CONFIG_NET_NS: Network namespace: built-in (pass)
  CONFIG_NET: Networking support: built-in (pass)
    CONFIG_INET: TCP/IP networking: built-in (pass)
      CONFIG_IPV6: The IPv6 protocol: built-in (pass)
    CONFIG_NETFILTER: Network packet filtering framework (Netfilter): built-in (pass)
      CONFIG_NETFILTER_ADVANCED: Advanced netfilter configuration: built-in (pass)
      CONFIG_NF_CONNTRACK: Netfilter connection tracking support: module (pass)
      CONFIG_NETFILTER_XTABLES: Netfilter Xtables support: module (pass)
        CONFIG_NETFILTER_XT_TARGET_REDIRECT: REDIRECT target support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_COMMENT: "comment" match support: module (pass)
        CONFIG_NETFILTER_XT_MARK: nfmark target and match support: module (pass)
        CONFIG_NETFILTER_XT_SET: set target and match support: module (pass)
        CONFIG_NETFILTER_XT_TARGET_MASQUERADE: MASQUERADE target support: module (pass)
        CONFIG_NETFILTER_XT_NAT: "SNAT and DNAT" targets support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_ADDRTYPE: "addrtype" address type match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_CONNTRACK: "conntrack" connection tracking match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_MULTIPORT: "multiport" Multiple port match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_RECENT: "recent" match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_STATISTIC: "statistic" match support: module (pass)
      CONFIG_NETFILTER_NETLINK: module (pass)
      CONFIG_NF_NAT: module (pass)
      CONFIG_IP_SET: IP set support: module (pass)
        CONFIG_IP_SET_HASH_IP: hash:ip set support: module (pass)
        CONFIG_IP_SET_HASH_NET: hash:net set support: module (pass)
      CONFIG_IP_VS: IP virtual server support: module (pass)
        CONFIG_IP_VS_NFCT: Netfilter connection tracking: built-in (pass)
      CONFIG_NF_CONNTRACK_IPV4: IPv4 connetion tracking support (required for NAT): unknown (warning)
      CONFIG_NF_REJECT_IPV4: IPv4 packet rejection: module (pass)
      CONFIG_NF_NAT_IPV4: IPv4 NAT: unknown (warning)
      CONFIG_IP_NF_IPTABLES: IP tables support: module (pass)
        CONFIG_IP_NF_FILTER: Packet filtering: module (pass)
          CONFIG_IP_NF_TARGET_REJECT: REJECT target support: module (pass)
        CONFIG_IP_NF_NAT: iptables NAT support: module (pass)
        CONFIG_IP_NF_MANGLE: Packet mangling: module (pass)
      CONFIG_NF_DEFRAG_IPV4: module (pass)
      CONFIG_NF_CONNTRACK_IPV6: IPv6 connetion tracking support (required for NAT): unknown (warning)
      CONFIG_NF_NAT_IPV6: IPv6 NAT: unknown (warning)
      CONFIG_IP6_NF_IPTABLES: IP6 tables support: module (pass)
        CONFIG_IP6_NF_FILTER: Packet filtering: module (pass)
        CONFIG_IP6_NF_MANGLE: Packet mangling: module (pass)
        CONFIG_IP6_NF_NAT: ip6tables NAT support: module (pass)
      CONFIG_NF_DEFRAG_IPV6: module (pass)
    CONFIG_BRIDGE: 802.1d Ethernet Bridging: module (pass)
      CONFIG_LLC: module (pass)
      CONFIG_STP: module (pass)
  CONFIG_EXT4_FS: The Extended 4 (ext4) filesystem: built-in (pass)
  CONFIG_PROC_FS: /proc file system support: built-in (pass)
</pre>
</details>

### What happened?

k0s coredns, metrics-server and dns stuck at crashloopbackoff. 
kubectl describe on their pods and they all have similar events. 
`Events:
  Type     Reason            Age                    From               Message
  ----     ------            ----                   ----               -------
  Warning  FailedScheduling  15m                    default-scheduler  0/1 nodes are available: 1 node(s) didn't match pod anti-affinity rules. preemption: 0/1 nodes are available: 1 No preemption victims found for incoming pod..
  Normal   Scheduled         15m                    default-scheduler  Successfully assigned kube-system/coredns-878bb57ff-nzf8k to u9
  Normal   Pulled            15m                    kubelet            Container image "quay.io/k0sproject/coredns:1.10.1" already present on machine
  Normal   Created           15m                    kubelet            Created container coredns
  Normal   Started           15m                    kubelet            Started container coredns
  Warning  Unhealthy         14m (x22 over 15m)     kubelet            Readiness probe failed: Get "http://10.244.0.21:8181/ready": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
  Warning  Unhealthy         11m (x3 over 11m)      kubelet            Liveness probe failed: Get "http://10.244.0.21:8080/health": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
  Normal   Killing           11m                    kubelet            Container coredns failed liveness probe, will be restarted
  Normal   Pulled            11m                    kubelet            Container image "quay.io/k0sproject/coredns:1.10.1" already present on machine
  Normal   Created           11m                    kubelet            Created container coredns
  Normal   Started           11m                    kubelet            Started container coredns
  Warning  Unhealthy         6m47s (x161 over 11m)  kubelet            Readiness probe failed: Get "http://10.244.0.21:8181/ready": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
  Warning  BackOff           106s (x12 over 3m57s)  kubelet            Back-off restarting failed container coredns in pod coredns-878bb57ff-nzf8k_kube-system(3cc64ead-88cd-4378-840e-42c82a60e589)`

`kubectl log on their pod` have the same output  

> Error from server: Get "https://192.168.1.187:10250/containerLogs/kube-system/coredns-878bb57ff-nzf8k/coredns": No agent available

`kubectl get nodes -owide`
NAME   STATUS   ROLES    AGE   VERSION       INTERNAL-IP     EXTERNAL-IP   OS-IMAGE       KERNEL-VERSION      CONTAINER-RUNTIME
u9     Ready    <none>   82m   v1.27.1+k0s   192.168.1.187   <none>        Ubuntu 22.10   5.19.0-41-generic   containerd://1.7.0

### Steps to reproduce

1. Installed k0s cluster suing the manual installation stated [here](https://docs.k0sproject.io/v1.27.1+k0s.0/k0s-multi-node/)
2.  Get pods in all namespaces 

### Actual behavior

`kubectl get po -A`

NAMESPACE     NAME                              READY   STATUS             RESTARTS         AGE
kube-system   coredns-878bb57ff-nzf8k           0/1     Running            8 (5m9s ago)     20m
kube-system   konnectivity-agent-hsb8f          1/1     Running            27 (50s ago)     73m
kube-system   kube-proxy-t564d                  1/1     Running            0                73m
kube-system   kube-router-tcw7j                 1/1     Running            0                73m
kube-system   metrics-server-7f86dff975-trqfq   0/1     CrashLoopBackOff   29 (3m19s ago)   74m

### Screenshots and logs

got logs from /var/log/containers directory 
coredns logs 
![core](https://github.com/k0sproject/k0s/assets/90752027/df95e191-4f6d-49c1-83d4-6256b0c789bc)

konnectivity logs 
![konnectivity](https://github.com/k0sproject/k0s/assets/90752027/513168bd-2dab-49ca-9acf-e547dd76589f)

metrics-server logs
![metrics](https://github.com/k0sproject/k0s/assets/90752027/890201c6-e3a0-4b07-a7bb-ff469afc8187)

### Additional context

I have one initial controller and one worker node

**Comment by Bugs5382** [comment]
So I am working on a n issue where the drive would fill up with endless amounts of k0s syslog messages... still trying to disable and/or lower to justing errors. @jnummelin  ??  You check your disk space `df -k` to make sure nothing is at 100% where k0s is installed.

**Comment by jnummelin** [comment]
From the logs the root cause looks like connectivity issue between the workers and controllers.

In `konnectivity` logs it seems to fail to connect to `192.168.1.156`. Core-dns and metrics seem to fail to connect to `10.96.0.1` which is the cluster internal svc address for API. Based on these I'd assume that in kube-proxy logs you'll see something similar, it failing to connect to API. Which in turn will make it not able to actually create in-cluster svc for API.

So make sure that worker nodes can connect to the controller address and on the controller they are publishing the right address. In case of multi interface controllers, you need to configure `spec.api.address` for the right address. By default k0s picks the first non-local address it finds on the node.
