### ISSUE TITLE
Update documentation to indicate how helm can be connected 

### ISSUE THREAD

**Issue by h3b4r1** [k0sproject/k0s#3121]
### Is your feature request related to a problem? Please describe.

I have been attempting to connect helm using the api as opposed to using helm charts within k0s, this is simply so I can run helm interactively for testing etc without having to rebuild the cluster each time. The documentation says that this is possible however the how is missing, I have attempted to point helm to the k0s.yaml file but no joy.

### Describe the solution you would like

Update the documentation to show either a link to a how-to or simply include the method for deploying helm with k0s.

### Describe alternatives you've considered

This seems to be the only really valid solution at this point

**Comment by jnummelin** [comment]
https://docs.k0sproject.io/v1.27.1+k0s.0/FAQ/?h=kubeconfig#how-do-i-connect-to-the-cluster

So the admin kubeconfig is by default at `/var/lib/k0s/pki/admin.conf`. Grab that and point Helm to use that with `KUBECONFIG` env var and you're good to go.

**Comment by CmdrSharp** [comment]
Should this be closed @jnummelin? :) It seems like a question answered and one that doesn't need any changes to docs.
