### ISSUE TITLE
Report binary size during the PRs 

### ISSUE THREAD

**Issue by mikhail-sakhnov** [k0sproject/k0s#3191]
### Is your feature request related to a problem? Please describe.

For the last 1.5-2 years we had a steady grow of the binary size. 

k0s binary size increased by almost 10% during the last year: 183 mb was the size of asset for amd64 linux in the april of 2022, slow growth to the 200 during the year and then increased to 213 with the 1.26 release.

It would be nice to have some bot reporting which will comment PR with the size of the build artifact for the PR.

**Comment by kke** [comment]
https://github.com/nikolaydubina/go-binsize-treemap this looks like a fun tool

**Comment by makhov** [comment]
> https://github.com/nikolaydubina/go-binsize-treemap this looks like a fun tool

Yeah, but we build the binary with `-s -w` ldflags, so it won't work out of the box

**Comment by ncopa** [comment]
comments can be added with https://github.com/marketplace/actions/add-pr-comment

**Comment by ncopa** [comment]
I had a look at this, and it seems a bit complicated to give permissions for a forked repo to post comments in the PR. Basically, we'd need to set up a proxy service. I don't think it is worth it.

As an alternate option, we can post the binary size as a [GITHUB_STEP_SUMMARY](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#adding-a-job-summary). It is stupid and simple, even if not as convenient as having a PR comment.

You have an example here: https://github.com/k0sproject/k0s/actions/runs/5473483526/attempts/1#summary-14820194608

Is that good enough?
