### ISSUE TITLE
Use existing Docker install

### ISSUE THREAD

**Issue by dlsniper** [k0sproject/k0s#3216]
### Before creating an issue, make sure you've checked the following:

- [X] You are running the latest released version of k0s
- [X] Make sure you've searched for existing issues, both open and closed
- [X] Make sure you've searched for PRs too, a fix might've been merged already
- [X] You're looking at docs for the released version, "main" branch docs are usually ahead of released versions.

### Platform

```shell
Linux 6.2.6-76060206-generic #202303130630~1685473338~22.04~995127e SMP PREEMPT_DYNAMIC Tue M x86_64 GNU/Linux
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
```

### Version

v1.27.2+k0s.0

### Sysinfo

<details><summary>`k0s sysinfo`</summary>
<pre>
Machine ID: "94f4b6c3981137856e885ff5638fcbba238e6a74c86b92ab93212c3c630fdded" (from machine) (pass)
Total memory: 62.5 GiB (pass)
Disk space available for /var/lib/k0s: 323.3 GiB (pass)
Operating system: Linux (pass)
  Linux kernel release: 6.2.6-76060206-generic (pass)
  Max. file descriptors per process: current: 1048576 / max: 1048576 (pass)
  Executable in path: modprobe: /usr/sbin/modprobe (pass)
  /proc file system: mounted (0x9fa0) (pass)
  Control Groups: version 2 (pass)
    cgroup controller "cpu": available (pass)
    cgroup controller "cpuacct": available (via cpu in version 2) (pass)
    cgroup controller "cpuset": available (pass)
    cgroup controller "memory": available (pass)
    cgroup controller "devices": available (assumed) (pass)
    cgroup controller "freezer": available (assumed) (pass)
    cgroup controller "pids": available (pass)
    cgroup controller "hugetlb": available (pass)
    cgroup controller "blkio": available (via io in version 2) (pass)
  CONFIG_CGROUPS: Control Group support: built-in (pass)
    CONFIG_CGROUP_FREEZER: Freezer cgroup subsystem: built-in (pass)
    CONFIG_CGROUP_PIDS: PIDs cgroup subsystem: built-in (pass)
    CONFIG_CGROUP_DEVICE: Device controller for cgroups: built-in (pass)
    CONFIG_CPUSETS: Cpuset support: built-in (pass)
    CONFIG_CGROUP_CPUACCT: Simple CPU accounting cgroup subsystem: built-in (pass)
    CONFIG_MEMCG: Memory Resource Controller for Control Groups: built-in (pass)
    CONFIG_CGROUP_HUGETLB: HugeTLB Resource Controller for Control Groups: built-in (pass)
    CONFIG_CGROUP_SCHED: Group CPU scheduler: built-in (pass)
      CONFIG_FAIR_GROUP_SCHED: Group scheduling for SCHED_OTHER: built-in (pass)
        CONFIG_CFS_BANDWIDTH: CPU bandwidth provisioning for FAIR_GROUP_SCHED: built-in (pass)
    CONFIG_BLK_CGROUP: Block IO controller: built-in (pass)
  CONFIG_NAMESPACES: Namespaces support: built-in (pass)
    CONFIG_UTS_NS: UTS namespace: built-in (pass)
    CONFIG_IPC_NS: IPC namespace: built-in (pass)
    CONFIG_PID_NS: PID namespace: built-in (pass)
    CONFIG_NET_NS: Network namespace: built-in (pass)
  CONFIG_NET: Networking support: built-in (pass)
    CONFIG_INET: TCP/IP networking: built-in (pass)
      CONFIG_IPV6: The IPv6 protocol: built-in (pass)
    CONFIG_NETFILTER: Network packet filtering framework (Netfilter): built-in (pass)
      CONFIG_NETFILTER_ADVANCED: Advanced netfilter configuration: built-in (pass)
      CONFIG_NF_CONNTRACK: Netfilter connection tracking support: module (pass)
      CONFIG_NETFILTER_XTABLES: Netfilter Xtables support: module (pass)
        CONFIG_NETFILTER_XT_TARGET_REDIRECT: REDIRECT target support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_COMMENT: "comment" match support: module (pass)
        CONFIG_NETFILTER_XT_MARK: nfmark target and match support: module (pass)
        CONFIG_NETFILTER_XT_SET: set target and match support: module (pass)
        CONFIG_NETFILTER_XT_TARGET_MASQUERADE: MASQUERADE target support: module (pass)
        CONFIG_NETFILTER_XT_NAT: "SNAT and DNAT" targets support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_ADDRTYPE: "addrtype" address type match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_CONNTRACK: "conntrack" connection tracking match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_MULTIPORT: "multiport" Multiple port match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_RECENT: "recent" match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_STATISTIC: "statistic" match support: module (pass)
      CONFIG_NETFILTER_NETLINK: module (pass)
      CONFIG_NF_NAT: module (pass)
      CONFIG_IP_SET: IP set support: module (pass)
        CONFIG_IP_SET_HASH_IP: hash:ip set support: module (pass)
        CONFIG_IP_SET_HASH_NET: hash:net set support: module (pass)
      CONFIG_IP_VS: IP virtual server support: module (pass)
        CONFIG_IP_VS_NFCT: Netfilter connection tracking: built-in (pass)
      CONFIG_NF_CONNTRACK_IPV4: IPv4 connetion tracking support (required for NAT): unknown (warning)
      CONFIG_NF_REJECT_IPV4: IPv4 packet rejection: module (pass)
      CONFIG_NF_NAT_IPV4: IPv4 NAT: unknown (warning)
      CONFIG_IP_NF_IPTABLES: IP tables support: module (pass)
        CONFIG_IP_NF_FILTER: Packet filtering: module (pass)
          CONFIG_IP_NF_TARGET_REJECT: REJECT target support: module (pass)
        CONFIG_IP_NF_NAT: iptables NAT support: module (pass)
        CONFIG_IP_NF_MANGLE: Packet mangling: module (pass)
      CONFIG_NF_DEFRAG_IPV4: module (pass)
      CONFIG_NF_CONNTRACK_IPV6: IPv6 connetion tracking support (required for NAT): unknown (warning)
      CONFIG_NF_NAT_IPV6: IPv6 NAT: unknown (warning)
      CONFIG_IP6_NF_IPTABLES: IP6 tables support: module (pass)
        CONFIG_IP6_NF_FILTER: Packet filtering: module (pass)
        CONFIG_IP6_NF_MANGLE: Packet mangling: module (pass)
        CONFIG_IP6_NF_NAT: ip6tables NAT support: module (pass)
      CONFIG_NF_DEFRAG_IPV6: module (pass)
    CONFIG_BRIDGE: 802.1d Ethernet Bridging: module (pass)
      CONFIG_LLC: module (pass)
      CONFIG_STP: module (pass)
  CONFIG_EXT4_FS: The Extended 4 (ext4) filesystem: built-in (pass)
  CONFIG_PROC_FS: /proc file system support: built-in (pass)
</pre>
</details>

### What happened?

I'm trying to run K0s with the existing Docker setup on the system following the documentation here: https://docs.k0sproject.io/v1.27.2+k0s.0/dockershim/

I installed the DockerShim:
```
cri-dockerd --version
cri-dockerd 0.3.3 (b58acf8f)
```

### Steps to reproduce

1. sudo k0s controller --single --cri-socket=docker:unix:/var/run/cri-dockerd.sock

### Expected behavior

The system should be ready to start and accept pods.

### Actual behavior

The system is in NotReady state and fails to start.

```
sudo k0s kubectl get nodes -o wide
```
<pre>
NAME      STATUS     ROLES           AGE   VERSION       INTERNAL-IP   EXTERNAL-IP   OS-IMAGE            KERNEL-VERSION           CONTAINER-RUNTIME
monzi12   NotReady   control-plane   37m   v1.27.2+k0s   10.27.0.149   <none>        Pop!_OS 22.04 LTS   6.2.6-76060206-generic   docker://24.0.2
</pre>

### Screenshots and logs

<pre>
INFO[2023-06-15 11:40:07] E0615 11:40:07.799761  190152 remote_runtime.go:176] "RunPodSandbox from runtime service failed" err="rpc error: code = Unknown desc = failed to create a sandbox for pod \"kube-router-bskkn\": Error response from daemon: cgroup-parent for systemd cgroup should be a valid slice named as \"xxx.slice\""  component=kubelet stream=stderr
</pre>

### Additional context

What I would like to ultimately achieve is run k0s and deploy images that I build with `docker build` on my system into it.

E.g. `docker build` will produce an image like `dlsniper/demo:1.2.3` and for a pod container, I'm referencing `dlsniper/demo:1.2.3` in my deployment definition. However, because the image is not pushed to any docker registry yet, the pod won't start.

That's why, I thought that starting k0s while reusing the existing Docker deployment will fix the problem.

Am I approaching this problem in the wrong way?

Edit: I should mention that Docker is configured to run without requiring `sudo`.

**Comment by jnummelin** [comment]
The CRI opt should be `--cri-socket docker:unix:///var/run/cri-dockerd.sock`, notice the three `/` chars.

**Comment by dlsniper** [comment]
@jnummelin thanks for the quick response.

Sadly, that doesn't fix it.
I've tried resetting the environment first with `sudo k0s reset` and then started:
```
sudo k0s controller --single --cri-socket=docker:unix:///var/run/cri-dockerd.sock
```

This is what the pod has:
<details>
<pre>
Name:                 kube-router-h5xkk
Namespace:            kube-system
Priority:             2000001000
Priority Class Name:  system-node-critical
Service Account:      kube-router
Node:                 monzi12/10.27.0.149
Start Time:           Thu, 15 Jun 2023 15:46:50 +0300
Labels:               controller-revision-hash=6f577fffc9
                      k8s-app=kube-router
                      pod-template-generation=1
                      tier=node
Annotations:          prometheus.io/port: 8080
                      prometheus.io/scrape: true
Status:               Pending
IP:                   10.27.0.149
IPs:
  IP:           10.27.0.149
Controlled By:  DaemonSet/kube-router
Init Containers:
  install-cni-bins:
    Container ID:  
    Image:         quay.io/k0sproject/cni-node:1.1.1-k0s.1
    Image ID:      
    Port:          <none>
    Host Port:     <none>
    Args:
      install
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /host/opt/cni/bin from cni-bin (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-wqbs6 (ro)
  install-cniconf:
    Container ID:  
    Image:         quay.io/k0sproject/kube-router:v1.5.1
    Image ID:      
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/sh
      -c
      set -e -x; if [ ! -f /etc/cni/net.d/10-kuberouter.conflist ]; then if [ -f /etc/cni/net.d/*.conf ]; then rm -f /etc/cni/net.d/*.conf; fi; TMP=/etc/cni/net.d/.tmp-kuberouter-cfg; cp /etc/kube-router/cni-conf.json ${TMP}; mv ${TMP} /etc/cni/net.d/10-kuberouter.conflist; fi
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /etc/cni/net.d from cni-conf-dir (rw)
      /etc/kube-router from kube-router-cfg (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-wqbs6 (ro)
Containers:
  kube-router:
    Container ID:  
    Image:         quay.io/k0sproject/kube-router:v1.5.1
    Image ID:      
    Port:          <none>
    Host Port:     <none>
    Args:
      --run-router=true
      --run-firewall=true
      --run-service-proxy=false
      --bgp-graceful-restart=true
      --metrics-port=8080
      --hairpin-mode=true
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Requests:
      cpu:     250m
      memory:  16Mi
    Liveness:  http-get http://:20244/healthz delay=10s timeout=1s period=3s #success=1 #failure=3
    Environment:
      NODE_NAME:                   (v1:spec.nodeName)
      KUBE_ROUTER_CNI_CONF_FILE:  /etc/cni/net.d/10-kuberouter.conflist
    Mounts:
      /etc/cni/net.d from cni-conf-dir (rw)
      /lib/modules from lib-modules (ro)
      /run/xtables.lock from xtables-lock (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-wqbs6 (ro)
Conditions:
  Type              Status
  Initialized       False 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  lib-modules:
    Type:          HostPath (bare host directory volume)
    Path:          /lib/modules
    HostPathType:  
  cni-conf-dir:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/cni/net.d
    HostPathType:  
  cni-bin:
    Type:          HostPath (bare host directory volume)
    Path:          /opt/cni/bin
    HostPathType:  DirectoryOrCreate
  kube-router-cfg:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      kube-router-cfg
    Optional:  false
  xtables-lock:
    Type:          HostPath (bare host directory volume)
    Path:          /run/xtables.lock
    HostPathType:  FileOrCreate
  kube-api-access-wqbs6:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Burstable
Node-Selectors:              <none>
Tolerations:                 :NoSchedule op=Exists
                             :NoExecute op=Exists
                             CriticalAddonsOnly op=Exists
                             node-role.kubernetes.io/master:NoSchedule op=Exists
                             node.kubernetes.io/disk-pressure:NoSchedule op=Exists
                             node.kubernetes.io/memory-pressure:NoSchedule op=Exists
                             node.kubernetes.io/network-unavailable:NoSchedule op=Exists
                             node.kubernetes.io/not-ready:NoExecute op=Exists
                             node.kubernetes.io/pid-pressure:NoSchedule op=Exists
                             node.kubernetes.io/unreachable:NoExecute op=Exists
                             node.kubernetes.io/unschedulable:NoSchedule op=Exists
Events:
  Type     Reason                  Age                   From               Message
  ----     ------                  ----                  ----               -------
  Normal   Scheduled               18m                   default-scheduler  Successfully assigned kube-system/kube-router-h5xkk to monzi12
  Warning  FailedCreatePodSandBox  3m19s (x71 over 18m)  kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create a sandbox for pod "kube-router-h5xkk": Error response from daemon: cgroup-parent for systemd cgroup should be a valid slice named as "xxx.slice"
</pre>
</details>

I've attached the full logs, hope they help: [k0s.log](https://github.com/k0sproject/k0s/files/11757864/k0s.log)

**Comment by dlsniper** [comment]
I've installed Docker via the default setup instructions here: https://docs.docker.com/engine/install/ubuntu/ and then used the steps here to manage docker as a non-root user: https://docs.docker.com/engine/install/linux-postinstall/#manage-docker-as-a-non-root-user. 
Hope it helps.

**Comment by twz123** [comment]
Can you try to instruct kubelet to use the `systemd` cgroup driver? Like so:

Create a `k0s.yaml` config file:

```yaml
apiVersion: k0s.k0sproject.io/v1beta1
kind: ClusterConfig
metadata:
  name: k0s
spec:
  workerProfiles:
    - name: default
      values:
        cgroupDriver: systemd
```

Start k0s via `sudo k0s controller --single --cri-socket=docker:unix:///var/run/cri-dockerd.sock --config=./k0s.yaml`.

**Comment by dlsniper** [comment]
@twz123 Thank you! It works with the proposed configuration.
I'm sorry for not getting back to you sooner.
Should I close this issue or send a PR to the documentation to include this configuration?

**Comment by twz123** [comment]
PRs are, as always, highly appreciated! 😃

**Comment by twz123** [comment]
Docs have been updated.
