### ISSUE TITLE
containerd.d folder merge does not happen

### ISSUE THREAD

**Issue by rmannibucau** [k0sproject/k0s#3283]
### Before creating an issue, make sure you've checked the following:

- [X] You are running the latest released version of k0s
- [X] Make sure you've searched for existing issues, both open and closed
- [X] Make sure you've searched for PRs too, a fix might've been merged already
- [X] You're looking at docs for the released version, "main" branch docs are usually ahead of released versions.

### Platform

```shell
RH 8.6, linux 4.18.0-372.9.1.el8.x86_64
```

### Version

v1.27.2+k0s.0

### Sysinfo

-

### What happened?

I tried to add a /etc/k0s/containerd.d/xxxx.toml with this content:

```
version = 2

[plugins]

  [plugins."io.containerd.grpc.v1.cri"]

    [plugins."io.containerd.grpc.v1.cri".registry]
      config_path = "/etc/k0s/certs.d"

```

idea is to be able to configure private registries in `/etc/k0s/certs.d`

Issue is /run/k0s/containerd-cri.toml concatenate the files instead of merging so containerd does not start anymore and certs.d is ignored.

### Expected behavior

containerd.d files are merged respecting their prefix if a number (as in most unix `.d` folders) and file is readable.
No error starting: `containerd: failed to load TOML: /run/k0s/containerd-cri.toml: (136, 2): duplicated tables`.

### Actual behavior

Node does not start containerd properly.

**Comment by rmannibucau** [comment]
@jnummelin the same than dumping the default one with `k0s` binary and concatenating the other ones (a single one) so something like `cat /etc/k0s/containerd.default.yaml /etc/k0s/containerd.d/*.yaml > merged.yaml` in terms of behavior.

**Comment by jnummelin** [comment]
I see where the issue is now. The main use case we had for this was to enable additional runtimes (such as gVisor etc.) where the TOML keys are NOT overlapping with the default CRI config. So essentially we need to figure out how to actually merge the toml configs rather than concatenate them to make your use case work.

**Comment by stevefan1999-personal** [comment]
@jnummelin Yep. A simple example is to change the default snapshotter to ZFS:

```toml
[plugins."io.containerd.grpc.v1.cri".containerd]
  snapshotter = "zfs"
  
```

Try this: [mesosphere/toml-merge: A utility to merge TOML configuration, especially useful for containerd config. (github.com)](https://github.com/mesosphere/toml-merge)

**Comment by jnummelin** [comment]
@stevefan1999-personal Thanks for pointing us to https://github.com/mesosphere/toml-merge, that seems to do the job nicely for this. See https://github.com/k0sproject/k0s/pull/3412
