### ISSUE TITLE
Remove config option `spec.api.tunneledNetworkingMode`

### ISSUE THREAD

**Issue by jnummelin** [k0sproject/k0s#3381]
Let's remove the option for `[spec.api.tunneledNetworkingMode](https://docs.k0sproject.io/v1.27.4+k0s.0/configuration/#specapi)`

It has been always very undocumented feature and the use is extremely minimal.

## Why remove

This feature forces us to maintain our own [fork](https://github.com/k0sproject/apiserver-network-proxy) of konnectivity. The very unfortunate fact is that upstream has declined the original PR implementing this feature from which point our fork is created. That renders keeping up-to-date with upstream practically impossible now.

**Comment by twz123** [comment]
This was done in #3441.
