### ISSUE TITLE
Question: How can i Update OpenEBS?

### ISSUE THREAD

**Issue by hofq** [k0sproject/k0s#3433]
### Before creating an issue, make sure you've checked the following:

- [X] You are running the latest released version of k0s
- [X] Make sure you've searched for existing issues, both open and closed
- [X] Make sure you've searched for PRs too, a fix might've been merged already
- [X] You're looking at docs for the released version, "main" branch docs are usually ahead of released versions.

### Platform

```shell
Debian 12 Bookworm
```

### Version

v1.27.4+k0s.0

### Sysinfo

<details><summary>`k0s sysinfo`</summary>
<pre>
Total memory: 31.3 GiB (pass)
Disk space available for /var/lib/k0s: 865.2 GiB (pass)
Operating system: Linux (pass)
  Linux kernel release: 6.1.0-10-amd64 (pass)
  Max. file descriptors per process: current: 1048576 / max: 1048576 (pass)
  Executable in path: modprobe: /usr/sbin/modprobe (pass)
  /proc file system: mounted (0x9fa0) (pass)
  Control Groups: version 2 (pass)
    cgroup controller "cpu": available (pass)
    cgroup controller "cpuacct": available (via cpu in version 2) (pass)
    cgroup controller "cpuset": available (pass)
    cgroup controller "memory": available (pass)
    cgroup controller "devices": available (assumed) (pass)
    cgroup controller "freezer": available (assumed) (pass)
    cgroup controller "pids": available (pass)
    cgroup controller "hugetlb": available (pass)
    cgroup controller "blkio": available (via io in version 2) (pass)
  CONFIG_CGROUPS: Control Group support: built-in (pass)
    CONFIG_CGROUP_FREEZER: Freezer cgroup subsystem: built-in (pass)
    CONFIG_CGROUP_PIDS: PIDs cgroup subsystem: built-in (pass)
    CONFIG_CGROUP_DEVICE: Device controller for cgroups: built-in (pass)
    CONFIG_CPUSETS: Cpuset support: built-in (pass)
    CONFIG_CGROUP_CPUACCT: Simple CPU accounting cgroup subsystem: built-in (pass)
    CONFIG_MEMCG: Memory Resource Controller for Control Groups: built-in (pass)
    CONFIG_CGROUP_HUGETLB: HugeTLB Resource Controller for Control Groups: built-in (pass)
    CONFIG_CGROUP_SCHED: Group CPU scheduler: built-in (pass)
      CONFIG_FAIR_GROUP_SCHED: Group scheduling for SCHED_OTHER: built-in (pass)
        CONFIG_CFS_BANDWIDTH: CPU bandwidth provisioning for FAIR_GROUP_SCHED: built-in (pass)
    CONFIG_BLK_CGROUP: Block IO controller: built-in (pass)
  CONFIG_NAMESPACES: Namespaces support: built-in (pass)
    CONFIG_UTS_NS: UTS namespace: built-in (pass)
    CONFIG_IPC_NS: IPC namespace: built-in (pass)
    CONFIG_PID_NS: PID namespace: built-in (pass)
    CONFIG_NET_NS: Network namespace: built-in (pass)
  CONFIG_NET: Networking support: built-in (pass)
    CONFIG_INET: TCP/IP networking: built-in (pass)
      CONFIG_IPV6: The IPv6 protocol: built-in (pass)
    CONFIG_NETFILTER: Network packet filtering framework (Netfilter): built-in (pass)
      CONFIG_NETFILTER_ADVANCED: Advanced netfilter configuration: built-in (pass)
      CONFIG_NF_CONNTRACK: Netfilter connection tracking support: module (pass)
      CONFIG_NETFILTER_XTABLES: Netfilter Xtables support: module (pass)
        CONFIG_NETFILTER_XT_TARGET_REDIRECT: REDIRECT target support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_COMMENT: "comment" match support: module (pass)
        CONFIG_NETFILTER_XT_MARK: nfmark target and match support: module (pass)
        CONFIG_NETFILTER_XT_SET: set target and match support: module (pass)
        CONFIG_NETFILTER_XT_TARGET_MASQUERADE: MASQUERADE target support: module (pass)
        CONFIG_NETFILTER_XT_NAT: "SNAT and DNAT" targets support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_ADDRTYPE: "addrtype" address type match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_CONNTRACK: "conntrack" connection tracking match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_MULTIPORT: "multiport" Multiple port match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_RECENT: "recent" match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_STATISTIC: "statistic" match support: module (pass)
      CONFIG_NETFILTER_NETLINK: module (pass)
      CONFIG_NF_NAT: module (pass)
      CONFIG_IP_SET: IP set support: module (pass)
        CONFIG_IP_SET_HASH_IP: hash:ip set support: module (pass)
        CONFIG_IP_SET_HASH_NET: hash:net set support: module (pass)
      CONFIG_IP_VS: IP virtual server support: module (pass)
        CONFIG_IP_VS_NFCT: Netfilter connection tracking: built-in (pass)
      CONFIG_NF_CONNTRACK_IPV4: IPv4 connetion tracking support (required for NAT): unknown (warning)
      CONFIG_NF_REJECT_IPV4: IPv4 packet rejection: module (pass)
      CONFIG_NF_NAT_IPV4: IPv4 NAT: unknown (warning)
      CONFIG_IP_NF_IPTABLES: IP tables support: module (pass)
        CONFIG_IP_NF_FILTER: Packet filtering: module (pass)
          CONFIG_IP_NF_TARGET_REJECT: REJECT target support: module (pass)
        CONFIG_IP_NF_NAT: iptables NAT support: module (pass)
        CONFIG_IP_NF_MANGLE: Packet mangling: module (pass)
      CONFIG_NF_DEFRAG_IPV4: module (pass)
      CONFIG_NF_CONNTRACK_IPV6: IPv6 connetion tracking support (required for NAT): unknown (warning)
      CONFIG_NF_NAT_IPV6: IPv6 NAT: unknown (warning)
      CONFIG_IP6_NF_IPTABLES: IP6 tables support: module (pass)
        CONFIG_IP6_NF_FILTER: Packet filtering: module (pass)
        CONFIG_IP6_NF_MANGLE: Packet mangling: module (pass)
        CONFIG_IP6_NF_NAT: ip6tables NAT support: module (pass)
      CONFIG_NF_DEFRAG_IPV6: module (pass)
    CONFIG_BRIDGE: 802.1d Ethernet Bridging: module (pass)
      CONFIG_LLC: module (pass)
      CONFIG_STP: module (pass)
  CONFIG_EXT4_FS: The Extended 4 (ext4) filesystem: module (pass)
  CONFIG_PROC_FS: /proc file system support: built-in (pass)
</pre>
</details>

### What happened?

I have a potential Memory Leak Issue with my OpenEBS LocalPath Storage provider.

To fix the Potential Issue i wanted to Bump the NDM Version from 2.0 to 2.1.0 as stated [here](https://github.com/openebs/openebs/issues/3564#issuecomment-1547738366)

To Upgrade the NDM Version i opted to bump the helm chart in the helm.k0sproject.io/Chart OpenEBS Ressource. So i set the Version in the Spec Section to "3.8.0" as this version of the Helm Chart uses 2.1.0 of NDM per default.

The Problem is that nothing happens and the Version of OpenEBS does not get upgraded.

### Steps to reproduce

1. Set Version of OpenEBS chart to 3.8.0 (in `helm.k0sproject.io/Chart -> spec.version: 3.8.0`)
2. Restart the Cluster
3. Status and Deployment does not get updated

### Expected behavior

The Version of the OpenEBS chart should increase.

### Actual behavior

The Version of the Chart in the Status Section does not increase and stays at 3.3.0 . The Revision and Updated Section get Updated but not the Version.

### Screenshots and logs

Files:
<details><summary>k0s-addon-chart-openebs</summary>
<pre>
status:
  appVersion: 3.3.0
  namespace: openebs
  releaseName: openebs
  revision: 31
  updated: 2023-08-28 16:34:41.056741425 +0200 CEST m=+121.896691460
  version: 3.3.0
spec:
  chartName: openebs-internal/openebs
  namespace: openebs
  releaseName: openebs
  timeout: 30m0s
  values: |

    localprovisioner:
      hostpathClass:
        enabled: true
        isDefaultClass: true
  version: 3.8.0
</pre>
</details>

Screenshots:
![grafik](https://github.com/k0sproject/k0s/assets/54744977/e28df576-cc72-448f-beb4-a32d0ce77862)

### Additional context

*Note that my Process was based on other Documentation Sections as there is no Upgrade Path for OpenEBS in K0s Documented.*

**Comment by hofq** [comment]
@jnummelin can you bump the OpenEBS Version in the Next Release?
Currently i have to restart my Node Every Day to clear the Memory

**Comment by hofq** [comment]
> Skimmed through the referenced issue, but is there a OpenEBS fix available on some release?
> 
> If there is a known fixed version, we can look into upgrading it in k0s

3.4.0 of the Helm Chart should already include the mentioned fix [here](https://github.com/openebs/charts/commit/34a030cb322f79c83bd8bcab009f33c5ade1c247) since it upgrades NDM from 2.0 to 2.1. If you choose to bump to a newer version, that also shouldn't harm.

Thanks for your help

**Comment by juanluisvaladas** [comment]
Hi @hofq,
The version is hardcoded so the maintainers had a discussion about the best way of doing this.

Currently the controller just deploys a helm chart, so we've decided that it makes more sense to document this as yet another helm extension [such as rook](https://docs.k0sproject.io/v1.27.5+k0s.0/examples/rook-ceph/).

So what we're going to do is:

1- Documenting how to migrate from [the bundled configuration](https://docs.k0sproject.io/v1.27.5+k0s.0/storage/?h=openebs#bundled-openebs-storage) to a [helm chart in k0s configuration](https://docs.k0sproject.io/v1.27.5+k0s.0/helm-charts/)
2- Once the documentation is clear, we'll deprecate the [bundled configuration](https://docs.k0sproject.io/v1.27.5+k0s.0/storage/?h=openebs#bundled-openebs-storage) in favor of the extension.

Once you've migrated it to a helm chart, you can just migrate openEBS as you normally would.

Does this solution sound reasonable to you?
Thanks in advance for the feedback.

**Comment by hofq** [comment]
> Hi @hofq, The version is hardcoded so the maintainers had a discussion about the best way of doing this.
> 
> Currently the controller just deploys a helm chart, so we've decided that it makes more sense to document this as yet another helm extension [such as rook](https://docs.k0sproject.io/v1.27.5+k0s.0/examples/rook-ceph/).
> 
> So what we're going to do is:
> 
> 1- Documenting how to migrate from [the bundled configuration](https://docs.k0sproject.io/v1.27.5+k0s.0/storage/?h=openebs#bundled-openebs-storage) to a [helm chart in k0s configuration](https://docs.k0sproject.io/v1.27.5+k0s.0/helm-charts/) 2- Once the documentation is clear, we'll deprecate the [bundled configuration](https://docs.k0sproject.io/v1.27.5+k0s.0/storage/?h=openebs#bundled-openebs-storage) in favor of the extension.
> 
> Once you've migrated it to a helm chart, you can just migrate openEBS as you normally would.
> 
> Does this solution sound reasonable to you? Thanks in advance for the feedback.

This sounds perfect! Looking forward to your implementation :)

**Comment by juanluisvaladas** [comment]
Hi, I was working on this and found #3282 so I need to fix this first.

**Comment by hofq** [comment]
Would be nice if you could bump the openebs version in the next release, that would at least fix my local issues with openebs
