### ISSUE TITLE
Kernel modules not being loaded

### ISSUE THREAD

**Issue by mbentley** [k0sproject/k0s#349]
**Version**
```
$ mke version
v0.6.0
```
**Platform**
Which platform did you run mke on?
```
$ lsb_release -a
n/a; Alpine Linux 3.12.1
```
**What happened?**
When starting mke, it says that it is loading the kernel modules but it fails:

```
WARN[2020-10-30 17:48:07] failed to load overlay kernel module: /sbin/modprobe overlay
WARN[2020-10-30 17:48:07] failed to load nf_conntrack kernel module: /sbin/modprobe nf_conntrack
WARN[2020-10-30 17:48:07] failed to load br_netfilter kernel module: /sbin/modprobe br_netfilter
INFO[2020-10-30 17:48:07] I1030 17:48:07.940768    2417 cache.go:39] Caches are synced for autoregister controller  component=kube-apiserver
INFO[2020-10-30 17:48:07] I1030 17:48:07.943509    2418 registry.go:173] Registering SelectorSpread plugin  component=kube-scheduler
INFO[2020-10-30 17:48:07] I1030 17:48:07.943535    2418 registry.go:173] Registering SelectorSpread plugin  component=kube-scheduler
WARN[2020-10-30 17:48:07] Failed to enable /proc/sys/net/bridge/bridge-nf-call-iptables: open /proc/sys/net/bridge/bridge-nf-call-iptables: no such file or directory
WARN[2020-10-30 17:48:07] Failed to enable /proc/sys/net/bridge/bridge-nf-call-ip6tables: open /proc/sys/net/bridge/bridge-nf-call-ip6tables: no such file or directory
```

**How To Reproduce**
Start mke (make sure to enable as a worker) without those kernel modules loaded, watch for logs once things start to come up

**Expected behavior**
the modprobe commands should work
```
alpine1:~# which modprobe
/sbin/modprobe
```

I can manually load the kernel modules myself just fine.

**Screenshots & Logs**
See logs above.

**Additional context**
Tests might not hit this if running inside of Docker; Docker would have already loaded those kernel modules most likely.  Something else might be loading some of the kernel modules after running but it seems odd that it would be shelling out and doing the exact commands that it should to load the kernel modules yet it doesn't load them successfully.

**Comment by jnummelin** [comment]
@mbentley have you seen this with later versions of k0s? We haven't seen this in any of our testings thus not sure if this is really k0s issue or not?

**Comment by mbentley** [comment]
No, I haven't seen issues in recent versions of k0s.  I think this can be closed.
