### ISSUE TITLE
New pre-flight check for IPVS/ipest support

### ISSUE THREAD

**Issue by twz123** [k0sproject/k0s#3502]
### Is your feature request related to a problem? Please describe.

K0s can run kube-proxy in IPVS mode, if configured. This may fail on some systems that don't support IPVS, i.e. don't have the required dependencies installed. On those systems, kube-proxy in IPVS mode will be crash-looping.

### Describe the solution you would like

We could consider to add a pre-flight check for IPVS, along the lines of [k8s's `ipvs.CanUseIPVSProxier`](https://pkg.go.dev/k8s.io/kubernetes@v1.28.2/pkg/proxy/ipvs#CanUseIPVSProxier).

### Describe alternatives you've considered

Don't add it. Approprate error messages are not too deeply buried in the kube-proxy logs. But still, might be helpful to have this info up-front, when troubleshooting.

### Additional context

IPVS support needs to have some kernel modules loaded. Kube-proxy tries to be helpful and tries to load those beforehand. The feature detection will fail without those modules being loaded, but still, it might work after kube-proxy could load them. The pre-flight checks probably shouldn't try to load them. But: there might be dragons: [k/k#108877](https://github.com/kubernetes/kubernetes/issues/108877).

**Comment by twz123** [comment]
Kube-router requires ipset, so makes sense to check for that, too. See #3673.

**Comment by ncopa** [comment]
I wonder if it would make more sense to simply bundle `ipset` binary with k0s. I believe it it less than 200k.

**Comment by twz123** [comment]
The ipset binary is really only required by kube-proxy and kube-router. Both are run as OCI images and ship their own version of ipset. Bundling ipset with k0s would merely allow k0s to execute `ipvs.CanUseIPVSProxier`, which is relying on its presence. This may or may not be a sufficient argument for inclusion. OTOH, maybe k0s can incorporate some other checks, like checking for the kernel module being present/loaded...

**Comment by twz123** [comment]
Probably doesn't make sense to have this pre-flight check, as k0s would need to bundle an additional binary just for that.
