### ISSUE TITLE
Add Alpine 3.20 to OS testing matrix

### ISSUE THREAD

**Issue by twz123** [k0sproject/k0s#3503]
### Is your feature request related to a problem? Please describe.

Alpine 3.20 isn't currently tested in the OS testing matrix.

### Describe the solution you would like

Add it to the matrix.

### Additional context

I've had problems getting SSH logins to work back in the day, that's why it hasn't been added until now. Probably just needs the right config settings.

**Comment by kke** [comment]
An image will be available at quay once footloose fork release is rolled out.

**Comment by twz123** [comment]
Bump to 3.20 :upside_down_face:
