### ISSUE TITLE
Add fallback for missing /etc/machine-id

### ISSUE THREAD

**Issue by ncopa** [k0sproject/k0s#353]
**Is your feature request related to a problem? Please describe.**
There is no guarantee that `/etc/machine-id` exists on the host system. Would be convenient with a fallback if it doesn't.

**Describe the solution you'd like**
Would be nice if mke would:
- use `/var/lib/mke/machine-id` if it exists. If not:
  - copy `/etc/machine-id` to `/var/lib/mke/machine-id` if it exists, otherwise:
    - generate our own machine id and store as `/var/lib/mke/machine-id`

**Describe alternatives you've considered**

Other option would be to use checksum(hostname) as fallback.

Alternatively we could also let `mke` create `/etc/machine-id` if its missing. It shouldn't hurt anything.

**Additional context**
I think `kubelet` may require a working `/etc/machine-id` so maybe the best idea is to generate it if it is missing.

**Comment by phroggyy** [comment]
I believe https://github.com/denisbrodbeck/machineid is used for machineid, so I'd amend this to say that we use the output of that library as the fallback (just rather than /etc/machine-id). I like the idea of keeping it in /var/lib/k0s, so that K0s doesn't need root perms for writing to /etc

**Comment by ncopa** [comment]
So, the problem is that https://github.com/denisbrodbeck/machineid return error if `/etc/machine-id` is missing. I was thinking:
```diff
diff --git a/pkg/util/machineid.go b/pkg/util/machineid.go
index 1f12bc7..792aac7 100644
--- a/pkg/util/machineid.go
+++ b/pkg/util/machineid.go
@@ -4,5 +4,9 @@ import "github.com/denisbrodbeck/machineid"
 
 // MachineID returns protected id for the current machine
 func MachineID() (string, error) {
-       return machineid.ProtectedID("k0sproject-k0s")
+       id, err := machineid.ProtectedID("k0sproject-k0s")
+       if err != nil {
+               // do the fallback
+       }
+       return id, nil
 }
```

I think we should try create the `/etc/machine-id` if its missing since kubelet will fail without it anyway. But it may be a bit controversial?
