### ISSUE TITLE
How to read the API Server logs?

### ISSUE THREAD

**Issue by CmdrSharp** [k0sproject/k0s#3535]
Given that the kube-apiserver is tucked away (seemingly regardless of whether the controllers are also workers) - where would one go to read their logs in order to troubleshoot potential issues? Looking into /var/logs on our Flatcar machines, we can't seem to identify any k0s-related logs.

**Comment by twz123** [comment]
K0s logs to stdout, so it depends on how you start it. If you're using systemd, the logs should be available via `journalctl`.

**Comment by CmdrSharp** [comment]
Nevermind; my bad - I was looking at the wrong machine :) journalctl indeed logs it with `component=kube-apiserver`.
Thanks!
