### ISSUE TITLE
node fails to configure network properly

### ISSUE THREAD

**Issue by iggy** [k0sproject/k0s#3673]
### Before creating an issue, make sure you've checked the following:

- [X] You are running the latest released version of k0s
- [X] Make sure you've searched for existing issues, both open and closed
- [X] Make sure you've searched for PRs too, a fix might've been merged already
- [X] You're looking at docs for the released version, "main" branch docs are usually ahead of released versions.

### Platform

```shell
A mixture of Alpine and Ubuntu normally, but I've narrowed it down to a reproducer on just 1 or 2 Alpine nodes
```

### Version

v1.28.2

### Sysinfo

<details><summary>`k0s sysinfo`</summary>
<pre>
Machine ID: "22d777860d5887635c83059ae6845fe34e78e475fd215b1ced086b821b8f8aec" (from machine) (pass)
Total memory: 3.8 GiB (pass)
Disk space available for /var/lib/k0s: 2.9 TiB (pass)
Name resolution: localhost: [127.0.0.1 ::1] (pass)
Operating system: Linux (pass)
  Linux kernel release: 6.3.6 (pass)
  Max. file descriptors per process: current: 4096 / max: 4096 (warning: < 65536)
  AppArmor: unavailable (pass)
  Executable in path: umount: /bin/umount (pass)
  Executable in path: umount: /bin/umount (pass)
  Executable in path: umount: /bin/umount (pass)
  /proc file system: mounted (0x9fa0) (pass)
  Control Groups: version 1 (pass)
    cgroup controller "cpu": available (pass)
    cgroup controller "cpuacct": available (pass)
    cgroup controller "cpuset": available (pass)
    cgroup controller "memory": available (pass)
    cgroup controller "devices": available (pass)
    cgroup controller "freezer": available (pass)
    cgroup controller "pids": available (pass)
    cgroup controller "hugetlb": available (pass)
    cgroup controller "blkio": available (pass)
  CONFIG_CGROUPS: Control Group support: no kernel config found (warning)
  CONFIG_NAMESPACES: Namespaces support: no kernel config found (warning)
  CONFIG_NET: Networking support: no kernel config found (warning)
  CONFIG_EXT4_FS: The Extended 4 (ext4) filesystem: no kernel config found (warning)
  CONFIG_PROC_FS: /proc file system support: no kernel config found (warning)
---
Machine ID: "44a67ef57997b64d28a609865914c18a916dfec299a3f0d698de76f0a6394d94" (from machine) (pass)
Total memory: 62.7 GiB (pass)
Disk space available for /var/lib/k0s: 2.9 TiB (pass)
Name resolution: localhost: [::1 127.0.0.1] (pass)
Operating system: Linux (pass)
  Linux kernel release: 6.5.0+ (pass)
  Max. file descriptors per process: current: 4096 / max: 4096 (warning: < 65536)
  AppArmor: unavailable (pass)
  Executable in path: umount: /bin/umount (pass)
  Executable in path: umount: /bin/umount (pass)
  Executable in path: umount: /bin/umount (pass)
  /proc file system: mounted (0x9fa0) (pass)
  Control Groups: version 2 (pass)
    cgroup controller "cpu": available (pass)
    cgroup controller "cpuacct": available (via cpu in version 2) (pass)
    cgroup controller "cpuset": available (pass)
    cgroup controller "memory": available (pass)
    cgroup controller "devices": available (assumed) (pass)
    cgroup controller "freezer": available (assumed) (pass)
    cgroup controller "pids": available (pass)
    cgroup controller "hugetlb": available (pass)
    cgroup controller "blkio": available (via io in version 2) (pass)
  CONFIG_CGROUPS: Control Group support: built-in (pass)
    CONFIG_CGROUP_FREEZER: Freezer cgroup subsystem: built-in (pass)
    CONFIG_CGROUP_PIDS: PIDs cgroup subsystem: built-in (pass)
    CONFIG_CGROUP_DEVICE: Device controller for cgroups: built-in (pass)
    CONFIG_CPUSETS: Cpuset support: built-in (pass)
    CONFIG_CGROUP_CPUACCT: Simple CPU accounting cgroup subsystem: built-in (pass)
    CONFIG_MEMCG: Memory Resource Controller for Control Groups: built-in (pass)
    CONFIG_CGROUP_HUGETLB: HugeTLB Resource Controller for Control Groups: built-in (pass)
    CONFIG_CGROUP_SCHED: Group CPU scheduler: built-in (pass)
      CONFIG_FAIR_GROUP_SCHED: Group scheduling for SCHED_OTHER: built-in (pass)
        CONFIG_CFS_BANDWIDTH: CPU bandwidth provisioning for FAIR_GROUP_SCHED: built-in (pass)
    CONFIG_BLK_CGROUP: Block IO controller: built-in (pass)
  CONFIG_NAMESPACES: Namespaces support: built-in (pass)
    CONFIG_UTS_NS: UTS namespace: built-in (pass)
    CONFIG_IPC_NS: IPC namespace: built-in (pass)
    CONFIG_PID_NS: PID namespace: built-in (pass)
    CONFIG_NET_NS: Network namespace: built-in (pass)
  CONFIG_NET: Networking support: built-in (pass)
    CONFIG_INET: TCP/IP networking: built-in (pass)
      CONFIG_IPV6: The IPv6 protocol: built-in (pass)
    CONFIG_NETFILTER: Network packet filtering framework (Netfilter): built-in (pass)
      CONFIG_NETFILTER_ADVANCED: Advanced netfilter configuration: built-in (pass)
      CONFIG_NF_CONNTRACK: Netfilter connection tracking support: built-in (pass)
      CONFIG_NETFILTER_XTABLES: Netfilter Xtables support: built-in (pass)
        CONFIG_NETFILTER_XT_TARGET_REDIRECT: REDIRECT target support: built-in (pass)
        CONFIG_NETFILTER_XT_MATCH_COMMENT: "comment" match support: built-in (pass)
        CONFIG_NETFILTER_XT_MARK: nfmark target and match support: built-in (pass)
        CONFIG_NETFILTER_XT_SET: set target and match support: built-in (pass)
        CONFIG_NETFILTER_XT_TARGET_MASQUERADE: MASQUERADE target support: built-in (pass)
        CONFIG_NETFILTER_XT_NAT: "SNAT and DNAT" targets support: built-in (pass)
        CONFIG_NETFILTER_XT_MATCH_ADDRTYPE: "addrtype" address type match support: built-in (pass)
        CONFIG_NETFILTER_XT_MATCH_CONNTRACK: "conntrack" connection tracking match support: built-in (pass)
        CONFIG_NETFILTER_XT_MATCH_MULTIPORT: "multiport" Multiple port match support: built-in (pass)
        CONFIG_NETFILTER_XT_MATCH_RECENT: "recent" match support: built-in (pass)
        CONFIG_NETFILTER_XT_MATCH_STATISTIC: "statistic" match support: built-in (pass)
      CONFIG_NETFILTER_NETLINK: built-in (pass)
      CONFIG_NF_NAT: built-in (pass)
      CONFIG_IP_SET: IP set support: built-in (pass)
        CONFIG_IP_SET_HASH_IP: hash:ip set support: built-in (pass)
        CONFIG_IP_SET_HASH_NET: hash:net set support: built-in (pass)
      CONFIG_IP_VS: IP virtual server support: built-in (pass)
        CONFIG_IP_VS_NFCT: Netfilter connection tracking: built-in (pass)
        CONFIG_IP_VS_SH: Source hashing scheduling: built-in (pass)
        CONFIG_IP_VS_RR: Round-robin scheduling: built-in (pass)
        CONFIG_IP_VS_WRR: Weighted round-robin scheduling: built-in (pass)
      CONFIG_NF_CONNTRACK_IPV4: IPv4 connetion tracking support (required for NAT): unknown (warning)
      CONFIG_NF_REJECT_IPV4: IPv4 packet rejection: built-in (pass)
      CONFIG_NF_NAT_IPV4: IPv4 NAT: unknown (warning)
      CONFIG_IP_NF_IPTABLES: IP tables support: built-in (pass)
        CONFIG_IP_NF_FILTER: Packet filtering: built-in (pass)
          CONFIG_IP_NF_TARGET_REJECT: REJECT target support: built-in (pass)
        CONFIG_IP_NF_NAT: iptables NAT support: built-in (pass)
        CONFIG_IP_NF_MANGLE: Packet mangling: built-in (pass)
      CONFIG_NF_DEFRAG_IPV4: built-in (pass)
      CONFIG_NF_CONNTRACK_IPV6: IPv6 connetion tracking support (required for NAT): unknown (warning)
      CONFIG_NF_NAT_IPV6: IPv6 NAT: unknown (warning)
      CONFIG_IP6_NF_IPTABLES: IP6 tables support: built-in (pass)
        CONFIG_IP6_NF_FILTER: Packet filtering: built-in (pass)
        CONFIG_IP6_NF_MANGLE: Packet mangling: built-in (pass)
        CONFIG_IP6_NF_NAT: ip6tables NAT support: built-in (pass)
      CONFIG_NF_DEFRAG_IPV6: built-in (pass)
    CONFIG_BRIDGE: 802.1d Ethernet Bridging: built-in (pass)
      CONFIG_LLC: built-in (pass)
      CONFIG_STP: built-in (pass)
  CONFIG_EXT4_FS: The Extended 4 (ext4) filesystem: built-in (pass)
  CONFIG_PROC_FS: /proc file system support: built-in (pass)
</pre>
</details>

### What happened?

`kube-router` pod on the worker node (also happened when I tried controller+worker) goes into `CrashLoopBackOff`. I found a similar (but unrelated afaict) issue #1334 that at least lead me to figure out that the subnet isn't being populated in `/etc/cni/net.d/10-kuberouter.conflist`. Unlike that other issue, I do see `podCIDR` in the `kc get no` output.

The node in question has a bridge setup. `br0` is connected to `eth0`. The bridge is the main interface, so I know it's working as expected (also I can start VMs using the bridge and they work as well).

I don't see anything super useful in the k0s logs. I can't get the pod logs due to a `No agent available` error.

### Steps to reproduce

I'm not entirely sure. The config is pretty standard, but I haven't tried to reproduce it anywhere else. I don't have any more hardware to try to reproduce it locally. I have broken it down to the simplest config to try to narrow down possibilities.

1. Create a 1 or 2 node cluster
2.
3.

### Screenshots and logs

```
# k0s kubectl logs
Error: cannot stat k0s kubeconfig, is the server running?: stat /var/lib/k0s/pki/admin.conf: no such file or directory
```
Trying to pull logs using the kubeconfig output by `k0s kubeconfig` fails with the above error about no agent available

### Additional context

I was initially seeing this in a multi-controller cluster (where the node in question was a controller). I also reproduced it in a single node cluster and a single controller+single worker (where the node in question was a worker).

I have another node that has a bride setup that seems to be working okay (at least the kube-router pod starts on it).

**Comment by jnummelin** [comment]
You should see the pod logs on disk at /var/log/containers/...

If Kube-router is crashing, hopefully the logs have some clue

**Comment by iggy** [comment]
TIL the logs were right there the whole time. Turned out to be a missing kernel config bit (I have to build my own on this box for bcachefs). It was some QoS stuff which I didn't expect to be required. Not sure if it makes sense to check for that in `k0s sysinfo`. I know you can't check for every single required setting.

For posterity, the missing config was `CONFIG_NET_EMATCH_IPSET`. Which is only accessible if you first enable some other QoS stuff. `Networking support` -> `Networking options` -> `QoS and/or fair queueing` -> `Extended Matches` -> `IPset`

Thank you for the quick response @jnummelin

**Comment by jnummelin** [comment]
We definitely need to check and understand in which cases kube-router needs `CONFIG_NET_EMATCH_IPSET `. And also then add it to the sysprobes we have in place. The whole idea of those is to bring forward these sort of issues BEFORE anything else starts and the problems get harder to diagnose.

**Comment by jnummelin** [comment]
Dug a bit into this. Kube-router is using `ipset` in network policy and route controllers.

Most of the kernel checks k0s does is implemented using Kubernetes sys probes. Kube-proxy does not AFAIK use `ipset` unless it's running in ipvs mode. And ipvs not being the default, I believe Kubernetes probes are omitting those required modules.

Thus IMO we need to add `CONFIG_NET_EMATCH_IPSET`, and maybe some other related ones, into k0s sysprobes.

@twz123 WDYT?

**Comment by twz123** [comment]
IIRC we have the k0s config available when running the sysprobes, so we can probably conditionally require that kernel config if IPVS is used. Maybe that applies not only to Kube-Router, but also to Calico?

**Comment by twz123** [comment]
The sysprobe stuff is being tracked in #3502.
