### ISSUE TITLE
Support for Kube-Proxy's nftables backend (KEP-3866)

### ISSUE THREAD

**Issue by twz123** [k0sproject/k0s#3702]
### Is your feature request related to a problem? Please describe.

Kube-Proxy is about to get the new nftables backend as described in [KEP-3866].

[KEP-3866]: https://github.com/kubernetes/enhancements/blob/master/keps/sig-network/3866-nftables-proxy/README.md

### Describe the solution you would like

Support for this in k0s.

### Additional context

The kube-proxy image will need the `nft` binary for this to work.

**Comment by jnummelin** [comment]
Implemented in #4934, docs coming in #5038
