### ISSUE TITLE
How to change worker profiles on an already installed cluster

### ISSUE THREAD

**Issue by Mihai-CMM** [k0sproject/k0s#3703]
### Before creating an issue, make sure you've checked the following:

- [X] You are running the latest released version of k0s
- [X] Make sure you've searched for existing issues, both open and closed
- [X] Make sure you've searched for PRs too, a fix might've been merged already
- [X] You're looking at docs for the released version, "main" branch docs are usually ahead of released versions.

### Platform

```shell
Hello
How to change the settings (add the eviction thresholds) on an already installed cluster
I had the cluster installed with k0sctl. I see this options for new install
spec:
  workerProfiles:
    - name: custom-eviction
      values:
        evictionHard:
          memory.available: "500Mi"
          nodefs.available: "1Gi"
          imagefs.available: "100Gi"
        evictionMinimumReclaim:
          memory.available: "0Mi"
          nodefs.available: "500Mi"
          imagefs.available: "2Gi"

But how can i add them later

Thank you
```

### Sysinfo

<details><summary>`k0s sysinfo`</summary>
<pre>
➡️ Please replace this text with the output of `k0s sysinfo`. ⬅️
</pre>
</details>

### Steps to reproduce

1.
2.
3.

**Comment by twz123** [comment]
You can edit the k0s config file on your controller nodes accordingly and restart them. After that, you need to restart the worker nodes that should receive the new profile. Don't forget to add the `--profile=custom-eviction` to your k0s start script on those workers. There's also the `default` worker profile which will be taken by workers for which no special profile has been specified.

Note that when you are using dynamic config, then you don't need to edit the config files on the controllers, and don't need to restart them, but rather edit the custom ClusterConfig resource `k0s`. The workers need to be restarted, nevertheless.

**Comment by Mihai-CMM** [comment]
thank you
