### ISSUE TITLE
Docs: "Get Started" link on website leads to old version of docs

### ISSUE THREAD

**Issue by makkes** [k0sproject/k0s#3708]
### Before creating an issue, make sure you've checked the following:

- [X] You are running the latest released version of k0s
- [X] Make sure you've searched for existing issues, both open and closed
- [X] Make sure you've searched for PRs too, a fix might've been merged already
- [X] You're looking at docs for the released version, "main" branch docs are usually ahead of released versions.

### What happened?

The "Get started" link on https://k0sproject.io/ leads to old version of the docs.

### Steps to reproduce

1. Go to https://k0sproject.io/
2. Click the "Get Started" button in the middle of the page

### Expected behavior

I'll see the latest version of the docs

### Actual behavior

I'm sent to https://docs.k0sproject.io/v1.23.6+k0s.2/install/ with a banner at the top saying " You are not currently viewing the documentation for the current stable release of k0s. Click here to go to the documentation of the current stable release. ".

**Comment by twz123** [comment]
Oops. Thanks for pointing out!
