### ISSUE TITLE
quay broken?

### ISSUE THREAD

**Issue by matti** [k0sproject/k0s#3713]
using docker.io/k0sproject/k0s:v1.27.2-k0s.0 because that's what k0smotron uses

```
Error syncing pod, skipping\" err=\"failed to \\\"StartContainer\\\" for \\\"install-cni-bins\\\" with ErrImagePull: \\\"rpc error: code = Unknown desc = failed to pull and unpack image \\\\\\\"quay.io/k0sproject/cni-node:1.1.1-k0s.1\\\\\\\": failed to copy: httpReadSeeker: failed open: unexpected status code https://quay.io/v2/k0sproject/cni-node/blobs/sha256:63b65145d645c1250c391b2d16ebe53b3747c295ca8ba2fcb6b0cf064a4dc21c: 403 Forbidden\\\"\" pod=\"kube-system/kube-router-fqpzd\" podUID=2faba1b7-7c6a-486d-8963-84af79160395" component=kubelet stream=stderr
```

```
$ docker pull quay.io/k0sproject/cni-node:1.1.1-k0s.1
1.1.1-k0s.1: Pulling from k0sproject/cni-node
af6eaf76a39c: Pulling fs layer
20782fa4dd46: Pulling fs layer
7c6d781118ef: Pulling fs layer
7cde727e65a7: Waiting
653055c82d5e: Waiting
error pulling image configuration: download failed after attempts=1: error parsing HTTP 403 response body: invalid character '<' l
```

```
$ docker pull quay.io/v2/k0sproject/cni-node/blobs/sha256:63b65145d645c1250c391b2d16ebe53b3747c295ca8ba2fcb6b0cf064a4dc21c

Error response from daemon: Head "https://quay.io/v2/v2/k0sproject/cni-node/blobs/sha256/manifests/63b65145d645c1250c391b2d16ebe53b3747c295ca8ba2fcb6b0cf064a4dc21c": denied: Namespace v2 has been disabled. Please contact a system administrato
```

**Comment by matti** [comment]
![Uploading image.png…]()

**Comment by matti** [comment]
Update - We are continuing to resolve this issue. Thanks for your patience and we apologize for the inconvenience.
Nov 14, 2023 - 08:55 EST

Identified - We have identified an issue where some pulls of older images may not succeed. We have identified the issue and are working on a fix. We apologize for the inconvenience.
Nov 13, 2023 - 17:04 EST

**Comment by matti** [comment]
![image](https://github.com/k0sproject/k0s/assets/3893/5517e77b-0fcf-4910-8f38-338d4b23396e)

**Comment by matti** [comment]
403 turned to 502

**Comment by jnummelin** [comment]
Not much we can do about Quay downtimes unfortunately

**Comment by matti** [comment]
you could publish the default images to a better service

**Comment by twz123** [comment]
> you could publish the default images to a better service

Open for suggestions. Note that if you're concerned about the stability of quay.io, you can still use k0s's image airgap bundle to pre-install all the images on each node. Moreover, you can override the image registry in the k0s configuration and let it point to another registry under your control. Or you could leverage something like [uber/kraken](https://github.com/uber/kraken) to make image distribution a peer-to-peer thing in your cluster.
