### ISSUE TITLE
On reboot Unable to connect to the server: x509: certificate has expired or is not yet valid

### ISSUE THREAD

**Issue by averagenative** [k0sproject/k0s#3732]
### Before creating an issue, make sure you've checked the following:

- [X] You are running the latest released version of k0s
- [X] Make sure you've searched for existing issues, both open and closed
- [X] Make sure you've searched for PRs too, a fix might've been merged already
- [X] You're looking at docs for the released version, "main" branch docs are usually ahead of released versions.

### Platform

```shell
Linux 5.15.0-88-generic #98-Ubuntu SMP Mon Oct 2 15:18:56 UTC 2023 x86_64 GNU/Linux
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

### Version

v1.28.3+k0s.0

### Sysinfo

<details><summary>`k0s sysinfo`</summary>
<pre>
Machine ID: "6e480565869c6f294ad3b5d39db8279aa42b06412dd614e7e9b6ae772be019d8" (from machine) (pass)
Total memory: 19.5 GiB (pass)
Disk space available for /var/lib/k0s: 262.6 GiB (pass)
Name resolution: localhost: [127.0.0.1] (pass)
Operating system: Linux (pass)
  Linux kernel release: 5.15.0-88-generic (pass)
  Max. file descriptors per process: current: 1048576 / max: 1048576 (pass)
  AppArmor: active (pass)
  Executable in PATH: modprobe: /usr/sbin/modprobe (pass)
  Executable in PATH: mount: /usr/bin/mount (pass)
  Executable in PATH: umount: /usr/bin/umount (pass)
  /proc file system: mounted (0x9fa0) (pass)
  Control Groups: version 2 (pass)
    cgroup controller "cpu": available (pass)
    cgroup controller "cpuacct": available (via cpu in version 2) (pass)
    cgroup controller "cpuset": available (pass)
    cgroup controller "memory": available (pass)
    cgroup controller "devices": available (assumed) (pass)
    cgroup controller "freezer": available (assumed) (pass)
    cgroup controller "pids": available (pass)
    cgroup controller "hugetlb": available (pass)
    cgroup controller "blkio": available (via io in version 2) (pass)
  CONFIG_CGROUPS: Control Group support: built-in (pass)
    CONFIG_CGROUP_FREEZER: Freezer cgroup subsystem: built-in (pass)
    CONFIG_CGROUP_PIDS: PIDs cgroup subsystem: built-in (pass)
    CONFIG_CGROUP_DEVICE: Device controller for cgroups: built-in (pass)
    CONFIG_CPUSETS: Cpuset support: built-in (pass)
    CONFIG_CGROUP_CPUACCT: Simple CPU accounting cgroup subsystem: built-in (pass)
    CONFIG_MEMCG: Memory Resource Controller for Control Groups: built-in (pass)
    CONFIG_CGROUP_HUGETLB: HugeTLB Resource Controller for Control Groups: built-in (pass)
    CONFIG_CGROUP_SCHED: Group CPU scheduler: built-in (pass)
      CONFIG_FAIR_GROUP_SCHED: Group scheduling for SCHED_OTHER: built-in (pass)
        CONFIG_CFS_BANDWIDTH: CPU bandwidth provisioning for FAIR_GROUP_SCHED: built-in (pass)
    CONFIG_BLK_CGROUP: Block IO controller: built-in (pass)
  CONFIG_NAMESPACES: Namespaces support: built-in (pass)
    CONFIG_UTS_NS: UTS namespace: built-in (pass)
    CONFIG_IPC_NS: IPC namespace: built-in (pass)
    CONFIG_PID_NS: PID namespace: built-in (pass)
    CONFIG_NET_NS: Network namespace: built-in (pass)
  CONFIG_NET: Networking support: built-in (pass)
    CONFIG_INET: TCP/IP networking: built-in (pass)
      CONFIG_IPV6: The IPv6 protocol: built-in (pass)
    CONFIG_NETFILTER: Network packet filtering framework (Netfilter): built-in (pass)
      CONFIG_NETFILTER_ADVANCED: Advanced netfilter configuration: built-in (pass)
      CONFIG_NF_CONNTRACK: Netfilter connection tracking support: module (pass)
      CONFIG_NETFILTER_XTABLES: Netfilter Xtables support: module (pass)
        CONFIG_NETFILTER_XT_TARGET_REDIRECT: REDIRECT target support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_COMMENT: "comment" match support: module (pass)
        CONFIG_NETFILTER_XT_MARK: nfmark target and match support: module (pass)
        CONFIG_NETFILTER_XT_SET: set target and match support: module (pass)
        CONFIG_NETFILTER_XT_TARGET_MASQUERADE: MASQUERADE target support: module (pass)
        CONFIG_NETFILTER_XT_NAT: "SNAT and DNAT" targets support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_ADDRTYPE: "addrtype" address type match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_CONNTRACK: "conntrack" connection tracking match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_MULTIPORT: "multiport" Multiple port match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_RECENT: "recent" match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_STATISTIC: "statistic" match support: module (pass)
      CONFIG_NETFILTER_NETLINK: module (pass)
      CONFIG_NF_NAT: module (pass)
      CONFIG_IP_SET: IP set support: module (pass)
        CONFIG_IP_SET_HASH_IP: hash:ip set support: module (pass)
        CONFIG_IP_SET_HASH_NET: hash:net set support: module (pass)
      CONFIG_IP_VS: IP virtual server support: module (pass)
        CONFIG_IP_VS_NFCT: Netfilter connection tracking: built-in (pass)
        CONFIG_IP_VS_SH: Source hashing scheduling: module (pass)
        CONFIG_IP_VS_RR: Round-robin scheduling: module (pass)
        CONFIG_IP_VS_WRR: Weighted round-robin scheduling: module (pass)
      CONFIG_NF_CONNTRACK_IPV4: IPv4 connetion tracking support (required for NAT): unknown (warning)
      CONFIG_NF_REJECT_IPV4: IPv4 packet rejection: module (pass)
      CONFIG_NF_NAT_IPV4: IPv4 NAT: unknown (warning)
      CONFIG_IP_NF_IPTABLES: IP tables support: module (pass)
        CONFIG_IP_NF_FILTER: Packet filtering: module (pass)
          CONFIG_IP_NF_TARGET_REJECT: REJECT target support: module (pass)
        CONFIG_IP_NF_NAT: iptables NAT support: module (pass)
        CONFIG_IP_NF_MANGLE: Packet mangling: module (pass)
      CONFIG_NF_DEFRAG_IPV4: module (pass)
      CONFIG_NF_CONNTRACK_IPV6: IPv6 connetion tracking support (required for NAT): unknown (warning)
      CONFIG_NF_NAT_IPV6: IPv6 NAT: unknown (warning)
      CONFIG_IP6_NF_IPTABLES: IP6 tables support: module (pass)
        CONFIG_IP6_NF_FILTER: Packet filtering: module (pass)
        CONFIG_IP6_NF_MANGLE: Packet mangling: module (pass)
        CONFIG_IP6_NF_NAT: ip6tables NAT support: module (pass)
      CONFIG_NF_DEFRAG_IPV6: module (pass)
    CONFIG_BRIDGE: 802.1d Ethernet Bridging: module (pass)
      CONFIG_LLC: module (pass)
      CONFIG_STP: module (pass)
  CONFIG_EXT4_FS: The Extended 4 (ext4) filesystem: built-in (pass)
  CONFIG_PROC_FS: /proc file system support: built-in (pass)

</pre>
</details>

### What happened?

Followed quickstart guide, verified kubectl access and pod availability. Reboot. On reboot, the generated certs are set for a future timeframe (Not Before: Nov 18 23:31:00 2023 GMT) . Cluster rebooted @ 13:31 EST (GMT-5). API server not available.

### Steps to reproduce

1. curl -sSLf https://get.k0s.sh | sudo sh
2. sudo k0s install controller --single
3. sudo k0s start
4. sudo k0s kubectl get po -A
5. sudo reboot now
6. sudo k0s kubectl get po -A

### Expected behavior

On reboot, generation of certs that are valid for current system time

### Actual behavior

Certs generated are valid 10 hours in the future

### Screenshots and logs

openssl x509 -in /var/lib/k0s/pki/server.crt -noout -text

```Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            61:4e:b9:28:ab:fd:36:2f:3b:30:b1:e0:db:8f:57:93:08:76:73:a5
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: CN = kubernetes-ca
        Validity
            Not Before: Nov 18 23:31:00 2023 GMT
            Not After : Nov 17 23:31:00 2024 GMT
        Subject: O = kubernetes, CN = kubernetes
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (2048 bit)
                Modulus:
                    00:c1:02:8d:8d:ff:58:bf:f2:00:a9:aa:71:99:8d:
                    1c:34:90:c7:8e:f5:1d:15:33:93:cf:14:c9:68:ef:
                    87:a5:1e:3d:0a:00:2e:b1:44:2a:50:b1:57:a7:b2:
                    44:68:7f:11:18:01:e5:1b:43:55:2c:72:cf:fc:86:
                    cb:cb:28:06:2c:f4:c1:e2:66:78:74:1c:fb:70:d3:
                    6a:15:9c:18:39:7b:b7:2f:e3:e1:09:58:82:2b:3f:
                    4a:00:25:84:65:5d:49:c0:2d:34:03:6f:ae:8a:b6:
                    ad:20:ef:c1:b9:8a:e2:1f:34:ff:27:63:d1:46:c2:
                    d0:12:61:ee:6b:29:3d:4a:96:d2:6d:46:88:18:61:
                    f3:9c:b9:6b:02:5c:3e:c8:e4:df:98:05:21:7e:46:
                    93:42:e4:01:82:b5:57:2c:15:0e:ce:44:c9:b0:8c:
                    2c:b8:9c:33:f0:cf:82:22:c4:90:43:01:a4:07:ff:
                    34:9d:6d:54:36:49:73:2b:48:d6:50:97:58:56:96:
                    77:d8:50:ee:bc:9d:4c:82:64:61:65:0a:e7:a8:83:
                    45:90:c9:d0:6e:3d:85:86:56:4a:57:7b:53:c3:47:
                    98:d2:fc:56:f3:e9:47:1d:17:fb:5d:11:27:e7:fe:
                    2d:d4:50:93:e1:70:7f:83:3a:37:1f:37:3e:c7:f5:
                    0e:8b
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Key Usage: critical
                Digital Signature, Key Encipherment
            X509v3 Extended Key Usage: 
                TLS Web Server Authentication, TLS Web Client Authentication
            X509v3 Basic Constraints: critical
                CA:FALSE
            X509v3 Subject Key Identifier: 
                78:66:85:76:EC:B8:8D:E9:EE:72:59:41:05:63:BC:CB:48:6B:34:49
            X509v3 Authority Key Identifier: 
                53:EF:34:07:12:9A:F1:26:F8:EC:F5:6D:7C:A9:73:33:9E:3E:68:43
            X509v3 Subject Alternative Name: 
                DNS:kubernetes, DNS:kubernetes.default, DNS:kubernetes.default.svc, DNS:kubernetes.default.svc.cluster, DNS:kubernetes.svc.cluster.local, DNS:localhost, IP Address:127.0.0.1, IP Address:172.23.18.11, IP Address:FE80:0:0:0:250:56FF:FEB8:6A53, IP Address:10.96.0.1
    Signature Algorithm: sha256WithRSAEncryption
    Signature Value:
        33:7d:25:ba:fe:01:8b:1d:41:8e:e2:2c:68:88:92:71:bb:58:
        b6:bd:0f:d8:d5:d1:da:17:27:7f:58:c9:ba:52:4b:7a:24:b5:
        0e:2d:d6:35:73:35:f6:21:77:46:aa:f9:6b:05:87:5d:6f:ea:
        cf:ae:92:e7:2e:a1:64:e0:7c:bc:cf:d3:3d:a0:10:8a:67:f8:
        1f:27:f8:cd:c8:40:05:1f:f0:23:04:13:de:a9:5c:00:4d:64:
        08:ae:ba:77:d9:e5:1c:a6:6e:e8:92:59:97:1f:43:db:a4:55:
        77:24:5b:42:88:03:cf:e5:6f:be:e2:1e:a9:cf:29:56:dc:13:
        be:6b:c7:59:d4:2d:1b:b7:76:8d:da:95:2e:33:5f:ca:df:a0:
        16:4e:9e:3f:70:0d:90:cc:38:35:ee:50:ad:7d:91:bd:12:d7:
        c6:e7:9d:d7:3a:0c:a7:c4:3c:4a:9a:9c:0a:10:da:42:0c:e1:
        6a:bb:88:9c:70:7a:8c:9e:96:5a:5c:66:74:06:44:f6:4d:97:
        d9:46:e8:5f:57:bd:64:c9:89:32:a2:cd:34:a8:ed:55:3d:a1:
        6b:6b:84:38:ef:56:b6:c0:4c:03:84:c6:ac:f3:76:3a:55:96:
        99:9c:57:6f:2c:54:e0:97:e7:84:f1:d8:1f:b2:46:ea:48:57:
        d8:13:48:36
```

Current time:
```user@host: ~ → date 
Sat Nov 18 01:52:29 PM EST 2023
```

### Additional context

Found related issue here: https://github.com/k0sproject/k0s/issues/1766

Running as a single node test/sandbox cluster

Server running in EST (GMT-5)

**Comment by jnummelin** [comment]
Hmm, would it be possible that k0s regenerate the certs before ntpd starts up?

Maybe look at the system logs to see if it has a clue when NTP kicks in, is that before or after k0s cert generation. On systemd I believe the unit for time sync is systemd-timesynd.

**Comment by averagenative** [comment]
Rebooted again, he's a snippet of journalctl output for the time post-reboot

Is there a command to regenerate certs that I can just run post-boot and restart the cluster?

```
Nov 20 09:27:04 hostname systemd[1]: Starting Network Time Synchronization...
Nov 20 09:27:04 hostname systemd[1]: Starting Record System Boot/Shutdown in UTMP...

Nov 20 09:27:08 hostname systemd-timesyncd[800]: Network configuration changed, trying to establish connection.

Nov 20 09:27:17 hostname containerd[908]: time="2023-11-20T09:27:17.297040392-05:00" level=info msg="starting containerd" revision= version=1.7.2
...
Nov 20 09:27:17 hostname containerd[908]: time="2023-11-20T09:27:17.467500932-05:00" level=info msg="containerd successfully booted in 0.171551s"
Nov 20 09:27:17 hostname systemd[1]: Started containerd container runtime.
Nov 20 09:27:18 hostname k0s[891]: time="2023-11-20 09:27:18" level=info msg="using api address: 172.23.18.11

Nov 20 09:27:32 hostname systemd-timesyncd[800]: Network configuration changed, trying to establish connection.

Nov 20 09:27:32 hostname systemd-timesyncd[800]: Initial synchronization to time server 91.189.91.157:123 (ntp.ubuntu.com).
```

**Comment by jnummelin** [comment]
Based on the logs, here's what _seems_ to happen:

`Nov 20 09:27:18` k0s process starts, one of the first things it does is that it regenerates the serving certs.

`Nov 20 09:27:32` time sync happens. Could this change the system time now AFTER k0s has generated the serving certs? Is there anything more about the timesync, does it's logs have any info when it changes the time, how much it differs etc.?

One thing you could try out is to add `systemd-timesyncd` as a pre-requisite to k0s systemd unit. So something like:

```
root@lima-1284-14135419:/# cat /etc/systemd/system/k0scontroller.service
[Unit]
Description=k0s - Zero Friction Kubernetes
Documentation=https://docs.k0sproject.io
ConditionFileIsExecutable=/usr/local/bin/k0s

After=network-online.target systemd-timesyncd.service
...
```

**Comment by twz123** [comment]
> Is there a command to regenerate certs that I can just run post-boot and restart the cluster?

Simply deleting those from k0s's data directory and a subsequent k0s restart should be enough. K0s will simply generate new ones if they're missing.

New certs also mean that all previously joined nodes have to be rejoined afterwards.

**Comment by averagenative** [comment]
Was able to just wipe out server.crt and server.key from /var/lib

I was able to regenerate certs with the system up, so this seems like a viable workaround
```
sudo su
cd /var/lib/k0s/pki/
rm server*
systemctl restart k0scontroller.service
```

And then your suspicion appears to be confirmed. I was able to update the systemd unit file and it regenerates certs with a workable time

```
04:49:04 user@host ~ → cat /etc/systemd/system/k0scontroller.service 
[Unit]
Description=k0s - Zero Friction Kubernetes
Documentation=https://docs.k0sproject.io
ConditionFileIsExecutable=/usr/local/bin/k0s

After=network-online.target systemd-timesyncd.service 
Wants=network-online.target 

[Service]
StartLimitInterval=5
StartLimitBurst=10
ExecStart=/usr/local/bin/k0s controller --single=true

RestartSec=120
Delegate=yes
KillMode=process
LimitCORE=infinity
TasksMax=infinity
TimeoutStartSec=0
LimitNOFILE=999999
Restart=always

[Install]
WantedBy=multi-user.target
```

Room for an enhancement or just note for systemd hosts?
