### ISSUE TITLE
Copyright boilerplate linter doesn't allow changing the year

### ISSUE THREAD

**Issue by kke** [k0sproject/k0s#3734]
When modifying a file that has the boilerplate, I expect that I should also update the copyright year to the last modified year.

If you do that, the boilerplate linter fails the PR.

**Comment by twz123** [comment]
> When modifying a file that has the boilerplate, I expect that I should also update the copyright year to the last modified year.

I remember that @juanluisvaladas has asked for clarification about this back in the day, and IIRC the result was that it's "best" to list the year of a file's inception in the copyright clause. That's what the linter enforces (as good as possible, at least).

> OTOH, one of the reasons for creating Apache-2 was to avoid boilerplate headers.

I think we could at least consider to use SPDX one-liners. Would be in favor of at least reducing boilerplate, when not being able to get rid of it completely. But I reckon license and copyright are two distinct but related things, so maybe being able to omit the license might not imply that we're able to omit the copyright as well.
