### ISSUE TITLE
Supporting gollvm (Go 1.15.2)

### ISSUE THREAD

**Issue by advancedwebdeveloper** [k0sproject/k0s#374]
Hi.

I wonder how you deal with reflection libraries. Hence https://github.com/json-iterator/go/issues/501 and https://github.com/json-iterator/go/issues/462 .

I have some interest in building your projects with [gollvm](https://go.googlesource.com/gollvm/) ("llvm-goc") . Hence [this](https://go.googlesource.com/gollvm/#buildstatic) .

Ivan

**Comment by ncopa** [comment]
This is how we deal with reflection libraries: https://github.com/k0sproject/k0s/search?q=reflect

I suppose we can only support gollvm once upstream kubernetes supports it.

**Comment by advancedwebdeveloper** [comment]
> This is how we deal with reflection libraries: https://github.com/k0sproject/k0s/search?q=reflect
It is OK - so perhaps the problem itself in json-iterator.
If you are using the standard reflection API - you might be interested to replace reflect2 with reflect (do a reverse action, against what json-iterator's maintainers did).

> 
> I suppose we can only support gollvm once upstream kubernetes supports it.
Not necessarily: unmaintained https://github.com/modern-go/reflect2 is the only cause of compilation failure.

Btw gollvm doesn't compile, using the latest commits.
But the older version, which I released, is wokring - it is compatible with Go 1.15.2.

@ncopa , you didn't react on my attempts to build gollvm on Alpine.

https://lists.alpinelinux.org/~alpine/users/%3CCANFCsz_JEd61oV%3Dz4w6A_JzA%3DRh4r0sh3feKNKrgdnPkTrvHuA%40mail.gmail.com%3E
https://github.com/golang/go/issues/42308

Please follow up - so I could contribute via a patch.

**Comment by jasmingacic** [comment]
@advancedwebdeveloper If you can write a patch for this we will be glad to review it and get it merged.
