### ISSUE TITLE
any plans for the ability to update cluster config via autopilot?

### ISSUE THREAD

**Issue by danj-replicated** [k0sproject/k0s#3781]
### Describe the solution you would like

I would like to be able to push cluster config changes to control nodes via autopilot in order to update helm extensions alongside k0s binary upgrades in non-k0sctl managed clusters. 

### Additional context

- is this something you've considered already? 
- would you be open to this as a contribution to the project?

**Comment by jnummelin** [comment]
So you mean something like defining the new configurations as part of the plan object? Autopilot would then drop it in before doing the binary upgrade and restart?

This goes a bit into the direction of dynamic configuration: https://docs.k0sproject.io/stable/dynamic-configuration/

**Comment by danj-replicated** [comment]
Yeh that's what I was thinking. 

for context, I'm trying to find a way to programatically update helm extensions in a static-config cluster not managed by k0sctl. 

I did initially think about ignoring the cluster config and creating `chart` resources in the cluster, but as far as I know, there's currently no way to configure helm repository config from inside such a cluster.

**Comment by danj-replicated** [comment]
Though now I'm thinking about it... moving to using dynamic config and interacting with the `clusterconfig` via the api sounds much nicer...
