### ISSUE TITLE
K0s images retention

### ISSUE THREAD

**Issue by jsalgado78** [k0sproject/k0s#3805]
### Is your feature request related to a problem? Please describe.

I've a K0s cluster deployed using airgap bundle and I'm trying to prevent K0s image pulling from Internet with "default_pull_policy: Never" but kubelet can remove basic K0s images as coredns in nodes where coredns is not running.

A basic K0s image should be marked or recovered in some way to prevent its deletion in kubelet garbage collection.

Thanks

**Comment by jnummelin** [comment]
https://github.com/k0sproject/k0s/issues/3389

This is implemented in https://github.com/k0sproject/k0s/pull/3408 and released in 1.28 series. @jsalgado78 does that not work as expected? OR are you running older than 1.28 version?

**Comment by jsalgado78** [comment]
Thanks.

I've detected in a K0s cluster running v1.27.5. I'd no idea that it's implemented in 1.28
