### ISSUE TITLE
Support kube-router v.2.0.0

### ISSUE THREAD

**Issue by simonfelding** [k0sproject/k0s#3814]
### Is your feature request related to a problem? Please describe.

I'm having an issue with kube-router (https://github.com/cloudnativelabs/kube-router/issues/1588) where it creates iptables rules in the filter chain, which causes many iptables related commands to break and require using the nft tools.

### Describe the solution you would like

Replace kube-router v.1.6.0 with v.2.0.0.

**Comment by jnummelin** [comment]
hmm, I don't see how updating kube-router to 2.0.0 would fix that issue. 🤔 

Like I mentioned in https://github.com/cloudnativelabs/kube-router/issues/1588, k0s tries it's best to build the distro in a way that all the networking stuff actually works. Currently this means that we keep the iptables, and some other related tools, versions in sync between all components.
