### ISSUE TITLE
Document additional required host binaries

### ISSUE THREAD

**Issue by twz123** [k0sproject/k0s#3841]
K0s actually requires quite some host binaries to be present on worker machines. The docs should reflect that, and maybe some sysprobes should be added. See https://github.com/k0sproject/k0s/issues/3386#issuecomment-1864203357 for details:

> Looking at the repo https://github.com/kubernetes/mount-utils where all mount stuff is implemented, replacing `(u)mount` calls with syscalls is only small part of the problem. There's plenty of other exec calls it does to resize FS, systemd dependencies, FS initialization etc.. Replacing all these is really not feasible or possible. So replacing just mount doesn't really get us anywhere IMO. xref: https://github.com/kubernetes/mount-utils/issues/13

**Comment by jnummelin** [comment]
I think the challenge, especially relating to the mount-utils, is that not all the host bins are _always_ needed. I think some of the exec calls are still due to in-tree volume providers and thus not always really needed. But in general I agree, we need to document these at least as _soft_ dependencies.

**Comment by ncopa** [comment]
Isn't this fixed with https://github.com/k0sproject/k0s/commit/19c800dfa05ec3e84eb7315e0057bc740d304db7 which both adds mount/umount to docs and a sysprobe?

**Comment by twz123** [comment]
> Isn't this fixed with [19c800d](https://github.com/k0sproject/k0s/commit/19c800dfa05ec3e84eb7315e0057bc740d304db7) which both adds mount/umount to docs and a sysprobe?

This issue is about even more binaries, as Jussi pointed out in https://github.com/k0sproject/k0s/issues/3386#issuecomment-1864203357.
