### ISSUE TITLE
Use real sentences for comments kube-builder "managed" objects

### ISSUE THREAD

**Issue by jnummelin** [k0sproject/k0s#3924]
The comments are copied over to OpenAPI/CRD spec but that does not take in the line breaks, see https://github.com/k0sproject/k0s/pull/3902#discussion_r1448475347. We should use real sentences, with punctuation so the field comments in CRDs/OpenAPI will be more readable.

**Comment by kke** [comment]
I'll take a stab at writing a quick `go/ast` / `go/parser` script for this.
