### ISSUE TITLE
Support for dual-stack Kubernetes cluster

### ISSUE THREAD

**Issue by unixfox** [k0sproject/k0s#394]
**Is your feature request related to a problem? Please describe.**
I'm trying to run k0s as a dual stack Kubernetes cluster but I'm unable to modify the calico ipam in order to enable the ipv6 support.

**Describe the solution you'd like**
I would like to be able to turn on the IPv6 support in calico like described here: https://docs.projectcalico.org/networking/ipv6.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by unixfox** [comment]
I spent a couple of hours trying to get a dual stack cluster working on k0s and I made it:
```
/ # ping -4 google.com
PING google.com (216.58.208.110): 56 data bytes
64 bytes from 216.58.208.110: seq=0 ttl=118 time=1.006 ms
--- google.com ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 1.006/1.006/1.006 ms
/ # ping -6 google.com
PING google.com (2a00:1450:400e:80e::200e): 56 data bytes
64 bytes from 2a00:1450:400e:80e::200e: seq=0 ttl=118 time=1.631 ms
--- google.com ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 1.631/1.631/1.631 ms
/ # ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
3: eth0@if7: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1450 qdisc noqueue 
    link/ether 06:9e:bb:3a:6c:07 brd ff:ff:ff:ff:ff:ff
    inet 10.244.9.129/32 brd 10.244.9.129 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fda8:4310:a52a:294e:ff3c:2d40:6522:980/128 scope global 
       valid_lft forever preferred_lft forever
    inet6 fe80::49e:bbff:fe3a:6c07/64 scope link 
       valid_lft forever preferred_lft forever
```

My success was hugely contributed by this article: https://medium.com/@elfakharany/how-to-enable-ipv6-on-kubernetes-aka-dual-stack-cluster-ac0fe294e4cf

Here what I had to do in order to get this working:

### 1. Hardcode the service CIDR and pod CIDR directly into the code

Specifying both CIDR like this in the k0s.yaml:
```yml
  network:
    podCIDR: "10.244.0.0/16,fd00::/108"
    serviceCIDR: "10.96.0.0/12,fd01/108"
```
Resulted into an error:
```
failed to parse service CIDR 10.96.0.0/12,fd01/112: invalid CIDR address: 10.96.0.0/12,fd01/112: invalid CIDR address: 10.96.0.0/12,fd01/112
```
I don't know what's stopping me from doing that but it's nether apiserver nor controllermanager because they didn't complain when passing the CIDR using the command line parameters.

I also had to remove `node-cidr-mask-size` because this command line parameter is forbidden in dual stack cluster.

Here is the diff for https://github.com/k0sproject/k0s/blob/main/pkg/component/server/controllermanager.go:
```diff
49c49
< 	"node-cidr-mask-size":             "24",
---
>         "node-cidr-mask-size-ipv6":             "108",
80c80
< 		"cluster-cidr":                     a.ClusterConfig.Spec.Network.PodCIDR,
---
> 		"cluster-cidr":                     "10.244.0.0/16,fd00::/108",
86c86
< 		"service-cluster-ip-range":         a.ClusterConfig.Spec.Network.ServiceCIDR,
---
> 		"service-cluster-ip-range":         "10.96.0.0/16,fd01::/108",
```

And for https://github.com/k0sproject/k0s/blob/main/pkg/component/server/apiserver.go:
```diff
102c102
< 			"service-cluster-ip-range":         a.ClusterConfig.Spec.Network.ServiceCIDR,
---
> 			"service-cluster-ip-range":         "10.96.0.0/16,fd01::/108",
```

Note: I didn't specify `--node-cidr-mask-size-ipv4` because the default value is `24` which is the same as the `node-cidr-mask-size` parameter in k0s code.

### 2. Enable the feature gates
In order to get dual stack it's required to enable the feature gate `IPv6DualStack` like this in the k0s.yaml for kubelet, apiserver and controller manager:
```yml
spec:
  api:
    address: x.x.x.x
    sans:
    - x.x.x.x
    extraArgs:
      feature-gates: "IPv6DualStack=true"
  controllerManager:
    extraArgs:
      feature-gates: "IPv6DualStack=true"
  workerProfiles:
    - name: custom-role
      values:
         key: featureGates
         mapping:
             innerKey: "IPv6DualStack=true"
```

### 3. Enable the dual stack support in Calico by modifying manifests in the code
I was unable to override the calico manifests file (`calico-DaemonSet-calico-node.yaml` & `calico-ConfigMap-calico-config.yaml`) in `/var/lib/k0s/manifests/calico` because they were replaced by their default manifests at each restart of the control plane.

I had to modify them directly into the code.

Here is the diff for https://github.com/k0sproject/k0s/blob/main/static/manifests/calico/DaemonSet/calico-node.yaml:
```diff
209c209,210
<             # Disable IPv6 on Kubernetes.
---
>             - name: IP6
>               value: "autodetect"
211c212
<               value: "false"
---
>               value: "true"
```

And for https://github.com/k0sproject/k0s/blob/main/static/manifests/calico/ConfigMap/calico-config.yaml:
```diff
36c36,38
<               "type": "calico-ipam"
---
>               "type": "calico-ipam",
>               "assign_ipv4": "true",
>               "assign_ipv6": "true"
```

### 4. Enable kube-proxy IPv6 compatibility

I had to modify the clusterCIDR of kube-proxy manifest (`/var/lib/k0s/manifests/kubeproxy/kube-proxy.yaml`) to a CIDR with IPv4 and IPv6 and then enable the IPv6 feature gate like this:
```yml
  config.conf: |-
    clusterCIDR: "10.244.0.0/16,fd01::/108"
    featureGates:
      IPv6DualStack: true
```

Unfortunately, like calico this file gets replaced by their default version at every restart of the control plane.

### 5. Get IPv6 connectivity
This one is required because I used a private IPv6 subnet but if I used a public IPv6 subnet then this shouldn't be needed.

I applied this Kubernetes manifest: https://raw.githubusercontent.com/abohmeed/ip-masq-agent/master/ip-masq-agent.yaml.

It's taken from the article that I mentioned at the start.

--------------

I'm not a Golang developer but I'll try my best for explaining what should be changed in order to get a dual stack support in k0s:

1. Add a dualstack parameter for calico in k0s.yaml. This will set the correct parameters like explained in `3. Enable the dual stack support in Calico by modifying manifests in the code`.
2. Modify the CIDR validator of `network.podCIDR` and `network.serviceCIDR`. This validator should also accept IPv6 subnets. I don't know what's the component for that though.
3. Remove `node-cidr-mask-size` parameter from the code of the controller manager (https://github.com/k0sproject/k0s/blob/main/pkg/component/server/controllermanager.go), this is not needed because `24` is already the default value according to the documentation: https://kubernetes.io/docs/reference/command-line-tools-reference/kube-controller-manager/
4. Allow to set new parameters to the default manifests, like it's already possible for kubelet using workerProfiles. In this case I had to add one parameter to kube-proxy

At least with these 4 change anyone can have a dual stack cluster in a vanilla k0s by adding some parameter in the k3s.yaml but the ideal way would be to just be one parameter (example: `dualstack: true`) that enable everything for running a dual stack cluster.

**Comment by jnummelin** [comment]
@unixfox Thanks for such a detailed analysis. 👏 

> the ideal way would be to just be one parameter (example: `dualstack: true`)

I absolutely agree with this. The simpler we can do it for the users the better. :)

We're pushing 0.8.0 out in few days thus I'm tentatively scheduling this for 0.9.0 milestone.

**Comment by unixfox** [comment]
@jnummelin It's always a pleasure to improve k0s.

As an IPv6 supporter, I'm happy to hear that you are considering this feature as an upcoming release. K0s will be the first lightweight Kubernetes distro to support dual stack, that's very promising.

Don't hesitate to ask me for some help about the development of this feature. For instance, I can test some preview binaries of k0s containing an early support of dual stack.

**Comment by soider** [comment]
@unixfox hi! how do you test the proper work of the dualstack setup?

**Comment by unixfox** [comment]
I'm not an expert in this field, but I'll still try to give my part.
You may also ask for help in the sub Reddit [/r/ipv6](https://old.reddit.com/r/ipv6/) & [/r/kubernetes](https://old.reddit.com/r/kubernetes/) and also in the issues about IPv6 created for k3s https://github.com/k3s-io/k3s/issues/1405 and https://github.com/k3s-io/k3s/issues/284.

Anyway, here is my part:

For testing a dualstack connectivity in a pod just create a simple pod with alpine image, and then do a ping to ipv6.google.com and ipv4.google.com. If both of the ping works then at least the external connectivity works.

After that you can also try to ping other pods in IPv6, get their IPv6 addresses and then ping them.

I haven't really tested kube-proxy, but you can also create a service with ClusterIP as a type and attach it to a pod that serve for example a webserver. After that try to curl the IPv6 address created by the service.

And for checking if you can accept some external IPv6 traffic, you can create a service with a NodePort and attach it to a pod that serve for example a webserver. Then use curl on the assigned port with the public IPv6 address of one of the node.

There are still a lot of things to test like the load balancer, but those things aren't included by default in k0s for IPv4 anyway, so it's not a must to test.

**Comment by rjb3977** [comment]
I'm trying to set up an IPv6-only k0s cluster and I'm running into an immediate panic caused by the fact that the call at [network.go:59](https://github.com/k0sproject/k0s/blob/79e37f71654b513ea2172c65aaaaa6767c9cc544/pkg/apis/v1beta1/network.go#L59) returns nil, since it's not an IPv6 address. I don't quite have the time to hack on k0s right now, so I'm not sure if that's the only blocker for an IPv6 single-stack k0s cluster from being possible purely through normal configuration.

**Comment by unixfox** [comment]
> I'm trying to set up an IPv6-only k0s cluster and I'm running into an immediate panic caused by the fact that the call at [network.go:59](https://github.com/k0sproject/k0s/blob/79e37f71654b513ea2172c65aaaaa6767c9cc544/pkg/apis/v1beta1/network.go#L59) returns nil, since it's not an IPv6 address. I don't quite have the time to hack on k0s right now, so I'm not sure if that's the only blocker for an IPv6 single-stack k0s cluster from being possible purely through normal configuration.

At the end of my big comment I noted that the services subnet validation need to accept IPv6 subnets. Indeed it's a required step for both running a dual stack cluster and IPv6 only cluster.

On the same comment I explained how to bypass this restriction for the moment by editing the code if you are interested to run k0s in a IPv6 only network.

**Comment by rjb3977** [comment]
> 
> At the end of my big comment I wrote that the services subnet validation need to accept IPv6 subnets. Indeed it's a required step for both running a dual stack cluster and IPv6 only cluster.
> 
> On the same comment I explained how to bypass this restriction for the moment by editing the code if you are interested to run k0s in a IPv6 only network.

Yeah, I saw that, I just didn't see any reference to the specific issue(s) in `network.go` so I figured I'd mention them.
