### ISSUE TITLE
Use kubelet extra args --hostname-override value as etcd hostname?

### ISSUE THREAD

**Issue by kke** [k0sproject/k0s#3985]
### What happened?

As reported in a [k0sctl issue](https://github.com/k0sproject/k0sctl/issues/648), k0s always uses `os.Hostname()` as the etcd `--name` value. Maybe the value should be replicated from `--kubelet-extra-args="--hostname-override=..."`?

**Comment by twz123** [comment]
The kubelet runs on workers, not on controllers. So this could only meaningfully apply to controller+worker nodes. Moreover, the os.Hostname() is also used in some other places, i.e. for events emitted by k0s. I agree, the node name handling in k0s is a bit messy and scattered around in many places, including autopilot. Fixing this would require some thought, though.

Is this a cosmetic thing, or would this fix a real problem?

**Comment by kke** [comment]
k0sctl has `spec: host: hostname:` for overriding the hostname. This only sets the `--hostname-override` but it doesn't help with etcd.

**Comment by twz123** [comment]
You could also pass `--name` to the etcd extra args, then.
