### ISSUE TITLE
Service type load balancer

### ISSUE THREAD

**Issue by chrisjsimpson** [k0sproject/k0s#401]
Question / Documentation 

If a Service object of type Load balancer is created on a bare metal deployment, is my understanding correct that using something like metallb would be a reasonable approach?

**Describe the solution you'd like**
Documentation on how this might be approached (happy to write a PR for this once understood).

**Describe alternatives you've considered**
Deployments vary a lot, there is no one answer to this. Perhaps there are good practices to document.

**Comment by coolamiy** [comment]
It depends as with bare metal there are multiple considerations.
1. If you can update dns entry then metalb is good solution as it will require range of ip to be reserved.
2. Using host network is another option accompanied with haproxy to work as edge node.
3. Using dedicated node for load balancing

**Comment by jnummelin** [comment]
Closing as this is not directly a k0s issue.

We do have an example of setting up MetalLB with Traefik, see https://docs.k0sproject.io/v1.21.0+k0s.0/examples/traefik-ingress/

**Comment by chainhead** [comment]
@jnummelin about the example you pasted above. How does it work when service type is left as default i.e. `ClusterIP`? Shouldn't the type be set to `LoadBalancer`?

This is what I get when I run the example.

```bash
k -n temp get all
NAME                                    READY   STATUS    RESTARTS   AGE
pod/whoami-deployment-85bfbd48f-mhlhc   1/1     Running   0          25s

NAME                     TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)   AGE
service/whoami-service   ClusterIP   10.109.27.47   <none>        80/TCP    25s

NAME                                READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/whoami-deployment   1/1     1            1           25s

NAME                                          DESIRED   CURRENT   READY   AGE
replicaset.apps/whoami-deployment-85bfbd48f   1         1         1       25s
```
