### ISSUE TITLE
metrics-server: connect: no route to host on brand new rocky linux 9 install with default setup

### ISSUE THREAD

**Issue by tgy** [k0sproject/k0s#4016]
### Before creating an issue, make sure you've checked the following:

- [X] You are running the latest released version of k0s
- [X] Make sure you've searched for existing issues, both open and closed
- [X] Make sure you've searched for PRs too, a fix might've been merged already
- [X] You're looking at docs for the released version, "main" branch docs are usually ahead of released versions.

### Platform

```shell
Linux 5.14.0-284.11.1.el9_2.x86_64 #1 SMP PREEMPT_DYNAMIC Tue May 9 17:09:15 UTC 2023 x86_64 GNU/Linux
NAME="Rocky Linux"
VERSION="9.2 (Blue Onyx)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="9.2"
PLATFORM_ID="platform:el9"
PRETTY_NAME="Rocky Linux 9.2 (Blue Onyx)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:9::baseos"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
SUPPORT_END="2032-05-31"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-9"
ROCKY_SUPPORT_PRODUCT_VERSION="9.2"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.2"
```

### Version

v1.29.1+k0s.0

### Sysinfo

<details><summary>`k0s sysinfo`</summary>
<pre>
Machine ID: "fcbd40ab20cfa160e8a99d22ab5609fc01cc48050dfd9535e2fd9ebcbf7148cb" (from machine) (pass)
Total memory: 1.7 GiB (pass)
Disk space available for /var/lib/k0s: 24.3 GiB (pass)
Name resolution: localhost: [::1 127.0.0.1] (pass)
Operating system: Linux (pass)
  Linux kernel release: 5.14.0-284.11.1.el9_2.x86_64 (pass)
  Max. file descriptors per process: current: 524288 / max: 524288 (pass)
  AppArmor: unavailable (pass)
  Executable in PATH: modprobe: /usr/sbin/modprobe (pass)
  Executable in PATH: mount: /usr/bin/mount (pass)
  Executable in PATH: umount: /usr/bin/umount (pass)
  /proc file system: mounted (0x9fa0) (pass)
  Control Groups: version 2 (pass)
    cgroup controller "cpu": available (is a listed root controller) (pass)
    cgroup controller "cpuacct": available (via cpu in version 2) (pass)
    cgroup controller "cpuset": available (is a listed root controller) (pass)
    cgroup controller "memory": available (is a listed root controller) (pass)
    cgroup controller "devices": available (device filters attachable) (pass)
    cgroup controller "freezer": available (cgroup.freeze exists) (pass)
    cgroup controller "pids": available (is a listed root controller) (pass)
    cgroup controller "hugetlb": available (is a listed root controller) (pass)
    cgroup controller "blkio": available (via io in version 2) (pass)
  CONFIG_CGROUPS: Control Group support: built-in (pass)
    CONFIG_CGROUP_FREEZER: Freezer cgroup subsystem: built-in (pass)
    CONFIG_CGROUP_PIDS: PIDs cgroup subsystem: built-in (pass)
    CONFIG_CGROUP_DEVICE: Device controller for cgroups: built-in (pass)
    CONFIG_CPUSETS: Cpuset support: built-in (pass)
    CONFIG_CGROUP_CPUACCT: Simple CPU accounting cgroup subsystem: built-in (pass)
    CONFIG_MEMCG: Memory Resource Controller for Control Groups: built-in (pass)
    CONFIG_CGROUP_HUGETLB: HugeTLB Resource Controller for Control Groups: built-in (pass)
    CONFIG_CGROUP_SCHED: Group CPU scheduler: built-in (pass)
      CONFIG_FAIR_GROUP_SCHED: Group scheduling for SCHED_OTHER: built-in (pass)
        CONFIG_CFS_BANDWIDTH: CPU bandwidth provisioning for FAIR_GROUP_SCHED: built-in (pass)
    CONFIG_BLK_CGROUP: Block IO controller: built-in (pass)
  CONFIG_NAMESPACES: Namespaces support: built-in (pass)
    CONFIG_UTS_NS: UTS namespace: built-in (pass)
    CONFIG_IPC_NS: IPC namespace: built-in (pass)
    CONFIG_PID_NS: PID namespace: built-in (pass)
    CONFIG_NET_NS: Network namespace: built-in (pass)
  CONFIG_NET: Networking support: built-in (pass)
    CONFIG_INET: TCP/IP networking: built-in (pass)
      CONFIG_IPV6: The IPv6 protocol: built-in (pass)
    CONFIG_NETFILTER: Network packet filtering framework (Netfilter): built-in (pass)
      CONFIG_NETFILTER_ADVANCED: Advanced netfilter configuration: built-in (pass)
      CONFIG_NF_CONNTRACK: Netfilter connection tracking support: module (pass)
      CONFIG_NETFILTER_XTABLES: Netfilter Xtables support: built-in (pass)
        CONFIG_NETFILTER_XT_TARGET_REDIRECT: REDIRECT target support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_COMMENT: "comment" match support: module (pass)
        CONFIG_NETFILTER_XT_MARK: nfmark target and match support: module (pass)
        CONFIG_NETFILTER_XT_SET: set target and match support: module (pass)
        CONFIG_NETFILTER_XT_TARGET_MASQUERADE: MASQUERADE target support: module (pass)
        CONFIG_NETFILTER_XT_NAT: "SNAT and DNAT" targets support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_ADDRTYPE: "addrtype" address type match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_CONNTRACK: "conntrack" connection tracking match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_MULTIPORT: "multiport" Multiple port match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_RECENT: "recent" match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_STATISTIC: "statistic" match support: module (pass)
      CONFIG_NETFILTER_NETLINK: module (pass)
      CONFIG_NF_NAT: module (pass)
      CONFIG_IP_SET: IP set support: module (pass)
        CONFIG_IP_SET_HASH_IP: hash:ip set support: module (pass)
        CONFIG_IP_SET_HASH_NET: hash:net set support: module (pass)
      CONFIG_IP_VS: IP virtual server support: module (pass)
        CONFIG_IP_VS_NFCT: Netfilter connection tracking: built-in (pass)
        CONFIG_IP_VS_SH: Source hashing scheduling: module (pass)
        CONFIG_IP_VS_RR: Round-robin scheduling: module (pass)
        CONFIG_IP_VS_WRR: Weighted round-robin scheduling: module (pass)
      CONFIG_NF_CONNTRACK_IPV4: IPv4 connetion tracking support (required for NAT): unknown (warning)
      CONFIG_NF_REJECT_IPV4: IPv4 packet rejection: module (pass)
      CONFIG_NF_NAT_IPV4: IPv4 NAT: unknown (warning)
      CONFIG_IP_NF_IPTABLES: IP tables support: module (pass)
        CONFIG_IP_NF_FILTER: Packet filtering: module (pass)
          CONFIG_IP_NF_TARGET_REJECT: REJECT target support: module (pass)
        CONFIG_IP_NF_NAT: iptables NAT support: module (pass)
        CONFIG_IP_NF_MANGLE: Packet mangling: module (pass)
      CONFIG_NF_DEFRAG_IPV4: module (pass)
      CONFIG_NF_CONNTRACK_IPV6: IPv6 connetion tracking support (required for NAT): unknown (warning)
      CONFIG_NF_NAT_IPV6: IPv6 NAT: unknown (warning)
      CONFIG_IP6_NF_IPTABLES: IP6 tables support: module (pass)
        CONFIG_IP6_NF_FILTER: Packet filtering: module (pass)
        CONFIG_IP6_NF_MANGLE: Packet mangling: module (pass)
        CONFIG_IP6_NF_NAT: ip6tables NAT support: module (pass)
      CONFIG_NF_DEFRAG_IPV6: module (pass)
    CONFIG_BRIDGE: 802.1d Ethernet Bridging: module (pass)
      CONFIG_LLC: module (pass)
      CONFIG_STP: module (pass)
  CONFIG_EXT4_FS: The Extended 4 (ext4) filesystem: module (pass)
  CONFIG_PROC_FS: /proc file system support: built-in (pass)
</pre>
</details>

### What happened?

The metrics-server fails to reach the Ready state due to network connection errors

### Steps to reproduce

1. install rocky linux 9
2. follow the quick start guide and install k0s as a controller+worker single node
3. start k0s
4. observe that the metrics-server does not reach the Ready state

### Expected behavior

I was expecting this to work out of the box since I did not do anything in particular. The default network configuration should work.

### Actual behavior

k0s fails to start completely

### Screenshots and logs

The `metrics-server` pod fails to reach the READY state

```
NAMESPACE     NAME                              READY   STATUS    RESTARTS   AGE
kube-system   kube-proxy-rv8jt                  1/1     Running   0          20m
kube-system   kube-router-6zb6t                 1/1     Running   0          20m
kube-system   metrics-server-7556957bb7-5vx7x   0/1     Running   0          20m
kube-system   coredns-6cd46fb86c-fnp4x          1/1     Running   0          20m
```

and shows a lot of network errors

```
E0204 15:42:23.270158       1 scraper.go:140] "Failed to scrape node" err="Get \"https://192.168.122.2:10250/metrics/resource\": dial tcp 192.168.122.2:10250: connect: no route to host" node="localhost.localdomain"
I0204 15:42:32.882632       1 server.go:187] "Failed probe" probe="metric-storage-ready" err="no metrics to serve"
E0204 15:42:38.271610       1 scraper.go:140] "Failed to scrape node" err="Get \"https://192.168.122.2:10250/metrics/resource\": dial tcp 192.168.122.2:10250: connect: no route to host" node="localhost.localdomain"
I0204 15:42:42.883660       1 server.go:187] "Failed probe" probe="metric-storage-ready" err="no metrics to serve"
I0204 15:42:52.881409       1 server.go:187] "Failed probe" probe="metric-storage-ready" err="no metrics to serve"
E0204 15:42:53.270071       1 scraper.go:140] "Failed to scrape node" err="Get \"https://192.168.122.2:10250/metrics/resource\": dial tcp 192.168.122.2:10250: connect: no route to host" node="localhost.localdomain"
I0204 15:43:02.887658       1 server.go:187] "Failed probe" probe="metric-storage-ready" err="no metrics to serve"
E0204 15:43:08.264941       1 scraper.go:140] "Failed to scrape node" err="Get \"https://192.168.122.2:10250/metrics/resource\": dial tcp 192.168.122.2:10250: connect: no route to host" node="localhost.localdomain"
I0204 15:43:12.877208       1 server.go:187] "Failed probe" probe="metric-storage-ready" err="no metrics to serve"
I0204 15:43:22.882220       1 server.go:187] "Failed probe" probe="metric-storage-ready" err="no metrics to serve"
E0204 15:43:23.268263       1 scraper.go:140] "Failed to scrape node" err="Get \"https://192.168.122.2:10250/metrics/resource\": dial tcp 192.168.122.2:10250: connect: no route to host" node="localhost.localdomain"
I0204 15:43:30.247542       1 server.go:187] "Failed probe" probe="metric-storage-ready" err="no metrics to serve"
I0204 15:43:32.889080       1 server.go:187] "Failed probe" probe="metric-storage-ready" err="no metrics to serve"
E0204 15:43:38.268468       1 scraper.go:140] "Failed to scrape node" err="Get \"https://192.168.122.2:10250/metrics/resource\": dial tcp 192.168.122.2:10250: connect: no route to host" node="localhost.localdomain"
I0204 15:43:42.872508       1 server.go:187] "Failed probe" probe="metric-storage-ready" err="no metrics to serve"
I0204 15:43:52.867031       1 server.go:187] "Failed probe" probe="metric-storage-ready" err="no metrics to serve"
E0204 15:43:53.270351       1 scraper.go:140] "Failed to scrape node" err="Get \"https://192.168.122.2:10250/metrics/resource\": dial tcp 192.168.122.2:10250: connect: no route to host" node="localhost.localdomain"
I0204 15:44:02.876004       1 server.go:187] "Failed probe" probe="metric-storage-ready" err="no metrics to serve"
E0204 15:44:08.265309       1 scraper.go:140] "Failed to scrape node" err="Get \"https://192.168.122.2:10250/metrics/resource\": dial tcp 192.168.122.2:10250: connect: no route to host" node="localhost.localdomain"
I0204 15:44:12.881978       1 server.go:187] "Failed probe" probe="metric-storage-ready" err="no metrics to serve"
I0204 15:44:22.880576       1 server.go:187] "Failed probe" probe="metric-storage-ready" err="no metrics to serve"
E0204 15:44:23.269221       1 scraper.go:140] "Failed to scrape node" err="Get \"https://192.168.122.2:10250/metrics/resource\": dial tcp 192.168.122.2:10250: connect: no route to host" node="localhost.localdomain"
I0204 15:44:32.884973       1 server.go:187] "Failed probe" probe="metric-storage-ready" err="no metrics to serve"
I0204 15:44:34.245789       1 server.go:187] "Failed probe" probe="metric-storage-ready" err="no metrics to serve"
```

**Comment by twz123** [comment]
I'm not able to repro this in a virtual machine image downloaded from https://dl.rockylinux.org/vault/rocky/9.2/images/x86_64/. I didn't do an installation from scratch though. The problem might be some firewall settings? The IP 192.168.122.2 should be the Kubernetes node's internal IP address. The pod should be allowed to connect to it. You can find the ports used by k0s in the [networking section](https://docs.k0sproject.io/v1.29.1+k0s.0/networking/#required-ports-and-protocols) of the docs.

**Comment by tgy** [comment]
Thanks @twz123 

Could this be a SSL certificate issue?


```
wget 'https://192.168.122.2:10250/metrics/resource'
--2024-02-05 17:35:32--  https://192.168.122.2:10250/metrics/resource
Connecting to 192.168.122.2:10250... connected.
ERROR: The certificate of ‘192.168.122.2’ is not trusted.
ERROR: The certificate of ‘192.168.122.2’ doesn't have a known issuer.
```

I disable the firewalld service, so there's no firewall running.

**Comment by twz123** [comment]
Yes, you need to specify the CA certificate, client certificate and private key. Try this:

```sh
wget -qO- \
  --ca-certificate=/var/lib/k0s/pki/ca.crt \
  --certificate=/var/lib/k0s/pki/admin.crt \
  --private-key /var/lib/k0s/pki/admin.key \
   https://192.168.122.2:10250/metrics/resource
```

This should give you the kubelet's container metrics.

**Comment by tgy** [comment]
ok i managed to make this work! it's important in Rocky Linux to disable the `firewalld` service.

i had to destroy completely the cluster, removing the pods, and reinstall everything to make this work.

closing this for now. i'll try to add some notes for rocky linux in the doc to make this work out of the box

**Comment by twz123** [comment]
We have a short snippet about [k0s & firewalld](https://docs.k0sproject.io/v1.29.1+k0s.1/networking/#firewalld-k0s) in the docs. It's not mentioning any specific Linux distro, though.
