### ISSUE TITLE
What's the shell/theme/plugin used in the demo on k0sproject.io? 😅

### ISSUE THREAD

**Issue by mcouthon** [k0sproject/k0s#404]
Sorry for the out-of-blue question, but can someone tell me what did you use for the terminal in the demo to look like it did? :) Specifically the status bar at the bottom looks great 👌

**Comment by jnummelin** [comment]
@adamparco You did the demo, care to elaborate your terminal setup? 😃

**Comment by adamparco** [comment]
Hi @mcouthon, the status bar at the bottom is my configured tmux.  You can see my .tmux config here:
https://github.com/adamparco/dotfiles/blob/5751feb42d94bbd0ff8dc3420281560514d0948e/tmux.conf#L115-L122

Also for my prompt I use https://github.com/sorin-ionescu/prezto with the sorin theme `prompt -p sorin`

**Comment by mcouthon** [comment]
Amazing! Thank you so much :)
