### ISSUE TITLE
K0S on the edge with multiple private network nodes

### ISSUE THREAD

**Issue by ErGallo23** [k0sproject/k0s#4048]
Hello,

 I am doing a project with specific requirements and I am not clear if K0S will be able to help me or if what I want to do is not feasible.

 Currently I have set up a small K0S cluster with two controller nodes in AWS, and in a private network (Edge) I have set up 2 worker nodes.  So far so good.  The project requirement is to set up about 50 worker nodes, each in different private networks (Edge nodes, with Postgres and/or a WebApp).  The goal is 25 apps on the Edge, with two nodes on each Edge.

 Is this infrastructure viable with K0S?  Would I need any additional tools (such as K0SMotron)?  Could I manage the cluster with Lens Desktop?

 The main question is whether I can have groups of worker nodes within the same private network and several private networks, or whether each of the worker nodes on the edge must have its own public IP.

 Many thanks in advance.

**Comment by jnummelin** [comment]
> The project requirement is to set up about 50 worker nodes, each in different private networks

Is there any connectivity between the edge sites? If there is none, then you might need to consider some common nodes (reachable from ALL sites) and perhaps setup some sort of "VPN" networking on top. This of course depends heavily on the apps that you plan to run. Do the apps need to communicate to other sites or are the apps always local to a site?

> Is this infrastructure viable with K0S?

In general yes. But like said above, the networking setup requires some thinking relating to the nature of the apps.

> Would I need any additional tools (such as K0SMotron)?

You do not *need* k0smotron. k0smotron makes things easier to manage when you have many clusters to manage. By the sounds of it, you're mostly looking this to be one single cluster. 

> Could I manage the cluster with Lens Desktop?

Yes you can.


> whether each of the worker nodes on the edge must have its own public IP

They do not have to have. But naturally, the pod-to-pod comms will NOT work unless the CNI (kube-router or calico) can establish the network between sites.

**Comment by ErGallo23** [comment]
Good night,

Thank you very much for the fast answer, it has helped me clarify where to proceed.

Regarding the first question, the answer is no, each group of nodes within the private network only need to talk to each other and the control plane, not to the other nodes on the Edge.

Thanks again
