### ISSUE TITLE
Ability to configure the data directory location of k0s

### ISSUE THREAD

**Issue by unixfox** [k0sproject/k0s#405]
This is a follow-up of https://github.com/k0sproject/k0s/pull/399#issuecomment-727948675.

**Is your feature request related to a problem? Please describe.**
Currently, k0s picks `/var/lib/k0s` and `/run/k0s` as the main directories for storing its files but the user is unable to change them.

**Describe the solution you'd like**
The ability to set both `/var/lib/k0s` and `/run/k0s` to a new location. An example of the command line parameters could be `--data-dir` for changing the location of the directory `/var/lib/k0s` and `--run-dir` for changing the location of the directory `/run/k0s`.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by ncopa** [comment]
Other options are:
- set the path through config file
- use `$HOME` and `/tmp/k0s` (or similar) as default when running as non-root.

Personally i think `--data-dir` and `--run-dir` is a good idea.

**Comment by unixfox** [comment]
Isn't the config only for the master? What if someone wants to change the data directory for a worker?

**Comment by ncopa** [comment]
> Isn't the config only for the master? What if someone wants to change the data directory for a worker?

good point.
