### ISSUE TITLE
need howto to bring up an entire cluster on a laptop

### ISSUE THREAD

**Issue by sandys** [k0sproject/k0s#406]
I'm coming from the swarm world - I would like to have an entire stack running on my laptop. Say an api +  postgresql database. How do I do that ?

its not very apparent if i can run the master on my laptop and have it operate as a node and get a bunch of application services running. Could you add a help doc on how to do that ?

**Comment by jnummelin** [comment]
You can run single node "cluster" by running: `k0s server --enable-worker`

That runs both the controlplane and a worker on the same node. The admin kube config is at `/var/lib/k0s/pki/admin.conf`

We definitely need to document this better.

**Comment by ncopa** [comment]
I don't know if updating the FAQ is enough? https://github.com/k0sproject/k0s/pull/408
