### ISSUE TITLE
Failed to pull the container image

### ISSUE THREAD

**Issue by superbrothers** [k0sproject/k0s#409]
When I tried k0s in docker, it failed to pull the container image.

```
$ docker pull docker.pkg.github.com/k0sproject/k0s/k0s:v0.7.0
Error response from daemon: unauthorized: Your request could not be authenticated by the GitHub Packages service. Please ensure your access token is valid and has the appropriate scopes configured.
```

Could you confirm the permissions of the container image?

**Comment by superbrothers** [comment]
I logged in with `docker.pkg.github.com` and was able to pull without problems!

Can you make the container image public?

**Comment by ncopa** [comment]
Does https://github.com/k0sproject/k0s/commit/9a4b8f2c9aecad8b5e839ca313cb59c66a6ae98c which I just merged solve this issue?

**Comment by superbrothers** [comment]
I was able to pull the image from Docker Hub. Thanks. This issue was solved by that merged commit.

However, as you know, Docker Hub has rate limit. I prefer `ghcr.io`, but that's up to you.
