### ISSUE TITLE
Manifest deployer tries to create ingress resource before ingress controller is ready

### ISSUE THREAD

**Issue by enp** [k0sproject/k0s#4104]
k0s started via docker with two manifests mounted to /var/lib/k0s/manifests:
- ingress-nginx as described in https://docs.k0sproject.io/stable/examples/nginx-ingress/#install-nginx-using-host-network
- my own application with ingress resource

No any ingress resource was deployed after k0s completely up and running, but ingress will appear on manual kubectl apply the same manifest

Looks like manifest deployer tries to create ingress resource before nginx ingress controller is ready - so how create ingress resource only after ingress controller via manifest deployer?

**Comment by jnummelin** [comment]
@enp Is this a standard `Ingress` resource you are referring to? If yes, it should not matter as the ingress controller will pick those up once it starts.

Or is this some custom CRD based ingress?

**Comment by twz123** [comment]
> k0s started via docker with two manifests mounted to /var/lib/k0s/manifests

How do you mount them? Can you provide an example? Note that manifest files below `/var/lib/k0s/manifests` need to be organized in folders, so you need to put them into, say `/var/lib/k0s/manifests/nginx-ingress/*.yaml`.

**Comment by enp** [comment]
Run (with mount) example:
```
docker run --name k0s --hostname k0s --rm --privileged -v k0s:/var/lib/k0s \
  -v $(pwd)/manifests:/var/lib/k0s/manifests \
  -p 6443:6443 -p 80:80 docker.io/k0sproject/k0s k0s controller --single
```
Manifest files in folders per files solves problem, thank you! But what is the reason for this limitation?

**Comment by twz123** [comment]
> Manifest files in folders per files solves problem, thank you! But what is the reason for this limitation?

K0s will add a "stack" annotation to all resources that are created via the manifest folder. This is used for automatic pruning (think: `kubectl apply --prune -f ...`). The folder name is used as the stack's name. Without a folder, it's not clear which stack name to choose.

**Comment by enp** [comment]
File name can be also used for stack name, why no? But idea is clear, thank you!
