### ISSUE TITLE
Way to manually change the role of a k0s node

### ISSUE THREAD

**Issue by Starttoaster** [k0sproject/k0s#4107]
I'm trying to change the role of my k0s controller nodes to controller+worker, to be able to re-use the same deployment method I have for node-exporters on my worker nodes on my controller nodes. So I changed the role in my k0sctl yaml file from `controller` to `controller+worker`. This led to the following output:

```
level=fatal msg="apply failed - log file saved to /root/.cache/k0sctl/k0sctl.log: failed on 3 hosts:\n - [OpenSSH] <redacted>: [OpenSSH] <redacted>: is configured as k0s controller+worker but is already running as controller - role change is not supported\n - [OpenSSH] <redacted>: [OpenSSH] <redacted>: is configured as k0s controller+worker but is already running as controller - role change is not supported
```

Note that I made the issue here, despite using k0sctl, I suspect the blocker is more of a k0s thing than a k0sctl thing. Sorry if this actually belongs on the k0sctl repo.

Is there a way to manually change the controller node role on an existing installation? Or do I need to do a dance of rotating in new controller+worker nodes, and rotating out old controller nodes? I understand that this isn't really a bug report or a feature request, this comes across as a general support Issue. Feel free to close it if this is too burdensome, though maybe the bug is the seeming lack of documentation around this logline/limitation? I'd have not made the Issue had I found some documentation telling me _why_ I can't change the role, or how to manually change it. Anyway, legitimately, thanks for your time.

And... maybe if you were to take this Issue as a Feature Request, it would be "Feat: make it possible to change from the controller role to the controller+worker role" (and perhaps the other way around 🤔 ) 😄 

By the way I'm using latest k0sctl and k0s `v1.29.1+k0s.1`

**Comment by twz123** [comment]
Related: #4051

**Comment by twz123** [comment]
Although not being officially supported, it might be as simple as that:

* Stop the controller: `sudo k0s stop`
* Copy over any worker related files to the controller, e.g. airgap image bundles, if any.
* Change the controller start script to include `--enable-worker` in the list of command line arguments. For systemd, the service file is usually located at `/etc/systemd/system/k0scontroller.service`.
* Start the controller: `sudo k0s start`

But keep in mind: I haven't tested this thoroughly. Do not try this on clusters that are not supposed to break.

**Comment by Starttoaster** [comment]
It looks like that works, thanks. Fwiw, the actual procedure I followed was:

Pre-upgrade:
1) Make sure all of your cluster controllers are currently running and can afford one controller's downtime for maintenance

Upgrade maintenance (loop for each controller):
1) Stop the systemd service: `systemctl stop k0scontroller`
2) Add the `--enable-worker` flag to the ExecStart param in the systemd unit at `/etc/systemd/system/k0scontroller.service`
3) Reload systemd: `systemctl daemon-reload`
4) Start the unit: `systemctl start k0scontroller`
5) Repeat 1-4 for each controller

And obviously if you were going from Controller+Worker back to Controller, there's the added steps from that other Issue of cordon/draining the Controller+Worker nodes initially.

Thanks for the tip. Since it's literally that simple... maybe it should be supported but require a `--no-really-do-it` flag or something? Or at least some documentation about how to do it. I feel bad for the overhead of creating an Issue if this is something that's been asked before.

**Comment by pschichtel** [comment]
For reference since I just did it and also found this issue via google, here my process of switching a worker to controller/controller+worker:

1. drain node
2. disable k0sworker.service
3. reboot
4. remove k0sworker.service
5. install
6. add controller role labels to the node:
    ```
    node-role.kubernetes.io/control-plane: "true"
    node.k0sproject.io/role: control-plane
    ```
7. uncordon the node
