### ISSUE TITLE
how to change a single node cluster into a multi-node one

### ISSUE THREAD

**Issue by Weaverzhu** [k0sproject/k0s#4122]
### Is your feature request related to a problem? Please describe.

joining a worker node to an existing cluster running creating token failed.

https://github.com/k0sproject/k0s/issues/1284 k0s seems to forbidden a single node cluster adding a worker.

### Describe alternatives you've considered

is there anyway besides creating a compeletely new cluster?

**Comment by wbo-yak** [comment]
Hi, 
I was able to get through by updating the systemd service file. 

- Remove "single=true" flag
- Allow controller to be a worker as well with "--enable-worker"
- Disable taints on the controller node
- Stop, Reload and Restart

``` 
systemctl stop k0scontroller 
systemctl daemon-reload
systemctl start k0scontroller
``` 

**Original file :** 
```
[Unit]
Description=k0s - Zero Friction Kubernetes
Documentation=https://docs.k0sproject.io
ConditionFileIsExecutable=/usr/local/bin/k0s

After=network-online.target
Wants=network-online.target

[Service]
StartLimitInterval=5
StartLimitBurst=10
ExecStart=/usr/local/bin/k0s controller --config=/etc/k0s/k0s.yaml --single=true

RestartSec=120
Delegate=yes
KillMode=process
LimitCORE=infinity
TasksMax=infinity
TimeoutStartSec=0
LimitNOFILE=999999
Restart=always

[Install]
WantedBy=multi-user.target
```

**Updated file **

```
[Unit]
Description=k0s - Zero Friction Kubernetes
Documentation=https://docs.k0sproject.io
ConditionFileIsExecutable=/usr/local/bin/k0s

After=network-online.target
Wants=network-online.target

[Service]
StartLimitInterval=5
StartLimitBurst=10
ExecStart=/usr/local/bin/k0s controller --config=/etc/k0s/k0s.yaml --enable-worker --no-taints

RestartSec=120
Delegate=yes
KillMode=process
LimitCORE=infinity
TasksMax=infinity
TimeoutStartSec=0
LimitNOFILE=999999
Restart=always

[Install]
WantedBy=multi-user.target
```

**Comment by ncopa** [comment]
The `--single` option was added as a simple way to create a tiny single node cluster for running containers on your laptop and similar.

If you want create a single node cluster that you'd like to extend later, you'll have to create it with `k0s controller --enable-worker --no-taints`.

I think we need fix documentation.
