### ISSUE TITLE
add --token-file $file for joining nodes

### ISSUE THREAD

**Issue by curx** [k0sproject/k0s#413]
**Is your feature request related to a problem? Please describe.**

for joining nodes to the cluster we use the set token on cmdline

**Describe the solution you'd like**

Add an option --token-file /path/to/token-file for joining nodes

**Additional context**

If I get the `ps -C k0s -o cmd` we can see the whole token in proc

```
# join a node k8s server $token
$ ps -C k0s -o cmd
CMD
k0s server A....long...token
```

**Comment by jasmingacic** [comment]
@curx Thank you for the suggestion.

In order to join a node to the cluster you should run `k0s worker [token]` you can find more details [here](https://github.com/k0sproject/k0s/blob/main/docs/create-cluster.md#joining-workers-to-cluster)

**Comment by jasmingacic** [comment]
@curx we just adde ability to pass in token-file to `k0s worker` [here](https://github.com/k0sproject/k0s/pull/420)
