### ISSUE TITLE
Add retries for helm chart installs.

### ISSUE THREAD

**Issue by hedge-sparrow** [k0sproject/k0s#4195]
### Is your feature request related to a problem? Please describe.

It's possible for a helm chart install to be cancelled by an etcd leadership election, in such a scenario the chart is uninstalled and marked as errored, requiring manual intervention to resolve.

### Describe the solution you would like

 It would be nice if we could add retries to helm chart installs.

### Additional context

Retries for chart installation would probably need fairly strict exponential backoffs and limited retry attempts. (maybe even just one)

**Comment by hedge-sparrow** [comment]
related: https://github.com/k0sproject/k0s/issues/3758

**Comment by juanluisvaladas** [comment]
Hi @hedge-sparrow, this is already fixed upstream and it will be available in the next release in all currently supported k0s versions (1.26 to 1.30).

This was fixed in https://github.com/k0sproject/k0s/pull/4064
