### ISSUE TITLE
Where can I find kubelet logs?

### ISSUE THREAD

**Issue by kbumsik** [k0sproject/k0s#4225]
### Is your feature request related to a problem? Please describe.

I had issue with kubelet (node is not ready) and containerd (misconfigured)

### Describe the solution you would like

While I figured the fixes out, I almost speculated all the things. It would be great if the official doc describes where logs for every components are located.

### Additional context

Here is what k3s did:
Related: https://github.com/k3s-io/k3s/issues/1061

**Comment by twz123** [comment]
Agree. Some section in the docs could cover this.

All the component's logs are part of the k0s logs, with the component field set to the component's name. If you're interested in kubelet logs, you can grep the k0s logs for `component=kubelet`, for example. If you're using systemd to start k0s, you can use something like `journalctl -u k0sworker.service |  grep component=kubelet`.
