### ISSUE TITLE
Error "ETCD_UNSUPPORTED_ARCH=arm64"

### ISSUE THREAD

**Issue by rockaut** [k0sproject/k0s#424]
**Version**
```
v0.7.0
```
**Platform**
Which platform did you run k0s on?
```
Raspberry Pi 4B 4GB with Ubuntu 20.10 arm64 Image

No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.10
Release:        20.10
Codename:       groovy
```
**What happened?**
```
INFO[2020-11-18 19:13:25] Starting to supervise                         component=etcd
INFO[2020-11-18 19:13:25] Started succesfully, go nuts                  component=etcd
INFO[2020-11-18 19:13:25] etcd on unsupported platform without ETCD_UNSUPPORTED_ARCH=arm64 set  component=etcd
WARN[2020-11-18 19:13:25] exit status 1                                 component=etcd
INFO[2020-11-18 19:13:25] respawning in 5 secs                          component=etcd
INFO[2020-11-18 19:13:30] Started succesfully, go nuts                  component=etcd
INFO[2020-11-18 19:13:30] etcd on unsupported platform without ETCD_UNSUPPORTED_ARCH=arm64 set  component=etcd
WARN[2020-11-18 19:13:30] exit status 1                                 component=etcd
INFO[2020-11-18 19:13:30] respawning in 5 secs                          component=etcd
INFO[2020-11-18 19:13:35] Started succesfully, go nuts                  component=etcd
INFO[2020-11-18 19:13:35] etcd on unsupported platform without ETCD_UNSUPPORTED_ARCH=arm64 set  component=etcd
WARN[2020-11-18 19:13:35] exit status 1                                 component=etcd
INFO[2020-11-18 19:13:35] respawning in 5 secs                          component=etcd
```

**How To Reproduce**
`k0s server --enable-worker` on arm64

**Additional context**
I just found this: https://github.com/etcd-io/etcd/issues/10677

**Comment by jnummelin** [comment]
https://github.com/k0sproject/k0s/blob/8f351b3887bf80480c041121d5d1353f94dda4df/docs/troubleshooting.md#k0s-server-fails-on-arm-boxes

**Comment by rockaut** [comment]
Sorry haven't seen this, thank you.

**Comment by rockaut** [comment]
Can confirm it works then.

**Comment by jakolehm** [comment]
@jnummelin should `k0s` set this env automatically?

**Comment by jnummelin** [comment]
So we've got few options how to make this better:
1. k0s to automatically set `ETCD_UNSUPPORTED_ARCH=arm64` for etcd
This would require a WARN level log entry and some more docs around it. The downside is that this bit "hides" the fact that etcd upstream is not officially supported on arm64

2. Make k0s to "validate" this condition and exit with proper message and instructions
This would make it clear for the user that they need to do something (add the env var). User would also get clear actions when k0s exits.

@rockaut As a user, which one would you prefer to have been seen?

**Comment by ruizmarlon** [comment]
@jnummelin I think option 1 but also make sure we document properly in our arm64 instructions.
