### ISSUE TITLE
Symlink podVolumePath

### ISSUE THREAD

**Issue by rlex** [k0sproject/k0s#428]
**Is your feature request related to a problem? Please describe.**

Some backup software (in my case velero with restic) assumes that pods are located in /var/lib/kubelet/pods for volumes backup. In k0s, it's /var/lib/k0s/kubelet/pods/.

**Describe the solution you'd like**
Since /var/lib/kubelet/pods is created anyway (and seemingly not used, since it's empty) it will be nice to have it symlinked to /var/lib/k0s/kubelet/pods/ for maximum compatibility, or at least mention it somewhere in docs.

**Comment by t3hmrman** [comment]
Would like to add that [I just spent some time thinking there was a problem with Rook due to this quirk](https://github.com/rook/rook/issues/7516).

I like the idea of `k0s` keeping all the relevant config in one place, but if you're going to do that, it would be a good idea to symlink the files/folders that are expected of a regular k8s installation. The amount of software/ecosystem that is going to break out of the box with k0s is probably going to be large.

At least a note in the documentation to do this is probably worth adding.

**Comment by t3hmrman** [comment]
So I just ran into this again, but this time while installing OpenEBS's Local PV provisioner [there's an issue where someone runs into it with k3s](https://github.com/openebs/zfs-localpv/issues/235). Really think it's worth considering to find a way to *not* upset this default -- maybe put the symlink on `k0s`'s side, by having `/var/lib/k0s/kublet` be a symlink to `/var/lib/kubelet`?

**Comment by t3hmrman** [comment]
Ran into this again, this time while working with KubeVirt -- they have [`/var/lib/kubelet` in places hardcoded](https://github.com/kubevirt/kubevirt/blob/099be903803556bfe3a85075a7b55f0a711d9ca7/pkg/util/util.go#L15) (mentioned in [issue #5069 over there](https://github.com/kubevirt/kubevirt/issues/5069)) and unfortunately this time it can't be changed quite so easily. 

The symlink approach does get past this issue, and I'm likely going to leave it in place.

```console
# ln -s /var/lib/k0s/kubelet /var/lib/kubelet
```

Ideally changing the project to use a custom kubelet directory would be the solution but not all projects (probably many projects) don't expect a custom kubelet dir.

**Comment by jnummelin** [comment]
@t3hmrman thanks for "documenting" these findings in this issue.

There was two main topics we wanted to cover when we decided early to use a "custom" dir:
- All k0s related data in one place. helps in finding stuff when debugging and especially when cleaning up
- Having single config option to push all data to different place `--data-dir`. Helps e.g. in cases/distros where whole `/var` is mounted with noexec etc.

As you've found out, creating the symlink might work in most cases but still fail on others. Thus I'm slightly hesitant of making it automatically created by k0s itself. Like you said:
> Actually, you should probably NOT do this. It is probably better that projects fail very obviously than subtly.

**Comment by t3hmrman** [comment]
Hey @jnummelin no problem, I'm finding great utility in `k0s` so far, so it's the least I could do. I definitely still agree with you and past me -- this almost certainly should not be automatically created. Also of course I agree with the goals and rational behind the custom dir, generally having all the config in one place is a good thing.

I figure if this issue exists I can at least document them. IMO this issue might be closable as is (basically wontfix) -- don't know how others feel though, I didn't file this issue.

Enough documentation and some guidance around well known projects where you might run into this issue (maybe even issues on those other projects to allow the kubelet folder to be editable) is probably enough to fix this for most people -- there are only so many addons that do something serious/important enough to need access to the kubelet dir. For the usual case where people aren't working with bare metal (and trying to install things like kubevirt, rook etc), this won't be a problem I think (and if it is, maybe they'll find this issue).

**Comment by jnummelin** [comment]
> Enough documentation and some guidance around well known projects where you might run into this issue 

This is very good point. We've already covered few example "extensions" in the docs, see e.g.:
https://docs.k0sproject.io/v1.21.2+k0s.0/examples/rook-ceph/
(this actually mentions the need for changing the base path for kubelet)

Maybe we should use this approach to document the "quirks" with some of the commonly used addons. PRs welcomed 😉 

> maybe even issues on those other projects to allow the kubelet folder to be editable

👍  for this too. Having "hardcoded" paths for kubelet "stuff" seems like a bad idea in general. We've seen use cases where complete `/var` is .e.g mounted as noexec which might break many of those assumptions as some of the extension points with kubelet are using dropped executables etc.

**Comment by t3hmrman** [comment]
Ahh awesome, you already have a "cookbooks" style section, that would be the perfect place for this information to go. 

I'll try and take a stab at writing what the setup looks like from a scratch Ubuntu VM (caveat is they need access to virtualization of course so this usually will have to be a "bare metal" setup)  and maybe that can approach the current quality of the rook-ceph example docs. I can certainly say that having pages for the commonly used addons is definitely a good way to go -- good for search results, etc. If I search "k0s kubevirt" and the page shows up, instantly reassures me.

> +1 for this too. Having "hardcoded" paths for kubelet "stuff" seems like a bad idea in general. We've seen use cases where complete /var is .e.g mounted as noexec which might break many of those assumptions as some of the extension points with kubelet are using dropped executables etc.

[Filed an issue with KubeVirt](https://github.com/kubevirt/kubevirt/issues/5913), will see what they say about this, it's a nice to have for them but not sure it would make it high on their priority list.
