### ISSUE TITLE
[Question] How to decode the token?

### ISSUE THREAD

**Issue by unixfox** [k0sproject/k0s#431]
In the documentation: https://github.com/k0sproject/k0s/blob/main/docs/create-cluster.md, it's written that token is base64 encoded kubeconfig but when trying to decode the provided base64 I don't get a kubeconfig but a bunch of strange characters:
![2020-11-19_14-27](https://user-images.githubusercontent.com/4016501/99666225-9df25c80-2a62-11eb-8581-dee7ca058533.png)

Is the token encrypted? If so how do I decrypt it?

**Comment by jnummelin** [comment]
oh, the doc is slightly outdated. it's also gzipped: https://github.com/k0sproject/k0s/blob/d6c7551938626a6b3101056beb853a9cf720c215/pkg/token/joinencode.go#L26

This should do the trick to decode it:
```
 echo $token | base64 -D | gunzip -
```

**Comment by jjainschigg-r** [comment]
Small -d on some systems (e.g., Ubuntu): echo $token | base64 -d | gunzip -
