### ISSUE TITLE
Allow change of CNI Plugin

### ISSUE THREAD

**Issue by Rohmilchkaese** [k0sproject/k0s#4343]
### Is your feature request related to a problem? Please describe.

I would love to be able to change CNI Plugins. 
Lets say people get started with Kuberouter. Okay, they move on and maybe want to go with Cilium or whatever solution out there. 

### Describe the solution you would like

I have seen the following [Issue](https://github.com/k0sproject/k0s/issues/3707)! As @juanluisvaladas stated, its on purpose not supported, which i can understand, because of course, it could be dangerous. 

But: If people lets say tested, that whatever other Plugin is feasible for the workload theyre intending to run, they should be able to switch. It doesnt even have to be an automated process. But you could probagete the changes, and then lets say one could train the node and restart k0sworker.server. eg.

### Describe alternatives you've considered

Rebuilding cluster. But that is way to much work. Considering all the restoring that would have to be done. Especially for production environment's.

**Comment by juanluisvaladas** [comment]
Hi @Rohmilchkaese,

Quoting  https://github.com/k0sproject/k0s/issues/3707#issuecomment-1894182815:

> the limitation of not allowing to change the CNI provider is imposed by k0s to prevent damages. You can skip this check **at your own risk** by following these steps:
> 
>     1. Stop every worker
> 
>     2. Restart k0s every controller with `spec.network.provider: calico`
> 
>     3. Remove the kuberouter manifests on every controller: `rm -rf  /var/lib/k0s/manifests/kuberouter/`
> 
>     4. Delete the kube-router daemonset `k0s kc delete ds -n kube-system   kube-router`
> 
>     5. Restart k0s every controller again and make sure kube-router is not redeployed
> 
>     6. On every worker remove /etc/cni/net.d/*
> 
>     7. Restart every worker
> 
> 
> Keep in mind that this procedure isn't supported or properly tested and it could go wrong at any time

My understanding is that this should address what you're requesting, or am I missing something?

**Comment by Rohmilchkaese** [comment]
Yeah, i mean it is what i was looking for! Maybe we can add it to docs..
