### ISSUE TITLE
Support config kubelet arg "--pod-infra-container-image"

### ISSUE THREAD

**Issue by hashwing** [k0sproject/k0s#437]
**Is your feature request related to a problem? Please describe.**
Support config kubelet arg "--pod-infra-container-image"

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by AceAttorney** [comment]
need this feature

**Comment by jnummelin** [comment]
this is possible now since 0.11 version: https://docs.k0sproject.io/v0.11.1/worker-node-config/#kubelet-args

so you'd need to run something like `k0s worker --kubelet-extra-args="--pod-infra-container=foobar/pause:v1.2.3"`
