### ISSUE TITLE
Include correct architecture binaries on ARMv8 & ARMv7 for the components

### ISSUE THREAD

**Issue by unixfox** [k0sproject/k0s#439]
**Is your feature request related to a problem? Please describe.**
When running `make EMBEDDED_BINS_BUILDMODE=fetch` on an ARM device (ARMv8 and ARMv7), k0s downloads AMD64/x86 binaries instead of the correct ARM architecture.

**Describe the solution you'd like**
I would like that k0s downloads the binaries for the correct architecture and if a prebuilt binary doesn't exist then build it.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by ncopa** [comment]
I'm not sure all componets provide precompiled arm binaries?
Looks like runc only provides precompiled binaries for amd64:
https://github.com/opencontainers/runc/releases

**Comment by unixfox** [comment]
You are right, not all components provides ARM prebuilt binaries.

Should we then compile them from the source code just like for kine and konnectivity-server?

I just changed the title due to that.

**Comment by ncopa** [comment]
I had a look at this and this is a bit more difficult than it seems. We'd also need [calico images](https://github.com/k0sproject/k0s/blob/fd0aead271d660ca8576e9dceaf96e7d2a0fc15b/pkg/constant/constant.go#L97) to support 32 bit arm, and currently they don't. So even if we got the binaries built for 32 bit arm, it wouldn't actually work.

**Comment by unixfox** [comment]
What do you think about providing pre-built k0s binaries for ARMv7 with just a limited support so without calico working?
Users would have to deploy calico themselves by for example compiling calico (https://github.com/projectcalico/cni-plugin/issues/869) or using another CNI?
At least if a user really wants to use k0s on ARMv7 then he doesn't have to go through the hassle of compiling k0s.

**Comment by jnummelin** [comment]
Closed as there's now armv7 compatible builds available
