### ISSUE TITLE
Remove pinning from outdated k0s-imported OCI images

### ISSUE THREAD

**Issue by twz123** [k0sproject/k0s#4433]
When k0s [imports](https://docs.k0sproject.io/v1.30.0+k0s.0/airgap-install/#2a-sync-the-bundle-file-with-the-airgapped-machine-locally) OCI images into containerd, it [pins](https://github.com/k0sproject/k0s/issues/3389) them to prevent them from being garbage collected. If the OCI images are replaced regularly over time, e.g. if an airgapped cluster is regularly upgraded, these images will pile up in containerd's image filesystem, potentially leading to disk pressure at some point.

K0s should be smart about this. It should unpin imported images that are no longer in the import folder. This will allow containerd to remove any old images once they are no longer in use.

**Comment by ricardomaraschini** [comment]
I am more than happy to work on this if no one is acting yet.

**Comment by jnummelin** [comment]
❤️ 

One idea I had for this was to label each image with the filename where it was imported from. That way we can delete images which no more has bundle file for it. Haven't spent much time thinking about this so there might be some gaps in my idea... 😂

**Comment by twz123** [comment]
> I am more than happy to work on this if no one else is acting yet.

Yes, please! Go ahead :rocket:

I was thinking about adding some extra labels to the imported images, so that k0s can identify which ones have been imported previously. Then it could remove the pin label from those previously imported images that aren't part of any of the bundles in the bundle dir anymore. Or sth. along those lines. WDYT?

**Comment by ricardomaraschini** [comment]
I had designed a possible solution using Labels as proposed. Let me know what you think: https://github.com/k0sproject/k0s/pull/4500
