### ISSUE TITLE
Specify resolvers for coredns

### ISSUE THREAD

**Issue by Starttoaster** [k0sproject/k0s#4459]
Looking around in k0sctl docs, I don't see an option for specifying the forward servers for coredns. They just forward to the host's `/etc/resolv.conf` file. See the coredns configmap here:

```
kubectl get configmap coredns -o yaml
apiVersion: v1
data:
  Corefile: |
    .:53 {
        errors
        health
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          ttl 30
          fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        forward . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
    }
```

My hosts all use Tailscale's "magic DNS" in there, alongside a couple of other resolvers. However, Tailscale's magic DNS appears to have a rate limit that is causing issues on our cluster hosts for nameserver limits. And I think _ideally_ I would be able to set the forward address to something I specify, like `1.1.1.1`. See an example of the Events we're getting in the cluster here:

```
Nameserver limits were exceeded, some nameservers have been omitted, the applied nameserver line is: 100.100.100.100 1.1.1.1
```

I think ideally, I would still be able to use "magicDNS" on these hosts outside of the context of kubernetes, but have coredns not attempt to go through magicDNS at all. If that's possible now, I guess I just didn't see it in the documentation. But if I'm right and it's not possible now, this is a feature suggestion for it. :)

**Comment by Starttoaster** [comment]
Also, apologies if this would be better suited for the k0sctl project. This struck me as something maybe k0s would need to support before k0sctl could, so I made the issue here.

**Comment by twz123** [comment]
Currently, I think the only option to reliably change the CoreDNS configuration is to roll your own CoreDNS manifests. You can start the controller nodes using `--disable-components=coredns` and take over ownership of the manifests in `<data-dir>/manifests/coredns`.

**Comment by twz123** [comment]
> Thanks for the response! Is `<data-dir>` a location in a git repo, or a location on my k8s hosts then?

This is the data directory for k0s, i.e. what's passed to the `--data-dir` flag when launching k0s. If you didn't specify it, it defaults to `/var/lib/k0s`.

**Comment by Starttoaster** [comment]
It'd be cool to have a feature for that in k0s/k0sctl. But for now my team is just managing the corefile ConfigMap, rather than the whole coredns deployment. Basically just installing/upgrading with k0sctl and then really quickly paving over the default configmap with our own.

Anyway, we can close this Issue. Sounds like there's a feature proposal outside of this Issue and I'm not sure there's any guidance outside of that to provide here. If you can think of a reason why us managing just the CoreDNS ConfigMap is a bad idea, please let me know though.

**Comment by ABaradar** [comment]
>  then really quickly paving over the default configmap with our own.

I actually handled it a bit differently in [my setup](https://github.com/ABaradar/CtlBreeze?tab=readme-ov-file#coredns-configuration-note) and it’s worked well for us. Instead of manually patching the CoreDNS ConfigMap after each k0sctl install/upgrade, I declare all of my CoreDNS tweaks in helm chart extension’s values. That way, on every install or upgrade, the ConfigMap is rendered exactly how I need it—no extra scripting or manual steps required.

just thought I’d mention it in case it’s helpful!
