### ISSUE TITLE
Have a darwin-amd64 binary of k0s

### ISSUE THREAD

**Issue by cmoulliard** [k0sproject/k0s#449]
**Is your feature request related to a problem? Please describe.**
We cannot use the existing binaries (amd or arm) on macos as it will report when excuted from a terminal
```
zsh: exec format error: ./k0s-v0.7.0-amd64
```

**Describe the solution you'd like**
Release for macos a binary `k0s-darwin-amd64`

**Comment by jnummelin** [comment]
There's no Darwin binary build as kube components do not support Darwin.  That means there will probably never be `k0s` for darwin built.

**Comment by jnummelin** [comment]
Closing as upstream kubernetes does not support Darwin so k0s cannot either.
