### ISSUE TITLE
Backport bump Helm Library version

### ISSUE THREAD

**Issue by jdewinne** [k0sproject/k0s#4541]
### Is your feature request related to a problem? Please describe.

helm charts reconciliation does not work for oci registries when running k0s behind a proxy. the bug has been solved upstream (helm) and has now been released.

PR that fixed it for k0s 1.30 and higher: #4297

Helm PR that addressed the bug:

[helm/helm#12761](https://github.com/helm/helm/pull/12761)

### Describe the solution you would like

Backport the PR #4297 to k0s 1.28 and 1.29

### Describe alternatives you've considered

An alternative could be creating and maintaining a fork of 1.28 and 1.29.

**Comment by jnummelin** [comment]
Backporting to 1.29 should be trivial as the Helm dependency there is also on 3.14.x

1.28 is unfortunately not so easy as Helm there is 3.12.x and there's probably some incompatible golang APIs involved. Didn't check but we've also seen very problematic dependency chains with Helm so I don't think updating helm to 3.14.x in 1.28 branch would work. @twz123 WDYT?

**Comment by twz123** [comment]
Backporting to 1.28 and 1.27 seems to be problematic. 1.28 is on Helm 3.12, 1.27 is on Helm 3.11. I doubt that upstream Helm will backport this fix that far.

**Comment by jdewinne** [comment]
Thanks for looking into this. Knowing that 1.28 will also be EOL in a couple months, I think just focusing on 1.29 should already be sufficient. I noticed the PR #4570 is already available. Thank you for that!

**Comment by twz123** [comment]
Alright. Backported to 1.29.
