### ISSUE TITLE
Not accurate documentation for nvidia-container-runtime

### ISSUE THREAD

**Issue by nekwar** [k0sproject/k0s#4558]
### Before creating an issue, make sure you've checked the following:

- [ ] You are running the latest released version of k0s
- [X] Make sure you've searched for existing issues, both open and closed
- [X] Make sure you've searched for PRs too, a fix might've been merged already
- [X] You're looking at docs for the released version, "main" branch docs are usually ahead of released versions.

### Platform

```shell
PRETTY_NAME="Ubuntu 22.04.4 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.4 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

### Version

v1.29.1+k0s.0

### Sysinfo

<details><summary>`k0s sysinfo`</summary>
<pre>
➡️ Please replace this text with the output of `k0s sysinfo`. ⬅️
</pre>
</details>

### What happened?

This part of a documentation for nvidia-container-runtime is not accurate: https://docs.k0sproject.io/head/runtime/#using-nvidia-container-runtime

Following this doc, we're getting this error message on some of the pods (that are using `nvidia` RuntimeClass):
```
Failed to create pod sandbox: rpc error: code = Unknown desc = failed to get sandbox runtime: no runtime for "nvidia" is configured
```
More details can be obtained here: https://github.com/NVIDIA/gpu-operator/issues/463

### Steps to reproduce

1. Add new .toml config in `/etc/k0s/containerd.d/` according to the documentation https://docs.k0sproject.io/head/runtime/#using-nvidia-container-runtime with nvidia runtime configuration
2. Deploy NVIDIA GPU operator following this article https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/latest/getting-started.html#gpu-operator-helm-chart-options

### Additional context
**Root cause**
The root cause for this issue is that containerd config from `/etc/k0s/containerd.d/<config-name>.toml` is not merged correctly due to https://github.com/containerd/containerd/issues/5837 (because `/etc/k0s/containerd.toml` contains `imports` section)

**Solution:**
Set `CONTAINERD_CONFIG` env in gpu-operator helm chart to `/run/k0s/containerd-cri.toml`. Example:
```bash
helm install --wait gpu-operator -n gpu-operator --create-namespace nvidia/gpu-operator --set operator.defaultRuntime=containerd --set toolkit.env\[0\].name=CONTAINERD_CONFIG --set toolkit.env\[0\].value=/run/k0s/containerd-cri.toml --set toolkit.env\[1\].name=CONTAINERD_SOCKET --set toolkit.env\[1\].value=/run/k0s/containerd.sock --set toolkit.env\[2\].name=CONTAINERD_RUNTIME_CLASS --set toolkit.env\[2\].value=nvidia
```

I think the best solution here would be to correct documentation.

**Comment by twz123** [comment]
The documentation is about installing the NVIDIA Container Runtime. This issue seems to be related to the GPU operator, which is not yet documented. Would you mind opening a PR for that?

> Solution:
> Set CONTAINERD_CONFIG env in gpu-operator helm chart to /run/k0s/containerd-cri.toml.

Not sure if that's a sustainable solution, as k0s will regenerate that file on startup and on each change to `/etc/k0s/containerd.d/*`. Do you know what the operator does to the containerd config file? Maybe let `CONTAINERD_CONFIG` point to, say, `/etc/k0s/containerd.d/nvidia-gpu-operator.yaml` instead?

**Comment by twz123** [comment]
Alright, closing, as the docs PR landed.
