### ISSUE TITLE
Cannot get master in the list of nodes

### ISSUE THREAD

**Issue by lucj** [k0sproject/k0s#466]
**Version**
```
$ k0s version
v0.7.0
```

**Platform**
Which platform did you run k0s on?
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal
```

**What happened?**

I created a 3 nodes cluster (master + 2 workers). The master is not listed with a 'kubectl get nodes'

**Screenshots & Logs**
Also add any output from kubectl if applicable:
```
$ kubectl get no
NAME    STATUS   ROLES    AGE     VERSION
node2   Ready    <none>   7m6s    v1.19.3
node3   Ready    <none>   6m59s   v1.19.3
```

**Comment by ncopa** [comment]
This is because the master by design does not run any workloads by default, so it works as intended.

If you really want your master to accept workloads you have to start the server with `k0s server --enable-worker`. The master should  show up in `kubectl` after that.

**Comment by lucj** [comment]
Sorry, it was not intended to be filled as an issue, but was simply a question :)
Thanks for your help

**Comment by lucj** [comment]
Is it the same reason why api server, controller-manager and scheduler are not listed in the kube-system pods ?
````
$ kubectl get po -A
NAMESPACE     NAME                                       READY   STATUS              RESTARTS   AGE
kube-system   calico-kube-controllers-5f6546844f-vw4kt   1/1     Running             0          4h6m
kube-system   calico-node-fg9rk                          1/1     Running             0          26m
kube-system   calico-node-wrgg2                          1/1     Running             0          25m
kube-system   coredns-5c98d7d4d8-jdhdc                   0/1     CrashLoopBackOff    9          4h6m
kube-system   konnectivity-agent-khfcq                   1/1     Running             0          25m
kube-system   konnectivity-agent-r9v2v                   1/1     Running             0          25m
kube-system   kube-proxy-8zq2g                           1/1     Running             0          26m
kube-system   kube-proxy-qnslk                           1/1     Running             0          25m
kube-system   metrics-server-7d4bcb75dd-sx7kb            0/1     ContainerCreating   0          4h6m
````

**Comment by ncopa** [comment]
No worries, it means the documentation could be more clear

> Is it the same reason why api server, controller-manager and scheduler are not listed in the kube-system pods ?

Correct. The api server and controller manager does not run in pods, but as "naked" processes on the host. You can see them with the command `ps xa`
