### ISSUE TITLE
K0s iptables rules block ssh login

### ISSUE THREAD

**Issue by DevTech288** [k0sproject/k0s#4661]
### Before creating an issue, make sure you've checked the following:

- [X] You are running the latest released version of k0s
- [X] Make sure you've searched for existing issues, both open and closed
- [X] Make sure you've searched for PRs too, a fix might've been merged already
- [X] You're looking at docs for the released version, "main" branch docs are usually ahead of released versions.

### Platform

```shell
Linux 6.1.0-21-cloud-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.90-1 (2024-05-03) x86_64 GNU/Linux
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
xqt@Praktikum2024:~/kube/helm_charts$
```

### Version

v1.29.2+k0s.0

### Sysinfo

Machine ID: "9bfdb95be2494eb5a457adc93d2f09086da6872435e96cefb1f96a45e585855e" (from machine) (pass)
Total memory: 15.6 GiB (pass)
Disk space available for /var/lib/k0s: 105.4 GiB (pass)
Name resolution: localhost: [::1 127.0.0.1] (pass)
Operating system: Linux (pass)
  Linux kernel release: 6.1.0-21-cloud-amd64 (pass)
  Max. file descriptors per process: current: 1048576 / max: 1048576 (pass)
  AppArmor: active (pass)
  Executable in PATH: modprobe: /usr/sbin/modprobe (pass)
  Executable in PATH: mount: /usr/bin/mount (pass)
  Executable in PATH: umount: /usr/bin/umount (pass)
  /proc file system: mounted (0x9fa0) (pass)
  Control Groups: version 2 (pass)
    cgroup controller "cpu": available (is a listed root controller) (pass)
    cgroup controller "cpuacct": available (via cpu in version 2) (pass)
    cgroup controller "cpuset": available (is a listed root controller) (pass)
    cgroup controller "memory": available (is a listed root controller) (pass)
    cgroup controller "devices": available (device filters attachable) (pass)
    cgroup controller "freezer": available (cgroup.freeze exists) (pass)
    cgroup controller "pids": available (is a listed root controller) (pass)
    cgroup controller "hugetlb": available (is a listed root controller) (pass)
    cgroup controller "blkio": available (via io in version 2) (pass)
  CONFIG_CGROUPS: Control Group support: built-in (pass)
    CONFIG_CGROUP_FREEZER: Freezer cgroup subsystem: built-in (pass)
    CONFIG_CGROUP_PIDS: PIDs cgroup subsystem: built-in (pass)
    CONFIG_CGROUP_DEVICE: Device controller for cgroups: built-in (pass)
    CONFIG_CPUSETS: Cpuset support: built-in (pass)
    CONFIG_CGROUP_CPUACCT: Simple CPU accounting cgroup subsystem: built-in (pass)
    CONFIG_MEMCG: Memory Resource Controller for Control Groups: built-in (pass)
    CONFIG_CGROUP_HUGETLB: HugeTLB Resource Controller for Control Groups: built-in (pass)
    CONFIG_CGROUP_SCHED: Group CPU scheduler: built-in (pass)
      CONFIG_FAIR_GROUP_SCHED: Group scheduling for SCHED_OTHER: built-in (pass)
        CONFIG_CFS_BANDWIDTH: CPU bandwidth provisioning for FAIR_GROUP_SCHED: built-in (pass)
    CONFIG_BLK_CGROUP: Block IO controller: built-in (pass)
  CONFIG_NAMESPACES: Namespaces support: built-in (pass)
    CONFIG_UTS_NS: UTS namespace: built-in (pass)
    CONFIG_IPC_NS: IPC namespace: built-in (pass)
    CONFIG_PID_NS: PID namespace: built-in (pass)
    CONFIG_NET_NS: Network namespace: built-in (pass)
  CONFIG_NET: Networking support: built-in (pass)
    CONFIG_INET: TCP/IP networking: built-in (pass)
      CONFIG_IPV6: The IPv6 protocol: built-in (pass)
    CONFIG_NETFILTER: Network packet filtering framework (Netfilter): built-in (pass)
      CONFIG_NETFILTER_ADVANCED: Advanced netfilter configuration: built-in (pass)
      CONFIG_NF_CONNTRACK: Netfilter connection tracking support: module (pass)
      CONFIG_NETFILTER_XTABLES: Netfilter Xtables support: module (pass)
        CONFIG_NETFILTER_XT_TARGET_REDIRECT: REDIRECT target support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_COMMENT: "comment" match support: module (pass)
        CONFIG_NETFILTER_XT_MARK: nfmark target and match support: module (pass)
        CONFIG_NETFILTER_XT_SET: set target and match support: module (pass)
        CONFIG_NETFILTER_XT_TARGET_MASQUERADE: MASQUERADE target support: module (pass)
        CONFIG_NETFILTER_XT_NAT: "SNAT and DNAT" targets support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_ADDRTYPE: "addrtype" address type match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_CONNTRACK: "conntrack" connection tracking match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_MULTIPORT: "multiport" Multiple port match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_RECENT: "recent" match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_STATISTIC: "statistic" match support: module (pass)
      CONFIG_NETFILTER_NETLINK: module (pass)
      CONFIG_NF_NAT: module (pass)
      CONFIG_IP_SET: IP set support: module (pass)
        CONFIG_IP_SET_HASH_IP: hash:ip set support: module (pass)
        CONFIG_IP_SET_HASH_NET: hash:net set support: module (pass)
      CONFIG_IP_VS: IP virtual server support: module (pass)
        CONFIG_IP_VS_NFCT: Netfilter connection tracking: built-in (pass)
        CONFIG_IP_VS_SH: Source hashing scheduling: module (pass)
        CONFIG_IP_VS_RR: Round-robin scheduling: module (pass)
        CONFIG_IP_VS_WRR: Weighted round-robin scheduling: module (pass)
      CONFIG_NF_CONNTRACK_IPV4: IPv4 connetion tracking support (required for NAT): unknown (warning)
      CONFIG_NF_REJECT_IPV4: IPv4 packet rejection: module (pass)
      CONFIG_NF_NAT_IPV4: IPv4 NAT: unknown (warning)
      CONFIG_IP_NF_IPTABLES: IP tables support: module (pass)
        CONFIG_IP_NF_FILTER: Packet filtering: module (pass)
          CONFIG_IP_NF_TARGET_REJECT: REJECT target support: module (pass)
        CONFIG_IP_NF_NAT: iptables NAT support: module (pass)
        CONFIG_IP_NF_MANGLE: Packet mangling: module (pass)
      CONFIG_NF_DEFRAG_IPV4: module (pass)
      CONFIG_NF_CONNTRACK_IPV6: IPv6 connetion tracking support (required for NAT): unknown (warning)
      CONFIG_NF_NAT_IPV6: IPv6 NAT: unknown (warning)
      CONFIG_IP6_NF_IPTABLES: IP6 tables support: module (pass)
        CONFIG_IP6_NF_FILTER: Packet filtering: module (pass)
        CONFIG_IP6_NF_MANGLE: Packet mangling: module (pass)
        CONFIG_IP6_NF_NAT: ip6tables NAT support: module (pass)
      CONFIG_NF_DEFRAG_IPV6: module (pass)
    CONFIG_BRIDGE: 802.1d Ethernet Bridging: module (pass)
      CONFIG_LLC: module (pass)
      CONFIG_STP: module (pass)
  CONFIG_EXT4_FS: The Extended 4 (ext4) filesystem: built-in (pass)
  CONFIG_PROC_FS: /proc file system support: built-in (pass)

### What happened?

A colleague of mine installed k0s on a Debian 12 VM. Since then, the iptables rules created by k0s block my ssh login (port 22). When I delete them using sudo iptables -F and then sudo iptables -X, the ssh login works. However, they are recreating and I can not find how to change k0s to not create iptables rules that block my ssh port. On the VM there is only gitlab installed with k0s. Maybe gitlab-gitlab-shell is creating the iptables rule. What may cause k0s to create rules that block ssh login?

### Steps to reproduce

1. install k0s
2. install gitlab in k0s
3. login with ssh -> Permission denied (publickey,keyboard-interactive).
However telnet <ip> 22 works

If i stop the gitlab pods then ssh port 22 is not even reachable:
1. sudo k0s kubectl scale deployment.apps --replicas 0 --all -n gitlab
2. login with ssh -> Connection refused.
3. telnet <ip> 22 -> Verbindungsaufbau zu 22...Es konnte keine Verbindung mit dem Host hergestellt werden, auf Port 23: Verbindungsfehler

### Expected behavior

Login with ssh ->successfully logged into VM

### Actual behavior

Login with ssh -> not logged into VM (only after VM restart before k0s boots)

### Screenshots and logs

sudo k0s kubectl logs gitlab-gitlab-shell-b9f9cd7cb-d76jb -n gitlab
Defaulted container "gitlab-shell" out of: gitlab-shell, certificates (init), configure (init)
Begin parsing .tpl templates from /etc/gitlab-shell
Writing /srv/gitlab-shell/config.yml
Copying other config files found in /etc/gitlab-shell to /srv/gitlab-shell
Using existing Host Keys
{"component": "gitlab-shell","subcomponent":"ssh","time":"2024-06-20T08:13:13Z","message":"kex_exchange_identification: Connection closed by remote host\r"}
{"component": "gitlab-shell","subcomponent":"ssh","time":"2024-06-20T08:13:18Z","message":"kex_exchange_identification: Connection closed by remote host\r"}
{"component": "gitlab-shell","subcomponent":"ssh","time":"2024-06-20T08:13:23Z","message":"kex_exchange_identification: Connection closed by remote host\r"}
{"component": "gitlab-shell","subcomponent":"ssh","time":"2024-06-20T08:13:28Z","message":"kex_exchange_identification: Connection closed by remote host\r"}

**Comment by twz123** [comment]
> What may cause k0s to create rules that block ssh login?

K0s is not creating any iptables rules on its own. It's kube-proxy and the CNI implementation (kube-router by default) which are doing this. No idea why this happens, though.

/cc #4648 and @juanluisvaladas

Just a wild guess, might be completely unrelated: Could it have something to do with the automatic detection of addresses (#4582)?

**Comment by juanluisvaladas** [comment]
I don't think k0s can create any rule related to this, my guess is that the gitlab deployment is messing somehow with iptables rules and ssh (which makes sense because most git servers will use ssh).

I think the most reasonable thing here is to check the output of `iptables-save -c` and see what's blocking port 22.
Also I'd like to see the yaml output of the gitlab pod and services.

> Just a wild guess, might be completely unrelated: Could it have something to do with the automatic detection of addresses (https://github.com/k0sproject/k0s/pull/4582)?

I'm more inclined to think it's probably caused by gitlab, but it's certainly worth keeping this in mind

**Comment by DevTech288** [comment]
Here my outputs of iptables-save -c and the output of gitlab pods and services
[iptables_output.txt](https://github.com/user-attachments/files/15914342/iptables_output.txt)
[girlab_svc_output.txt](https://github.com/user-attachments/files/15914343/svc_output.txt)
[gitlab_deployment_output.txt](https://github.com/user-attachments/files/15914344/yaml_output.txt)

**Comment by juanluisvaladas** [comment]
Hi @DevTech288, it looks like it's the service: `gitlab/gitlab-nginx-ingress-controller` when you try to ssh to `10.176.32.199`. Is it correct that you're trying to ssh to this address?

To be more precise, the rules I see in IPtables filtering destination port 22 are:
```
[0:0] -A INPUT -p tcp -m tcp --dport 22 -j ACCEPT <- this is your rule, it's fine
[0:0] -A KUBE-SERVICES -d 10.109.37.154/32 -p tcp -m comment --comment "gitlab/gitlab-nginx-ingress-controller:gitlab-shell cluster IP" -m tcp --dport 22 -j KUBE-SVC-4EYBQSXCAR4MY2II <- this is a cluster IP, shouldn't affect you

[5:260] -A KUBE-SERVICES -d 10.176.32.199/32 -p tcp -m comment --comment "gitlab/gitlab-nginx-ingress-controller:gitlab-shell external IP" -m tcp --dport 22 -j KUBE-EXT-4EYBQSXCAR4MY2II <- this is probably the culprit

[0:0] -A KUBE-SERVICES -d 10.108.18.107/32 -p tcp -m comment --comment "gitlab/gitlab-gitlab-shell:ssh cluster IP" -m tcp --dport 22 -j KUBE-SVC-5NSPTL6HOMDUVKYJ
[0:0] -A KUBE-SVC-4EYBQSXCAR4MY2II ! -s 10.244.0.0/16 -d 10.109.37.154/32 -p tcp -m comment --comment "gitlab/gitlab-nginx-ingress-controller:gitlab-shell cluster IP" -m tcp --dport 22 -j KUBE-MARK-MASQ <- This is yet another cluster IP, so again it should be unrelated

[0:0] -A KUBE-SVC-5NSPTL6HOMDUVKYJ ! -s 10.244.0.0/16 -d 10.108.18.107/32 -p tcp -m comment --comment "gitlab/gitlab-gitlab-shell:ssh cluster IP" -m tcp --dport 22 -j KUBE-MARK-MASQ <- Again, a clusterIP, I understand 10.244.0.0/16 is the pod network so it should be unrelated
```
I see the service has:
```
- apiVersion: v1
  kind: Service
  metadata:
    <snip>
    name: gitlab-nginx-ingress-controller
    namespace: gitlab
    <snip>
  spec:
    allocateLoadBalancerNodePorts: true
    clusterIP: 10.109.37.154
    clusterIPs:
    - 10.109.37.154
    externalIPs:
    - 10.176.32.199 <- This is where you forward 10.176.32.199 to nginx
    externalTrafficPolicy: Local
    healthCheckNodePort: 32055
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http
      nodePort: 30608
      port: 80
      protocol: TCP
      targetPort: http
    - name: gitlab-shell
      nodePort: 32107
      port: 22
      protocol: TCP
      targetPort: gitlab-shell
    selector:
      app: nginx-ingress
      component: controller
      release: gitlab
    sessionAffinity: None
    type: LoadBalancer
  status:
    loadBalancer: {}
```

**Comment by DevTech288** [comment]
Hi, @juanluisvaladas I updated port 22 to 2222 in the service, now it works. Thank you so much!

**Comment by DevTech288** [comment]
Closed as solved

**Comment by DevTech288** [comment]
Closed as solved
