### ISSUE TITLE
32-bit k0s

### ISSUE THREAD

**Issue by mchaker** [k0sproject/k0s#468]
**Is your feature request related to a problem? Please describe.**
I can't compile k0s for 32-bit machines.

**Describe the solution you'd like**
I would like to successfully compile/build/run k0s for 32-bit machines

**Describe alternatives you've considered**
I have only tried `make EMBEDDED_BINS_BUILDMODE=fetch`

**Additional context**
I have a Pentium 4 Dell Optiplex SX260 with 2 GB RAM that I would like to install k0s on, and join to an existing cluster as a worker node.

If joining an existing cluster won't work, I would like to be able to install k0s and run it as a controller node, with other 32-bit machines as worker nodes.

**Comment by jnummelin** [comment]
> I have only tried make EMBEDDED_BINS_BUILDMODE=fetch

That's not gonna work as upstream kube does not build the bins for 32bit archs

Even if we'd be able to build k0s and most kube components as 32bit, there's still bunch upstream components which do not ship 32bit images: pause, kube-proxy, coredns

**Comment by ncopa** [comment]
I had a look at this and it seems that none of the images we are using supports 32 bit x86
https://github.com/k0sproject/k0s/blob/fd0aead271d660ca8576e9dceaf96e7d2a0fc15b/pkg/constant/constant.go#L88

Upstream would need to support 32 bit x86 before we can do so.

**Comment by mchaker** [comment]
I see, thanks for the clarification. I'll look into finding/making 32-bit images of all upstream dependencies.
