### ISSUE TITLE
RabbitMQ chart never leaves pending

### ISSUE THREAD

**Issue by cameronelliott** [k0sproject/k0s#470]
**Version**
```
v0.8.0-rc1-2-g1ad08a9
```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic
```
$ lsb_release -a
```
**What happened?**
Particular chart never gets past Pending to Running

**How To Reproduce**
```
helm repo add bitnami https://charts.bitnami.com/bitnami
helm install my-release bitnami/rabbitmq
kubectl get pod --all-namespaces
```
Normally this goes running under 1 minute, on same hardware on k3s
20 minutes later on k0s this is still in pending not running state.

**Expected behavior**
I would expect it to go running in under 60 seconds.

**Additional context**
Tested the three 'how to repoduce' commands under k3s and k8s(digital ocean) and the helm chart goes into
running under a minute.

**Comment by WilliamDahlen** [comment]
What does kubectl describe pod <podname> say under Events:? Do you have any other pods running on the same cluster?

**Comment by cameronelliott** [comment]
```
1 pod has unbound immediate PersistentVolumeClaims
```
Sorry, you probably don't want to be helping at this level.

**Comment by jnummelin** [comment]
k0s does not currently ship with any PV provider. So to be able to use PVs you must first setup some provider. In non-cloud envs you could use [Rook](https://github.com/rook/rook/blob/master/Documentation/helm-operator.md) or [OpenEBS](https://github.com/openebs/openebs) for example.

**Comment by jnummelin** [comment]
As this is not really k0s issue, closing.
