### ISSUE TITLE
Automation-friendly cluster setup

### ISSUE THREAD

**Issue by pricec** [k0sproject/k0s#473]
**Is your feature request related to a problem? Please describe.**
As a cluster operator, I would like to create a cluster using infrastructure as code. The requirement to use the encoded kubeconfig join token makes this more challenging than I would like. My current solution works something like the following.

1. Create base VM image with k0s included.
2. Using terraform, create controller and worker instances.
3. Using ansible, set up and start a systemd service running k0s on the primary master.
3. Using ansible, create a controller and worker tokens on the primary controller.
4. Using ansible, copy the controller join token to each secondary controller, set up and start a systemd service running k0s.
5. Using ansible, copy the worker join token to each worker, set up and start a systemd service running k0s.

**Describe the solution you'd like**
I would like to have a secondary join flow which allows me to join a worker or a controller to the primary controller by providing a pre-shared key together with the address of the primary controller. This would allow a solution something like the following.

1. Create base VM with k0s included.
2. Using terraform, create the primary controller; provide the k0s configuration (including pre-shared join token) and the systemd unit file as write_file directives in the cloud-init configuration.
3-4. Repeat 2, except for secondary controllers and workers and providing the IP address of the primary controller in addition to the join token.

Any join flow which allows cloud-init to be used rather than requiring direct provisioning steps will greatly simplify deployment on all modern cloud and virtualization platforms.

**Comment by pricec** [comment]
#206 may be related

**Comment by jasmingacic** [comment]
At the moment you can do this with terraform on AWS by doing similar to this https://github.com/k0sproject/k0s/blob/main/inttest/conformance/terraform/main.tf of course you would have to remove installation of the sonobouy on the controller. 
Does this help?

**Comment by trawler** [comment]
Hi @pricec 
We are fully aware that #206 is a desired feature and is actually in the works. I will keep your issue open, and will link it to the new feature PR when it's ready. Thanks for your report!

**Comment by pricec** [comment]
> At the moment you can do this with terraform on AWS by doing similar to this https://github.com/k0sproject/k0s/blob/main/inttest/conformance/terraform/main.tf of course you would have to remove installation of the sonobouy on the controller.
> Does this help?

I'm able to do something like this (i.e. use ansible after terraform), but the point is that this is not the kind of tidy solution I'm looking for. I'd like to have a lower friction setup by seeding the necessary information in a cloud-init rather than needing to worry about SSH connections after the fact. SSH connections may not even be possible in certain configurations, but more to the point, I want to be able to set up auto-scaling groups with userdata, and requiring extra SSH steps makes that harder than it needs to be.
