### ISSUE TITLE
Following https://docs.k0sproject.io/v1.30.2+k0s.0/install/ to setup but sudo k0s kubectl get nodes is showing "No resources found"

### ISSUE THREAD

**Issue by Jaryllan** [k0sproject/k0s#4769]
### Before creating an issue, make sure you've checked the following:

- [X] You are running the latest released version of k0s
- [X] Make sure you've searched for existing issues, both open and closed
- [X] Make sure you've searched for PRs too, a fix might've been merged already
- [X] You're looking at docs for the released version, "main" branch docs are usually ahead of released versions.

### Platform

```shell
Linux 5.15.0-116-generic #126-Ubuntu SMP Mon Jul 1 10:14:24 UTC 2024 x86_64 GNU/Linux
PRETTY_NAME="Ubuntu 22.04.4 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.4 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

and

Linux 6.8.0-38-generic #38-Ubuntu SMP PREEMPT_DYNAMIC Fri Jun  7 15:25:01 UTC 2024 x86_64 GNU/Linux
PRETTY_NAME="Ubuntu 24.04 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04 LTS (Noble Numbat)"
VERSION_CODENAME=noble
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=noble
LOGO=ubuntu-logo
```

### Version

v1.30.2+k0s.0

### Sysinfo

<details><summary>`k0s sysinfo`</summary>
<pre>
➡️ Total memory: 11.6 GiB (pass)
Disk space available for /var/lib/k0s: 119.4 GiB (pass)
Name resolution: localhost: [127.0.0.1] (pass)
Operating system: Linux (pass)
  Linux kernel release: 6.8.0-38-generic (pass)
  Max. file descriptors per process: current: 1048576 / max: 1048576 (pass)
  AppArmor: active (pass)
  Executable in PATH: modprobe: /usr/sbin/modprobe (pass)
  Executable in PATH: mount: /usr/bin/mount (pass)
  Executable in PATH: umount: /usr/bin/umount (pass)
  /proc file system: mounted (0x9fa0) (pass)
  Control Groups: version 2 (pass)
    cgroup controller "cpu": available (is a listed root controller) (pass)
    cgroup controller "cpuacct": available (via cpu in version 2) (pass)
    cgroup controller "cpuset": available (is a listed root controller) (pass)
    cgroup controller "memory": available (is a listed root controller) (pass)
    cgroup controller "devices": available (device filters attachable) (pass)
    cgroup controller "freezer": available (cgroup.freeze exists) (pass)
    cgroup controller "pids": available (is a listed root controller) (pass)
    cgroup controller "hugetlb": available (is a listed root controller) (pass)
    cgroup controller "blkio": available (via io in version 2) (pass)
  CONFIG_CGROUPS: Control Group support: built-in (pass)
    CONFIG_CGROUP_FREEZER: Freezer cgroup subsystem: built-in (pass)
    CONFIG_CGROUP_PIDS: PIDs cgroup subsystem: built-in (pass)
    CONFIG_CGROUP_DEVICE: Device controller for cgroups: built-in (pass)
    CONFIG_CPUSETS: Cpuset support: built-in (pass)
    CONFIG_CGROUP_CPUACCT: Simple CPU accounting cgroup subsystem: built-in (pass)
    CONFIG_MEMCG: Memory Resource Controller for Control Groups: built-in (pass)
    CONFIG_CGROUP_HUGETLB: HugeTLB Resource Controller for Control Groups: built-in (pass)
    CONFIG_CGROUP_SCHED: Group CPU scheduler: built-in (pass)
      CONFIG_FAIR_GROUP_SCHED: Group scheduling for SCHED_OTHER: built-in (pass)
        CONFIG_CFS_BANDWIDTH: CPU bandwidth provisioning for FAIR_GROUP_SCHED: built-in (pass)
    CONFIG_BLK_CGROUP: Block IO controller: built-in (pass)
  CONFIG_NAMESPACES: Namespaces support: built-in (pass)
    CONFIG_UTS_NS: UTS namespace: built-in (pass)
    CONFIG_IPC_NS: IPC namespace: built-in (pass)
    CONFIG_PID_NS: PID namespace: built-in (pass)
    CONFIG_NET_NS: Network namespace: built-in (pass)
  CONFIG_NET: Networking support: built-in (pass)
    CONFIG_INET: TCP/IP networking: built-in (pass)
      CONFIG_IPV6: The IPv6 protocol: built-in (pass)
    CONFIG_NETFILTER: Network packet filtering framework (Netfilter): built-in (pass)
      CONFIG_NETFILTER_ADVANCED: Advanced netfilter configuration: built-in (pass)
      CONFIG_NF_CONNTRACK: Netfilter connection tracking support: module (pass)
      CONFIG_NETFILTER_XTABLES: Netfilter Xtables support: module (pass)
        CONFIG_NETFILTER_XT_TARGET_REDIRECT: REDIRECT target support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_COMMENT: "comment" match support: module (pass)
        CONFIG_NETFILTER_XT_MARK: nfmark target and match support: module (pass)
        CONFIG_NETFILTER_XT_SET: set target and match support: module (pass)
        CONFIG_NETFILTER_XT_TARGET_MASQUERADE: MASQUERADE target support: module (pass)
        CONFIG_NETFILTER_XT_NAT: "SNAT and DNAT" targets support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_ADDRTYPE: "addrtype" address type match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_CONNTRACK: "conntrack" connection tracking match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_MULTIPORT: "multiport" Multiple port match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_RECENT: "recent" match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_STATISTIC: "statistic" match support: module (pass)
      CONFIG_NETFILTER_NETLINK: module (pass)
      CONFIG_NF_NAT: module (pass)
      CONFIG_IP_SET: IP set support: module (pass)
        CONFIG_IP_SET_HASH_IP: hash:ip set support: module (pass)
        CONFIG_IP_SET_HASH_NET: hash:net set support: module (pass)
      CONFIG_IP_VS: IP virtual server support: module (pass)
        CONFIG_IP_VS_NFCT: Netfilter connection tracking: built-in (pass)
        CONFIG_IP_VS_SH: Source hashing scheduling: module (pass)
        CONFIG_IP_VS_RR: Round-robin scheduling: module (pass)
        CONFIG_IP_VS_WRR: Weighted round-robin scheduling: module (pass)
      CONFIG_NF_CONNTRACK_IPV4: IPv4 connetion tracking support (required for NAT): unknown (warning)
      CONFIG_NF_REJECT_IPV4: IPv4 packet rejection: module (pass)
      CONFIG_NF_NAT_IPV4: IPv4 NAT: unknown (warning)
      CONFIG_IP_NF_IPTABLES: IP tables support: module (pass)
        CONFIG_IP_NF_FILTER: Packet filtering: module (pass)
          CONFIG_IP_NF_TARGET_REJECT: REJECT target support: module (pass)
        CONFIG_IP_NF_NAT: iptables NAT support: module (pass)
        CONFIG_IP_NF_MANGLE: Packet mangling: module (pass)
      CONFIG_NF_DEFRAG_IPV4: module (pass)
      CONFIG_NF_CONNTRACK_IPV6: IPv6 connetion tracking support (required for NAT): unknown (warning)
      CONFIG_NF_NAT_IPV6: IPv6 NAT: unknown (warning)
      CONFIG_IP6_NF_IPTABLES: IP6 tables support: module (pass)
        CONFIG_IP6_NF_FILTER: Packet filtering: module (pass)
        CONFIG_IP6_NF_MANGLE: Packet mangling: module (pass)
        CONFIG_IP6_NF_NAT: ip6tables NAT support: module (pass)
      CONFIG_NF_DEFRAG_IPV6: module (pass)
    CONFIG_BRIDGE: 802.1d Ethernet Bridging: module (pass)
      CONFIG_LLC: module (pass)
      CONFIG_STP: module (pass)
  CONFIG_EXT4_FS: The Extended 4 (ext4) filesystem: built-in (pass)
  CONFIG_PROC_FS: /proc file system support: built-in (pass) ⬅️
</pre>
</details>

### What happened?

Followed step by step guide on a single node k0s from this link https://docs.k0sproject.io/v1.30.2+k0s.0/install/. But when i ran sudo k0s kubectl get nodes, there were no nodes. Which is different result from the document's step 5.

### Steps to reproduce

1. Follow the setup guide from this link https://docs.k0sproject.io/v1.30.2+k0s.0/install/

### Expected behavior

sudo k0s kubectl get nodes command should show at least 1 node as shown in the https://docs.k0sproject.io/v1.30.2+k0s.0/install/

### Actual behavior

$ sudo k0s kubectl get nodes
No resources found

**Comment by twz123** [comment]
I assume you used `sudo k0s install controller --single`, followed by `sudo k0s start`? Can you share the output of `systemctl status k0scontroller.service`?

**Comment by Jaryllan** [comment]
This is the result from systemctl status k0scontroller.service
```
● k0scontroller.service - k0s - Zero Friction Kubernetes
     Loaded: loaded (/etc/systemd/system/k0scontroller.service; enabled; preset: enabled)
     Active: active (running) since Wed 2024-07-17 01:02:34 UTC; 8min ago
       Docs: https://docs.k0sproject.io
   Main PID: 1315 (k0s)
      Tasks: 126
     Memory: 547.6M (peak: 589.7M)
        CPU: 41.997s
     CGroup: /system.slice/k0scontroller.service
             ├─1315 /usr/local/bin/k0s controller --single=true
             ├─1327 /var/lib/k0s/bin/kine "--endpoint=sqlite:/var/lib/k0s/db/state.db?mode=rwc&_journal=WAL&cache=shared" --listen-address=unix:///run/k0s/>
             ├─1337 /var/lib/k0s/bin/kube-apiserver --enable-bootstrap-token-auth=true --client-ca-file=/var/lib/k0s/pki/ca.crt --proxy-client-key-file=/va>
             ├─1421 /var/lib/k0s/bin/kube-scheduler --profiling=false --authentication-kubeconfig=/var/lib/k0s/pki/scheduler.conf --authorization-kubeconfi>
             └─1422 /var/lib/k0s/bin/kube-controller-manager --node-cidr-mask-size=24 --leader-elect=false --bind-address=127.0.0.1 --profiling=false --aut>
```

From checking the logs of the k0scontroller with journalctl, i notice the following repetitive logs. Is this due to the k0scontroller is taking the Automatic Private IP Addressing (APIPA) IP address (169.254.xx.xx) instead of my own configured static IP (eg: 192.168.1.173)?

```
Jul 17 01:04:49 k0s k0s[1315]: time="2024-07-17 01:04:49" level=info msg="E0717 01:04:49.373397    1422 resource_quota_controller.go:440] unable to retrieve the complete list of server APIs: metrics.k8s.io/v1beta1: stale GroupVersion discovery: metrics.k8s.io/v1beta1" component=kube-controller-manager stream=stderr
Jul 17 01:04:49 k0s k0s[1315]: time="2024-07-17 01:04:49" level=info msg="I0717 01:04:49.812824    1422 garbagecollector.go:826] \"failed to discover some groups\" logger=\"garbage-collector-controller\" groups=\"<internal error: json: unsupported type: map[schema.GroupVersion]error>\"" component=kube-controller-manager stream=stderr
Jul 17 01:04:52 k0s k0s[1315]: time="2024-07-17 01:04:52" level=info msg="W0717 01:04:52.385159    1337 lease.go:265] Resetting endpoints for master service \"kubernetes\" to [169.254.141.19]" component=kube-apiserver stream=stderr
Jul 17 01:04:52 k0s k0s[1315]: time="2024-07-17 01:04:52" level=info msg="E0717 01:04:52.386224    1337 controller.go:159] unable to sync kubernetes service: Endpoints \"kubernetes\" is invalid: subsets[0].addresses[0].ip: Invalid value: \"169.254.141.19\": may not be in the link-local range (169.254.0.0/16, fe80::/10)" component=kube-apiserver stream=stderr
Jul 17 01:04:54 k0s k0s[1315]: time="2024-07-17 01:04:54" level=info msg="current cfg matches existing, not gonna do anything" component=coredns
```

**Comment by Jaryllan** [comment]
I did a quick fix on the network, I can confirm the issue was due to the k0scontroller is picking up the APIPA IP address (169.254.xx.xx). Once it is picking up my configured static IP address, the result is as describe in https://docs.k0sproject.io/v1.30.2+k0s.0/install/

**Comment by twz123** [comment]
Maybe k0s could prefer non-link-local addresses over link-local ones when auto-detecting them... :thinking:
