### ISSUE TITLE
Consider the need for node-local dns cache

### ISSUE THREAD

**Issue by jnummelin** [k0sproject/k0s#48]
It was a thing e.g. in Pharos: https://github.com/kontena/pharos-docs/tree/master/networking#node_local_dns_cache-optional-default-true

See also: https://kubernetes.io/docs/tasks/administer-cluster/nodelocaldns/

**Comment by jnummelin** [comment]
Still relevant thing to consider

**Comment by makhov** [comment]
node-cache replacement supporting HA setup
https://github.com/contentful-labs/coredns-nodecache

**Comment by jnummelin** [comment]
Users can deploy this on their own following the guide: https://kubernetes.io/docs/tasks/administer-cluster/nodelocaldns/
