### ISSUE TITLE
Add release docs

### ISSUE THREAD

**Issue by trawler** [k0sproject/k0s#481]
**Is your feature request related to a problem? Please describe.**
The current docs directory relates to the version in `main`. For release docs, users must use the tagged link, and that might not be so obvious.

**Describe the solution you'd like**
We should come up with a solution for releasing release-related docs, and have them updated with each release.

**Describe alternatives you've considered**
I like couscous, since it has GitHub actions integration, that can easily be integrated with our release workflow: https://couscous.io/docs/githubaction.html

**Comment by miskun** [comment]
I'd say we collaborate with people from k8slens project. We have just automated everything in there so getting proper docs site for k0s should be trivial c&p work.
