### ISSUE TITLE
Option To Create Namespace If It doesn't Exist For Helm Charts Installation

### ISSUE THREAD

**Issue by infinitydon** [k0sproject/k0s#4852]
### Is your feature request related to a problem? Please describe.

Using helm command there is an option _**--create-namespace**_, this create NS if it does not exist during installation of an helm chart

### Describe the solution you would like

Add option of something like **_createNamespace: true_** to the Helm extension

### Describe alternatives you've considered

None so far

### Additional context

I could not find reference to this in the k0s, if it exists, kindly let me know

**Comment by emosbaugh** [comment]
I believe --create-namespace is hardcoded to true looking at the code

https://github.com/k0sproject/k0s/blob/5db0100a02e6ece8fd6dbbe40a76a5e44aa49118/pkg/helm/helm.go#L224

I've updated the docs to reflect this

https://github.com/k0sproject/k0s/pull/4893
