### ISSUE TITLE
Disabling control plane isolation?

### ISSUE THREAD

**Issue by rlewkowicz** [k0sproject/k0s#4854]
I followed the ansible docs, but made it so all nodes were controller and worker. Getting the nodes returns nothing although the cluster is up and info does return. 

I think this is the control plane isolation? I would like my masters to show up in kubectl anyway. Is there an install flag to disable this?

**Comment by jnummelin** [comment]
When you run the controller, you can pass --enable-worker flag so the controller also starts kubelet etc
