### ISSUE TITLE
Failed to start on freshly installed Fedora33

### ISSUE THREAD

**Issue by kstych** [k0sproject/k0s#488]
hi,

tried following
1. Fresh Fedora 33 system (4 core/16gb/1TB)

2. followed https://github.com/k0sproject/k0s/blob/main/docs/k0s-single-node.md
for 0.7.0 / 0.8.0 and 0.8.1-rc1

kubectl keeps saying pending for all pods even after 48 minutes

in the logs i keep seeing 

WARN[2020-12-03 10:18:51] exit status 255                               component=kubelet
...
...
INFO[2020-12-03 10:18:51] respawning in 5 secs                          component=kubelet

**Comment by jnummelin** [comment]
Check the logs before kubelet crashing, hopefully has some info why it's crashing. k0s tries to keep it running by respawning it, but clearly there's something in the env why it cannot run.

Just tested on fresh Fedora 33:
```
[root@fedora-4gb-hel1-1 ~]# cat /etc/os-release 
NAME=Fedora
VERSION="33 (Thirty Three)"
ID=fedora
VERSION_ID=33
VERSION_CODENAME=""
PLATFORM_ID="platform:f33"
PRETTY_NAME="Fedora 33 (Thirty Three)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:33"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f33/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=33
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=33
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
[root@fedora-4gb-hel1-1 ~]# kubectl get node,pod -A
NAME                     STATUS   ROLES    AGE     VERSION
node/fedora-4gb-hel1-1   Ready    <none>   3m50s   v1.19.4

NAMESPACE     NAME                                           READY   STATUS    RESTARTS   AGE
kube-system   pod/calico-kube-controllers-5f6546844f-8l5pp   1/1     Running   0          3m49s
kube-system   pod/calico-node-rm5zg                          1/1     Running   0          3m49s
kube-system   pod/coredns-5c98d7d4d8-k2855                   1/1     Running   0          3m56s
kube-system   pod/konnectivity-agent-pt4xl                   1/1     Running   0          3m30s
kube-system   pod/kube-proxy-htv8p                           1/1     Running   0          3m50s
```

**Comment by kstych** [comment]
@jnummelin hi, thankyou for the reply, i am attaching the logs since the command is run until first kublet 255 status, please see if you can point me to a fix
[k0s.zip](https://github.com/k0sproject/k0s/files/5635578/k0s.zip)

**Comment by jnummelin** [comment]
```
time="2020-12-03 10:47:27" level=info msg="F1203 10:47:27.842409   11008 kubelet.go:1296] Failed to start ContainerManager failed to get rootfs info: failed to get device for dir \"/var/lib/k0s/kubelet\": could not find device with major: 0, minor: 36 in cached partitions map" component=kubelet

```

After that kubelet goes tumbling down.

**Comment by kstych** [comment]
hi, so re-installed fedora 33 with single ext4 root partition (earlier was default btrfs), now it is different error 
(also changed --data-dir to /root/k0s_data)
[k0s.txt](https://github.com/k0sproject/k0s/files/5635896/k0s.txt)

![k0s](https://user-images.githubusercontent.com/4062349/101015300-38878b00-358d-11eb-9996-64cb565bda01.png)

**Comment by trawler** [comment]
> hi, so re-installed fedora 33 with single ext4 root partition (earlier was default btrfs), now it is different error
> (also changed --data-dir to /root/k0s_data)
> [k0s.txt](https://github.com/k0sproject/k0s/files/5635896/k0s.txt)
> 
> ![k0s](https://user-images.githubusercontent.com/4062349/101015300-38878b00-358d-11eb-9996-64cb565bda01.png)

yes, the latest logs show kubelet started successfully, but that calico-node is having a problem:
```
time="2020-12-03 12:01:39" level=info msg="I1203 12:01:39.385963    7221 kubelet.go:1898] SyncLoop (container unhealthy): \"calico-node-4kpm2_kube-system(b8fc828e-d79c-4f62-b5fd-1e28661caa75)\"" component=kubelet
time="2020-12-03 12:01:39" level=info msg="I1203 12:01:39.387055    7221 topology_manager.go:219] [topologymanager] RemoveContainer - Container ID: ff512929983cb059f5f54ca13bc4e40182f259c69ba971069869ca35b70900f1" component=kubelet
time="2020-12-03 12:01:39" level=info msg="E1203 12:01:39.388912    7221 pod_workers.go:191] Error syncing pod b8fc828e-d79c-4f62-b5fd-1e28661caa75 (\"calico-node-4kpm2_kube-system(b8fc828e-d79c-4f62-b5fd-1e28661caa75)\"), skipping: failed to \"StartContainer\" for \"calico-node\" with 
```

Can you check the pod's description + logs?
```
kubectl -n kube-system logs calico-node-4kpm2
kubectl -n tube-system describe pod calico-node-4kpm2
```

**Comment by kstych** [comment]
hi 
log command fails with 
--
Error from server: Get "https://192.168.1.2:10250/containerLogs/kube-system/calico-node-494dd/calico-node": dial timeout
--

describe pod shows
--
Name:                 calico-node-494dd
Namespace:            kube-system
Priority:             2000001000
Priority Class Name:  system-node-critical
Node:                 k8s.kstych.com/192.168.1.2
Start Time:           Thu, 03 Dec 2020 13:17:10 +0000
Labels:               controller-revision-hash=7478c9ff74
                      k8s-app=calico-node
                      pod-template-generation=1
Annotations:          <none>
Status:               Running
IP:                   192.168.1.2
IPs:
  IP:           192.168.1.2
Controlled By:  DaemonSet/calico-node
Init Containers:
  upgrade-ipam:
    Container ID:  containerd://54538b89b34d836c87b6b37dac3c1266e242455d244fc3af1d8daf4d598583d3
    Image:         calico/cni:v3.16.2
    Image ID:      docker.io/calico/cni@sha256:546aadd2363d93785e65dc6580036ec831824361fc909d5d00d82b60325fcc7d
    Port:          <none>
    Host Port:     <none>
    Command:
      /opt/cni/bin/calico-ipam
      -upgrade
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Thu, 03 Dec 2020 13:18:00 +0000
      Finished:     Thu, 03 Dec 2020 13:18:00 +0000
    Ready:          True
    Restart Count:  0
    Environment Variables from:
      kubernetes-services-endpoint  ConfigMap  Optional: true
    Environment:
      KUBERNETES_NODE_NAME:        (v1:spec.nodeName)
      CALICO_NETWORKING_BACKEND:  <set to the key 'calico_backend' of config map 'calico-config'>  Optional: false
    Mounts:
      /host/opt/cni/bin from cni-bin-dir (rw)
      /var/lib/cni/networks from host-local-net-dir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from calico-node-token-gm4b7 (ro)
  install-cni:
    Container ID:  containerd://690c19d81e898096d72eb4d85c57a39c84998c4af70db3a2ce4a4231def3d191
    Image:         calico/cni:v3.16.2
    Image ID:      docker.io/calico/cni@sha256:546aadd2363d93785e65dc6580036ec831824361fc909d5d00d82b60325fcc7d
    Port:          <none>
    Host Port:     <none>
    Command:
      /opt/cni/bin/install
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Thu, 03 Dec 2020 13:18:01 +0000
      Finished:     Thu, 03 Dec 2020 13:18:05 +0000
    Ready:          True
    Restart Count:  0
    Environment Variables from:
      kubernetes-services-endpoint  ConfigMap  Optional: true
    Environment:
      CNI_CONF_NAME:         10-calico.conflist
      CNI_NETWORK_CONFIG:    <set to the key 'cni_network_config' of config map 'calico-config'>  Optional: false
      KUBERNETES_NODE_NAME:   (v1:spec.nodeName)
      CNI_MTU:               <set to the key 'veth_mtu' of config map 'calico-config'>  Optional: false
      SLEEP:                 false
    Mounts:
      /host/etc/cni/net.d from cni-net-dir (rw)
      /host/opt/cni/bin from cni-bin-dir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from calico-node-token-gm4b7 (ro)
  flexvol-driver:
    Container ID:   containerd://074b9f757e7c272de5e190304270c05615121082cdc250db36aac896dc95441f
    Image:          calico/pod2daemon-flexvol:v3.16.2
    Image ID:       docker.io/calico/pod2daemon-flexvol@sha256:ad11e9e902da6d1be7fb4bb90cfb3e155347825fa742ab20a35f68a419aef3d5
    Port:           <none>
    Host Port:      <none>
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Thu, 03 Dec 2020 13:18:18 +0000
      Finished:     Thu, 03 Dec 2020 13:18:18 +0000
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /host/driver from flexvol-driver-host (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from calico-node-token-gm4b7 (ro)
Containers:
  calico-node:
    Container ID:   containerd://0929325d0f416a95b4bf87daa7000494224d7fb047fdaddc60c440f8c295924f
    Image:          calico/node:v3.16.2
    Image ID:       docker.io/calico/node@sha256:b86447952e70a96cb9c778589469de816e6a3ac6ccd9ddf0fe07fe10fe4a89d3
    Port:           <none>
    Host Port:      <none>
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Thu, 03 Dec 2020 13:21:31 +0000
      Finished:     Thu, 03 Dec 2020 13:21:31 +0000
    Ready:          False
    Restart Count:  5
    Requests:
      cpu:      250m
    Liveness:   exec [/bin/calico-node -felix-live] delay=10s timeout=1s period=10s #success=1 #failure=6
    Readiness:  exec [/bin/calico-node -felix-ready] delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment Variables from:
      kubernetes-services-endpoint  ConfigMap  Optional: true
    Environment:
      DATASTORE_TYPE:                     kubernetes
      WAIT_FOR_DATASTORE:                 true
      NODENAME:                            (v1:spec.nodeName)
      CALICO_NETWORKING_BACKEND:          <set to the key 'calico_backend' of config map 'calico-config'>  Optional: false
      CLUSTER_TYPE:                       k8s
      IP:                                 autodetect
      CALICO_IPV4POOL_IPIP:               Never
      CALICO_IPV4POOL_VXLAN:              Always
      FELIX_VXLANPORT:                    4789
      FELIX_VXLANVNI:                     4096
      FELIX_IPINIPMTU:                    <set to the key 'veth_mtu' of config map 'calico-config'>  Optional: false
      FELIX_VXLANMTU:                     <set to the key 'veth_mtu' of config map 'calico-config'>  Optional: false
      FELIX_WIREGUARDMTU:                 <set to the key 'veth_mtu' of config map 'calico-config'>  Optional: false
      CALICO_IPV4POOL_CIDR:               10.244.0.0/16
      CALICO_DISABLE_FILE_LOGGING:        true
      FELIX_DEFAULTENDPOINTTOHOSTACTION:  ACCEPT
      FELIX_IPV6SUPPORT:                  false
      FELIX_LOGSEVERITYSCREEN:            info
      FELIX_HEALTHENABLED:                true
    Mounts:
      /lib/modules from lib-modules (ro)
      /run/xtables.lock from xtables-lock (rw)
      /var/lib/calico from var-lib-calico (rw)
      /var/run/calico from var-run-calico (rw)
      /var/run/nodeagent from policysync (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from calico-node-token-gm4b7 (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  lib-modules:
    Type:          HostPath (bare host directory volume)
    Path:          /lib/modules
    HostPathType:  
  var-run-calico:
    Type:          HostPath (bare host directory volume)
    Path:          /var/run/calico
    HostPathType:  
  var-lib-calico:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/calico
    HostPathType:  
  xtables-lock:
    Type:          HostPath (bare host directory volume)
    Path:          /run/xtables.lock
    HostPathType:  FileOrCreate
  cni-bin-dir:
    Type:          HostPath (bare host directory volume)
    Path:          /opt/cni/bin
    HostPathType:  
  cni-net-dir:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/cni/net.d
    HostPathType:  
  host-local-net-dir:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/cni/networks
    HostPathType:  
  policysync:
    Type:          HostPath (bare host directory volume)
    Path:          /var/run/nodeagent
    HostPathType:  DirectoryOrCreate
  flexvol-driver-host:
    Type:          HostPath (bare host directory volume)
    Path:          /usr/libexec/kubernetes/kubelet-plugins/volume/exec/nodeagent~uds
    HostPathType:  DirectoryOrCreate
  calico-node-token-gm4b7:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  calico-node-token-gm4b7
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  kubernetes.io/os=linux
Tolerations:     :NoScheduleop=Exists
                 :NoExecuteop=Exists
                 CriticalAddonsOnly op=Exists
                 node.kubernetes.io/disk-pressure:NoSchedule op=Exists
                 node.kubernetes.io/memory-pressure:NoSchedule op=Exists
                 node.kubernetes.io/network-unavailable:NoSchedule op=Exists
                 node.kubernetes.io/not-ready:NoExecute op=Exists
                 node.kubernetes.io/pid-pressure:NoSchedule op=Exists
                 node.kubernetes.io/unreachable:NoExecute op=Exists
                 node.kubernetes.io/unschedulable:NoSchedule op=Exists
Events:
  Type     Reason     Age                From               Message
  ----     ------     ----               ----               -------
  Normal   Scheduled  14m                default-scheduler  Successfully assigned kube-system/calico-node-494dd to k8s.kstych.com
  Normal   Pulling    14m                kubelet            Pulling image "calico/cni:v3.16.2"
  Normal   Pulled     13m                kubelet            Successfully pulled image "calico/cni:v3.16.2" in 29.632721325s
  Normal   Created    13m                kubelet            Created container upgrade-ipam
  Normal   Started    13m                kubelet            Started container upgrade-ipam
  Normal   Pulled     13m                kubelet            Container image "calico/cni:v3.16.2" already present on machine
  Normal   Created    13m                kubelet            Created container install-cni
  Normal   Started    13m                kubelet            Started container install-cni
  Normal   Pulling    13m                kubelet            Pulling image "calico/pod2daemon-flexvol:v3.16.2"
  Normal   Started    13m                kubelet            Started container flexvol-driver
  Normal   Created    13m                kubelet            Created container flexvol-driver
  Normal   Pulled     13m                kubelet            Successfully pulled image "calico/pod2daemon-flexvol:v3.16.2" in 12.13093019s
  Normal   Pulling    13m                kubelet            Pulling image "calico/node:v3.16.2"
  Normal   Pulled     12m                kubelet            Successfully pulled image "calico/node:v3.16.2" in 20.11457009s
  Normal   Pulled     12m (x2 over 12m)  kubelet            Container image "calico/node:v3.16.2" already present on machine
  Normal   Created    12m (x3 over 12m)  kubelet            Created container calico-node
  Normal   Started    12m (x3 over 12m)  kubelet            Started container calico-node
  Warning  BackOff    12m (x4 over 12m)  kubelet            Back-off restarting failed container

--

**Comment by trawler** [comment]
Unfortunately the "describe" command does not immediately show any clear issue. I imagine this should be found in the calico-node logs themselves, but the fact that you are unable to reach the logs implies that you have something filtering traffic inside your fedora OS. Perhaps firewalld, iptables, or otherwise...

**Comment by kstych** [comment]
hi, firewalld is disabled, iptables not loaded.
will try other things

**Comment by jnummelin** [comment]
The `kubectl logs ...` failing is a result of the konnectivity agent not booting up on the node. And that's because calico does not get up so the node does not get into fully ready state. (basically scheduling is still disabled for that node)

On the node directly, you should see calico logs with something like:
```
less /var/log/pods/kube-system_calico-node-plsng_5eef5253-9612-489c-bc8c-33c55cfe059d/calico-node/0.log
```

(the pod/container id's will be different of course.)

Maybe there's a hint why it fails to start.

**Comment by kstych** [comment]
`2020-12-03T11:14:26.673852127-05:00 stdout F 2020-12-03 16:14:26.673 [INFO][9] startup/startup.go 361: Early log level set to info
2020-12-03T11:14:26.67388076-05:00 stdout F 2020-12-03 16:14:26.673 [INFO][9] startup/startup.go 377: Using NODENAME environment for node name
2020-12-03T11:14:26.673885643-05:00 stdout F 2020-12-03 16:14:26.673 [INFO][9] startup/startup.go 389: Determined node name: localhost.localdomain
2020-12-03T11:14:26.674839959-05:00 stdout F 2020-12-03 16:14:26.674 [INFO][9] startup/startup.go 421: Checking datastore connection
2020-12-03T11:14:26.68191561-05:00 stdout F 2020-12-03 16:14:26.681 [INFO][9] startup/startup.go 445: Datastore connection verified
2020-12-03T11:14:26.681931771-05:00 stdout F 2020-12-03 16:14:26.681 [INFO][9] startup/startup.go 109: Datastore is ready
2020-12-03T11:14:26.684398313-05:00 stdout F 2020-12-03 16:14:26.684 [INFO][9] startup/customresource.go 101: Error getting resource Key=GlobalFelixConfig(name=CalicoVersion) Name="calicoversion" Resource="GlobalFelixConfigs" error=the server could not find the requested resource (get GlobalFelixConfigs.crd.projectcalico.org calicoversion)
2020-12-03T11:14:26.689832034-05:00 stdout F 2020-12-03 16:14:26.689 [INFO][9] startup/startup.go 487: Initialize BGP data
2020-12-03T11:14:26.690096697-05:00 stdout F 2020-12-03 16:14:26.690 [WARNING][9] startup/startup.go 742: Unable to auto-detect an IPv4 address: no valid IPv4 addresses found on the host interfaces
2020-12-03T11:14:26.690124109-05:00 stdout F 2020-12-03 16:14:26.690 [WARNING][9] startup/startup.go 509: Couldn't autodetect an IPv4 address. If auto-detecting, choose a different autodetection method. Otherwise provide an explicit address.
2020-12-03T11:14:26.690182037-05:00 stdout F 2020-12-03 16:14:26.690 [INFO][9] startup/startup.go 325: Clearing out-of-date IPv4 address from this node IP=""
2020-12-03T11:14:26.696651524-05:00 stdout F 2020-12-03 16:14:26.696 [WARNING][9] startup/startup.go 1310: Terminating
2020-12-03T11:14:26.69825547-05:00 stderr F Calico node failed to start`

**Comment by kstych** [comment]
this fixes the issue and starts everything

kubectl set env daemonset/calico-node -n kube-system IP_AUTODETECTION_METHOD=interface=wlo.*

**Comment by trawler** [comment]
hmmm, I noticed your network interface is called `wlo1` and it seems the issue was reported before:
https://github.com/projectcalico/calico/issues/3094#issuecomment-571626097

In short, it means that calico excludes any interface with the `lo` string, since they assume it's a localhost interface - https://github.com/projectcalico/node/blob/master/pkg/startup/startup_linux.go#L29-L32

@jnummelin can you confirm that in your working fedora33 host, the interface has a different name?

**Comment by trawler** [comment]
related to #479
