### ISSUE TITLE
Add ability to configure external IP for worker

### ISSUE THREAD

**Issue by unixfox** [k0sproject/k0s#492]
**Is your feature request related to a problem? Please describe.**
I would like to use metrics-server in a cluster where the workers aren't in the same internal network and this require to use workers external IP.

**Describe the solution you'd like**
I would like to be able to set the external IP of the workers with a command line parameter just like it's possible on k3s with `--node-external-ip`: https://rancher.com/docs/k3s/latest/en/installation/install-options/agent-config/

For both IPv4 and IPv6.

**Describe alternatives you've considered**
Set the external IP manually by editing the node properties using kubectl after adding the node.

**Additional context**
N/A

**Comment by jnummelin** [comment]
This requires we implement a cloud controller of sorts in k0s so it picks up the address from labels (or somewhere else) and pushes it to the node addresses.

It's definitely something I've had bubbling in my head, good that we got an issue to track this with. :)

**Comment by unixfox** [comment]
I just updated the original comment because now that dual stack https://github.com/k0sproject/k0s/issues/394 got merged I would really like to see the ability to set both IPv4 and IPv6 external IP addresses.

**Comment by mmack** [comment]
I have a similar problem:

I want to install k0s on a bunch of nodes that are connected via wireguard. They have firewall rules so that only wireguard traffic is able to reach the nodes on their public ip's. I can add only internal ip's to the k0s server config, still the nodes are publishing their own external ip in k8s as the "Internal-IP".

**Comment by jnummelin** [comment]
@mmack I'm not sure this is the same problem. Your case sounds bit more as "kubelet is reporting _wrong_ IP as the internal address". This would be solvable by enabling k0s worker to set `--node-ip` flag on kubelet process, that'll "override" the address it defaults to reporting.

**Comment by unixfox** [comment]
> @mmack I'm not sure this is the same problem. Your case sounds bit more as "kubelet is reporting _wrong_ IP as the internal address". This would be solvable by enabling k0s worker to set `--node-ip` flag on kubelet process, that'll "override" the address it defaults to reporting.

that would still be a good start towards exposing the external IP if the nodes are connected using their external IP.

**Comment by mmack** [comment]
> @mmack I'm not sure this is the same problem. Your case sounds bit more as "kubelet is reporting _wrong_ IP as the internal address". This would be solvable by enabling k0s worker to set `--node-ip` flag on kubelet process, that'll "override" the address it defaults to reporting.

@jnummelin: As far as i read the docs, i can set that node-ip on the server config as a worker profile, correct? So the problem is that then i need to set a profile for each node, b/c the ip is obviously different per worker.. 
Any other idea? `k0s worker --node-ip X` does not work either...

**Comment by jnummelin** [comment]
There seems to be slight confusion what is mean by "external-ip" :) When kubelet reports it's own IP, whether autodetected or given by `--node-ip`, it's set as "internal-ip" in the nodes api object. External-ip field is only to be set by "cloud controllers" which we currently do not have specific to k0s.

> k0s worker --node-ip X does not work either...

Yes, does not work as we do not have that flag on k0s worker. Yet. 

I think we need to come up with some generic way to pass ANY additional flags to kubelet, some thing like `k0s worker --extra-kubelet-args="--node-ip=1.2.3.4 --foo=bar"`. If I understood the requests made in this issue, having the ability to set the `--node-ip` would be sufficient. Right?

**Comment by unixfox** [comment]
> I think we need to come up with some generic way to pass ANY additional flags to kubelet, some thing like `k0s worker --extra-kubelet-args="--node-ip=1.2.3.4 --foo=bar"`. If I understood the requests made in this issue, having the ability to set the `--node-ip` would be sufficient. Right?
> 
Unfortunately no, this feature request is about ExternalIP not InternalIP. ExternalIP is useful for exposing the real external IP when the server is in a private subnet like on Google cloud or AWS.
This ExternalIP can be used with ExternalDNS for example.

I'll make another issue for `--node-ip`.

**Comment by jnummelin** [comment]
> ExternalIP is useful for exposing the real external IP when the server is in a private subnet like on Google cloud or AWS.

In those cases you'd get the "External-IP" properly populated if you deploy the cloud controller for the cloud you are using.
See more at https://docs.k0sproject.io/v0.10.0/cloud-providers/

**Comment by unixfox** [comment]
> > ExternalIP is useful for exposing the real external IP when the server is in a private subnet like on Google cloud or AWS.
> 
> In those cases you'd get the "External-IP" properly populated if you deploy the cloud controller for the cloud you are using.
> See more at [docs.k0sproject.io/v0.10.0/cloud-providers](https://docs.k0sproject.io/v0.10.0/cloud-providers/)

Google cloud don't have a working CCM for the public yet but those clouds were just an example. Sometimes you just want to have an ExternalIP and that's it. No real need of having the extra features of the official CCM (AWS, Azure and so on).

This is also useful for setting the ExternalIP on a bare metal kubernetes cluster where there is no cloud controller manager existing as of today.

**Comment by jnummelin** [comment]
> This is also useful for setting the ExternalIP on a bare metal kubernetes cluster where there is no cloud controller manager existing as of today.

Oh yes, there's definitely use cases for this sort of functionality. My brain just got too hang on the AWS/GCP part :D
