### ISSUE TITLE
Automatic certificate rotation

### ISSUE THREAD

**Issue by vroad** [k0sproject/k0s#496]
**Is your feature request related to a problem? Please describe.**
Does k0s support rotating certificates without downtime?

**Describe the solution you'd like**
k0s automatically checks for certificate expiration, renew certificates, and restart controllers one by one.

**Describe alternatives you've considered**
Using other tools that can rotate certificates.
Does kucero work out of box on k0s?

https://github.com/SUSE/kucero

**Additional context**
Can I rotate etcd certificates as well? 

I'm not sure if k0s supports running etcd in separate node groups. How is etcd certificate rotation handled in that case?

Using TLS bootstrap will help in rotating at least for kubelet certificates, but you can't use cloud-provider=external with that, at least for now.

https://kubernetes.io/docs/tasks/administer-cluster/running-cloud-controller/#chicken-and-egg

**Comment by jnummelin** [comment]
> Does k0s support rotating certificates without downtime?

Currently no. For kubelet we should enable the normal cert rotation feature. For controllers the story is more complicated. 😄 

Currently when ever k0s controller process starts it ensures all certs are in place. If you delete the relevant certs it will re-create them when starting. Of course you should not delete the CA nor the SA keys. :) This of course means restarting the controllers but if you have an LB in front it should not matter that much.

> Does kucero work out of box on k0s?

Haven't tried but highly doubt it will work. It seems to expect to be running as a daemonset on master nodes which we do not have in k0s. We'd need to embed the "raw" kucero on controllers as a normal process.


> I'm not sure if k0s supports running etcd in separate node groups.

Currently k0s does not support external etcd. If that's something you'd wish to see maybe create separate issue for it. Should not be too difficult to make happen.

> How is etcd certificate rotation handled in that case?

In case of external etcd the cert rotation should be IMO handled by something external to k0s. In this case the etcd CA is not "owned" by k0s and thus k0s cannot create new client certs for it.
