### ISSUE TITLE
rc-update error when executing k0s stop in Docker container

### ISSUE THREAD

**Issue by data-dude** [k0sproject/k0s#4966]
### Before creating an issue, make sure you've checked the following:

- [X] You are running the latest released version of k0s
- [X] Make sure you've searched for existing issues, both open and closed
- [X] Make sure you've searched for PRs too, a fix might've been merged already
- [X] You're looking at docs for the released version, "main" branch docs are usually ahead of released versions.

### Platform

```shell
cat /etc/redhat-release 
Rocky Linux release 9.4 (Blue Onyx)
```

### Version

docker.io/k0sproject/k0s:v1.30.4-k0s.0

### Sysinfo

```
Total memory: 7.4 GiB (pass)
Disk space available for /var/lib/k0s: 97.7 GiB (pass)
Name resolution: localhost: [::1 127.0.0.1] (pass)
Operating system: Linux (pass)
  Linux kernel release: 5.14.0-427.33.1.el9_4.x86_64 (pass)
  Max. file descriptors per process: current: 1073741816 / max: 1073741816 (pass)
  AppArmor: unavailable (pass)
  Executable in PATH: modprobe: /sbin/modprobe (pass)
  Executable in PATH: mount: /bin/mount (pass)
  Executable in PATH: umount: /bin/umount (pass)
  /proc file system: mounted (0x9fa0) (pass)
  Control Groups: version 2 (pass)
    cgroup controller "cpu": available (is a listed root controller) (pass)
    cgroup controller "cpuacct": available (via cpu in version 2) (pass)
    cgroup controller "cpuset": available (is a listed root controller) (pass)
    cgroup controller "memory": available (is a listed root controller) (pass)
    cgroup controller "devices": available (device filters attachable) (pass)
    cgroup controller "freezer": available (cgroup.freeze exists) (pass)
    cgroup controller "pids": available (is a listed root controller) (pass)
    cgroup controller "hugetlb": available (is a listed root controller) (pass)
    cgroup controller "blkio": available (via io in version 2) (pass)
  CONFIG_CGROUPS: Control Group support: no kernel config found (warning)
  CONFIG_NAMESPACES: Namespaces support: no kernel config found (warning)
  CONFIG_NET: Networking support: no kernel config found (warning)
  CONFIG_EXT4_FS: The Extended 4 (ext4) filesystem: no kernel config found (warning)
  CONFIG_PROC_FS: /proc file system support: no kernel config found (warning)
```

### What happened?

k0s stop give the error:  Error: "rc-service" failed: exec: "rc-service": executable file not found in $PATH

### Steps to reproduce

1. docker run -d --name k0s --hostname k0s --privileged -p 6443:6443 docker.io/k0sproject/k0s:v1.30.4-k0s.0
2. / # k0s status
Version: v1.30.4+k0s.0
Process ID: 7
Role: controller
Workloads: true
SingleNode: false
Kube-api probing successful: true
Kube-api probing last error:  

3. / # k0s stop
Error: "rc-service" failed: exec: "rc-service": executable file not found in $PATH

### Expected behavior

no error

**Comment by jnummelin** [comment]
There's two reasons why this happens.

1. There's no rc-service in the image.

2. k0s is NOT installed as openRC service in the image.

I think the main question is, should `k0s stop` command have some "fallback" to stop/kill the running k0s process?

**Comment by data-dude** [comment]
> There's two reasons why this happens.
> 
>     1. There's no rc-service in the image.
> 
>     2. k0s is NOT installed as openRC service in the image.
> 
> 
> I think the main question is, should `k0s stop` command have some "fallback" to stop/kill the running k0s process?

I'm running the basic docker image on dockherhub:
docker.io/k0sproject/k0s:v1.30.4-k0s.0

I would think it should have the necessary pieces to work

**Comment by jnummelin** [comment]
Why do you need/want to run `k0s stop` in the first place? The image is built so that it _should_ gracefully stop k0s and everything else when you stop the container itself.

**Comment by data-dude** [comment]
> Why do you need/want to run `k0s stop` in the first place? The image is built so that it _should_ gracefully stop k0s and everything else when you stop the container itself.

When I tried running k0s controller -c <my new configuration>   it wouldn't take the change.  And I thought I read you need to stop k0s and start it and then run 'k0s controller -c <my configuration>.

**Comment by jnummelin** [comment]
For configuration, you have two options:

Mount the config file from local source, something like:

```
docker run -d --name k0s --hostname k0s --privileged -v /var/lib/k0s -v /path/to/k0s.yaml:/etc/k0s.yaml -p 6443:6443 --cgroupns=host docker.io/k0sproject/k0s:v1.30.4-k0s.0 -- k0s controller --enable-worker --config /etc/k0s.yaml
```
When you change the config, just restart the container.

Use env variables, something like (in terms of compose):
```
version: "3.9"
services:
  k0s:
    container_name: k0s
    image: docker.io/k0sproject/k0s:v1.30.4-k0s.0
    command: k0s controller --config=/etc/k0s/config.yaml --enable-worker
    hostname: k0s
    privileged: true
    cgroup: host
    volumes:
      - "/var/lib/k0s"
    ports:
      - "6443:6443"
    network_mode: "bridge"
    environment:
      K0S_CONFIG: |-
        apiVersion: k0s.k0sproject.io/v1beta1
        kind: ClusterConfig
        metadata:
          name: k0s
        # Any additional configuration goes here ...
```

The downside of env way is that to change it you need to re-create the container. but that's not a problem as `/var/lib/k0s` is defined as a volume

**Comment by kke** [comment]
It should be rather simple to detect if k0s is running as a child pid of one of the init systems.

**Comment by data-dude** [comment]
When i change the config I need to restart the container

**Comment by data-dude** [comment]
When i change the config I need to restart the container
