### ISSUE TITLE
Docs interpolation generates vNone+k0s.0

### ISSUE THREAD

**Issue by kke** [k0sproject/k0s#4969]
Googling "k0s install" took me to https://docs.k0sproject.io/v1.27.2+k0s.0/k0s-multi-node/

There I see things like:

```shell
curl -sSLf https://get.k0s.sh | sudo K0S_VERSION=vNone+k0s.0 sh
```

![image](https://github.com/user-attachments/assets/1aa49807-c2c3-4b39-80e4-897800817337)

These come from `v{{{ extra.k8s_version }}}+k0s.0` in the markdown template.

**Comment by twz123** [comment]
The docs of versions v1.27.1+k0s.0 up to v1.27.6+k0s.0 are affected. Supposedly connected to #3594. I think I forgot to expose the required environment variable to mike/mkdocs in the rebuild script.

**Comment by twz123** [comment]
I think its fixed.
