### ISSUE TITLE
Add support for ppc64le architecture

### ISSUE THREAD

**Issue by rpsene** [k0sproject/k0s#503]
This is an exploratory feature request. As a ppc64le user, I would be able to run k0s on this platform either on premises or on cloud and would like to understand if the community is open to accept contributions targeting that architecture. 

If so, what would be key parts to concern about multi-arch support?

p.s: I'm just starting looking at the code.

**Comment by ncopa** [comment]
> If so, what would be key parts to concern about multi-arch support?

That the upstream container images like calico and similar supports multi-arch. For example, calico does not support 32 bit arches. However, IIRC they do support ppc64le, so I think ppc64le should be doable.

**Comment by jnummelin** [comment]
>  would like to understand if the community is open to accept contributions targeting that architecture.

Definitely we'd be happy to see contributions on this area.

> If so, what would be key parts to concern about multi-arch support?

As @ncopa pointed out, the key is to see all the mandatory system-level images have proper multiarch support for ppc. Compiling all the kube bins and k0s itself should not be a big issue as long as there's a ppc to run the build on.

If we want to make it as far as providing a ready made bin bundle for ppc we'd probably need a Github actions runner for it so we can bake the release on it.

**Comment by rpsene** [comment]
@ncopa @jnummelin thanks for the initial feedback. 

ppc64le is not 32bit and calico is supported on Power (https://hub.docker.com/r/calico/cni/tags?page=1&ordering=last_updated).  We can provide some ppc64le resources for free (https://openpower.ic.unicamp.br/minicloud/) and although the native support for ppc64le at GH Actions is not something that will happen soon (we need to handle the .net porting or wait them to migrate the Runner to GO), we will need to think about a workaround (for instance, Travis supports Power).

I will dig into the source code and ask more questions

**Comment by jnummelin** [comment]
@rpsene Have you had a chance to look at ppc support?

**Comment by rpsene** [comment]
@jnummelin this is in my TODO list, but behind some items at this moment. I hope to touch it during the 2Q 2021.

**Comment by ALutz273** [comment]
is there any news?

**Comment by mtarsel** [comment]
Hi all, @rpsene is no longer focused on this work and unicamp is no longer available. I will check in with our team this week to see if we should continue with this ppc64le support. Instead of Unicamp we can use Oregon State University's Open Source Lab (OSU OSL). More info about public ppc64le resources here: https://osuosl.org/

**Comment by mtarsel** [comment]
I'm not sure there is a strong use case to use k0s on ppc64le at this time. Power architecture is not generally limited by resources like memory or processing. I think this can stay closed but thanks for bringing it to my attention.
