### ISSUE TITLE
Allow providing extra args to kube-proxy

### ISSUE THREAD

**Issue by byDimasik** [k0sproject/k0s#5032]
### Is your feature request related to a problem? Please describe.

MKE 3 allows users to specify additional flags for kube-proxy. In MKE 4, we need to provide the same functionality for backward compatibility reasons. Since MKE 4 is based on k0s, this functionality should be supported by k0s in order for us to utilize it.

### Describe the solution you would like

k0s already allows additional flags to be provided to the API server, scheduler, and controller manager using the `extraArgs` field, but kube-proxy doesn't have it. It would be great if kube-proxy also had this setting.

**Comment by juanluisvaladas** [comment]
@byDimasik This will be included in 1.31.1. Do you need it backported?

**Comment by byDimasik** [comment]
> @byDimasik This will be included in 1.31.1. Do you need it backported?

We do not need it backported. Thank you for your quick action!
