### ISSUE TITLE
Investigate graceful shutdown in kubernetes 1.20

### ISSUE THREAD

**Issue by ncopa** [k0sproject/k0s#509]
Investigate if the graceful shutdown feature in kuberentes 1.20 is something we want enable by default.

https://kubernetes.io/blog/2020/12/08/kubernetes-1-20-release-announcement/#alpha-graceful-node-shutdown

**Comment by tanvp112** [comment]
how do we know which k8s component --feature-gate needs to add GracefulNodeShutdown=true?

command line tools reference of kube-apiserver, kube-proxy, kube-controller-manager, kube-scheduler all have referenced to this feature; does that mean we append GracefulNodeShutdown=true to ALL of these component --feature-gate?

**Comment by ncopa** [comment]
Graceful shutdown is enabled by default since kubernetes 1.21. https://kubernetes.io/blog/2021/04/21/graceful-node-shutdown-beta/
I think we stick to upstream kuberentes' defaults.
