### ISSUE TITLE
Cleanup a worker node

### ISSUE THREAD

**Issue by lucj** [k0sproject/k0s#512]
**Is your feature request related to a problem? Please describe.**
I'm doing some testing with k0s adding a worker node and I'd like to re-initialize the node quite often

**Describe the solution you'd like**
I'd love to have an option that allows to delete the folders / files generated on the worker node, something like ```k0s clear``` :)

**Describe alternatives you've considered**
Manual removal of /var/lib/k0s, /var/lib/kubelet, ... (not sure all the things that need to be removed)

**Comment by matti** [comment]
#519

**Comment by trawler** [comment]
also, same as #278
Closing for duplicity.
