### ISSUE TITLE
Use staged containerd

### ISSUE THREAD

**Issue by soider** [k0sproject/k0s#514]
Now we only support external container runtime on windows
To have same experience with linux, it’s nice to have staged containerd.

Right now we rely on the docker EE duding the k0s install because we need to build pause container so the issue is blocked at the moment by #513

**Comment by jnummelin** [comment]
Moving ahead in milestones as we're "blocked" on upstream on this

**Comment by soider** [comment]
@jnummelin are there any links for the discussion\issue in the upstream repo/slack to follow up?

**Comment by jnummelin** [comment]
The WIP PR has upstream links:  https://github.com/k0sproject/k0s/pull/654

**Comment by jnummelin** [comment]
There's still no upstream fix for calico/containerd so this is still a no-go 😞
