### ISSUE TITLE
worker hangs on reboot for approx 90s

### ISSUE THREAD

**Issue by matti** [k0sproject/k0s#524]
```
...systemd-shutdown[1]: Waiting for process: containerd
```

possibly related to #523 

and also in k3s: https://github.com/k3s-io/k3s/issues/2400

**Comment by jasmingacic** [comment]
Marking this as P1 bug as it is related to #523 which should be fixed.

**Comment by jasmingacic** [comment]
This issue has been resolved with #523 and other fixes
