### ISSUE TITLE
CoreDNS doen't work on new install

### ISSUE THREAD

**Issue by fabltd** [k0sproject/k0s#5310]
### Before creating an issue, make sure you've checked the following:

- [x] You are running the latest released version of k0s
- [x] Make sure you've searched for existing issues, both open and closed
- [x] Make sure you've searched for PRs too, a fix might've been merged already
- [x] You're looking at docs for the released version, "main" branch docs are usually ahead of released versions.

### Platform

```shell
K0s installed on:

Linux 6.8.0-49-generic #49-Ubuntu SMP PREEMPT_DYNAMIC Mon Nov  4 02:06:24 UTC 2024 x86_64 GNU/Linux
PRETTY_NAME="Ubuntu 24.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04.1 LTS (Noble Numbat)"
VERSION_CODENAME=noble
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=noble
LOGO=ubuntu-logo
```

### Version

v1.31.2+k0s.0

### Sysinfo

<details><summary>`k0s sysinfo`</summary>
<pre>
Total memory: 3.8 GiB (pass)
File system of /var/lib/k0s: ext4 (pass)
Disk space available for /var/lib/k0s: 20.7 GiB (pass)
Relative disk space available for /var/lib/k0s: 68% (pass)
Name resolution: localhost: [127.0.0.1] (pass)
Operating system: Linux (pass)
  Linux kernel release: 6.8.0-49-generic (pass)
  Max. file descriptors per process: current: 1048576 / max: 1048576 (pass)
  AppArmor: active (pass)
  Executable in PATH: modprobe: /usr/sbin/modprobe (pass)
  Executable in PATH: mount: /usr/bin/mount (pass)
  Executable in PATH: umount: /usr/bin/umount (pass)
  /proc file system: mounted (0x9fa0) (pass)
  Control Groups: version 2 (pass)
    cgroup controller "cpu": available (is a listed root controller) (pass)
    cgroup controller "cpuacct": available (via cpu in version 2) (pass)
    cgroup controller "cpuset": available (is a listed root controller) (pass)
    cgroup controller "memory": available (is a listed root controller) (pass)
    cgroup controller "devices": available (device filters attachable) (pass)
    cgroup controller "freezer": available (cgroup.freeze exists) (pass)
    cgroup controller "pids": available (is a listed root controller) (pass)
    cgroup controller "hugetlb": available (is a listed root controller) (pass)
    cgroup controller "blkio": available (via io in version 2) (pass)
  CONFIG_CGROUPS: Control Group support: built-in (pass)
    CONFIG_CGROUP_FREEZER: Freezer cgroup subsystem: built-in (pass)
    CONFIG_CGROUP_PIDS: PIDs cgroup subsystem: built-in (pass)
    CONFIG_CGROUP_DEVICE: Device controller for cgroups: built-in (pass)
    CONFIG_CPUSETS: Cpuset support: built-in (pass)
    CONFIG_CGROUP_CPUACCT: Simple CPU accounting cgroup subsystem: built-in (pass)
    CONFIG_MEMCG: Memory Resource Controller for Control Groups: built-in (pass)
    CONFIG_CGROUP_HUGETLB: HugeTLB Resource Controller for Control Groups: built-in (pass)
    CONFIG_CGROUP_SCHED: Group CPU scheduler: built-in (pass)
      CONFIG_FAIR_GROUP_SCHED: Group scheduling for SCHED_OTHER: built-in (pass)
        CONFIG_CFS_BANDWIDTH: CPU bandwidth provisioning for FAIR_GROUP_SCHED: built-in (pass)
    CONFIG_BLK_CGROUP: Block IO controller: built-in (pass)
  CONFIG_NAMESPACES: Namespaces support: built-in (pass)
    CONFIG_UTS_NS: UTS namespace: built-in (pass)
    CONFIG_IPC_NS: IPC namespace: built-in (pass)
    CONFIG_PID_NS: PID namespace: built-in (pass)
    CONFIG_NET_NS: Network namespace: built-in (pass)
  CONFIG_NET: Networking support: built-in (pass)
    CONFIG_INET: TCP/IP networking: built-in (pass)
      CONFIG_IPV6: The IPv6 protocol: built-in (pass)
    CONFIG_NETFILTER: Network packet filtering framework (Netfilter): built-in (pass)
      CONFIG_NETFILTER_ADVANCED: Advanced netfilter configuration: built-in (pass)
      CONFIG_NF_CONNTRACK: Netfilter connection tracking support: module (pass)
      CONFIG_NETFILTER_XTABLES: Netfilter Xtables support: module (pass)
        CONFIG_NETFILTER_XT_TARGET_REDIRECT: REDIRECT target support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_COMMENT: "comment" match support: module (pass)
        CONFIG_NETFILTER_XT_MARK: nfmark target and match support: module (pass)
        CONFIG_NETFILTER_XT_SET: set target and match support: module (pass)
        CONFIG_NETFILTER_XT_TARGET_MASQUERADE: MASQUERADE target support: module (pass)
        CONFIG_NETFILTER_XT_NAT: "SNAT and DNAT" targets support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_ADDRTYPE: "addrtype" address type match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_CONNTRACK: "conntrack" connection tracking match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_MULTIPORT: "multiport" Multiple port match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_RECENT: "recent" match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_STATISTIC: "statistic" match support: module (pass)
      CONFIG_NETFILTER_NETLINK: module (pass)
      CONFIG_NF_NAT: module (pass)
      CONFIG_IP_SET: IP set support: module (pass)
        CONFIG_IP_SET_HASH_IP: hash:ip set support: module (pass)
        CONFIG_IP_SET_HASH_NET: hash:net set support: module (pass)
      CONFIG_IP_VS: IP virtual server support: module (pass)
        CONFIG_IP_VS_NFCT: Netfilter connection tracking: built-in (pass)
        CONFIG_IP_VS_SH: Source hashing scheduling: module (pass)
        CONFIG_IP_VS_RR: Round-robin scheduling: module (pass)
        CONFIG_IP_VS_WRR: Weighted round-robin scheduling: module (pass)
      CONFIG_NF_CONNTRACK_IPV4: IPv4 connetion tracking support (required for NAT): unknown (warning)
      CONFIG_NF_REJECT_IPV4: IPv4 packet rejection: module (pass)
      CONFIG_NF_NAT_IPV4: IPv4 NAT: unknown (warning)
      CONFIG_IP_NF_IPTABLES: IP tables support: module (pass)
        CONFIG_IP_NF_FILTER: Packet filtering: module (pass)
          CONFIG_IP_NF_TARGET_REJECT: REJECT target support: module (pass)
        CONFIG_IP_NF_NAT: iptables NAT support: module (pass)
        CONFIG_IP_NF_MANGLE: Packet mangling: module (pass)
      CONFIG_NF_DEFRAG_IPV4: module (pass)
      CONFIG_NF_CONNTRACK_IPV6: IPv6 connetion tracking support (required for NAT): unknown (warning)
      CONFIG_NF_NAT_IPV6: IPv6 NAT: unknown (warning)
      CONFIG_IP6_NF_IPTABLES: IP6 tables support: module (pass)
        CONFIG_IP6_NF_FILTER: Packet filtering: module (pass)
        CONFIG_IP6_NF_MANGLE: Packet mangling: module (pass)
        CONFIG_IP6_NF_NAT: ip6tables NAT support: module (pass)
      CONFIG_NF_DEFRAG_IPV6: module (pass)
    CONFIG_BRIDGE: 802.1d Ethernet Bridging: module (pass)
      CONFIG_LLC: module (pass)
      CONFIG_STP: module (pass)
  CONFIG_EXT4_FS: The Extended 4 (ext4) filesystem: built-in (pass)
  CONFIG_PROC_FS: /proc file system support: built-in (pass)
</pre>
</details>

### What happened?

Core DNS does not work.

There are errors in the log. 

Nothing else is installed on this instance and its running in single mode

```
sudo k0s kubectl logs --namespace=kube-system -l k8s-app=kube-dns
[ERROR] plugin/errors: 2 7276122262170126455.3587526809832313128. HINFO: read udp 10.244.0.5:39267->192.168.102.1:53: i/o timeout
[ERROR] plugin/errors: 2 7276122262170126455.3587526809832313128. HINFO: read udp 10.244.0.5:48169->192.168.102.1:53: i/o timeout
[ERROR] plugin/errors: 2 7276122262170126455.3587526809832313128. HINFO: read udp 10.244.0.5:58995->192.168.102.1:53: i/o timeout
[ERROR] plugin/errors: 2 7276122262170126455.3587526809832313128. HINFO: read udp 10.244.0.5:44506->192.168.102.1:53: i/o timeout
[ERROR] plugin/errors: 2 7276122262170126455.3587526809832313128. HINFO: read udp 10.244.0.5:45598->192.168.102.1:53: i/o timeout
[ERROR] plugin/errors: 2 7276122262170126455.3587526809832313128. HINFO: read udp 10.244.0.5:33898->192.168.102.1:53: i/o timeout
[ERROR] plugin/errors: 2 7276122262170126455.3587526809832313128. HINFO: read udp 10.244.0.5:59554->192.168.102.1:53: i/o timeout
[ERROR] plugin/errors: 2 7276122262170126455.3587526809832313128. HINFO: read udp 10.244.0.5:51943->192.168.102.1:53: i/o timeout
[ERROR] plugin/errors: 2 7276122262170126455.3587526809832313128. HINFO: read udp 10.244.0.5:41380->192.168.102.1:53: i/o timeout
[ERROR] plugin/errors: 2 7276122262170126455.3587526809832313128. HINFO: read udp 10.244.0.5:53889->192.168.102.1:53: i/o timeout
```

### Steps to reproduce

Install fresh Ubuntu 24 machine. Install K0s. Test Core DNS

### Expected behavior

DNS should be operating.

### Actual behavior

Dns Fails

**Comment by twz123** [comment]
Can you be a bit more specific about how you installed k0s, and about your setup? Maybe some unusual network settings? I can't repro this using the [Quick Start Guide](https://docs.k0sproject.io/v1.31.2+k0s.0/install/#install-k0s) on an Ubuntu VM.

Did the following:

```sh
curl --proto '=https' --tlsv1.2 -sSf https://get.k0s.sh | sudo sh
sudo k0s install controller --single
sudo systemctl daemon-reload
sudo k0s start
```

and after a short while:

```console
$ sudo k0s kc get po -A
NAMESPACE     NAME                              READY   STATUS    RESTARTS   AGE
kube-system   coredns-c698ff8d6-wzpd6           1/1     Running   0          74s
kube-system   kube-proxy-9w9j9                  1/1     Running   0          72s
kube-system   kube-router-cs88q                 1/1     Running   0          72s
kube-system   metrics-server-78c4ccbc7f-dn4rb   1/1     Running   0          71s

$ sudo k0s kc -n kube-system logs coredns-c698ff8d6-wzpd6
.:53
[INFO] plugin/reload: Running configuration SHA512 = a0c06adb3aa41fc5baa9a525a356d4f8e0206ad810f6a0d1f005e63150f4cd85bb682bac617e725b3996ba493aee5bd94a076b3ff9c64726e7e00a033b2ab1ba
CoreDNS-1.11.3
linux/amd64, go1.22.2, a7ed346585e30b99317d36e4d007b7b19a228ea5

$ cat /etc/os-release
PRETTY_NAME="Ubuntu 24.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04.1 LTS (Noble Numbat)"
VERSION_CODENAME=noble
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=noble
LOGO=ubuntu-logo

$ uname -srvmo
Linux 6.8.0-49-generic #49-Ubuntu SMP PREEMPT_DYNAMIC Mon Nov  4 02:06:24 UTC 2024 x86_64 GNU/Linux
```

**Comment by isofinly** [comment]
Can confirm this issue.

```bash
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 24.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04.1 LTS (Noble Numbat)"
VERSION_CODENAME=noble
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=noble
LOGO=ubuntu-logo

$ sudo k0s install controller --single
$ sudo systemctl daemon-reload
$ sudo k0s start
$ sudo k0s kc get po -A
NAMESPACE     NAME                              READY   STATUS    RESTARTS   AGE
kube-system   coredns-c698ff8d6-k7c95           1/1     Running   0          42s
kube-system   kube-proxy-rhzf7                  1/1     Running   0          42s
kube-system   kube-router-5z8xn                 1/1     Running   0          42s
kube-system   metrics-server-78c4ccbc7f-47jz4   1/1     Running   0          37s

$ sudo k0s kc -n kube-system logs coredns-c698ff8d6-k7c95
.:53
[INFO] plugin/reload: Running configuration SHA512 = a0c06adb3aa41fc5baa9a525a356d4f8e0206ad810f6a0d1f005e63150f4cd85bb682bac617e725b3996ba493aee5bd94a076b3ff9c64726e7e00a033b2ab1ba
CoreDNS-1.11.3
linux/amd64, go1.22.2, a7ed346585e30b99317d36e4d007b7b19a228ea5
[ERROR] plugin/errors: 2 4360184873661664209.7828395894742686024. HINFO: read udp 10.244.0.172:50903->185.12.64.2:53: i/o timeout
[ERROR] plugin/errors: 2 4360184873661664209.7828395894742686024. HINFO: dial udp [2a01:4ff:ff00::add:1]:53: connect: network is unreachable
[ERROR] plugin/errors: 2 4360184873661664209.7828395894742686024. HINFO: dial udp [2a01:4ff:ff00::add:2]:53: connect: network is unreachable
[ERROR] plugin/errors: 2 4360184873661664209.7828395894742686024. HINFO: read udp 10.244.0.172:38206->185.12.64.2:53: i/o timeout

```

On my other VPS with the exact ubuntu version I get this:

```
$ sudo k0s kc -n kube-system logs coredns-c698ff8d6-786qf
.:53
[INFO] plugin/reload: Running configuration SHA512 = a0c06adb3aa41fc5baa9a525a356d4f8e0206ad810f6a0d1f005e63150f4cd85bb682bac617e725b3996ba493aee5bd94a076b3ff9c64726e7e00a033b2ab1ba
CoreDNS-1.11.3
linux/amd64, go1.22.2, a7ed346585e30b99317d36e4d007b7b19a228ea5
[ERROR] plugin/errors: 2 3151363470300593482.5431996333082820910. HINFO: read udp 10.244.0.3:49733->1.1.1.1:53: i/o timeout
[ERROR] plugin/errors: 2 3151363470300593482.5431996333082820910. HINFO: read udp 10.244.0.3:58474->1.1.1.1:53: i/o timeout
[ERROR] plugin/errors: 2 3151363470300593482.5431996333082820910. HINFO: read udp 10.244.0.3:36935->1.1.1.1:53: i/o timeout
[ERROR] plugin/errors: 2 3151363470300593482.5431996333082820910. HINFO: read udp 10.244.0.3:38392->1.1.1.1:53: i/o timeout
[ERROR] plugin/errors: 2 3151363470300593482.5431996333082820910. HINFO: read udp 10.244.0.3:53621->1.1.1.1:53: i/o timeout
[ERROR] plugin/errors: 2 3151363470300593482.5431996333082820910. HINFO: read udp 10.244.0.3:47369->1.1.1.1:53: i/o timeout
[ERROR] plugin/errors: 2 3151363470300593482.5431996333082820910. HINFO: read udp 10.244.0.3:60468->8.8.8.8:53: i/o timeout
[ERROR] plugin/errors: 2 3151363470300593482.5431996333082820910. HINFO: read udp 10.244.0.3:60315->8.8.8.8:53: i/o timeout
[ERROR] plugin/errors: 2 3151363470300593482.5431996333082820910. HINFO: read udp 10.244.0.3:45376->8.8.8.8:53: i/o timeout
[ERROR] plugin/errors: 2 3151363470300593482.5431996333082820910. HINFO: read udp 10.244.0.3:58080->1.1.1.1:53: i/o timeout
```

No firewall or other network filtering is enabled. 

The odd details is that if I create a traefik as load balancer deployment, it works and can route traffic to my pods, but pods cannot communicate with the web.

**Comment by jnummelin** [comment]
This might be connected to https://github.com/k0sproject/k0s/issues/5328

Would be interesting to see if the same workarounds, i.e. overriding the kube-router image would provide any help.

**Comment by soljarka** [comment]
Having the same problem with the same k0s version, using the same installation method.
I installed kubernetes-dashboard and I'm seeing similar coredns errors when trying to access it. Unlike in #5328, the kube-router is running normally.

**Comment by twz123** [comment]
The new v1.31.3+k0s.0 ships the fixed kube-router image by default now. Please ping here if the problem persists.

**Comment by Mwhite84** [comment]
This has been closed but fwiw, I'm still seeing the same behavior with the latest v1.31.3+k0s.0 image on Ubuntu 24.04.
