### ISSUE TITLE
kube-proxy: iptables / iptable_filter

### ISSUE THREAD

**Issue by mtds** [k0sproject/k0s#5336]
### Before creating an issue, make sure you've checked the following:

- [x] You are running the latest released version of k0s
- [x] Make sure you've searched for existing issues, both open and closed
- [x] Make sure you've searched for PRs too, a fix might've been merged already
- [x] You're looking at docs for the released version, "main" branch docs are usually ahead of released versions.

### Platform

```shell
Linux 5.14.0-503.15.1.el9_5.x86_64 #1 SMP PREEMPT_DYNAMIC Tue Nov 26 17:24:29 UTC 2024 x86_64 GNU/Linux
NAME="Rocky Linux"
VERSION="9.5 (Blue Onyx)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="9.5"
PLATFORM_ID="platform:el9"
PRETTY_NAME="Rocky Linux 9.5 (Blue Onyx)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:9::baseos"
HOME_URL="https://rockylinux.org/"
VENDOR_NAME="RESF"
VENDOR_URL="https://resf.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
SUPPORT_END="2032-05-31"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-9"
ROCKY_SUPPORT_PRODUCT_VERSION="9.5"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.5"
```

### Version

v1.31.2+k0s.0

### Sysinfo

<details><summary>`k0s sysinfo`</summary>
<pre>
Total memory: 45.5 GiB (pass)
File system of /var/lib/k0s: xfs (pass)
Disk space available for /var/lib/k0s: 94.0 GiB (pass)
Relative disk space available for /var/lib/k0s: 96% (pass)
Name resolution: localhost: [127.0.0.1 ::1] (pass)
Operating system: Linux (pass)
  Linux kernel release: 5.14.0-503.15.1.el9_5.x86_64 (pass)
  Max. file descriptors per process: current: 524288 / max: 524288 (pass)
  AppArmor: unavailable (pass)
  Executable in PATH: modprobe: /usr/sbin/modprobe (pass)
  Executable in PATH: mount: /usr/bin/mount (pass)
  Executable in PATH: umount: /usr/bin/umount (pass)
  /proc file system: mounted (0x9fa0) (pass)
  Control Groups: version 2 (pass)
    cgroup controller "cpu": available (is a listed root controller) (pass)
    cgroup controller "cpuacct": available (via cpu in version 2) (pass)
    cgroup controller "cpuset": available (is a listed root controller) (pass)
    cgroup controller "memory": available (is a listed root controller) (pass)
    cgroup controller "devices": available (device filters attachable) (pass)
    cgroup controller "freezer": available (cgroup.freeze exists) (pass)
    cgroup controller "pids": available (is a listed root controller) (pass)
    cgroup controller "hugetlb": available (is a listed root controller) (pass)
    cgroup controller "blkio": available (via io in version 2) (pass)
  CONFIG_CGROUPS: Control Group support: built-in (pass)
    CONFIG_CGROUP_FREEZER: Freezer cgroup subsystem: built-in (pass)
    CONFIG_CGROUP_PIDS: PIDs cgroup subsystem: built-in (pass)
    CONFIG_CGROUP_DEVICE: Device controller for cgroups: built-in (pass)
    CONFIG_CPUSETS: Cpuset support: built-in (pass)
    CONFIG_CGROUP_CPUACCT: Simple CPU accounting cgroup subsystem: built-in (pass)
    CONFIG_MEMCG: Memory Resource Controller for Control Groups: built-in (pass)
    CONFIG_CGROUP_HUGETLB: HugeTLB Resource Controller for Control Groups: built-in (pass)
    CONFIG_CGROUP_SCHED: Group CPU scheduler: built-in (pass)
      CONFIG_FAIR_GROUP_SCHED: Group scheduling for SCHED_OTHER: built-in (pass)
        CONFIG_CFS_BANDWIDTH: CPU bandwidth provisioning for FAIR_GROUP_SCHED: built-in (pass)
    CONFIG_BLK_CGROUP: Block IO controller: built-in (pass)
  CONFIG_NAMESPACES: Namespaces support: built-in (pass)
    CONFIG_UTS_NS: UTS namespace: built-in (pass)
    CONFIG_IPC_NS: IPC namespace: built-in (pass)
    CONFIG_PID_NS: PID namespace: built-in (pass)
    CONFIG_NET_NS: Network namespace: built-in (pass)
  CONFIG_NET: Networking support: built-in (pass)
    CONFIG_INET: TCP/IP networking: built-in (pass)
      CONFIG_IPV6: The IPv6 protocol: built-in (pass)
    CONFIG_NETFILTER: Network packet filtering framework (Netfilter): built-in (pass)
      CONFIG_NETFILTER_ADVANCED: Advanced netfilter configuration: built-in (pass)
      CONFIG_NF_CONNTRACK: Netfilter connection tracking support: module (pass)
      CONFIG_NETFILTER_XTABLES: Netfilter Xtables support: built-in (pass)
        CONFIG_NETFILTER_XT_TARGET_REDIRECT: REDIRECT target support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_COMMENT: "comment" match support: module (pass)
        CONFIG_NETFILTER_XT_MARK: nfmark target and match support: module (pass)
        CONFIG_NETFILTER_XT_SET: set target and match support: module (pass)
        CONFIG_NETFILTER_XT_TARGET_MASQUERADE: MASQUERADE target support: module (pass)
        CONFIG_NETFILTER_XT_NAT: "SNAT and DNAT" targets support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_ADDRTYPE: "addrtype" address type match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_CONNTRACK: "conntrack" connection tracking match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_MULTIPORT: "multiport" Multiple port match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_RECENT: "recent" match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_STATISTIC: "statistic" match support: module (pass)
      CONFIG_NETFILTER_NETLINK: module (pass)
      CONFIG_NF_NAT: module (pass)
      CONFIG_IP_SET: IP set support: module (pass)
        CONFIG_IP_SET_HASH_IP: hash:ip set support: module (pass)
        CONFIG_IP_SET_HASH_NET: hash:net set support: module (pass)
      CONFIG_IP_VS: IP virtual server support: module (pass)
        CONFIG_IP_VS_NFCT: Netfilter connection tracking: built-in (pass)
        CONFIG_IP_VS_SH: Source hashing scheduling: module (pass)
        CONFIG_IP_VS_RR: Round-robin scheduling: module (pass)
        CONFIG_IP_VS_WRR: Weighted round-robin scheduling: module (pass)
      CONFIG_NF_CONNTRACK_IPV4: IPv4 connetion tracking support (required for NAT): unknown (warning)
      CONFIG_NF_REJECT_IPV4: IPv4 packet rejection: module (pass)
      CONFIG_NF_NAT_IPV4: IPv4 NAT: unknown (warning)
      CONFIG_IP_NF_IPTABLES: IP tables support: module (pass)
        CONFIG_IP_NF_FILTER: Packet filtering: module (pass)
          CONFIG_IP_NF_TARGET_REJECT: REJECT target support: module (pass)
        CONFIG_IP_NF_NAT: iptables NAT support: module (pass)
        CONFIG_IP_NF_MANGLE: Packet mangling: module (pass)
      CONFIG_NF_DEFRAG_IPV4: module (pass)
      CONFIG_NF_CONNTRACK_IPV6: IPv6 connetion tracking support (required for NAT): unknown (warning)
      CONFIG_NF_NAT_IPV6: IPv6 NAT: unknown (warning)
      CONFIG_IP6_NF_IPTABLES: IP6 tables support: module (pass)
        CONFIG_IP6_NF_FILTER: Packet filtering: module (pass)
        CONFIG_IP6_NF_MANGLE: Packet mangling: module (pass)
        CONFIG_IP6_NF_NAT: ip6tables NAT support: module (pass)
      CONFIG_NF_DEFRAG_IPV6: module (pass)
    CONFIG_BRIDGE: 802.1d Ethernet Bridging: module (pass)
      CONFIG_LLC: module (pass)
      CONFIG_STP: module (pass)
  CONFIG_EXT4_FS: The Extended 4 (ext4) filesystem: module (pass)
  CONFIG_PROC_FS: /proc file system support: built-in (pass)
</pre>
</details>

### What happened?

* Installing `k0s` on a RHEL 9 box with `iptables` (with a loaded `iptable_filter`) prevents `kube-proxy` to create the relevant chains.
* More info the `Additional context` section.

### Expected behavior

* `kube-proxy` should be able to create by default when `iptable_filter` is loaded.

### Actual behavior

* No chains or table were created or altered.

### Additional context

We are currently testing `k0s` on a single controller installation and I believe we have stumbled upon a potential bug, although
maybe it's triggered by our current choice of the Linux platform (Rocky Linux 9.5, derivative of RHEL 9).

A little bit of context/history: the very first time that I ran `k0s install controller --single`, I did get the base pods running **but**
`kube-router` was constantly crashing:
```
~]# k0s kubectl get pods -A
NAMESPACE     NAME                              READY   STATUS             RESTARTS          AGE
kube-system   coredns-c698ff8d6-wbdpw           1/1     Running            0                 29m
kube-system   kube-proxy-4mrnx                  1/1     Running            0                 29m
kube-system   kube-router-bc7cm                 0/1     CrashLoopBackOff   5 (4m46s ago)     29m
kube-system   metrics-server-78c4ccbc7f-hdzpn   1/1     Running            0                 29m
```
Looking into the logs of `kube-router` was sufficient to identify the problem:
```
(...)
E1205 18:42:11.148929  102899 network_routes_controller.go:184] Failed to enable IP forwarding of traffic from pods: failed to run
iptables command: running [/sbin/iptables -t filter -C FORWARD -m comment --comment allow outbound traffic from pods -i kube-bridge -j ACCEPT --wait]:
exit status 3: iptables v1.8.9 (legacy): can't initialize iptables table `filter': Table does not exist (do you need to insmod?)
```
The `iptable_filter` module was indeed not loaded by default. As soon as I manually loaded the module via `modprobe`, the `kube-router`
came online and I was able to further test the installation (e.g. deploy NGINX-Ingress or OpenEBS).

The issue: for various reason, I decided to restart from scratch with a blank state. So, my first `k0s` installation was wiped off
following the procedure (`k0s stop && k0s reset`). The machine was also rebooted. So far, so good.

This time, I made sure that upon reboot the `iptable_filter` module would be loaded beforehand. Performing again the single controller
installation via `k0s` worked without issues **but** no `iptables` chains were created, all the tables were **completely empty**.

This was kinda puzzling, since the logs for `kube-proxy` (which should be in charge for this part via an `iptables` wrapper script) 
did not report any warning or error message but of course the entire networking between pods was not functioning at all and `kubectl`
was also not able to access properly the controller plane.

I wiped off the `k0s` installation, **unload** the `iptable_filter` module and then install again `k0s` a single controller instance.
This time all the `iptables` chains were created, although `kube-router` was complaining as before until I have reloaded `iptable_filter`
again.

My question: it seems to me that `kube-proxy` do not interact well with `iptables`. Is there a way to use `nftables` by default instead?
I have read the relevant part of the documentation (https://docs.k0sproject.io/stable/networking/?h=nftables#iptables) but it does not
seem that there's an option to force using it.

```
~$ ls -l /var/lib/k0s/bin/
total 417892
(...)
lrwxrwxrwx. 1 root root       17 Dec  9 14:34 ip6tables -> xtables-nft-multi
lrwxrwxrwx. 1 root root       17 Dec  9 14:34 ip6tables-restore -> xtables-nft-multi
lrwxrwxrwx. 1 root root       17 Dec  9 14:34 ip6tables-save -> xtables-nft-multi
lrwxrwxrwx. 1 root root       17 Dec  9 14:34 iptables -> xtables-nft-multi
lrwxrwxrwx. 1 root root       17 Dec  9 14:34 iptables-restore -> xtables-nft-multi
lrwxrwxrwx. 1 root root       17 Dec  9 14:34 iptables-save -> xtables-nft-multi
(...)
-r-xr-x---. 1 root root   497392 Dec  4 13:38 xtables-legacy-multi
-r-xr-x---. 1 root root   727056 Dec  4 13:38 xtables-nft-multi
```

`nftables` is installed by default on our Rocky Linux box but the service is inactive:
```
~$ dnf list installed | grep nftables
nftables.x86_64                                1:1.0.9-3.el9
python3-nftables.x86_64                        1:1.0.9-3.el9
```
Would it be sufficient to turn on the `nftables` service **before** installing `k0s` and manage to avoid this quirky interaction with `iptables`?

**Comment by jnummelin** [comment]
> Would it be sufficient to turn on the nftables service before installing k0s and manage to avoid this quirky interaction with iptables?

Sounds like so, yes. You can turn on the `nftables` mode in kube-proxy within the k0s config, something like:
```yaml
spec:
  network:
    kubeProxy:
      mode: nftables
```
See more at https://docs.k0sproject.io/stable/configuration/#specnetworkkubeproxy

This also sounds a bit like it might be the same issue as in https://github.com/k0sproject/k0s/issues/5328

The linked issue has some workarounds which might be worth trying out.

**Comment by twz123** [comment]
The new v1.31.3+k0s.0 ships the fixed kube-router image by default now. Please ping here if the problem persists.
