### ISSUE TITLE
Inconsistent `k0s etcd member-list` and `kubectl get EtcdMember`

### ISSUE THREAD

**Issue by pschichtel** [k0sproject/k0s#5369]
### Before creating an issue, make sure you've checked the following:

- [x] You are running the latest released version of k0s
- [x] Make sure you've searched for existing issues, both open and closed
- [x] Make sure you've searched for PRs too, a fix might've been merged already
- [x] You're looking at docs for the released version, "main" branch docs are usually ahead of released versions.

### Platform

```shell

```

### Version

v1.31.3+k0s

### What happened?

There was a small mess-up around hostnames a while back. I temporarily changed hostnames of the controller nodes of an existing cluster, which kubernetes didn't quite like, so I reverted the change. Everything recovered and has been working fine for months by now.

I've just checked things before the latest upgrade and noticed that `kubectl get EtcdMember` looks like this (values have been changed, but are consistent):

```
$ kubectl get EtcdMember
NAME             PEER ADDRESS   MEMBER ID          JOINED   RECONCILE STATUS
c1               10.0.0.1       c1id               True     
c1.example.org   10.0.0.1       c1id               True     
c2.example.org   10.0.0.2       c2id               True     
c3.example.org   10.0.0.3       c3id               True  
```

When I run `k0s etcd member-list` on one of the controller I get this:

```
$ k0s etcd member-list | jq
{
  "members": {
    "c1.example.org": "https://10.0.0.1:2380",
    "c2.example.org": "https://10.0.0.2:2380",
    "c3.example.org": "https://10.0.0.3:2380"
  }
}
```

So the member-list command reports 3 members as expected (5 node cluster, 3 controllers, 2 workers), but there is an extra EtcdMember resource for the c1 node with the wrong hostname, but the same peer address and member ids.

Since I'm not entirely sure what the consequences of just deleting the EtcdMember resource I'd like to run this by you first. What would be a safe way to correct this?

### Steps to reproduce

1. Setup a cluster while the node's `hostname` wrongly returns fqdns instead of hostnames and `hostname -f` wrongly returns hostnames instead of fqdns
2. Fix the hostname configuration such that `hostname` returns the hostname and `hostname -f` returns the fqdn
3. Restart one if your controller nodes, which will fail to come up due to some hostname mismatch (I don't quite remember the details, but I think kubelet failed to register at the api server due to a conflicting registration with a different hostname)
4. Revert the hostname fix
5. Restart the broken node again, it will now come up
6. Check `kubectl get EtcdMember`

### Expected behavior

My expectation was, that k0s would eventually self repair this itself, by comparing its state to etcd's state.

### Actual behavior

An inconsistent EtcdMember list is presented.

**Comment by pschichtel** [comment]
If I interpret https://github.com/k0sproject/k0s/blob/c84a0ea733e28991b55dc64fe6b1d0f83eec1153/pkg/component/controller/etcd_member_reconciler.go#L263 and https://github.com/k0sproject/k0s/blob/c84a0ea733e28991b55dc64fe6b1d0f83eec1153/pkg/component/controller/etcd_member_reconciler.go#L297-L304 correctly, I should be able to just set `leave` to true and then the reconciler will mark it accordingly and then I can just delete the resource, right? Or can I just skip that whole dance and delete the resource?

**Comment by juanluisvaladas** [comment]
Hi @pschichtel,
It should be safe to just delete the incorrect EtcdMember object with `kubectl delete etcdmember c1`.

We need to make sure we remove stale objects automatically, but. in the meantime just do a manual cleanup. This is related to https://github.com/k0sproject/k0s/issues/5161

**Comment by pschichtel** [comment]
yep, that worked as far as I can tell, no unexpected side-effects.
