### ISSUE TITLE
Pod creation failure: stat /var/lib/calico/nodename: no such file or directory

### ISSUE THREAD

**Issue by ChenQi1989** [k0sproject/k0s#539]
**Version**
v0.8.1

**Platform**
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic

**What happened?**
After starting up server using `k0s server' and joined a worker with `k0s worker "xxxx"', the cluster still cannot be setup.

$ kubectl get node
NAME            STATUS   ROLES    AGE   VERSION
pek-qchen1-d2   Ready    <none>   45h   v1.19.4

$ kubectl get pod -A
NAMESPACE     NAME                                       READY   STATUS              RESTARTS   AGE
kube-system   calico-kube-controllers-5f6546844f-zdsj4   0/1     ContainerCreating   0          46h
kube-system   calico-node-4922r                          1/1     Running             0          45h
kube-system   coredns-5c98d7d4d8-q9pl9                   0/1     ContainerCreating   0          46h
kube-system   konnectivity-agent-zsn4c                   0/1     ContainerCreating   0          3h22m
kube-system   kube-proxy-65rp8                           1/1     Running             0          45h

$ kubectl describe -n kube-system pod konnectivity-agent-zsn4c
<snip>
  Warning  FailedCreatePodSandBox  57m                   kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "15a9b57961c1c705881a68692954170fd283d1403d81c18c7e36f486b9321bba": stat /var/lib/calico/nodename: no such file or directory: check that the calico/node container is running and has mounted /var/lib/calico/
  Warning  FailedCreatePodSandBox  56m                   kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "171be3ed9416aef07ac82925c0abb0ce04255149359d50997ece695b0e13638a": stat /var/lib/calico/nodename: no such file or directory: check that the calico/node container is running and has mounted /var/lib/calico/
  Warning  FailedCreatePodSandBox  55m                   kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "1fc171f9f9611e3262b211638025427d91c1069ecf84ac810fb4fb0c304478bb": error getting ClusterInformation: Get "https://[10.96.0.1]:443/apis/crd.projectcalico.org/v1/clusterinformations/default": cannotconnect
  Warning  FailedCreatePodSandBox  54m                   kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "998913d755db097b4e800ca7078b42bf826823e6dda579cca90829ba16fa79a0": error getting ClusterInformation: Get "https://[10.96.0.1]:443/apis/crd.projectcalico.org/v1/clusterinformations/default": cannotconnect
  Warning  FailedCreatePodSandBox  2m36s (x36 over 52m)  kubelet            (combined from similar events): Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "92c44a1caedda97e0ad73dd8296c9d65ae87fa53c1fab41fccacc5b6b9235618": error getting ClusterInformation: Get "https://[10.96.0.1]:443/apis/crd.projectcalico.org/v1/clusterinformations/default": cannotconnect
<snip>

**How To Reproduce**
Server side:
k0s server
k0s token create --role=worker

Worker side:
k0s worker 'the long token'

**Expected behavior**
All pods are running.

**Additional context**
On the worker computer,  the following info printed again and again.
INFO[2020-12-17 13:50:34] E1217 13:50:34.849518   25640 kuberuntime_sandbox.go:69] CreatePodSandbox for pod "coredns-5c98d7d4d8-q9pl9_kube-system(e6d8ff82-ca5a-48cb-8a9b-e00249527e3e)" failed: rpc error: code = Unknown desc = failed to setup network for sandbox "711719d2b3c05589909e7ada8cf86b16d99a8c6074299cdb75ec0862e92e4e7b": error getting ClusterInformation: Get "https://[10.96.0.1]:443/apis/crd.projectcalico.org/v1/clusterinformations/default": cannotconnect  component=kubelet
INFO[2020-12-17 13:50:34] E1217 13:50:34.849531   25640 kuberuntime_manager.go:741] createPodSandbox for pod "coredns-5c98d7d4d8-q9pl9_kube-system(e6d8ff82-ca5a-48cb-8a9b-e00249527e3e)" failed: rpc error: code = Unknown desc = failed to setup network for sandbox "711719d2b3c05589909e7ada8cf86b16d99a8c6074299cdb75ec0862e92e4e7b": error getting ClusterInformation: Get "https://[10.96.0.1]:443/apis/crd.projectcalico.org/v1/clusterinformations/default": cannotconnect  component=kubelet
INFO[2020-12-17 13:50:34] E1217 13:50:34.849571   25640 pod_workers.go:191] Error syncing pod e6d8ff82-ca5a-48cb-8a9b-e00249527e3e ("coredns-5c98d7d4d8-q9pl9_kube-system(e6d8ff82-ca5a-48cb-8a9b-e00249527e3e)"), skipping: failed to "CreatePodSandbox" for "coredns-5c98d7d4d8-q9pl9_kube-system(e6d8ff82-ca5a-48cb-8a9b-e00249527e3e)" with CreatePodSandboxError: "CreatePodSandbox for pod \"coredns-5c98d7d4d8-q9pl9_kube-system(e6d8ff82-ca5a-48cb-8a9b-e00249527e3e)\" failed: rpc error: code = Unknown desc = failed to setup network for sandbox \"711719d2b3c05589909e7ada8cf86b16d99a8c6074299cdb75ec0862e92e4e7b\": error getting ClusterInformation: Get \"https://[10.96.0.1]:443/apis/crd.projectcalico.org/v1/clusterinformations/default\": cannotconnect"  component=kubelet
INFO[2020-12-17 13:50:37] time="2020-12-17T13:50:37.555377887+08:00" level=info msg="RunPodsandbox for &PodSandboxMetadata{Name:calico-kube-controllers-5f6546844f-zdsj4,Uid:079b263e-bc27-4909-99ea-f61bf8368f01,Namespace:kube-system,Attempt:0,}"  component=containerd

I figure it might be related to containerd, so below is the result of `ps -f | grep  containerd' on the worker side.
$ ps -ef | grep containerd
root      1118     1  0 Nov09 ?        00:14:18 /usr/bin/containerd
root      2324     1  0 Nov09 ?        00:21:32 /usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock
wrsadmin 18991 23260  0 11:35 pts/6    00:00:00 grep --color=auto containerd
root     25624 25612  1 10:24 pts/5    00:00:43 /var/lib/k0s/bin/containerd --root=/var/lib/k0s/containerd --state=/var/lib/k0s/run/containerd --address=/var/lib/k0s/run/containerd.sock --log-level=info --config=/etc/k0s/containerd.toml
root     25640 25612  3 10:24 pts/5    00:02:14 /var/lib/k0s/bin/kubelet --root-dir=/var/lib/k0s/kubelet --volume-plugin-dir=/usr/libexec/k0s/kubelet-plugins/volume/exec --config=/var/lib/k0s/kubelet-config.yaml --bootstrap-kubeconfig=/var/lib/k0s/kubelet-bootstrap.conf --kubeconfig=/var/lib/k0s/kubelet.conf --v=1 --resolv-conf=/run/systemd/resolve/resolv.conf --kube-reserved-cgroup=system.slice --runtime-cgroups=/system.slice/containerd.service --kubelet-cgroups=/system.slice/containerd.service --container-runtime=remote --container-runtime-endpoint=unix:///var/lib/k0s/run/containerd.sock
root     26044     1  0 10:24 pts/5    00:00:01 /usr/bin/containerd-shim-runc-v2 -namespace k8s.io -id 0c64fac6bac691e9daa1fe26a61227450267cfdee34acdefae251d2a13c311c9 -address /var/lib/k0s/run/containerd.sock
root     26045     1  0 10:24 pts/5    00:00:05 /usr/bin/containerd-shim-runc-v2 -namespace k8s.io -id e8ec67649ee03944ae3d9cb25f6253b034f3737b57767cd22f9e7ed1572fc2b6 -address /var/lib/k0s/run/containerd.sock

Note the 26044 and 26045, they are all related to k0s, but the running binary are from the host instead of from the k0s.
There's a /var/lib/k0s/bin/containerd-shim-runc-v2, but the actual running one is /usr/bin/containerd-shim-runc-v2.
Is it a problem?

**Comment by kstych** [comment]
hi can you check if you have network name that calico is ignoring (ifconfig) calico ignores any network with "lo" in its name

https://github.com/k0sproject/k0s/issues/488

**Comment by ChenQi1989** [comment]
@kstych Below is the output from the worker node.
$ ip address
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eno1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 98:90:96:d6:ff:cf brd ff:ff:ff:ff:ff:ff
    inet 128.224.162.187/23 brd 128.224.163.255 scope global dynamic noprefixroute eno1
       valid_lft 12181sec preferred_lft 12181sec
    inet6 fe80::9a90:96ff:fed6:ffcf/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
3: virbr0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default qlen 1000
    link/ether 52:54:00:52:87:93 brd ff:ff:ff:ff:ff:ff
    inet 192.168.122.1/24 brd 192.168.122.255 scope global virbr0
       valid_lft forever preferred_lft forever
4: virbr0-nic: <BROADCAST,MULTICAST> mtu 1500 qdisc fq_codel master virbr0 state DOWN group default qlen 1000
    link/ether 52:54:00:52:87:93 brd ff:ff:ff:ff:ff:ff
5: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default 
    link/ether 02:42:54:93:4d:55 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
       valid_lft forever preferred_lft forever
8: vxlan.calico: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UNKNOWN group default 
    link/ether 66:21:99:e0:c4:72 brd ff:ff:ff:ff:ff:ff
    inet 10.244.211.128/32 brd 10.244.211.128 scope global vxlan.calico
       valid_lft forever preferred_lft forever
    inet6 fe80::6421:99ff:fee0:c472/64 scope link 
       valid_lft forever preferred_lft forever

**Comment by jnummelin** [comment]
> There's a /var/lib/k0s/bin/containerd-shim-runc-v2, but the actual running one is /usr/bin/containerd-shim-runc-v2.
Is it a problem?

That definitely can cause some wonkiness.

Looking at the logs, I _think_ this is the root cause for calico to fail setting up the network for pods:
```
 Get "https://[10.96.0.1]:443/apis/crd.projectcalico.org/v1/clusterinformations/default": cannotconnect
```

So for some reason the calico pod cannot connect to API using the in-cluster service address. Next thing I'd check:
- How is the `kubernetes` in-cluster service created. `kubectl get svc,ep kubernetes`. Is the reported address(es) on the endpoint such that the node can connect to?
- Anything meaningfull in `kube-proxy` logs? Kube proxy is the one responsible to make the kubernetes service to work (via iptables)

**Comment by ChenQi1989** [comment]
@jnummelin Thanks for looking into this!

$ kubectl get svc,ep kubernetes
NAME                 TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
service/kubernetes   ClusterIP   10.96.0.1    <none>        443/TCP   6d23h

NAME                   ENDPOINTS              AGE
endpoints/kubernetes   128.224.153.232:6443   6d23h

$ kubectl logs -n kube-system kube-proxy-65rp8
Error from server: Get "https://128.224.162.187:10250/containerLogs/kube-system/kube-proxy-65rp8/kube-proxy": proxyconnect tcp: dial timeout

**Comment by ChenQi1989** [comment]
@jnummelin
The #541 gives me some hint, so I removed the whole containerd packages and killed the runc-v2 processes manually.
Now the runc-v2 processes are re-started and they are using the correct binary.
root     28061     1  0 16:14 pts/5    00:00:00 /var/lib/k0s/bin/containerd-shim-runc-v2 -namespace k8s.io -id 9c6f02950b05cdb627eb2b4aecbe26030dace9ef6f89825fbab0bcf67966643a -address /var/lib/k0s/run/containerd.sock
root     28087     1  0 16:14 pts/5    00:00:00 /var/lib/k0s/bin/containerd-shim-runc-v2 -namespace k8s.io -id 690915469fd1a0096f36b8667e981ec5f1ede46e06ea3f55ab5959e520964da7 -address /var/lib/k0s/run/containerd.sock

One question here: their ppid is 1, is it expected?

The bad news is that this still does not solve the problem.
$ kubectl get pod -A
NAMESPACE     NAME                                       READY   STATUS              RESTARTS   AGE
kube-system   calico-kube-controllers-5f6546844f-zdsj4   0/1     ContainerCreating   0          7d
kube-system   calico-node-4922r                          1/1     Running             1          6d23h
kube-system   coredns-5c98d7d4d8-q9pl9                   0/1     ContainerCreating   0          7d
kube-system   konnectivity-agent-zsn4c                   0/1     ContainerCreating   0          5d5h
kube-system   kube-proxy-65rp8                           1/1     Running             1          6d23h
$ kubectl describe pod -n kube-system calico-kube-controllers-5f6546844f-zdsj4 | tail -1
  Warning  FailedCreatePodSandBox  31s                    kubelet  Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "6d70dd6d28cd3bb9b6a7afd644b0a3aca4bb3a14d5d0687584fda569c5a118d7": error getting ClusterInformation: Get "https://[10.96.0.1]:443/apis/crd.projectcalico.org/v1/clusterinformations/default": cannotconnect

As I started the worker with 'http_proxy' set in env, I'm now wondering if this env var setting is related to this problem....

**Comment by jnummelin** [comment]
> One question here: their ppid is 1, is it expected?

yes, containerd "detaches" the container processes from itself when it creates the containers.

The main issue I see is that kube-proxy cannot talk to the API:
```
$ kubectl logs -n kube-system kube-proxy-65rp8
Error from server: Get "https://128.224.162.187:10250/containerLogs/kube-system/kube-proxy-65rp8/kube-proxy": proxyconnect tcp: dial timeout
```

So this is why the `10.96.0.1` service address is not working either and thus calico cannot get up properly.

I wonder why there's a difference in the API address in kube-proxy vs. kubernetes endpoints? Which of the addresses is correct?

**Comment by ChenQi1989** [comment]
@jnummelin
Thanks for looking into this. Below is the server & worker info.

* Server:
Host name: pek-lpg-core3
IP: 128.224.153.232
Commands run on it: k0s server; k0s token create --role=worker; kubectl xxx
Proxy setting: None

* Worker:
Hostname: pek-qchen1-d2
IP: 128.224.162.187
Commands run on it: k0s worker "the long token"
Proxy setting: http_proxy set in env

One more question, is there some convenient way to clean things up so that I can do a fresh setup again?

**Comment by jnummelin** [comment]
> is there some convenient way to clean things up so that I can do a fresh setup again?

Unfortunately there's no easy way. The "best" way is to:
- shutdown k0s, make sure all processes go down (containerd, kubelet, etc.)
- kill all container processes (the ones managed via containerd-shim), probably easiest to reboot at this point
- `rm -rf /var/lib/k0s/`
- start fresh

There's few issues already tracking the need for something like `k0s reset` which should handle all this automatically

**Comment by jasmingacic** [comment]
@ChenQi1989 Can you provide us with more info so we can further investigate this issue.

**Comment by jnummelin** [comment]
closing due inactivity
