### ISSUE TITLE
Cannot override "leader-elect" on scheduler

### ISSUE THREAD

**Issue by jakolehm** [k0sproject/k0s#540]
For non-ha purposes it would be great if user could disable leader-elect completely. It burns quite a bit CPU which is completely unnecessary if you have only one controller.

**Comment by jnummelin** [comment]
This would need some general `singleNode: true` type of config option to disable ALL leader elections as we also do them in k0s controller.

**Comment by ncopa** [comment]
I think there are multiple types of "single nodes"
- single non-ha controller with potentially multiple workers. this issue covers this
- single controller with --enable-worker. Which technically is a single node, but with the possibility to be extended. (what we currently have)
- single controller with --enable-worker but without ability to be extended. (ie single node for local development cluster on your laptop type of clusters)

**Comment by ncopa** [comment]
A discussion about this led to the conclusion that we do not need to enable the leader elector if `ExternalAddress` is not set.
