### ISSUE TITLE
All pods are in 'Pending' status after running 'k0s server --enable-worker'

### ISSUE THREAD

**Issue by ChenQi1989** [k0sproject/k0s#541]
**Version**
v0.8.1

**Platform**
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic

**What happened?**
After running 'k0s server --enable-worker', using 'kubectl get pod -A' to check status, and I got:
$ kubectl get pod -A
NAMESPACE     NAME                                       READY   STATUS    RESTARTS   AGE
kube-system   calico-kube-controllers-5f6546844f-sh5p5   0/1     Pending   0          29h
kube-system   calico-node-xthsq                          0/1     Pending   0          24h
kube-system   coredns-5c98d7d4d8-xgxxz                   0/1     Pending   0          29h
kube-system   kube-proxy-6jnpj                           0/1     Pending   0          24h

**How To Reproduce**
k0s server --enable-worker
kubectl get pod -A

**Expected behavior**
I would expect the pods are not pending.

**Screenshots & Logs**
Below are a few logs.

time="2020-12-17 00:30:30" level=info msg="k8s.io/kubernetes/vendor/github.com/google/cadvisor/manager.(*manager).watchForNewOoms.func1(0xc0013057a0, 0xc000882780)" co
mponent=kubelet
time="2020-12-17 00:30:30" level=info msg="\t/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/google/cadvisor/manager/
manager.go:1204 +0x59" component=kubelet
time="2020-12-17 00:30:30" level=info msg="created by k8s.io/kubernetes/vendor/github.com/google/cadvisor/manager.(*manager).watchForNewOoms" component=kubelet
time="2020-12-17 00:30:30" level=info msg="\t/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/google/cadvisor/manager/
manager.go:1203 +0xdf" component=kubelet
time="2020-12-17 00:30:30" level=info msg="I1217 00:30:30.532801   56589 status_manager.go:158] Starting to sync pod status with apiserver" component=kubelet
time="2020-12-17 00:30:30" level=warning msg="exit status 255" component=kubelet
time="2020-12-17 00:30:30" level=info msg="respawning in 5 secs" component=kubelet
time="2020-12-17 00:30:34" level=info msg="current config matches existing, not gonna do anything" component=coredns
time="2020-12-17 00:30:34" level=info msg="current config matches existing, not gonna do anything" component=kubeproxy
time="2020-12-17 00:30:34" level=info msg="current config matches existing, not gonna do anything" component=calico
time="2020-12-17 00:30:35" level=info msg="Started succesfully, go nuts" component=kubelet
time="2020-12-17 00:30:35" level=info msg="Flag --volume-plugin-dir has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information." component=kubelet
time="2020-12-17 00:30:35" level=info msg="Flag --resolv-conf has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information." component=kubelet
time="2020-12-17 00:30:35" level=info msg="Flag --kube-reserved-cgroup has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information." component=kubelet
time="2020-12-17 00:30:35" level=info msg="Flag --kubelet-cgroups has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information." component=kubelet
time="2020-12-17 00:30:35" level=info msg="I1217 00:30:35.700269   56672 flags.go:59] FLAG: --add-dir-header=\"false\"" component=kubelet
time="2020-12-17 00:30:35" level=info msg="I1217 00:30:35.700327   56672 flags.go:59] FLAG: --address=\"0.0.0.0\"" component=kubelet
time="2020-12-17 00:30:35" level=info msg="I1217 00:30:35.700334   56672 flags.go:59] FLAG: --allowed-unsafe-sysctls=\"[]\"" component=kubelet

**Comment by jnummelin** [comment]
kubelet seems to be crashing on the node and thus the worker part never comes up.

When kubelet crashes, it dumps unnecessary amount of stack traces etc. When it is restarting, after it dumps out the FLAGs it should hopefully print some more info why it is crashing. The above log does not really contain anything helpfull to determine to cause for kubelet crash.

**Comment by ChenQi1989** [comment]
file:///home/chenqi/test/pending.log

**Comment by ChenQi1989** [comment]
[pending.log](https://github.com/k0sproject/k0s/files/5728289/pending.log)

**Comment by ChenQi1989** [comment]
@jnummelin I've attached the log from the command 'sudo ./k0s server --enable-worker > pending.log 2>&1'
Does it contain anything useful?

**Comment by ncopa** [comment]
```
time="2020-12-17 00:29:04" level=info msg="F1217 00:29:04.574280   55536 server.go:166] listen tcp 0.0.0.0:10250: bind: address already in use" component=kubelet
time="2020-12-17 00:29:04" level=info msg="goroutine 963 [running]:" component=kubelet
```
Looks like there are already another running kubelet. Maybe try reboot the machine?

**Comment by ChenQi1989** [comment]
@ncopa
It's finally working!!! THANKS A LOT!
You are right. The root cause is about a running kubelet. I removed the whole package.

$ kubectl get pod -A
NAMESPACE     NAME                                       READY   STATUS    RESTARTS   AGE
kube-system   calico-kube-controllers-5f6546844f-sh5p5   1/1     Running   0          6d4h
kube-system   calico-node-xthsq                          1/1     Running   0          6d
kube-system   coredns-5c98d7d4d8-xgxxz                   1/1     Running   0          6d4h
kube-system   konnectivity-agent-78grj                   1/1     Running   0          4m31s
kube-system   kube-proxy-6jnpj                           1/1     Running   0          6d

1) Should this log message belong to the warning level?
2) I think it's better to update the doc to tell user about this negative effect of a running kubelet, suggesting them to disabling/stopping the service. People who are interested in k0s are very likely to have already had k8s packages installed on their servers.  And the kubelet.service is started once the kubelet package is installed.
