### ISSUE TITLE
1

### ISSUE THREAD

**Issue by id18522096554** [k0sproject/k0s#545]
**Version**
```
$ k0s version
```
**Platform**
Which platform did you run k0s on?
```
$ lsb_release -a
```
**What happened?**

**How To Reproduce**
How can we reproduce this issue? (as minimally and as precisely as possible)

**Expected behavior**

**Screenshots & Logs**
Also add any output from kubectl if applicable:
```
$ export KUBECONFIG=/var/lib/k0s/pki/admin.conf
$ kubectl logs ...
```

**Additional context**

**Comment by ncopa** [comment]
closing due to lack of information of the problem
