### ISSUE TITLE
Store current configuration to cluster

### ISSUE THREAD

**Issue by jnummelin** [k0sproject/k0s#552]
**Is your feature request related to a problem? Please describe.**
e.g. for cluster upgrades we need to know what was the previous version & config.

**Describe the solution you'd like**
I'd like to be able to read version & config info to be able to plan and do automatic upgrades etc. operations. Maybe a custom global CRD to store all this info in a single place so it'll be readable for all needed tools.

**Comment by mohmb66** [comment]
https://twitter.com/fato6861?s=21

**Comment by soider** [comment]
#516 is related to this, would be nice if it would be considered during the implementation of the current issue
