### ISSUE TITLE
K0s impacted by btrfs kubernetes bug #95826

### ISSUE THREAD

**Issue by usrbinkat** [k0sproject/k0s#576]
/kind bug
# Upstream [bug](https://github.com/kubernetes/kubernetes/issues/95826)

**Desired Outcome:**
Closing this bug unresolved may be a reasonable outcome as upstream but will likely resolve the root cause. Filing for awareness.

**What happened**:
`/var/lib/kubelet` is a subdirectory of the btrfs subvolume `/`. kubelet fails to start with the following error:

```
Failed to start ContainerManager failed to get rootfs info: failed to get device for dir "/var/lib/kubelet": could not find device with major: 0, minor: 46 in cached partitions map
```

**What you expected to happen**:
k0s starts kubelet normally on btrfs filesystems and doesn't fail with an error message
 
**How to reproduce it**:
* Install k0s on a system using btrfs as file system for / (or /var)
* Start k0s
* tail logs for kubelet rootfs device error

**Version**
```
root@edge:~# k0s version
v0.9.0-rc1
```
**Platform**
Which platform did you run k0s on?
```
root@edge:~#  lsb_release -a
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.1 LTS
Release:        20.04
Codename:       focal
```

Also add any output from kubectl if applicable:
```
$ export KUBECONFIG=/var/lib/k0s/pki/admin.conf
$ kubectl logs ...
```

**Additional context**
Also duplicated issue with k0s versions `0.7.0,0.8.0`
Also tested with same results on Fedora 33
Currently working around issue via os reinstall with ext4 instead of btrfs filesystem

**Comment by jnummelin** [comment]
@usrbinkat thanks for opening this for awareness. 👏   Not much we can do in k0s for this currently.
