### ISSUE TITLE
Allow k0s server to run with a BYO CRI Engine

### ISSUE THREAD

**Issue by trawler** [k0sproject/k0s#579]
**Is your feature request related to a problem? Please describe.**
`k0s server` does not support the `--cri-socket` flag, and so cannot run with a runtime other than containerD

**Describe the solution you'd like**
Add the above mentioned flag to server as well (for single-node setup)

**Additional context**
https://github.com/k0sproject/k0s/issues/523#issuecomment-750382756

**Comment by binoychitale** [comment]
Hi @trawler , I'd like to pick this issue.
From what I gather, we want to achieve the following:
1. Add the `--cri-socket` flag to the `k0s server` subcommand args.
2. The implementation for this should mirror the one in `k0s worker` where the `--cri-socket` arg is already being consumed.

If this approach is correct, can I go ahead and implement this?

**Comment by binoychitale** [comment]
I took the liberty to open a PR anyway, since I assumed most people would be on leave for the holidays (and it seemed like a  small change 😄 )

**Comment by jnummelin** [comment]
@binoychitale yes, many people are on holidays. :) 

👍  for taking this up
