### ISSUE TITLE
failed to find plugin "loopback" in path [/opt/cni/bin]

### ISSUE THREAD

**Issue by ChenQi1989** [k0sproject/k0s#582]
**Version**
v0.8.1

**Platform**
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic

**What happened?**
Creating simple busybox pod failed.

Error message from 'kubectl describe pod busybox'
"""
  Warning  FailedCreatePodSandBox  5m18s                kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for s
andbox "55dbd184d9926ada73934c2379359797774bd1046fa85b462f3cfa0dc3e4e242": failed to find plugin "loopback" in path [/opt/cni/bin]
"""

The yaml file is:
$ cat busybox-sleep.yaml
apiVersion: v1
kind: Pod
metadata:
  name: busybox-sleep
spec:
  containers:
  - name: busybox
    image: busybox
    args:
    - sleep
    - "1000000"
---
apiVersion: v1
kind: Pod
metadata:
  name: busybox-sleep-less
spec:
  containers:
  - name: busybox
    image: busybox
    args:
    - sleep
    - "1000"

**How To Reproduce**
1. k0s server --enable-worker
2. cp admin.conf to $HOME and export KUBECONFIG=~/admin.conf
3. kubectl apply -f busybox-sleep.yaml

**Expected behavior**
The pods are running.

Note:
After I installed kubernetes-cni on host, the pods were started correctly.
So does this mean that k0s requires kubernetes-cni installed on worker machines?

**Comment by jnummelin** [comment]
Did you run k0s with default Calico CNI? If yes, Calico should setup all the needed CNI bins on each node using an init-container. E.g. this is what I see on one of my older k0s test clusters:
```
 # ls -lah /opt/cni/bin/
total 127M
drwxr-xr-x 2 root root 4.0K Nov 11 15:52 .
drwxr-xr-x 3 root root 4.0K Nov 11 15:52 ..
-rwxr-xr-x 1 root root 4.0M Nov 11 15:52 bandwidth
-rwxr-xr-x 1 root root  36M Nov 11 15:52 calico
-rwxr-xr-x 1 root root  36M Nov 11 15:52 calico-ipam
-rwxr-xr-x 1 root root 3.0M Nov 11 15:52 flannel
-rwxr-xr-x 1 root root 3.5M Nov 11 15:52 host-local
-rwxr-xr-x 1 root root  36M Nov 11 15:52 install
-rwxr-xr-x 1 root root 3.1M Nov 11 15:52 loopback
-rwxr-xr-x 1 root root 3.8M Nov 11 15:52 portmap
-rwxr-xr-x 1 root root 3.3M Nov 11 15:52 tuning
```

> So does this mean that k0s requires kubernetes-cni installed on worker machines?

If you use k0s default bundled Calico for CNI, then you should not have to do this. In case of some other CNI, it depends on the CNI provider whether or not they bring the CNI bins t´"with them".

**Comment by ChenQi1989** [comment]
@jnummelin 
I didn't do any customization. What I do is:
1) k0s server --enable-worker
2) kubectl apply -f busybox-sleep.yaml
And the yaml file contents are as above. No extra customization were added.

**Comment by jnummelin** [comment]
@ChenQi1989 Do you see the node reported as `Ready` in `kubectl get node` list?

What avout Calico pods status, is it reported as ready too? calico-node pod has an init container that's supposed to put all the cni stuff in place. I wonder if it has failed to do so. Check the calico-node pod status and logs of all the containers in there to see if there's been some errors.

**Comment by jnummelin** [comment]
closing due inactivity

**Comment by mhasrup** [comment]
@jnummelin : can u help me ?

vagrant@master-1:~$ kubectl get pods -n kube-system
NAME                       READY   STATUS              RESTARTS   AGE
coredns-69cbb76ff8-nql5k   0/1     ContainerCreating   0          17h
coredns-69cbb76ff8-p44xg   0/1     ContainerCreating   0          17h
weave-net-2vdr7            1/2     CrashLoopBackOff    22         17h
weave-net-pqrx8            1/2     CrashLoopBackOff    23         17h
vagrant@master-1:~$ kubectl describe pod coredns-69cbb76ff8-nql5k -n kube-system
Name:               coredns-69cbb76ff8-nql5k
Namespace:          kube-system
Priority:           0
PriorityClassName:  <none>
Node:               worker-1/192.168.5.21
Start Time:         Sun, 09 Jan 2022 11:11:48 +0000
Labels:             k8s-app=kube-dns
                    pod-template-hash=69cbb76ff8
Annotations:        <none>
Status:             Pending
IP:                 
Controlled By:      ReplicaSet/coredns-69cbb76ff8
Containers:
  coredns:
    Container ID:  
    Image:         coredns/coredns:1.2.2
    Image ID:      
    Ports:         53/UDP, 53/TCP, 9153/TCP
    Host Ports:    0/UDP, 0/TCP, 0/TCP
    Args:
      -conf
      /etc/coredns/Corefile
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Limits:
      memory:  170Mi
    Requests:
      cpu:        100m
      memory:     70Mi
    Liveness:     http-get http://:8080/health delay=60s timeout=5s period=10s #success=1 #failure=5
    Environment:  <none>
    Mounts:
      /etc/coredns from config-volume (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from coredns-token-z4x9n (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  config-volume:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      coredns
    Optional:  false
  coredns-token-z4x9n:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  coredns-token-z4x9n
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     CriticalAddonsOnly
                 node-role.kubernetes.io/master:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason                  Age                   From               Message
  ----     ------                  ----                  ----               -------
  Normal   Scheduled               17h                   default-scheduler  Successfully assigned kube-system/coredns-69cbb76ff8-nql5k to worker-1
  Warning  FailedCreatePodSandBox  17h                   kubelet, worker-1  Failed create pod sandbox: rpc error: code = Unknown desc = [failed to set up sandbox container "b1858edb33e7a3f91fdc10f72a42b18db7ce44f28e45054da6566d2689832637" network for pod "coredns-69cbb76ff8-nql5k": NetworkPlugin cni failed to set up pod "coredns-69cbb76ff8-nql5k_kube-system" network: failed to find plugin "loopback" in path [/opt/cni/bin], failed to clean up sandbox container "b1858edb33e7a3f91fdc10f72a42b18db7ce44f28e45054da6566d2689832637" network for pod "coredns-69cbb76ff8-nql5k": NetworkPlugin cni failed to teardown pod "coredns-69cbb76ff8-nql5k_kube-system" network: failed to find plugin "portmap" in path [/opt/cni/bin]]
  Normal   SandboxChanged          17h (x25 over 17h)    kubelet, worker-1  Pod sandbox changed, it will be killed and re-created.
  Normal   SandboxChanged          4m3s (x327 over 17h)  kubelet, worker-1  Pod sandbox changed, it will be killed and re-created.
vagrant@master-1:~$
