### ISSUE TITLE
Cannot use WeaveNet cni plugins (failed to find plugin "loopback")

### ISSUE THREAD

**Issue by lucj** [k0sproject/k0s#597]
**Version**
```
$ k0s version
v0.9.1
```
**Platform**
Which platform did you run k0s on?
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal
```
**What happened?**
Pod cannot be created when using WeaveNet instead of Calico

**How To Reproduce**

- Run k0s server with the --enable-worker option and using the following configuration
````
apiVersion: k0s.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s
spec:
  api:
    address: 192.168.64.11
    sans:
    - 192.168.64.11
  network:
    provider: custom
````

192.168.64.11 is the IP address of a Ubuntu VM launched with Multipass.

- install WeaveNet with the standard command:

    kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"

**Expected behavior**
Pod created correctly

**Screenshots & Logs**
````
$ kubectl -n kube-system describe po coredns-5c98d7d4d8-b4gss
...
Warning  FailedCreatePodSandBox  46s (x17 over 4m11s)  kubelet            (combined from similar events): Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "cad3d419860aca52863ff9ee4185f5949704eaf04262be0e7dec8aa3240c203b": failed to find plugin "loopback" in path [/opt/cni/bin]
````

I have the following content in /opt/cni/bin:

````
$ find /opt/cni/bin/
/opt/cni/bin/
/opt/cni/bin/weave-plugin-2.7.0
/opt/cni/bin/weave-net
/opt/cni/bin/weave-ipam
````

On another cluster (that one created with kubeadm) we can see all the cni plugins in the /opt/cni/bin (among them the missing loopback one):

```
$ find /opt/cni/bin/
/opt/cni/bin/
/opt/cni/bin/ipvlan
/opt/cni/bin/loopback
/opt/cni/bin/portmap
/opt/cni/bin/flannel
/opt/cni/bin/weave-plugin-2.7.0
/opt/cni/bin/vlan
/opt/cni/bin/ptp
/opt/cni/bin/tuning
/opt/cni/bin/bridge
/opt/cni/bin/weave-net
/opt/cni/bin/dhcp
/opt/cni/bin/host-local
/opt/cni/bin/static
/opt/cni/bin/host-device
/opt/cni/bin/sbr
/opt/cni/bin/bandwidth
/opt/cni/bin/macvlan
/opt/cni/bin/weave-ipam
/opt/cni/bin/firewall
```

Copying all the plugins from [https://github.com/containernetworking/plugins/releases/tag/v0.9.0](https://github.com/containernetworking/plugins/releases/tag/v0.9.0) into /opt/cni/bin fixed the thing but I'm not sure about who should have the responsibility to ship those plugins though :(

As the command to install the WeaveNet plugin is quite standard, are there any pre-requisites on k0s side to ensure the CNI plugins are correctly shipped ?

**Comment by lucj** [comment]
Digging a little bit deeper, I saw the following plugin are present when running k0s with the default Calico plugins
````
# ls -al /opt/cni/bin
total 130020
drwxr-xr-x 2 root root     4096 Jan  5 19:16 .
drwxr-xr-x 3 root root     4096 Jan  5 19:16 ..
-rwxr-xr-x 1 root root  4159518 Jan  5 19:16 bandwidth
-rwxr-xr-x 1 root root 37257216 Jan  5 19:16 calico
-rwxr-xr-x 1 root root 37257216 Jan  5 19:16 calico-ipam
-rwxr-xr-x 1 root root  3069556 Jan  5 19:16 flannel
-rwxr-xr-x 1 root root  3614480 Jan  5 19:16 host-local
-rwxr-xr-x 1 root root 37257216 Jan  5 19:16 install
-rwxr-xr-x 1 root root  3209463 Jan  5 19:16 loopback
-rwxr-xr-x 1 root root  3939867 Jan  5 19:16 portmap
-rwxr-xr-x 1 root root  3356587 Jan  5 19:16 tuning
````
Are those all shipped by Calico ?

**Comment by jnummelin** [comment]
Given the fact that CNI providers need/rely on different CNI bins I think it's not a responsibility of k0s to bring all of those in. IMO all CNI vendors, at least the ones shipping things as containers, should have some init containers that puts things in place like Calico does.

I think we need to properly document this in the BYO CNI sections of docs.

**Comment by lucj** [comment]
That really makes sense.
Thanks a lot @jnummelin
