### ISSUE TITLE
Include OLM in k0s

### ISSUE THREAD

**Issue by jnummelin** [k0sproject/k0s#598]
**Is your feature request related to a problem? Please describe.**
[OLM](https://github.com/operator-framework/operator-lifecycle-manager) is getting more and more popular way to manage many different kinds of operator in clusters. Thus there's been some reuests to include OLM in k0s clusters as well.

**Additional context**
https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/install/install.md

**Comment by usrbinkat** [comment]
I was able to deploy OLM on K0s so I believe there is no blocker here. Can you provide more information as to what seems broken?

Proceedure:
  - Install OLM via  [Release Instructions](https://github.com/operator-framework/operator-lifecycle-manager/releases)

Validation:
  - Install [argocd-operator](https://github.com/argoproj-labs/argocd-operator) through olm via [manual operator deploy method](https://argocd-operator.readthedocs.io/en/latest/install/olm)
  
  Anecdotally I also installed the ETCD operator from OLM just to see what blockers look like in the future and that operator installed without issue.

**Comment by jnummelin** [comment]
> Can you provide more information as to what seems broken?

@usrbinkat Nothing is broken AFAIK and as youäve also found out. This issue is mainly to track some work to make OLM "bundled-in"  with k0s. So that there's OLM setup out-of-box with k0s.

**Comment by usrbinkat** [comment]
@jnummelin I'm curious, are you looking to add a `extensions.operators.operator` spec to compliment the `extensions.helm.repositories` spec to accomplish this? or?

**Comment by jasmingacic** [comment]
As per our discussion earlier. 
OLM is fairly easy to install on a cluster. Three [lines ](https://github.com/operator-framework/operator-lifecycle-manager/releases) in shell.
Bundling OLM into k0s might not fit the scope of k0s. If the idea is to have k0s as super easy way to install kubernetes cluster on any infrastructure. Adding OLM opens many more questions that need to be answered. 
@mviitane 

I will close this for now.
