### ISSUE TITLE
Determine version and role of currently running k0s instance

### ISSUE THREAD

**Issue by kke** [k0sproject/k0s#602]
K0s needs something along the lines of:

```
$ k0s status
not running
```

```
$ k0s status
running: k0s worker version 0.9.1 
```

```
$ k0s status
running: k0s controller version 0.9.1
```

I guess it could be made simply with something like `/run/k0s/status` which would look something like:

```
pid=1234
role=worker
version=0.9.1
```

The `k0s status` command would read this status file, check the pid exists and looks like a k0s,  and then report the rest of it.

A regular pid file like `/run/k0s/k0s.pid` could also be handy, it could be checked when trying to launch a new instance to avoid multiple instances and maybe the PID file could be somehow utilized by systemd/openrc/whatever init system.

**Comment by jnummelin** [comment]
I _think_ we can dig out the needed info from standard proc bits:
```
~# ps -ef | grep ‘k0s server’
root       91598   91571  0 15:30 pts/0    00:00:00 sudo k0s server
root       91600   91598  0 15:30 pts/0    00:00:00 k0s server
root       91926   91776  0 15:32 pts/1    00:00:00 grep --color=auto k0s server
~# /proc/91600/exe version
v0.8.1
~# cat /proc/91600/cmdline
k0s--debug--data-dir=/var/lib/k0s/custom-data-dirworker--token-file=/token
```

Of course it would be probably easier to have all the needed info in some more easily parseable format in some custom status file

**Comment by jasmingacic** [comment]
#637 should handle this.

Closing the issue.
