### ISSUE TITLE
Decide on terminology for server/controller

### ISSUE THREAD

**Issue by kke** [k0sproject/k0s#603]
The seems to be a mix'n'match of the terms `controller` and `server` used to describe the same thing. The documentation for example is talking about adding controllers and there's for example `k0s token create --role=controller` which then generates a token to be used for `kos install server` (#594).

**Comment by trawler** [comment]
I would vote for server -> controller

**Comment by jnummelin** [comment]
> I would vote for server -> controller

I second this

**Comment by jasmingacic** [comment]
We could add alias for server/controller just to make everyone happy.
