### ISSUE TITLE
Improve usage of external long running clients

### ISSUE THREAD

**Issue by soider** [k0sproject/k0s#604]
So far we use clients to external services (k8s api, etcd, may be something else) just in place. That led to possibilities of having resource leaks and unnecessary activities. 
We could improve that by introducing some application level holder for all external deps and passing them as arguments\fields to the place of usage. 

In the basic form it could be done by just initing everything once in the main and then passing to reconcilers and components.

Currently known cases where we can share the client instances:

- [x] etcd client
- [x] kube client, #610 
- [x] leader elector

**Comment by jnummelin** [comment]
All known cases are fixed. If there's some further enhancements needed  lets open separate issues for those.
