### ISSUE TITLE
Decide on the the systemd example implentation

### ISSUE THREAD

**Issue by movd** [k0sproject/k0s#605]
There currently are two systemd unit file templates in the repo:

A) how `k0s install` creates the unit: https://github.com/k0sproject/k0s/blob/main/pkg/install/service.go 
B) https://github.com/k0sproject/k0s/blob/main/init/k0s.service

It would be good if both implementations were to be combined for consistency.

**Comment by jasmingacic** [comment]
@movd I believe the second one should be removed as it isn't being used

**Comment by trawler** [comment]
Since we use our own systemd template here: https://github.com/k0sproject/k0s/blob/main/pkg/install/service.go#L79-L108 we can actually tweak the template to our liking... 
I vote +1 on modifying the template to match the original init example and remove the static version.
