### ISSUE TITLE
k0s server startup indicates private address as public

### ISSUE THREAD

**Issue by chasemp** [k0sproject/k0s#619]
**Version**
```
$ k0s version

```
> v0.8.1

**Platform**
Which platform did you run k0s on?
```
$ lsb_release -a
```

> Distributor ID:	Ubuntu
> Description:	Ubuntu 20.04.1 LTS
> Release:	20.04
> Codename:	focal

**What happened?**

Startup log line calls out private addressing as "public" address:

> startup "INFO\[2020-12-11 21:15:01\] using public address: 172.31.12.11"

I'm not sure what the context here is for public, but if it's a public/private indicator from [rfc1918](https://tools.ietf.org/html/rfc1918) then it's incorrect.  

**How To Reproduce**

> k0s server on a host with only private IPv4 addresses

**Expected behavior**

Either of these would be accurate:

> startup "INFO\[2020-12-11 21:15:01\] using address: 172.31.12.11"
> startup "INFO\[2020-12-11 21:15:01\] using private address: 172.31.12.11"

**Additional context**

**Comment by jnummelin** [comment]
> I'm not sure what the context here is for public, but if it's a public/private indicator from rfc1918 then it's incorrect.

Yes, it's incorrect per se. The logic is basically so that k0s picks by default the first non-loopback address it finds to be used as the API address. Not sure if there's widespread term used for that sort of purpose.
