### ISSUE TITLE
LICENSE placeholders not filled out

### ISSUE THREAD

**Issue by kke** [k0sproject/k0s#630]
The Apache-2 portion of [LICENSE file](https://github.com/k0sproject/k0s/blob/afd11e82a9727ff1bc1ac883a966a59831694d12/LICENSE#L194) has the placeholders for copyright information:

```
   Copyright [yyyy] [name of copyright owner]
```

**Comment by ncopa** [comment]
This is in the APPENDIX section, which explains how to use the license. This is after "END OF TERMS AND CONDITIONS".

It shows the boilerplate to be added to each file. The placeholders should be replaced in each file the boilerplate is added to.

A quick search shows that we have the placeholders replaced in every file so I think we are all good.
