### ISSUE TITLE
does k0s support docker out of the box

### ISSUE THREAD

**Issue by blueray453** [k0sproject/k0s#641]
As far I know, current [dockershim has been deprecated][1] by Kubernetes maintainers. As a result [Mirantis has taken over support of Kubernetes dockershim][2]. I also know that [Mirantis announces a new kubernetes distribution named k0s][3].

What I am interested to know is, does docker get special treatment when using k0s? I mean out of the box support for docker or something like that? 

What I found so far is<sup>[1][4]</sup>, 

> k0s supports users bringing their own CRI runtime (for example, docker).

However, I was expecting docker swarm level integration when using k0s. Am I missing something?

  [1]: https://kubernetes.io/blog/2020/12/02/dockershim-faq/
  [2]: https://www.mirantis.com/blog/mirantis-to-take-over-support-of-kubernetes-dockershim-2/
  [3]: https://www.infoq.com/news/2020/12/k0s-kubernetes-distribution/
  [4]: https://docs.k0sproject.io/latest/custom-cri-runtime/

**Comment by jnummelin** [comment]
Yes, k0s supports docker out-of-box. You can run the worker with something like:
```
k0s worker --cri-socket docker:unix:///var/run/docker.sock <token>
```

That will still start the embedded dockershim "within" kubelet, it's still there untill 1.23 kubenetes at least.

There's no decisions made whether or not we'll ship the dockershim with k0s.

**Comment by blueray453** [comment]
How can we know, whether you decide to ship the dockershim with k0s or not? And is https://github.com/Mirantis/cri-dockerd the new dockershim you are referring to?

**Comment by jnummelin** [comment]
> How can we know, when you decide to ship the dockershim with k0s or not?

When we ship with a kubernetes version which does NOT anymore have the dockershim in, we will document how to run k0s with docker. That documentation will state whether or not k0s comes with the dockershim.
