### ISSUE TITLE
alpine 3.13, can't start server

### ISSUE THREAD

**Issue by sacesare** [k0sproject/k0s#646]
**Version**
```
0.9.1
```
**Platform**
Which platform did you run k0s on?
```
alpine 3.13
```
**What happened?**
Nothing happens, just hangs forever in pending state.

**How To Reproduce**
/var/lib/k0s directory is empty.
run:
```
k0s server
```

**Expected behavior**
Cluster started and server node active.

**Screenshots & Logs**
```
test1:/# kubectl get node
No resources found
test1:/# kubectl get pod -A
NAMESPACE     NAME                                       READY   STATUS    RESTARTS   AGE
kube-system   calico-kube-controllers-5f6546844f-lqlvz   0/1     Pending   0          2m48s
kube-system   coredns-5c98d7d4d8-jxxqp                   0/1     Pending   0          2m48s
kube-system   metrics-server-7d4bcb75dd-8p5dl            0/1     Pending   0          2m48s
test1:/#
```

**Comment by jnummelin** [comment]
As explained in the [FAQ](https://docs.k0sproject.io/v0.9.1/FAQ/#why-doesnt-kubectl-get-nodes-list-the-k0s-server) running `k0s server` will NOT start the worker component at all thus there's nothing to run those pods yet. If you want to start the worker on the same node you can run `k0s server --enable-worker`.

Closing as this is working as designed.

**Comment by sacesare** [comment]
```
k0s server --enable-worker
```
same state, nothing changed-cluster not started.

**Comment by sacesare** [comment]
Sorry, my fault, cgroups not started:
```
rc-service cgroups start
```
fixed issue.
