### ISSUE TITLE
k0s uninstall command

### ISSUE THREAD

**Issue by sacesare** [k0sproject/k0s#653]
**Is your feature request related to a problem? Please describe.**
I can't cleanup after k0s automatically, using single command like "uninstall/cleanup".

**Describe the solution you'd like**
k0s uninstall- stop/remove service.
After that, something like:
```
pkill -9 runc #terminate shims
umount -R /var/lib/k0s/kubelet #for --enable-worker option
df | grep /var/lib/k0s/run | awk '{$5?$5:$6}' | xargs umount
rm -rf /var/lib/k0s

```

**Comment by jnummelin** [comment]
duplicate of #519
