### ISSUE TITLE
Kubelet writes certs outside of k0s data dir

### ISSUE THREAD

**Issue by jakolehm** [k0sproject/k0s#675]
**Version**
```
v0.10.0-beta2
```
**Platform**
Which platform did you run k0s on?
```
Alpine (docker container)
```
**What happened?**

K0s kubelet writes certificates to `/var/lib/kubelet` which is a bit unexpected. 

**How To Reproduce**

Run k0s on a container that has `/var/lib/k0s` volume. After k0s is up & running recreate that container -> kubelet does not find certificates because they are not in the volume.

**Expected behavior**

I would expect that all critical state is within k0s data dir.

**Screenshots & Logs**

```
failed to start kubelet config client: failed to load kubeconfig: invalid configuration: [unable to read client-cert /var/lib/kubelet/pki/kubelet-client-current.pem for default-auth due to open /var/lib/kubelet/pki/kubelet-client-current.pem: no such file or directory, unable to read client-key /var/lib/kubelet/pki/kubelet-client-current.pem for default-auth due to open /var/lib/kubelet/pki/kubelet-client-current.pem: no such file or directory]
```

**Comment by beatcracker** [comment]
+1, I had to add 

```yaml
volumes:
  - 'data:/var/lib/k0s'
  - 'kubelet:/var/lib/kubelet'
```

to my `docker-compose.yaml`, otherwise certificates were regenerated every time I do `docker-compose up & down`
