### ISSUE TITLE
k0s worker can't join a cluster with an API server address set to an IPv6 address

### ISSUE THREAD

**Issue by unixfox** [k0sproject/k0s#688]
**Version**
v0.10.0

**Platform**
Debian 10 amd64

**What happened?**
When I set an IPv6 address for the API server, no workers will be able to join the cluster.

**How To Reproduce**
Find your public IPv6 address, you may be able to reproduce it with a private IPv6 address that starts with `fe80::` but I haven't tested on that case.

Generate a new default configuration:
```
k0s default-config > ./k0s.yaml
```

Set spec.api.address to an IPv6 address and add it so the san like this example:
```yml
spec:
  api:
    address: 2a03:b0c0:2:d0::f60:3001
    sans:
    - 2a03:b0c0:2:d0::f60:3001
```

Launch k0s server with a worker: `k0s server --enable-worker`.

You should now see no worker appearing with `kubectl get nodes`, no `kubelet` running and a very high CPU usage from the apiserver.

**Expected behavior**
To have k0s working normally like it would with an IPv4 address set for the API server address.

**Screenshots & Logs**
N/A

**Additional context**
N/A

**Comment by soider** [comment]
@unixfox have you tried externalAddress instead? Do you try to operate in single ipv6 mode?

**Comment by mviitane** [comment]
Just to check, did you do any configuration changes in the network section, like
https://docs.k0sproject.io/main/dual-stack/

**Comment by unixfox** [comment]
> @unixfox have you tried externalAddress instead?

Yes I tried with externalAddress and I got the same results.

> Do you try to operate in single ipv6 mode?

What you do mean by that? In IPv6 only? If that's what you asked then no the node has both working IPv4 connectivity and IPv6 connectivity.

I tried with the built-in worker: `--enable-worker` and without it by launching the node worker separately.

**Comment by jnummelin** [comment]
@unixfox Is this a dual-stack setup or are you just trying to set the api.address to ipv6 address in "normal" ipv4 cluster?

**Comment by unixfox** [comment]
> @unixfox Is this a dual-stack setup or are you just trying to set the api.address to ipv6 address in "normal" ipv4 cluster?

It's a dual stack setup.

**Comment by jnummelin** [comment]
ok, then [this](https://github.com/kubernetes/kubernetes/issues/88069#issuecomment-585261266) feels like very similar case. In there, the "solution" (AFAIK) was to change the order of CIDR blocks to `ipv6-block,ipv4-block`. Maybe give it a try to see if you get any further.

How eve, next issue you'll probably bump into is the fact that we do not create IPv6 CIDR address in the api-server SANs automatically, so probably calico and others cannot connect to it using the cluster IP.

**Comment by soider** [comment]
@unixfox the issue would be fixed as a part of the https://github.com/k0sproject/k0s/pull/694

**Comment by unixfox** [comment]
Sorry for the late reply.

Thank you @soider, I do confirm that #694 fixes the issue.
