### ISSUE TITLE
k0s in a container "leaks" zombies

### ISSUE THREAD

**Issue by jnummelin** [k0sproject/k0s#698]
**Version**
0.10.0

Affects all k0s container imges though

**Platform**
Docker

**What happened?**
k0s running in a container "leaks" containerd-shims processes as zombies. eventually will OOM as there's too many of them.

This is caused by the fact that currently k0s itself is the PID 1 in the container and does not handle the containerd-shim (and related) childs.

**How To Reproduce**
run k0s in a container and make kube to recreate pods often.

**Expected behavior**
No 🧟  processes

**Additional context**

Easily mitigated by putting tini in the container as pid 1 so it'll reap zombies

**Comment by unixfox** [comment]
I'm not 100% sure, but I've seen the konnectivity agent just disappearing and thus produce an exact bug like https://github.com/k0sproject/k0s/issues/665.

So this may solve https://github.com/k0sproject/k0s/issues/665, but I'm not 100% sure. This need some testing.

**Comment by ncopa** [comment]
a zombie process is a process that has terminated, but the parent (or anything else) does not get the exit status (using wait/waitpid syscalls), so the kernel can not free the resources from the exited process. This will show up as a zombie process in the process list.

I doubt this will solve #665. zombie process does not do anything except consume kernel memory.
