### ISSUE TITLE
Calico IPv6 autodetection customization

### ISSUE THREAD

**Issue by unixfox** [k0sproject/k0s#702]
**Is your feature request related to a problem? Please describe.**
Currently, it's only possible to set the IP autodetection for IPv4 with `IP_AUTODETECTION_METHOD`.

**Describe the solution you'd like**
I would like to be able to set the IPv6 autodetection on Calico. This environment variable: `IP6_AUTODETECTION_METHOD`.

**Describe alternatives you've considered**
Installing Calico externally.

**Additional context**
N/A

**Comment by soider** [comment]
@unixfox 
We actually run now calico always with IP6 equals `autodetect`, for the dual-stack mode.
Could you elaborate what do you want to be introduced?

**Comment by unixfox** [comment]
> @unixfox
> We actually run now calico always with IP6 equals `autodetect`, for the dual-stack mode.
> Could you elaborate what do you want to be introduced?

Sorry for not being descriptive enough about this issue.
Basically I would like to be able to customize the env `IP6_AUTODETECTION_METHOD`.

This is related to this issue: https://github.com/k0sproject/k0s/issues/479 which was about customizing `IP_AUTODETECTION_METHOD` instead.

**Comment by soider** [comment]
@jnummelin @unixfox any ideas here, should it be separate settings or the one?

I see following options:
- 2 separate settings in config for ip autodetection, one for ipv4 one for ipv6
- 1 setting which values is always used for both ipv4 and ipv6 values in manifest
- 2 settings, but by default use the same `ipAutoDetection` mode for both ipv4 and ipv6, and specify ipv6 autodetection mode only if second setting is non empty.

**Comment by unixfox** [comment]
@soider I like the third option because we should have some default options but also provide the ability to change those default options if for example one has a special environment where the IPv4 traffic doesn't take the same route/interface as the IPv6 traffic.
Also, some values from `IP_AUTODETECTION_METHOD` could be invalid for `IP6_AUTODETECTION_METHOD`, for example `can-reach=8.8.8.8` so that's why it's good to let the customization on both of the `ipAutoDetection` settings.

**Comment by jnummelin** [comment]
I kinda like the third option too the most.
