### ISSUE TITLE
konnectivity-agent issue in ubuntu 20 desktop

### ISSUE THREAD

**Issue by gcvalderrama** [k0sproject/k0s#731]
**Version**
```
$ 1.0
```
**Platform**
UBUNTU 20 and Raspberry pi 4
```
$ lsb_release -a
```
**What happened?**

![image](https://user-images.githubusercontent.com/2818939/108902276-e7b28c00-75e9-11eb-8817-90f9e92c4051.png)

**How To Reproduce**

* Disable conainerd rule in apparmor ubuntu 

* Install on ubuntu as single executable 

**Expected behavior**

konnectivity without error

**Screenshots & Logs**

![image](https://user-images.githubusercontent.com/2818939/108902400-0c0e6880-75ea-11eb-93f0-68d2154212cc.png)

![image](https://user-images.githubusercontent.com/2818939/108902454-1af51b00-75ea-11eb-809f-7551cd0b6822.png)

**Additional context**

**Comment by jnummelin** [comment]
@gcvalderrama Is there something that does not work in your cluster? The error you see is harmless and is seen in the logs whenever the connection through konnectivity gets closed on either side. See https://kubernetes.slack.com/archives/CPS4Z8G8N/p1612385402007800

**Comment by jnummelin** [comment]
Closing as inactive.
