### ISSUE TITLE
Creating swagger.json out of custom CRDs

### ISSUE THREAD

**Issue by mostrovoi** [k0sproject/k0s#740]
I would like to use your project as part of my release pipeline to retrieve swagger.json from OpenAPI

I have basically custom CRDs and I would like to install them in k0s and retrieve the swagger.json 

Is OpenApi endpoint supported and can I retrieve swagger.json from k0s?

**Comment by soider** [comment]
@mostrovoi hi!
We do support OpenAPI. 

On the freshly installed cluster it is available as usual under the path `/openapi/v2`

For example:

```
# kubectl  proxy &
[1] 11986
# Starting to serve on 127.0.0.1:8001

# curl 127.0.0.1:8001/openapi/v2 > swagger.json
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 4187k    0 4187k    0     0  78.6M      0 --:--:-- --:--:-- --:--:-- 78.6M
```

**Comment by jnummelin** [comment]
closing as answered.
