### ISSUE TITLE
k0s reset enhancement: support docker CRI

### ISSUE THREAD

**Issue by trawler** [k0sproject/k0s#742]
**Is your feature request related to a problem? Please describe.**
k0s reset supports only containerd, it should also support docker as a container runtime.

**Comment by jewertow** [comment]
Can I work on this issue?

**Comment by jnummelin** [comment]
@jewertow of course

**Comment by jewertow** [comment]
Great, I already investigated how to change current implementation, so I will submit a PR soon.
