### ISSUE TITLE
k0s reset: don't use crictl as a dependency

### ISSUE THREAD

**Issue by trawler** [k0sproject/k0s#743]
**Is your feature request related to a problem? Please describe.**
In order to decrease the size footprint of the compiled k0s binary, we should remove crictl from the embedded bins.

**Describe the solution you'd like**
crictl stop and rm operations should be imported into k0s as a library.

**Comment by jewertow** [comment]
@trawler could I work on this issue?

**Comment by jasmingacic** [comment]
@jewertow go ahead give it a try

**Comment by jewertow** [comment]
Ok, cool. I will try to implement it.
I have one question: if the main goal is to decrease the size footprint of the compiled k0s binary, maybe it would be even better to import `cri-api` instead of `crictl` and implement these operations?

**Comment by trawler** [comment]
@jewertow since cri-tools already use cri-api, I don't see why not :) that sounds like a good plan. 👍
