### ISSUE TITLE
k0s install: relative paths from options should be converted to absolute

### ISSUE THREAD

**Issue by jasmingacic** [k0sproject/k0s#749]
When path to files with any of install subcommands  doesn't file path doesn't get parsed in service stubs.

```
k0s install controller -c k0s.yaml
```

```
ExecStart=/root/go/src/github.com/k0sproject/k0s/k0s controller --config=val.yaml
```

Which when running will not get resolved.

Also there was a mention of the same issue here: `https://miracloud.slack.com/archives/C01CQPVUELA/p1614696996086800`

**Comment by kke** [comment]
Would it be more confusing if `k0s install controller --config=foo.yaml` would actually install a copy of that yaml into the "default" location such as `/etc/k0s/k0s.yaml` and the installed service would be configured to read it from there instead of using a file in some strange location like `~randomguy/projects/k0s/foofoo.yaml`?

**Comment by trawler** [comment]
> Would it be more confusing if `k0s install controller --config=foo.yaml` would actually install a copy of that yaml into the "default" location such as `/etc/k0s/k0s.yaml` and the installed service would be configured to read it from there instead of using a file in some strange location like `~randomguy/projects/k0s/foofoo.yaml`?

I know we have users that may not have root access for controller nodes. in which case, this will prevent them from running this command. Unless necessary, I'd like to avoid being _too_ opinionated.

**Comment by trawler** [comment]
> > Would it be more confusing if `k0s install controller --config=foo.yaml` would actually install a copy of that yaml into the "default" location such as `/etc/k0s/k0s.yaml` and the installed service would be configured to read it from there instead of using a file in some strange location like `~randomguy/projects/k0s/foofoo.yaml`?
> 
> I know we have users that may not have root access for controller nodes. in which case, this will prevent them from running this command. Unless necessary, I'd like to avoid being _too_ opinionated.

Ok, on second thought - these users will not be able to run the install command anyway :) but still, I don't like the idea of copying too many files around, that we later need to clean-up.

**Comment by jasmingacic** [comment]
I would rather let users decide where the config should reside. Automating it might cause confusion

**Comment by trawler** [comment]
re-opened mistakenly
