### ISSUE TITLE
Improve documentation for Zsh autocompletion

### ISSUE THREAD

**Issue by trawler** [k0sproject/k0s#781]
**What happened?**
The existing documentation on how to enable zsh auto-completion is incorrect/missing information.

**Expected behavior**
In this page: https://docs.k0sproject.io/v0.11.0/install/#zsh

The following should be removed:
```
# To load completions for each session, execute once:
$ k0s completion zsh > "${fpath[1]}/_k0s"
```
and replaced by
```
$ echo "source <(k0s completion zsh)" >> ~/.zshrc
```

**Comment by kke** [comment]
That would run k0s on every shell invocation, not a best practice.

The usual way is something like:

```shell
k0s completion zsh > /usr/local/share/zsh/site-functions/_k0s
```

**Comment by kke** [comment]
The current example of doing:

```shell
k0s completion zsh > "${fpath[1]}/_k0s"
```

may end up writing the file somewhere weird if you're using some zsh plugin framework, for example on my system it would go to `/Users/kimmo/Library/Caches/antibody/https-COLON--SLASH--SLASH-github.com-SLASH-robbyrussell-SLASH-oh-my-zsh/functions`.
