### ISSUE TITLE
Build default bundle for the airgap install

### ISSUE THREAD

**Issue by soider** [k0sproject/k0s#785]
**Is your feature request related to a problem? Please describe.**
With #755 is landing to the main branch we'd have a way to install k0s cluster at the airgaped environment

To perform such installation end-user need to have OCI bundle of images. There is guide available in the documentation on creating such bundle, but would be beneficial to the UX to have such bundle available on the release page.

**Describe the solution you'd like**
One way is to modify release workflow to export OCI images from the cluster we setup during the e2e tests in the release workflow.

**Describe alternatives you've considered**
We can also set up completely separate workflow which would build bundle by using `docker images save` command

**Comment by krasnosvar** [comment]
Can i  describe my problem here?

I created ```bundle_file``` in Ubuntu 20.04 and copied to CentOS7.
But in diconnected CentOS7 pods are in Pending state

# cat /etc/*release*
CentOS Linux release 7.5.1804 (Core) 
Derived from Red Hat Enterprise Linux 7.5 (Source)
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

CentOS Linux release 7.5.1804 (Core) 
CentOS Linux release 7.5.1804 (Core) 
cpe:/o:centos:centos:7


# k0s version
v0.12.0-rc.2


# k0s kubectl get po --all-namespaces
NAMESPACE     NAME                                       READY   STATUS    RESTARTS   AGE
kube-system   calico-kube-controllers-688f579c58-cwpsz   0/1     Pending   0          4m13s
kube-system   coredns-5c98d7d4d8-bzv8n                   0/1     Pending   0          4m17s
kube-system   metrics-server-6fbcd86f7b-lkcx2            0/1     Pending   0          4m2s


[root@test-vm ~]# systemctl status k0scontroller -l
● k0scontroller.service - k0s - Zero Friction Kubernetes
   Loaded: loaded (/etc/systemd/system/k0scontroller.service; enabled; vendor preset: disabled)
   Active: active (running) since Чт 2021-03-25 03:56:12 MSK; 8min ago
     Docs: https://docs.k0sproject.io
 Main PID: 1506 (k0s)
    Tasks: 101
   Memory: 949.7M
   CGroup: /system.slice/k0scontroller.service
           ├─1506 /usr/bin/k0s controller --config=/root/k0s.yaml --enable-worker=true
           ├─1516 /var/lib/k0s/bin/etcd --data-dir=/var/lib/k0s/etcd --listen-client-urls=https://127.0.0.1:2379 --advertise-client-urls=https://127.0.0.1:2379 --client-cert-auth=true --listen-peer-urls=https://10.8.153.7:2380 --initial-advertise-peer-urls=https://10.8.153.7:2380 --name=test-vm.local.domain --trusted-ca-file=/var/lib/k0s/pki/etcd/ca.crt --cert-file=/var/lib/k0s/pki/etcd/server.crt --key-file=/var/lib/k0s/pki/etcd/server.key --peer-trusted-ca-file=/var/lib/k0s/pki/etcd/ca.crt --peer-key-file=/var/lib/k0s/pki/etcd/peer.key --peer-cert-file=/var/lib/k0s/pki/etcd/peer.crt --log-level=info --peer-client-cert-auth=true --enable-pprof=false
           ├─1530 /var/lib/k0s/bin/kube-apiserver --egress-selector-config-file=/var/lib/k0s/konnectivity.conf --service-account-issuer=api --client-ca-file=/var/lib/k0s/pki/ca.crt --kubelet-client-key=/var/lib/k0s/pki/apiserver-kubelet-client.key --proxy-client-key-file=/var/lib/k0s/pki/front-proxy-client.key --requestheader-allowed-names=front-proxy-client --tls-cert-file=/var/lib/k0s/pki/server.crt --api-audiences=system:konnectivity-server --requestheader-client-ca-file=/var/lib/k0s/pki/front-proxy-ca.crt --service-cluster-ip-range=10.96.0.0/12 --v=1 --allow-privileged=true --advertise-address=10.8.153.7 --insecure-port=0 --tls-private-key-file=/var/lib/k0s/pki/server.key --requestheader-extra-headers-prefix=X-Remote-Extra- --secure-port=6443 --enable-admission-plugins=NodeRestriction --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname --kubelet-client-certificate=/var/lib/k0s/pki/apiserver-kubelet-client.crt --proxy-client-cert-file=/var/lib/k0s/pki/front-proxy-client.crt --service-account-signing-key-file=/var/lib/k0s/pki/sa.key --requestheader-group-headers=X-Remote-Group --enable-bootstrap-token-auth=true --service-account-key-file=/var/lib/k0s/pki/sa.pub --kubelet-certificate-authority=/var/lib/k0s/pki/ca.crt --profiling=false --requestheader-username-headers=X-Remote-User --authorization-mode=Node,RBAC --etcd-servers=https://127.0.0.1:2379 --etcd-cafile=/var/lib/k0s/pki/etcd/ca.crt --etcd-certfile=/var/lib/k0s/pki/apiserver-etcd-client.crt --etcd-keyfile=/var/lib/k0s/pki/apiserver-etcd-client.key
           ├─1537 /var/lib/k0s/bin/konnectivity-server --enable-profiling=false --uds-name=/run/k0s/konnectivity-server/konnectivity-server.sock --cluster-key=/var/lib/k0s/pki/server.key --server-port=0 --logtostderr=true --server-count=1 --kubeconfig=/var/lib/k0s/pki/konnectivity.conf --v=1 --server-id=5284af5fccba554793465b1eb134dd7a3d884115996eeea256d469b842c1a897 --agent-port=8132 --admin-port=8133 --authentication-audience=system:konnectivity-server --stderrthreshold=1 --mode=grpc --agent-namespace=kube-system --agent-service-account=konnectivity-agent --cluster-cert=/var/lib/k0s/pki/server.crt
           ├─1549 /var/lib/k0s/bin/kube-scheduler --authentication-kubeconfig=/var/lib/k0s/pki/scheduler.conf --authorization-kubeconfig=/var/lib/k0s/pki/scheduler.conf --kubeconfig=/var/lib/k0s/pki/scheduler.conf --v=1 --bind-address=127.0.0.1 --leader-elect=true --profiling=false --leader-elect=false
           ├─1559 /var/lib/k0s/bin/kube-controller-manager --bind-address=127.0.0.1 --authentication-kubeconfig=/var/lib/k0s/pki/ccm.conf --cluster-cidr=10.244.0.0/16 --service-cluster-ip-range=10.96.0.0/12 --node-cidr-mask-size=24 --use-service-account-credentials=true --cluster-name=k0s --controllers=*,bootstrapsigner,tokencleaner --kubeconfig=/var/lib/k0s/pki/ccm.conf --cluster-signing-key-file=/var/lib/k0s/pki/ca.key --requestheader-client-ca-file=/var/lib/k0s/pki/front-proxy-ca.crt --allocate-node-cidrs=true --client-ca-file=/var/lib/k0s/pki/ca.crt --cluster-signing-cert-file=/var/lib/k0s/pki/ca.crt --enable-hostpath-provisioner=true --service-account-private-key-file=/var/lib/k0s/pki/sa.key --v=1 --leader-elect=true --profiling=false --authorization-kubeconfig=/var/lib/k0s/pki/ccm.conf --root-ca-file=/var/lib/k0s/pki/ca.crt --leader-elect=false
           ├─1569 /usr/bin/k0s api --config=/root/k0s.yaml --data-dir=/var/lib/k0s
           └─1598 /var/lib/k0s/bin/containerd --root=/var/lib/k0s/containerd --state=/run/k0s/containerd --address=/run/k0s/containerd.sock --log-level=info --config=/etc/k0s/containerd.toml

мар 25 04:04:07 test-vm.local.domain k0s[1506]: time="2021-03-25 04:04:07" level=info msg="current config matches existing, not gonna do anything" component=calico
мар 25 04:04:07 test-vm.local.domain k0s[1506]: time="2021-03-25 04:04:07" level=info msg="current config matches existing, not gonna do anything" component=kubeproxy
мар 25 04:04:12 test-vm.local.domain k0s[1506]: time="2021-03-25 04:04:12" level=info msg="I0325 04:04:12.399999    1530 client.go:360] parsed scheme: \"passthrough\"" component=kube-apiserver
мар 25 04:04:12 test-vm.local.domain k0s[1506]: time="2021-03-25 04:04:12" level=info msg="I0325 04:04:12.400091    1530 passthrough.go:48] ccResolverWrapper: sending update to cc: {[{https://127.0.0.1:2379  <nil> 0 <nil>}] <nil> <nil>}" component=kube-apiserver
мар 25 04:04:12 test-vm.local.domain k0s[1506]: time="2021-03-25 04:04:12" level=info msg="I0325 04:04:12.400119    1530 clientconn.go:948] ClientConn switching balancer to \"pick_first\"" component=kube-apiserver
мар 25 04:04:17 test-vm.local.domain k0s[1506]: time="2021-03-25 04:04:17" level=info msg="current config matches existing, not gonna do anything" component=coredns
мар 25 04:04:17 test-vm.local.domain k0s[1506]: time="2021-03-25 04:04:17" level=info msg="current config matches existing, not gonna do anything" component=calico
мар 25 04:04:17 test-vm.local.domain k0s[1506]: time="2021-03-25 04:04:17" level=info msg="current config matches existing, not gonna do anything" component=kubeproxy
мар 25 04:04:20 test-vm.local.domain k0s[1506]: time="2021-03-25 04:04:20" level=info msg="I0325 04:04:20.065960    1559 request.go:655] Throttling request took 1.047885733s, request: GET:https://localhost:6443/apis/authorization.k8s.io/v1beta1?timeout=32s" component=kube-controller-manager
мар 25 04:04:21 test-vm.local.domain k0s[1506]: time="2021-03-25 04:04:21" level=info msg="W0325 04:04:21.017972    1559 garbagecollector.go:703] failed to discover some groups: map[metrics.k8s.io/v1beta1:the server is currently unable to handle the request]" component=kube-controller-manager

**Comment by soider** [comment]
@krasnosvar hello!

Could you get the output of "kubectl describe pod" commands for those pods that are in pending state?

Also, could you check the containerd with ctr tool if it has images imported by using command ```ctr --namespace k8s.io --address /run/k0s/containerd.sock images list```

**Comment by krasnosvar** [comment]
*Also, could you check the containerd with ctr tool if it has images imported by using command ctr --namespace k8s.io --address /run/k0s/containerd.sock images list*
I created bundle with docker, maybe i need recreate it by ctr?


*Could you get the output of "kubectl describe pod" commands for those pods that are in pending state?*
```
# service firewalld status
Redirecting to /bin/systemctl status firewalld.service
● firewalld.service - firewalld - dynamic firewall daemon
   Loaded: loaded (/usr/lib/systemd/system/firewalld.service; disabled; vendor preset: enabled)
   Active: inactive (dead)
     Docs: man:firewalld(1)



# k0s kubectl describe pod --all-namespaces
Name:                 calico-kube-controllers-688f579c58-cwpsz
Namespace:            kube-system
Priority:             2000000000
Priority Class Name:  system-cluster-critical
Node:                 <none>
Labels:               k8s-app=calico-kube-controllers
                      pod-template-hash=688f579c58
Annotations:          <none>
Status:               Pending
IP:                   
IPs:                  <none>
Controlled By:        ReplicaSet/calico-kube-controllers-688f579c58
Containers:
  calico-kube-controllers:
    Image:      docker.io/calico/kube-controllers:v3.16.2
    Port:       <none>
    Host Port:  <none>
    Readiness:  exec [/usr/bin/check-status -r] delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:
      ENABLED_CONTROLLERS:  node
      DATASTORE_TYPE:       kubernetes
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from calico-kube-controllers-token-mcjv7 (ro)
Conditions:
  Type           Status
  PodScheduled   False 
Volumes:
  calico-kube-controllers-token-mcjv7:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  calico-kube-controllers-token-mcjv7
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  kubernetes.io/os=linux
Tolerations:     CriticalAddonsOnly op=Exists
                 node-role.kubernetes.io/master:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason            Age                  From               Message
  ----     ------            ----                 ----               -------
  Warning  FailedScheduling  77s (x787 over 13h)  default-scheduler  no nodes available to schedule pods


Name:           coredns-5c98d7d4d8-bzv8n
Namespace:      kube-system
Priority:       0
Node:           <none>
Labels:         k8s-app=kube-dns
                pod-template-hash=5c98d7d4d8
Annotations:    <none>
Status:         Pending
IP:             
IPs:            <none>
Controlled By:  ReplicaSet/coredns-5c98d7d4d8
Containers:
  coredns:
    Image:       docker.io/coredns/coredns:1.7.0
    Ports:       53/UDP, 53/TCP, 9153/TCP
    Host Ports:  0/UDP, 0/TCP, 0/TCP
    Args:
      -conf
      /etc/coredns/Corefile
    Limits:
      memory:  170Mi
    Requests:
      cpu:        100m
      memory:     70Mi
    Liveness:     http-get http://:8080/health delay=60s timeout=1s period=10s #success=1 #failure=3
    Readiness:    http-get http://:8181/ready delay=0s timeout=1s period=2s #success=1 #failure=3
    Environment:  <none>
    Mounts:
      /etc/coredns from config-volume (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from coredns-token-xzss7 (ro)
Conditions:
  Type           Status
  PodScheduled   False 
Volumes:
  config-volume:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      coredns
    Optional:  false
  coredns-token-xzss7:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  coredns-token-xzss7
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  beta.kubernetes.io/os=linux
Tolerations:     CriticalAddonsOnly op=Exists
                 node-role.kubernetes.io/master:NoSchedule op=Exists
                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason            Age                  From               Message
  ----     ------            ----                 ----               -------
  Warning  FailedScheduling  77s (x768 over 13h)  default-scheduler  no nodes available to schedule pods


Name:                 metrics-server-6fbcd86f7b-lkcx2
Namespace:            kube-system
Priority:             2000000000
Priority Class Name:  system-cluster-critical
Node:                 <none>
Labels:               k8s-app=metrics-server
                      pod-template-hash=6fbcd86f7b
Annotations:          <none>
Status:               Pending
IP:                   
IPs:                  <none>
Controlled By:        ReplicaSet/metrics-server-6fbcd86f7b
Containers:
  metrics-server:
    Image:      gcr.io/k8s-staging-metrics-server/metrics-server:v0.3.7
    Port:       4443/TCP
    Host Port:  0/TCP
    Args:
      --cert-dir=/tmp
      --secure-port=4443
      --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
      --kubelet-insecure-tls
    Requests:
      cpu:        10m
      memory:     30M
    Readiness:    http-get https://:https/healthz delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:  <none>
    Mounts:
      /tmp from tmp-dir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from metrics-server-token-gvvtl (ro)
Conditions:
  Type           Status
  PodScheduled   False 
Volumes:
  tmp-dir:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  metrics-server-token-gvvtl:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  metrics-server-token-gvvtl
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  kubernetes.io/os=linux
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason            Age                  From               Message
  ----     ------            ----                 ----               -------
  Warning  FailedScheduling  47s (x787 over 13h)  default-scheduler  no nodes available to schedule pods


Name:                 metrics-server-7d4bcb75dd-pghdp
Namespace:            kube-system
Priority:             2000000000
Priority Class Name:  system-cluster-critical
Node:                 <none>
Labels:               k8s-app=metrics-server
                      pod-template-hash=7d4bcb75dd
Annotations:          <none>
Status:               Pending
IP:                   
IPs:                  <none>
Controlled By:        ReplicaSet/metrics-server-7d4bcb75dd
Containers:
  metrics-server:
    Image:      gcr.io/k8s-staging-metrics-server/metrics-server:v0.3.7
    Port:       4443/TCP
    Host Port:  0/TCP
    Args:
      --cert-dir=/tmp
      --secure-port=4443
      --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
      --kubelet-insecure-tls
    Readiness:    http-get https://:https/healthz delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:  <none>
    Mounts:
      /tmp from tmp-dir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from metrics-server-token-gvvtl (ro)
Conditions:
  Type           Status
  PodScheduled   False 
Volumes:
  tmp-dir:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  metrics-server-token-gvvtl:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  metrics-server-token-gvvtl
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  kubernetes.io/os=linux
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason            Age                    From               Message
  ----     ------            ----                   ----               -------
  Warning  FailedScheduling  77s (x197 over 3h16m)  default-scheduler  no nodes available to schedule pods
```

**Comment by krasnosvar** [comment]
recreated ```bundle_file``` in CentOS7 with never k0s binary, coped it into disconnected CentOS7 and all is ok!
```
#k0s version
v0.12.0


# kubectl get po --all-namespaces
NAMESPACE     NAME                                       READY   STATUS    RESTARTS   AGE
kube-system   calico-kube-controllers-688f579c58-57kr9   1/1     Running   0          7m19s
kube-system   calico-node-ph8xm                          1/1     Running   0          7m4s
kube-system   coredns-5c98d7d4d8-m4w2s                   1/1     Running   0          7m47s
kube-system   konnectivity-agent-vbmbp                   1/1     Running   0          6m51s
kube-system   kube-proxy-d5vhh                           1/1     Running   0          7m40s
kube-system   metrics-server-6fbcd86f7b-4hdpl            1/1     Running   0          7m24s
```

**Comment by soider** [comment]
>  Warning  FailedScheduling  47s (x787 over 13h)  default-scheduler  no nodes available to schedule pods


It looks to me like non running kubelet rather than airgap install issue
