### ISSUE TITLE
/var/lib/kubelet/plugins_registry/ is not a directory

### ISSUE THREAD

**Issue by 0SkillAllLuck** [k0sproject/k0s#810]
**Version**

v0.12.0

**Platform**

Ubuntu 20.04.02

**What happened?**
When trying to install a csi-driver the driver installation fails with:

```
MountVolume.SetUp failed for volume "registration-dir" : hostPath type check failed: /var/lib/kubelet/plugins_registry/ is not a directory
```

**How To Reproduce**

1. Setup k0s cluster
2. Try to install [hetznercloud/csi-driver](https://github.com/hetznercloud/csi-driver)

**Expected behavior**

CSI Driver can be installed

**Comment by 0SkillAllLuck** [comment]
Manually creating the folder fixed the issue for now.

**Comment by 0SkillAllLuck** [comment]
For anybody running into the same issue. I solved it by just updating the [hetznercloud/csi-driver](https://github.com/hetznercloud/csi-driver) with the changed path. A helm chart with the option can be found here: [quhive/charts](https://github.com/quhive/charts)

**Comment by NiklasRosenstein** [comment]
I had the same issue with the Hetzner CSI driver. My solution was to sed the path:

```
curl -L https://raw.githubusercontent.com/hetznercloud/csi-driver/v2.2.0/deploy/kubernetes/hcloud-csi.yml | sed 's:/var/lib/kubelet:/var/lib/k0s/kubelet:' > hcloud-csi.yml
./kubectl apply -f hcloud-csi.yml
````

**Comment by hanny-ph** [comment]
I had the same issue with the [sergelogvinov/proxmox-csi-plugin](https://github.com/sergelogvinov/proxmox-csi-plugin) using Helm. I could fix the issue by updating the `proxmox-csi.yaml`:

```
# proxmox-csi.yaml
node:
  kubeletDir: "/var/lib/k0s/kubelet"
```
