### ISSUE TITLE
Network policy enforcement is delayed

### ISSUE THREAD

**Issue by rtoma** [k0sproject/k0s#833]
**Version**
```
$ k0s version
0.13.0
```
**Platform**
Which platform did you run k0s on?
rpi4
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 10 (buster)
Release:	10
Codename:	buster
```
**What happened?**
Egress that is supposed to be blocked isn't for first 10-15 seconds of pod life.

**How To Reproduce**
Create namespace with network policies blocking some types of egress.
Create a pod and in it, do some egress which is blocked.

**Expected behavior**
Egress from new pod is blocked.

**Screenshots & Logs**
Also add any output from kubectl if applicable:
```
$ export KUBECONFIG=/var/lib/k0s/pki/admin.conf
$ kubectl logs ...
```

**Additional context**

Seen same in k3s https://github.com/k3s-io/k3s/issues/947 - was fixed in k3s adding event listeners https://github.com/k3s-io/k3s/pull/2363, maybe applicable to k0s?

**Comment by jnummelin** [comment]
@rtoma thanks for reporting this. Could you check if the policy enforcement is faster with [1.2.0](https://github.com/cloudnativelabs/kube-router/releases/tag/v1.2.0) kube-router? You can override the version by providing a "custom" image to be used, something like this in the config: (omitting all non-related stuff)
```
spec:
  images:
    kuberouter:
      cni:
        image: docker.io/cloudnativelabs/kube-router
        version: v1.2.0
```
(check the `k0s default-config` for reference)

**Comment by rtoma** [comment]
@jnummelin sorry, cant reproduce my finding anymore with v1.1.1. This may be related to recreating my cluster and its current low pod count. Unsure - I will close and sorry for wasting your time.

**Comment by jnummelin** [comment]
@rtoma no worries. I think it would help us testing and verifying if you could outline the steps you used to observe this previously.

And nevertheless, we should bump the kube-router version in next release as it has quite a few fixes in it, especially on perf side

**Comment by rtoma** [comment]
fyi - I have tested kube-router v1.1.1 vs v1.2.0 and indeed the later is faster in updating iptables rules.

my testcase:
- in namespace with networkpolicies denying ingress + egress
- run a pod that requests http://1.1.1.1 every few seconds
- apply egress network policy
- observe requests
- delete egress network policy
- observe requests
- apply, observe, delete, observe ....

Observations are not consistent, but with v1.1.1 it can take several seconds. With v1.2.0 near instant.
