### ISSUE TITLE
Automated Backup, Restore, and External Disaster Recovery Solutions for Etcd and Overall Configuration File

### ISSUE THREAD

**Issue by Richard-Barrett** [k0sproject/k0s#844]
If there is not an Automated Current Etcd and Configuration Backup Process, it would be a nice implementation.

Key Functionalities:
- Automated Backup Procedure for running good configuration
- Anytime a change is implemented to the configuration, a backup is stored somewhere for a rollback in case a configuration parameter messes up the known working configuration
- The backups were default for every 15-30 days and the interval of the backup is configurable
- The backups were default in /tmp/k0s/backup
- The backups could aid in restore for both configuration and overall running apps and pods

What is Liked:
We would like to see a fully automated backup procedure that meets the Key Functionalities mentioned above.
We would also like an external configuration built-in on top of the local host backup, in case a client environment needs to be backed up off-site for DTR.

**Comment by mviitane** [comment]
Hello @Richard-Barrett 
Thank you for the input! We are actually working with the basic parts of the backup & restore already. See 
#204 

This won’t yet cover the scheduled backup, but we’ll introduce a simple k0s subcommand to trigger the backup (and restore). Do you think you could solve the scheduling for example with CronJobs? https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs
