### ISSUE TITLE
Ability to list images on the filesystem

### ISSUE THREAD

**Issue by gakio12** [k0sproject/k0s#856]
I see from #743 that crictl was removed from the binary, however I would like to be able to list the images on the filesystem without having to get another binary (crictl) and pointing it at the k0s containerd location and namespace.

So the ask here is to be able to do something like
```bash
k0s image list
k0s image pull ...
k0s container list
```

I know this would be solved similar to how k0s now has the `kc` command for kubectl, but given `crictl` was removed in #743, I'm not sure that is an option, but `k0s crictl image ls` would have been great.

**Comment by jnummelin** [comment]
I would definitely be open to embedding either `ctr` or `crictl` like `k0s ctr image list` as long as it:
- does not bloat the binary too much (it's already quite big)
- does not break k0s own flags etc.

**Comment by jewertow** [comment]
I will submit a PR with support for `k0s ctr ...` soon.

**Comment by jewertow** [comment]
Sorry for the lack of progress. I will submit a PR this week.
