### ISSUE TITLE
CA syncking should be retried

### ISSUE THREAD

**Issue by jnummelin** [k0sproject/k0s#866]
**Version**
```
main
```

**What happened?**
With automation tools like k0sctl the cluster bootstrap is FAST. Every now and then the process get slightly slowed down with systemd unit restarts. Once the systemd unit is restarted, It'll pass as the first controller has gotten all the APIs up-and-running.

**How To Reproduce**
Use automation, human is not fast enough, to setup HA controlplane.

**Expected behavior**
CA, and other. sync between the controllers should probably use some retry functionality for scenarios like this.

**Screenshots & Logs**
Also add any output from kubectl if applicable:
```
Apr 28 11:30:18 k0s-controller-1 k0s[1168]: time="2021-04-28 11:30:18" level=info msg="initializing CASyncer\n"
Apr 28 11:30:18 k0s-controller-1 k0s[1168]: Error: failed to sync CA: Get "https://49.12.16.201:9443/v1beta1/ca": EOF
Apr 28 11:30:18 k0s-controller-1 k0s[1168]: failed to sync CA: Get "https://49.12.16.201:9443/v1beta1/ca": EOF
Apr 28 11:30:18 k0s-controller-1 systemd[1]: k0scontroller.service: Main process exited, code=exited, status=1/FAILURE
Apr 28 11:30:18 k0s-controller-1 systemd[1]: k0scontroller.service: Failed with result 'exit-code'.
```

**Comment by t3hmrman** [comment]
Is there any documentation on this CASyncer process? I'm getting this error, trying to set join a new node to an existing cluster. Trying to follow [the guide](https://docs.k0sproject.io/main/k0s-multi-node/) I'm getting the same error as you. is the `/v1beta1/ca` endpoint only open temporarily following the generation of a token?
