### ISSUE TITLE
Docs need clarification on k0s.yaml

### ISSUE THREAD

**Issue by 205g0** [k0sproject/k0s#873]
**Is your feature request related to a problem? Please describe.**
Docs need to be more clear on `k0s.yaml` because you guys refer from the start to it all the time and there's nowhere a clear description of this file and where it comes from, later there's is bit but yeah.

**Describe the solution you'd like**
I understood, that after installation...

- there isn't any `k0s.yaml` yet
- and if there isn't one yet, then the default values of `k0s default-config` are going to be used
- if you want to have different values, first generate the file yourself with `k0s default-config > k0s.yaml` and then it will be read from the folder where you execute `k0s`?? Or should it be somewhere in `/var/lib/k0s`?

A clear and concise description of how to deal with `k0s.yaml` is needed to just not waste time to find it out it oneself (first, I searched the entire file system for that file, then I found somewhere later in the docs that you can generate it but it still leaves questions open).

**Comment by 205g0** [comment]
There's more strange stuff:

If you run both `k0s default-config -h` and `k0s kubeconfig create -h` the CLI help states for both the same default file (?):

```
...
Flags:
  -c, --config string          config file (default: ./k0s.yaml)
...
```
But these are different files, so why is `(default: ./k0s.yaml)` stated for both? 😶

**Comment by 205g0** [comment]
Ok, I generated a `k0s.yaml` and extended it with the Traefik/helm example given in https://docs.k0sproject.io/v1.20.6+k0s.0/examples/traefik-ingress/ (I've put `extension:...` in `spec:`).

Then I restarted k0s via `sudo systemctl restart k0scontroller` three times, with `k0s.yaml` in the home dir, in `/var/lib/k0s` and another time in `/var/lib/k0s/manifests` and every time, nothing got deployed...

(?)

**Comment by 205g0** [comment]
I think I got one thing: `k0s controller` reads `./k0s.yaml` but when I do `k0s controller` it doesn't work because a controller is already running, so how can I restart this?

**Comment by mviitane** [comment]
Hi 205g0, I agree the documentation should be improved around `k0s.cfg`. There’s also a fault in the help printout about “`default: ./k0s.yaml`”. See #875. That has probably been confusing. We’ll fix those.

Installing k0s in the background (k0s install controller…) and trying to run it also foreground (k0s controller…) don’t work nicely together. After using both methods it’s better to reset k0s using `k0s reset` and then re-install k0s with `k0s install controller…` to get a good start.
