### ISSUE TITLE
k0s kubectl version not showing correct client version

### ISSUE THREAD

**Issue by rtoma** [k0sproject/k0s#880]
**Version**
```
$ k0s version
v1.21.0+k0s.0
```

Also observed on `v1.20.5-k0s1`.

**Platform**
Which platform did you run k0s on?
```
$ lsb_release -a
# not available on systems
```
**What happened?**

Output of `k0s kubectl version` does not show correct client version. See 'logs' section for detailed output.

Extract from output to illustrate issue:

```
version.Info{Major:"", Minor:"", GitVersion:"v0.0.0-master+$Format:%h$", GitCommit:"$Format:%H$",
```

**How To Reproduce**

Run `k0s kubectl version`.

**Expected behavior**

Correct client version in output.

**Screenshots & Logs**

```
$ ./k0s-v1.21.0+k0s.0-amd64 --data-dir $PWD/k0s-data kubectl version
Client Version: version.Info{Major:"", Minor:"", GitVersion:"v0.0.0-master+$Format:%h$", GitCommit:"$Format:%H$",  \
  GitTreeState:"", BuildDate:"1970-01-01T00:00:00Z", GoVersion:"go1.16.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.0-k0s1", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", \
  GitTreeState:"clean", BuildDate:"2021-04-29T15:07:22Z", GoVersion:"go1.16.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by soider** [comment]
We need to set linker flag LD_FLAGS += -X k8s.io/component-base/version.gitVersion=VALUE to have that structure printing proper version.
