### ISSUE TITLE
New k0s subcommands for start and stop

### ISSUE THREAD

**Issue by mviitane** [k0sproject/k0s#900]
**Describe the solution you'd like**

New k0s subcommands for k0s service (Linux init system)

- `k0s install` (remains the same)
- `k0s start` (corresponds to systemctl start k0s…)
- `k0s stop` (corresponds to systemctl stop k0s…)
- `k0s status` (remains the same, but possibly enhanced with data from systemctl status k0s…)

This would make starting and stopping k0s easier. After the install, users wouldn't need to find the rather technical init system command "systemctl start k0s…" to start k0s. Instead, k0s could hide these init system details (there can be different init systems used) and make it simple to use.

**Comment by jewertow** [comment]
The idea sounds very nice, but how will it work on Linux distributions that didn't adopted systemd?

**Comment by 205g0** [comment]
Which are those distros?

**Comment by jewertow** [comment]
Yes, you're right. I checked these distros and none of them seems to be relevant from k0s perspective.
Sorry for irrelevant question. I remembered that such distros exist, but I forgot that they are not popular.

**Comment by mviitane** [comment]
`k0s install` currently supports Systemd and OpenRC. The plan with `start` and `stop` is to support those same init systems.  If the Linux distro doesn't have either of those, then k0s can be started simply with `k0s controller/worker...`, but then the user needs to take care of for example starting k0s after the node restart in some other way.

**Comment by jasmingacic** [comment]
fixed in #896
