### ISSUE TITLE
"k0s install" UX improvement

### ISSUE THREAD

**Issue by mviitane** [k0sproject/k0s#928]
**Is your feature request related to a problem? Please describe.**

When installing k0s and forgetting to add the config file, it becomes difficult to re-install.

```
$ sudo k0s install controller --single
# forgot the config file, let's try again

$ sudo k0s install controller --single -c ~/k0s.yaml 
INFO[2021-05-12 12:34:19] Installing k0s service            
Error: failed to install k0s service: failed to install service: Init already exists: /etc/systemd/system/k0scontroller.service
2021-05-12 12:34:19.372931 I | failed to install k0s service: failed to install service: Init already exists: /etc/systemd/system/k0scontroller.service

$ sudo k0s reset
INFO[2021-05-12 12:34:37] Uninstalling the k0s service         
INFO failed to uninstall k0s service: failed to remove the k0s service: exit status 1 
FATA[2021-05-12 12:34:37] failed clean up pre-flight-checks: failed to find directory `/var/lib/k0s`, check if the node is provisioned
```

**Describe the solution you'd like**
1. I'd like to see that `k0s install` re-writes the k0s service with the updated arguments.
2. I'd like to see that `k0s reset` cleans up the existing init service even if `/var/lib/k0s` was not found.

**Comment by kke** [comment]
1. Maybe require `--force` for overwriting and suggest using force when it already exists (i think if the suggestions in #770 would be implemented, this problem would no longer exist)
2. Yes, seems to be a bug to me

**Comment by jasmingacic** [comment]
It is somewhat related to #878 and #879

**Comment by trawler** [comment]
By design, k0s reset doesn't stop with failure even if one or more sub-tasks fail. maybe we can return a better return code, to alert users that some tasks failed during the "reset" command.

**Comment by ncopa** [comment]
Dropping the `k0s install` would save us for all those issues, as @kke mentions in https://github.com/k0sproject/k0s/issues/770#issuecomment-848613480.

If we cannot drop the k0s installer, then I would prefer that the installer installs a default config under `/etc`. Configuring an app before installing it is unusual. Would be more intuitive to install it before configuring it.

**Comment by mviitane** [comment]
Closing issue. The second part (reset improvement) was implemented and delivered. This makes it rather easy to also re-install k0s if/when needed (first run reset, then install).
