### ISSUE TITLE
Arguments inherited to sub-commands that do not use them

### ISSUE THREAD

**Issue by kke** [k0sproject/k0s#942]
For example:

* `k0s worker` and `k0s default-config` accept `--config`
* `k0s help`, `k0s version`, `k0s completion` and `k0s docs` take `--data-dir` (I think every sub command takes it)

**Comment by jasmingacic** [comment]
`data-dir` param is added here https://github.com/k0sproject/k0s/blob/main/pkg/config/cli.go#L89 which is invoked in pretty much all commands and subcommands.
This can be very confusing

**Comment by ncopa** [comment]
I suggest that we start with adding unit tests, which "documents" how it is expected to be.

**Comment by jnummelin** [comment]
partially fixed in #1247

**Comment by twz123** [comment]
Cross-referencing another issue about subcommands: #1611
