### ISSUE TITLE
cannot determine current directory: stat .: permission denied

### ISSUE THREAD

**Issue by smijolovic** [k0sproject/k0s#984]
**Version**
```
1.21.2+k0s.0
```
**Platform**
```
Ubuntu 20.04
```
**What happened?**

When building from source using:
make EMBEDDED_BINS_BUILDMODE=docker

```
Successfully tagged localhost/k0sbuild.docker-image.konnectivity:latest
6484c1f049d8b57708b01c52c2a2e2cab391ad2271a43cc4384824ae3e1e6813
touch .docker-image.konnectivity.stamp
docker create k0sbuild.docker-image.konnectivity > .container.konnectivity.tmp
mv .container.konnectivity.tmp .container.konnectivity
docker export $(cat .container.konnectivity) | tar -C staging/linux/ -xv bin/konnectivity-server && touch staging/linux/bin/konnectivity-server
bin/konnectivity-server
make[1]: Leaving directory '/home/chaasmadmin/nimbus8/k0s/k0s-chaasm-1.21.2+k0s.0/k0s/embedded-bins'
touch .bins.linux.stamp
GOOS= GOCACHE=/tmp/.cache docker run --rm -v "/home/chaasmadmin/nimbus8/k0s/k0s-chaasm-1.21.2+k0s.0/k0s":/go/src/github.com/k0sproject/k0s -w /go/src/github.com/k0sproject/k0s -e GOOS -e CGO_ENABLED -e GOARCH -e GOCACHE --user $(id -u) "k0sbuild.docker-image.k0s" go run hack/gen-bindata/main.go -o bindata_linux -pkg assets \
     -gofile pkg/assets/zz_generated_offsets_linux.go \
     -prefix embedded-bins/staging/linux/ embedded-bins/staging/linux/bin
2021/06/22 21:51:24 cannot determine current directory: stat .: permission denied
make: *** [Makefile:97: pkg/assets/zz_generated_offsets_linux.go] Error 1
```

**Comment by smijolovic** [comment]
Might have been a umask issue  - set the build to 0022 and it went passed that part but now stuck on:

touch .bins.linux.stamp
GOOS= GOCACHE=/tmp/.cache docker run --rm -v "/home/chaasmadmin/nimbus8/k0s/k0s-chaasm-1.21.2+k0s.0/k0s":/go/src/github.com/k0sproject/k0s -w /go/src/github.com/k0sproject/k0s -e GOOS -e CGO_ENABLED -e GOARCH -e GOCACHE --user $(id -u) "k0sbuild.docker-image.k0s" go run hack/gen-bindata/main.go -o bindata_linux -pkg assets \
     -gofile pkg/assets/zz_generated_offsets_linux.go \
     -prefix embedded-bins/staging/linux/ embedded-bins/staging/linux/bin
bin/containerd-shim.gz: 2/6 MiB
bin/containerd-shim-runc-v1.gz: 2/8 MiB
bin/containerd-shim-runc-v2.gz: 2/8 MiB
bin/runc.gz: 3/9 MiB
bin/kine.gz: 4/12 MiB
bin/etcd.gz: 6/19 MiB
bin/konnectivity-server.gz: 8/29 MiB
bin/containerd.gz: 10/32 MiB
bin/kube-scheduler.gz: 12/44 MiB
bin/kube-controller-manager.gz: 16/58 MiB
bin/kube-apiserver.gz: 17/65 MiB
bin/kubelet.gz: 17/60 MiB
2021/06/22 23:10:17 open bindata_linux: permission denied
exit status 1
make: *** [Makefile:97: pkg/assets/zz_generated_offsets_linux.go] Error 1

**Comment by smijolovic** [comment]
Figured it out!

using rootless podman to build with:
make EMBEDDED_BINS_BUILDMODE=docker

The issue is the preservation of the userns uid/gid, causing the permission issues.

The fix:
Modify the GO variable in the Makefile:

GO ?= GOCACHE=/tmp/.cache docker run --rm -v "$(CURDIR)":/go/src/github.com/k0sproject/k0s \
        -w /go/src/github.com/k0sproject/k0s \
        -e GOOS \
        -e CGO_ENABLED \
        -e GOARCH \
        -e GOCACHE \
        **_--userns=keep-id_** --user $$(id -u) \

**Comment by jnummelin** [comment]
Closing as solved.
